Update to 0.11.3
Approved by:	nakai

diff --git a/lang/librep/files/patch-aa b/lang/librep/files/patch-aa
--- a/lang/librep/files/patch-aa
+++ b/lang/librep/files/patch-aa
@@ -1,11 +1,11 @@
---- configure.orig	Sun Mar 12 09:41:29 2000
-+++ configure	Thu Mar 23 18:17:51 2000
-@@ -2228,7 +2228,7 @@
+--- configure.orig	Thu Apr 13 09:53:31 2000
++++ configure	Mon Apr 17 20:09:51 2000
+@@ -2422,7 +2422,7 @@
  fi
  if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
    echo "$ac_t""yes" 1>&6
 -  GDBM_LIBS="-lgdbm"
 +  GDBM_LIBS="-lgdbm $LIBS"
- 	      
  else
    echo "$ac_t""no" 1>&6
+ { echo "configure: error: Cannot find GDBM library" 1>&2; exit 1; }
