Update to 5.3.27, USE_MYSQL, de-quote COMMENT, update the knobs info, and other assorted fixes, mostly from Alex's PR.
PR:		56462
Submitted by:	Alex Dupre <sysadmin@alexdupre.com>
Ob-woohoo:	run-time configuration of default-domain and MySQL info;
		at last it is possible to build a single package for
		deploying on multiple servers!

diff --git a/mail/vpopmail/files/patch-configure b/mail/vpopmail/files/patch-configure
--- a/mail/vpopmail/files/patch-configure
+++ b/mail/vpopmail/files/patch-configure
@@ -1,6 +1,6 @@
---- configure.old	Thu Feb 13 17:37:40 2003
-+++ configure	Thu Feb 13 17:38:32 2003
-@@ -1285,7 +1285,7 @@
+--- configure.orig	Thu Aug 28 21:09:47 2003
++++ configure	Fri Sep  5 00:13:14 2003
+@@ -1317,7 +1317,7 @@
    ;;
  esac
  
@@ -9,8 +9,8 @@
  then
      echo "configure: warning: === vpopmail must be configured as root. ===" 1>&2
      echo "configure: warning: === please switch to the root user and  ===" 1>&2
-@@ -1563,15 +1563,6 @@
- rm -f vpopusername 
+@@ -1601,15 +1601,6 @@
+ EOF
  
  
 -if test ! -d $vpopmaildir/etc
@@ -25,38 +25,22 @@
  # Check whether --enable-roaming-users or --disable-roaming-users was given.
  if test "${enable_roaming_users+set}" = set; then
    enableval="$enable_roaming_users"
-@@ -1637,7 +1628,7 @@
-   
-         if test "$tcpserver_file" = ""
-         then
+@@ -1671,17 +1662,7 @@
+ if test "${enable_tcpserver_file+set}" = set; then
+   enableval="$enable_tcpserver_file"
+   tcpserver_file="$enableval"
+-else
+-  
+-        if test "$tcpserver_file" = ""
+-        then
 -	    echo "127.:allow,RELAYCLIENT=\"\"" > "$vpopmaildir"/etc/tcp.smtp
-+	    echo "127.:allow,RELAYCLIENT=\"\"" > "$VCFGDIR"/tcp.smtp
-     	    tcpserver_file="$vpopmaildir"/etc/tcp.smtp
- 	
-             echo "configure: warning: Unable to find your tcpserver relay file." 1>&2
-@@ -2142,7 +2133,7 @@
-         fi
- 		auth_libs="-L$libdir $extralibflags -lmysqlclient -lz"
+-    	    tcpserver_file="$vpopmaildir"/etc/tcp.smtp
+-	
+-            echo "configure: warning: Unable to find your tcpserver relay file." 1>&2
+-            echo "configure: warning: Creating tcp.smtp in "$vpopmaildir"/etc/tcp.smtp." 1>&2
+-        fi
+-     
++  echo "127.:allow,RELAYCLIENT=\"\"" > ${VCFGDIR}/tcp.smtp
+ fi
  
--		echo "-L$vpopmaildir/lib -lvpopmail -L$libdir -lmysqlclient -lz" > $vpopmaildir/etc/lib_deps
-+		echo "-L$vpopmaildir/lib -lvpopmail -L$libdir -lmysqlclient -lz" > $VCFGDIR/lib_deps
- 		
-         ;;
- *)
-@@ -2399,14 +2390,14 @@
- 		authlib=
- 		
- 		auth_inc="-Icdb"
--		echo "-L$vpopmaildir/lib -lvpopmail" > $vpopmaildir/etc/lib_deps
-+		echo "-L$vpopmaildir/lib -lvpopmail" > $VCFGDIR/lib_deps
- 		
-         ;;
- *)
-         ;;
- esac
- 
--echo "-I$vpopmaildir/include" > $vpopmaildir/etc/inc_deps
-+echo "-I$vpopmaildir/include" > $VCFGDIR/inc_deps
- 
- # Check whether --enable-qmail-ext or --disable-qmail-ext was given.
- if test "${enable_qmail_ext+set}" = set; then
+ cat >> confdefs.h <<EOF
