- Fix new installations (patch disappeared in my last commit) [1] - Remove now useless post-patch target
Noticed by:	Cristiano Deana <cris@gufi.org> [1]
Approved by:	nork (mentor/implicitly)

diff --git a/mail/vpopmail/files/patch-configure b/mail/vpopmail/files/patch-configure
--- a/mail/vpopmail/files/patch-configure
+++ b/mail/vpopmail/files/patch-configure
@@ -1,5 +1,5 @@
 --- configure.orig	Mon Feb  2 06:24:19 2004
-+++ configure	Mon Feb  2 10:10:12 2004
++++ configure	Wed Feb 11 09:16:18 2004
 @@ -846,6 +846,8 @@
    --enable-qmail-newu=PATH   Full path to qmail-newu program.
    --enable-qmail-inject=PATH Full path to qmail-inject program.
@@ -78,7 +78,7 @@
  #----------------------------------------------------------------------
  
  echo "$as_me:$LINENO: checking whether we can locate the qmail directory" >&5
-@@ -5705,20 +5738,7 @@
+@@ -5705,28 +5738,8 @@
  if test "${enable_tcpserver_file+set}" = set; then
    enableval="$enable_tcpserver_file"
    tcpserver_file="$enableval"
@@ -98,5 +98,13 @@
 -
 +  echo "127.:allow,RELAYCLIENT=\"\"" > ${VCFGDIR}/tcp.smtp
  fi;
+-
+-    if test ! -f "$tcpserver_file"
+-    then
+-        { { echo "$as_me:$LINENO: error: Unable to find your tcp.smtp file, specify --enable-tcpserver-path=/full/path/to/tcp.smtp" >&5
+-echo "$as_me: error: Unable to find your tcp.smtp file, specify --enable-tcpserver-path=/full/path/to/tcp.smtp" >&2;}
+-   { (exit 1); exit 1; }; }
+-    fi
  
-     if test ! -f "$tcpserver_file"
+     echo "$as_me:$LINENO: result: yes" >&5
+ echo "${ECHO_T}yes" >&6
