- Fix build with gcc 4.X
PR:             ports/107819
Submitted by:   trasz (Maintainer)

diff --git a/emulators/tme/files/patch-configure b/emulators/tme/files/patch-configure
--- a/emulators/tme/files/patch-configure
+++ b/emulators/tme/files/patch-configure
@@ -1,5 +1,14 @@
---- configure.orig	Wed Jan  3 19:05:49 2007
-+++ configure	Wed Jan  3 19:06:10 2007
+--- configure.orig	Sun May 15 03:26:11 2005
++++ configure	Thu Jan 11 12:30:20 2007
+@@ -8890,7 +8890,7 @@
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  ac_cv_have_isinff=yes
++  ac_cv_have_isinff=no
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
 @@ -25853,7 +25853,7 @@
    enable_warnings=yes
  fi;
