Update to 0.96.5 of Quagga. This fixes a number of bugs, especially on -CURRENT, and adds support for the OSI IS-IS backbone routing protocol.
Submitted by:	Boris Kovalenko

diff --git a/net/quagga/pkg-install b/net/quagga/pkg-install
--- a/net/quagga/pkg-install
+++ b/net/quagga/pkg-install
@@ -53,14 +53,23 @@ case $2 in
 		fi
 	fi
 
-	chown -R ${ENABLE_USER}:${ENABLE_GROUP} ${SYSCONF_DIR}
-
 	mkdir ${LOCALSTATE_DIR}
 	if [ ! -d ${LOCALSTATE_DIR} ]; then
 	    echo "Creating \"${LOCALSTATE_DIR}\" failed."
 	    exit 1
 	fi
-
+	
 	chown -R ${ENABLE_USER}:${ENABLE_GROUP} ${LOCALSTATE_DIR}
+
+	if [ ! -d ${SYSCONF_DIR} ]; then
+	    mkdir -p ${SYSCONF_DIR}
+	fi
+	
+	if [ ! -d ${SYSCONF_DIR} ]; then
+	    echo "Creating \"${SYSCONF_DIR}\" failed."
+	    exit 1
+	fi
+
+	chown -R ${ENABLE_USER}:${ENABLE_GROUP} ${SYSCONF_DIR}
 	;;
 esac
