Update to latest version
PR:	ports/152423
Submitted by:	Richard Neese <r.neese@gmail.com>

diff --git a/net/freeswitch-core/files/pkg-install.in b/net/freeswitch-core/files/pkg-install.in
--- a/net/freeswitch-core/files/pkg-install.in
+++ b/net/freeswitch-core/files/pkg-install.in
@@ -1,32 +1,35 @@
 #!/bin/sh
+# $FreeBSD: /tmp/pcvs/ports/net/freeswitch-core/files/pkg-install.in,v 1.3 2010-12-08 18:33:22 jpaetzel Exp $
 #
-# $FreeBSD: /tmp/pcvs/ports/net/freeswitch-core/files/pkg-install.in,v 1.2 2010-07-16 14:57:42 jpaetzel Exp $
-#
 
-PATH=/bin:/usr/bin:/usr/sbin
+if [ "$2" != "PRE-INSTALL" ]; then
+	exit 0
+fi
 
-case $2 in
+FREESWITCHUSER=freeswitch
+FREESWITCHGROUP=${FREESWITCHUSER}
+FREESWITCHUID=610
+FREESWITCHGID=${FREESWITCHUID}
 
-PRE-INSTALL)
-  echo "---> Starting pre-install script:"
+if ! pw groupshow "${FREESWITCHGROUP}" 2>/dev/null 1>&2; then
+	if pw groupadd ${FREESWITCHGROUP} -g ${FREESWITCHGID}; then
+		echo "Added group \"${FREESWITCHGROUP}\"."
+	else
+		echo "Adding group \"${FREESWITCHGROUP}\" failed..."
+		exit 1
+	fi
+fi
 
-  if pw showgroup "freeswitch" 2>/dev/null; then
-    echo "---> Using existing group \"freeswitch\""
-  else
-    echo "---> Adding group \"freeswitch\""
-    pw addgroup freeswitch -h - || exit 1
-  fi
+if ! pw usershow "${FREESWITCHUSER}" 2>/dev/null 1>&2; then
+	if pw useradd ${FREESWITCHUSER} -u ${FREESWITCHUID} -g ${FREESWITCHGROUP} -h - \
+		-s "/sbin/nologin" -d "/nonexistent" \
+		-c "FREESWITCH Owner"; \
+	then
+		echo "Added user \"${FREESWITCHUSER}\"."
+	else
+		echo "Adding user \"${FREESWITCHUSER}\" failed..."
+		exit 1
+	fi
+fi
 
-
-  # Create user if required
-  if pw showuser "freeswitch" 2>/dev/null; then
-    echo "---> Using existing user \"freeswitch\""
-  else
-    echo "---> Adding user \"freeswitch\""
-    pw adduser freeswitch -g freeswitch -h - \
-      -d "/nonexistent" -s "/sbin/nologin" -c "freeswitch User" || exit 1
-  fi
-
-  ;;
-
-esac
+exit 0
