- Use shell instead of perl for pkg-(de)install [1] - Make portlint happy
PR:		ports/157212 [1]
Submitted by:	flz [1]

diff --git a/japanese/alias-fonts/pkg-install b/japanese/alias-fonts/pkg-install
--- a/japanese/alias-fonts/pkg-install
+++ b/japanese/alias-fonts/pkg-install
@@ -1,29 +1,32 @@
-#!/usr/bin/perl
+#!/bin/sh
 # $FreeBSD$
 
-$prefix = $ENV{'PKG_PREFIX'};
-$dir = "$prefix/lib/X11/fonts/local";
-$to =  "$dir/fonts.alias";
-$from = "$to.orig";
-$option = $ARGV[1];
-exit 0 if $option ne 'POST-INSTALL';
-rename($to, $from) || die("Can't rename: $!");
-open(IN, $from) || die("Can't open $from: $!");
-open(OUT, ">$to") || die("Can't open $to: $!");
-while (<IN>) {
-	chop;
-	if (/^\s*!/ || /^\s*$/) {
-		print OUT "$_\n";
-	}
-	else {
-		@line = split(/\s+/, $_);
-		@elm = split(/-+/, $line[0]);
-		if ($elm[1] ne 'alias') { 
-			print OUT "$_\n";
-		}
-	}
-}
-for (split(/\n/, <<"END"))
+if [ $1 != "POST-INSTALL" ]; then
+  exit 0
+fi
+
+dir="${PKG_PREFIX}/lib/X11/fonts/local";
+to="$dir/fonts.alias";
+from="$to.orig";
+
+if ! mv $to $from; then
+  echo "Couldn't rename $to."
+  exit 1
+fi
+
+IFS="
+"
+
+while read line; do
+  trimmed=${line# *}
+  case $trimmed in
+    !*|"") echo $line;;
+    -alias-*) echo $line;;
+    *) ;;
+  esac
+done < $from > $to
+
+cat <<EOF >> $to
 -alias-fixed-medium-r-normal--24-234-75-75-c-120-iso8859-1 -sony-fixed-medium-r-normal--24-230-75-75-c-120-iso8859-1
 -alias-fixed-medium-r-normal--20-190-75-75-c-200-iso8859-1 -kappa-fixed-medium-r-normal--20-190-75-75-c-100-iso8859-1
 -alias-fixed-medium-i-normal--20-190-75-75-c-200-iso8859-1 -kappa-fixed-medium-i-normal--20-190-75-75-c-100-iso8859-1
@@ -138,7 +141,4 @@ for (split(/\n/, <<"END"))
 -alias-fixed-bold-i-normal--16-150-75-75-c-160-jisx0213.2000-1 -misc-fixed-bold-i-normal--16-150-75-75-c-160-jisx0213.2000-1
 -alias-mincho-bold-r-normal--20-190-75-75-c-200-jisx0213.2000-1 -kappa-mincho-bold-r-normal--20-190-75-75-c-200-jisx0213.2000-1
 -alias-mincho-bold-i-normal--20-190-75-75-c-200-jisx0213.2000-1 -kappa-mincho-bold-i-normal--20-190-75-75-c-200-jisx0213.2000-1
-END
-{
-	print OUT "$_\n";
-}
+EOF
