- Use shell instead of perl for pkg-(de)install [1] - Make portlint happy
PR:		ports/157212 [1]
Submitted by:	flz [1]

diff --git a/japanese/alias-fonts/pkg-deinstall b/japanese/alias-fonts/pkg-deinstall
--- a/japanese/alias-fonts/pkg-deinstall
+++ b/japanese/alias-fonts/pkg-deinstall
@@ -1,24 +1,25 @@
-#!/usr/bin/perl
+#!/bin/sh
 # $FreeBSD$
 
-$prefix = $ENV{'PKG_PREFIX'};
-$dir = "$prefix/lib/X11/fonts/local";
-$to =  "$dir/fonts.alias";
-$from = "$to.orig";
-rename($to, $from) || die("Can't rename: $!");
-open(IN, $from) || die("Can't open $from: $!");
-open(OUT, ">$to") || die("Can't open $to: $!");
-while (<IN>) {
-	chop;
-	if (/^\s*!/ || /^\s*$/) {
-		print OUT "$_\n";
-	}
-	else {
-		@line = split(/\s+/, $_);
-		@elm = split(/-+/, $line[0]);
-		if ($elm[1] ne 'alias') {
-			print OUT "$_\n";
-		}
-	}
-}
-#system("$prefix/bin/xset fp rehash");
+dir="${PKG_PREFIX}/lib/X11/fonts/local";
+to="$dir/fonts.alias";
+from="$to.orig";
+
+if ! mv $to $from; then
+  echo "Couldn't rename $to."
+  exit 1
+fi
+
+IFS="
+"
+
+while read line; do
+  trimmed=${line# *}
+  case $trimmed in
+    !*|"") echo $line;;
+    -alias-*) echo $line;;
+    *) ;;
+  esac
+done < $from > $to
+
+rm $from
