[patch] japanese/sj3 is broken
	There are several problems with japanese/sj3 port.

	1. Original MASTER_SITES don't seem to work any longer.
	2. With the current patchset it builds okay, but it is said that it does not work correctly.
	3. It does not build under 7-CURRENT (i.e. with gcc4.2).

PR:		ports/113572
Submitted by:	Hirohisa Yamaguchi <umq@ueo.co.jp>
Approved by:	maintainer timeout

diff --git a/japanese/sj3-lib/pkg-install b/japanese/sj3-lib/pkg-install
--- a/japanese/sj3-lib/pkg-install
+++ b/japanese/sj3-lib/pkg-install
@@ -1,9 +1,36 @@
 #!/bin/sh
 
+PATH=/bin:/usr/sbin
+
 case $2 in
-    POST-INSTALL)
-	dic="${PKG_PREFIX}/lib/sj3/dict/user"
-	mkdir -p $dic
-	chown bin:bin $dic
+    PRE-INSTALL)
+	USER=_sj3
+	GROUP=${USER}
+	UID=912
+	GID=${UID}
+
+	if pw group show "${GROUP}" 2>/dev/null; then
+		echo "You already have a group \"${GROUP}\", so I will use it."
+	else
+		if pw groupadd ${GROUP} -g ${GID}; then
+			echo "Added group \"${GROUP}\"."
+		else
+			echo "Adding group \"${GROUP}\" failed..."
+			exit 1
+		fi
+	fi
+
+	if pw user show "${USER}" 2>/dev/null; then
+		echo "You already have a user \"${USER}\", so I will use it."
+	else
+		if pw useradd ${USER} -u ${UID} -g ${GROUP} -h - \
+			-d /nonexistent -s /sbin/nologin -c "SJ3 Daemon"
+		then
+			echo "Added user \"${USER}\"."
+		else
+			echo "Adding user \"${USER}\" failed..."
+			exit 1
+		fi
+	fi
 	;;
 esac
