Update to 20080110.  GTK_IM_MODULE and XMODIFIERS hack is added and enabled by default.  To disable this, you need to set $ADOBE_DISABLEIMMODULEHACK to YES.
Discussed on:	freebsd-ports@

diff --git a/print/acroreadwrapper/files/acroread.in b/print/acroreadwrapper/files/acroread.in
--- a/print/acroreadwrapper/files/acroread.in
+++ b/print/acroreadwrapper/files/acroread.in
@@ -1,4 +1,4 @@
-#!%%LINUXBASE%%/bin/sh
+#!/bin/sh
 # $FreeBSD$
 
 # environment variables:
@@ -13,6 +13,14 @@
 #     When this script is invoked as "acroread7" and "acroread8",
 #     ADOBE_VER is automatically set.
 #
+# ADOBE_DISABLEIMMODULEHACK:
+#     This script sets GTK_IM_MODULE as "xim" by default because
+#     immodules other than xim require the corresponding module files
+#     in Linux binary, not FreeBSD native versions (if a FreeBSD
+#     native immodule library exists and the corresponding Linux
+#     library does not, Adobe Reader attempts to load the FreeBSD
+#     binary and it will fail).  If $ADOBE_DISABLEIMMODULEHACK is
+#     defined as "YES", this behavior is disabled.
 
 ADOBE_LANG=`echo "${ADOBE_LANG}" | tr a-z A-Z`
 
@@ -63,7 +71,6 @@ esac
 case ${ADOBE_LANG} in
 CHS) : ${GDK_USE_XFT:=0}; export GDK_USE_XFT ;;
 CHT) : ${GDK_USE_XFT:=0}; export GDK_USE_XFT ;;
-JPN) : ${GTK_IM_MODULE:=xim}; export GTK_IM_MODULE ;;
 KOR) : ${GDK_USE_XFT:=0}; export GDK_USE_XFT ;;
 esac
 
@@ -94,19 +101,41 @@ case ${ADOBE_VER} in
 ;;
 esac
 
+case ${ADOBE_DISABLEIMMODULEHACK} in
+[Yy][Ee][Ss])	;; # do nothing
+*)
+	case ${ADOBE_VER}:${GTK_IM_MODULE} in
+	*:""|*:xim)
+		GTK_IM_MODULE=xim; export GTK_IM_MODULE
+	;;
+	7:scim)
+		GTK_IM_MODULE=xim; export GTK_IM_MODULE
+		XMODIFIERS="@im=SCIM"; export XMODIFIERS
+	;; 
+	8:scim)
+		GTK_IM_MODULE=scim; export GTK_IM_MODULE
+		XMODIFIERS="@im=SCIM"; export XMODIFIERS
+	;; 
+	*)
+		XMODIFIERS="@im=${GTK_IM_MODULE}"; export XMODIFIERS
+	;;
+	esac
+;;
+esac
+
 case $1 in
 --install-plugin)
 	echo "installing PDF plugin..."
 	echo "%%PREFIX%%/${ACROBASE}/${ADOBE_LANG}/Browser/intellinux/nppdf.so -> %%PREFIX%%/%%PLUGINDIR%%/nppdf.so"
-	mkdir -p /../%%PREFIX%%/%%PLUGINDIR%%
-	ln -s -f %%PREFIX%%/${ACROBASE}/${ADOBE_LANG}/Browser/intellinux/nppdf.so \
-	/../%%PREFIX%%/%%PLUGINDIR%%/nppdf.so
+	mkdir -p %%PREFIX%%/%%PLUGINDIR%%
+	ln -s -f %%PREFIX%%/${ACROBASE}/${ADOBE_LANG}/${BINPREFIX}/../Browser/intellinux/nppdf.so \
+	%%PREFIX%%/%%PLUGINDIR%%/nppdf.so
 	exit 0
 ;;
 --deinstall-plugin)
 	echo "deinstalling PDF plugin..."
-	rm -f /../%%PREFIX%%/%%PLUGINDIR%%/nppdf.so
-	rmdir /../%%PREFIX%%/%%PLUGINDIR%% 2> /dev/null || true
+	rm -f %%PREFIX%%/%%PLUGINDIR%%/nppdf.so
+	rmdir %%PREFIX%%/%%PLUGINDIR%% > /dev/null 2>&1 || true
 	exit 0
 ;;
 esac
