bento reported that amd64 built incorrectly; kris@ suggested that changing HAS_CONFIGURE to GNU_CONFIGURE will fix it.
also, etc/rc.d/sympa.sh was disabled and now works.

PR:		ports/64340
Submitted by:	maintainer

diff --git a/mail/sympa/files/patch-src-etc-script-sympa b/mail/sympa/files/patch-src-etc-script-sympa
--- a/mail/sympa/files/patch-src-etc-script-sympa
+++ b/mail/sympa/files/patch-src-etc-script-sympa
@@ -36,7 +36,7 @@
 -	if [ ${OSTYPE} = "IRIX" ]; then
 -		$sympadir/$1.pl $startparam && echo "success" || echo "failure"
 +	if [ ${OSTYPE} = "IRIX" -o ${OSTYPE} = "FreeBSD" ]; then
-+		su sympa -c "$sympadir/$1.pl $startparam" && echo "success" || echo "failure"
++		su -m sympa -c "$sympadir/$1.pl $startparam" && echo "success" || echo "failure"
  	else
  		$sympadir/$1.pl $startparam && success || failure
  	fi
