New port: linux_mesa3 with RedHat Package This is Linux Version of MesaLib version 3.
PR:		ports/18656
Submitted by:	Masahiro TAKEMURA <mastake@msel.t.u-tokyo.ac.jp>

diff --git a/graphics/linux_mesa3/Makefile b/graphics/linux_mesa3/Makefile
--- a/graphics/linux_mesa3/Makefile
+++ b/graphics/linux_mesa3/Makefile
@@ -1,44 +1,85 @@
-# New ports collection makefile for:    Mesa for Linux compat
-# Date created:         Oct, 8 1998
-# Whom:                 cracauer
+# New ports collection makefile for:	Mesa3 for Linux compat
+# Date created:		May 18 2000
+# Whom:			Masahiro TAKEMURA
 #
 # $FreeBSD$
 #
 
-PORTNAME=	mesa
-PORTVERSION=	2.6
-CATEGORIES=	graphics linux
-MASTER_SITES= 	ftp://iris.ssec.wisc.edu/pub/Mesa/old-versions/
-PKGNAMEPREFIX=	linux_
-DISTNAME=       MesaLib-${PORTVERSION}
+PORTNAME=		mesa
+PORTVERSION=		3.2.2
+CATEGORIES=		graphics linux
+MASTER_SITES=		${RPM_MIRRORS:S/__DIR__/${STDDIR}/g}
+PKGNAMEPREFIX=		linux_
+DISTFILES=		Mesa-${PORTVERSION:S/./-/g:S/-/./}.${MACHINE_ARCH}.rpm
+EXTRACT_ONLY=
 
-MAINTAINER=	cracauer@cons.org
+PATCH_SITES=		${RPM_MIRRORS:S/__DIR__/${UPDDIR}/g}
+PATCHFILES=
 
-BUILD_DEPENDS=	/compat/linux/usr/lib/libglide2x.so:${PORTSDIR}/graphics/linux_glide \
-		/compat/linux/usr/bin/gcc:${PORTSDIR}/devel/linux_devtools
+MAINTAINER=		mastake@msel.t.u-tokyo.ac.jp
 
-BROKEN=		linux crosscompilation needs to be fixed first
-ONLY_FOR_ARCHS=	i386
+BUILD_DEPENDS=		rpm2cpio:${PORTSDIR}/misc/rpm
+RUN_DEPENDS=		\
+	/compat/linux/lib/ld-linux.so.2:${PORTSDIR}/emulators/linux_base
 
-ALL_TARGET=	linux-glide
-MAKE_ENV=	PATH=${PREFIX}/usr/bin:$$PATH
-NO_FILTER_SHLIBS=yes
+ONLY_FOR_ARCHS=		i386
+DIST_SUBDIR=		rpm
+PREFIX=			/compat/linux
+NO_BUILD=		yes
+NO_FILTER_SHLIBS=	yes
+NO_MTREE=		yes
 
-PREFIX=		/compat/linux
-WRKSRC=		${WRKDIR}/Mesa-2.6/src
+RPM_MIRRORS=		\
+	ftp://ftp.freesoftware.com/pub/linux/redhat/__DIR__/ \
+	ftp://ftp.redhat.com/redhat/__DIR__/ \
+	ftp://ftp.infomagic.com/pub/mirrors/linux/RedHat/__DIR__/ \
+	ftp://ftp.crc.ca/mirrors/by-site/ftp.redhat.com/redhat/__DIR__/ \
+	ftp://ftp.nluug.nl/site/ftp.redhat.com/redhat/__DIR__/ \
+	ftp://mirror.nucba.ac.jp/mirror/redhat/__DIR__/ \
+	ftp://ftp.is.co.za/linux/distributions/redhat/__DIR__/ \
+	ftp://mirror.aarnet.edu.au/pub/linux/redhat/__DIR__/
 
-post-extract:
-	-${MKDIR} ${WRKSRC}/../lib/
+STDDIR=			redhat-6.2/${MACHINE_ARCH}/RedHat/RPMS
+UPDDIR=			updates/6.2/${MACHINE_ARCH}
+
+.include <bsd.port.pre.mk>
+
+RPMDIR=			${DISTDIR}/${DIST_SUBDIR}
 
 do-install:
-	${INSTALL_DATA} ${WRKSRC}/../lib/libMesaGL.so.2.6 ${PREFIX}/usr/lib/.
-	${LN} -fs libMesaGL.so.2.6 ${PREFIX}/usr/lib/libMesaGL.so.2
-	${LN} -fs libMesaGL.so.2.6 ${PREFIX}/usr/lib/libMesaGL.so
-	${LN} -fs libMesaGL.so.2.6 ${PREFIX}/usr/lib/libGL.so
-	@${MKDIR} ${PREFIX}/usr/include/GL
-	${INSTALL_DATA} ${WRKSRC}/../include/GL/* ${PREFIX}/usr/include/GL/.
-	${INSTALL_DATA} ${WRKSRC}/../include/glaux.h ${PREFIX}/usr/include/.
-	${INSTALL_DATA} ${WRKSRC}/../include/gltk.h ${PREFIX}/usr/include/.
-	-/compat/linux/sbin/ldconfig
+	@if [ -z "`kldstat -v | ${GREP} -E 'linux(aout|elf)'`" ]; then \
+		${ECHO} 'Linux mode is not enabled.\
+			Loading linux kernel module...' | fmt; \
+		linux || { \
+		${ECHO} 'The linux kernel module could not be loaded.\
+			Please manually load the module and retry.\
+			See "man linux" for details.' | fmt; \
+		${FALSE}; \
+		};\
+	fi
+#
+# Install all packages.
+#
+	@for R in ${DISTFILES}; do \
+		${ECHO} $$R; \
+		cd ${PREFIX} && rpm2cpio ${RPMDIR}/$$R | cpio -di; \
+	done
+#
+# Install updates
+#
+	@for R in ${PATCHFILES}; do \
+		${ECHO} $$R; \
+		cd ${PREFIX} && rpm2cpio ${RPMDIR}/$$R | cpio -di; \
+	done
+#
+# Create Symbolic link
+#
+	@for R in GL GLU; do \
+		cd ${PREFIX}/usr/X11R6/lib && ${LN} -s lib$$R.so libMesa$$R.so; \
+	done
+#
+# Finish
+#
+	${PREFIX}/sbin/ldconfig
 
-.include <bsd.port.mk>
+.include <bsd.port.post.mk>
