Fix broken startup script.
PR:		23810
Submitted by:	Martin Kammerhofer <mkamm@gmx.net>

diff --git a/www/junkbuster-zlib/files/junkbuster.sh.in b/www/junkbuster-zlib/files/junkbuster.sh.in
--- a/www/junkbuster-zlib/files/junkbuster.sh.in
+++ b/www/junkbuster-zlib/files/junkbuster.sh.in
@@ -1,14 +1,24 @@
 #!/bin/sh
+# $CVSHeader$
 
 case $1 in
 start)
-	test -d %%JDIR%% -a -x %%PREFIX%%/sbin/junkbuster -a -f %%JDIR%%/configfile || exit 1
+	if [ -d %%JDIR%% \
+	     -a -x %%PREFIX%%/sbin/junkbuster-zlib \
+	     -a -f %%JDIR%%/configfile ]; then
+		: seems OK
+	else
+		echo >&2 "$0: missing files!"
+		exit 1
+	fi
 	cd %%JDIR%%
-	su -m nobody -c "%%PREFIX%%/sbin/junkbuster configfile &"
-	echo -n " junkbuster"
+	su -m nobody -c "%%PREFIX%%/sbin/junkbuster-zlib configfile &" \
+	    >/dev/null \
+	&& echo -n " junkbuster" \
+	|| echo " junkbuster FAILED TO START"
 	;;
 stop)
-	killall junkbuster && echo -n " junkbuster"
+	killall junkbuster-zlib && echo -n " junkbuster"
 	;;
 *)
 	echo "Usage: `basename $0` {start|stop}" >&2
