- Update to 1.1.16.2. - Add FAAD option for external libfaad support. [*]
PR:		ports/131955 [*]
Submitted by:	Jan Henrik Sylvester <me@janh.de>

diff --git a/multimedia/libxine/files/patch-configure b/multimedia/libxine/files/patch-configure
--- a/multimedia/libxine/files/patch-configure
+++ b/multimedia/libxine/files/patch-configure
@@ -1,6 +1,6 @@
---- configure.orig	2008-06-28 22:13:45.000000000 -0500
-+++ configure	2008-06-28 22:13:45.000000000 -0500
-@@ -10049,6 +10049,12 @@
+--- configure.orig	2009-02-11 03:35:05.000000000 +0900
++++ configure	2009-02-22 18:37:34.000000000 +0900
+@@ -10363,6 +10363,12 @@
        fi
        ;;
  
@@ -11,9 +11,9 @@
 +	;;
 +
      netbsd* | netbsdelf*-gnu)
-       if echo __ELF__ | $CC -E - | grep __ELF__ >/dev/null; then
+       if echo __ELF__ | $CC -E - | $GREP __ELF__ >/dev/null; then
  	archive_cmds='$LD -Bshareable $libobjs $deplibs $linker_flags -o $lib'
-@@ -22431,7 +22437,7 @@
+@@ -13853,7 +13859,7 @@
                      if test -z "$haveit"; then
                        LIBICONV="${LIBICONV}${LIBICONV:+ }-L$found_dir"
                      fi
@@ -22,7 +22,51 @@
                                                                                          LIBICONV="${LIBICONV}${LIBICONV:+ }$found_so"
                      else
                                                                                                                                                                                  LIBICONV="${LIBICONV}${LIBICONV:+ }-l$name"
-@@ -37670,6 +37676,8 @@
+@@ -26519,12 +26525,12 @@
+         pkg_cv_CACA_CFLAGS="$CACA_CFLAGS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"caca >= 0.99beta14 cucul >= 0.99beta14 \"") >&5
+-  ($PKG_CONFIG --exists --print-errors "caca >= 0.99beta14 cucul >= 0.99beta14 ") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"caca >= 0.99beta13 cucul >= 0.99beta13 \"") >&5
++  ($PKG_CONFIG --exists --print-errors "caca >= 0.99beta13 cucul >= 0.99beta13 ") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_CACA_CFLAGS=`$PKG_CONFIG --cflags "caca >= 0.99beta14 cucul >= 0.99beta14 " 2>/dev/null`
++  pkg_cv_CACA_CFLAGS=`$PKG_CONFIG --cflags "caca >= 0.99beta13 cucul >= 0.99beta13 " 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -26537,12 +26543,12 @@
+         pkg_cv_CACA_LIBS="$CACA_LIBS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"caca >= 0.99beta14 cucul >= 0.99beta14 \"") >&5
+-  ($PKG_CONFIG --exists --print-errors "caca >= 0.99beta14 cucul >= 0.99beta14 ") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"caca >= 0.99beta13 cucul >= 0.99beta13 \"") >&5
++  ($PKG_CONFIG --exists --print-errors "caca >= 0.99beta13 cucul >= 0.99beta13 ") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_CACA_LIBS=`$PKG_CONFIG --libs "caca >= 0.99beta14 cucul >= 0.99beta14 " 2>/dev/null`
++  pkg_cv_CACA_LIBS=`$PKG_CONFIG --libs "caca >= 0.99beta13 cucul >= 0.99beta13 " 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -26561,9 +26567,9 @@
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        CACA_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "caca >= 0.99beta14 cucul >= 0.99beta14 "`
++	        CACA_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "caca >= 0.99beta13 cucul >= 0.99beta13 "`
+         else
+-	        CACA_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "caca >= 0.99beta14 cucul >= 0.99beta14 "`
++	        CACA_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "caca >= 0.99beta13 cucul >= 0.99beta13 "`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$CACA_PKG_ERRORS" >&5
+@@ -29191,6 +29197,8 @@
        fi
         CFLAGS="$ac_save_CFLAGS"
         LIBS="$ac_save_LIBS"
@@ -31,7 +75,7 @@
    fi
  
    if test "x$no_libFLAC" = "x" ; then
-@@ -50370,7 +50378,7 @@
+@@ -42228,7 +42236,7 @@
  
  xinelibdir='${libdir}/xine'
  xinedatadir='${datadir}/xine'
