- Separate TeX style files from math/gnuplot into math/gnuplot-tex-extras   to eliminate huge TeXLive dependency.  Note that TeX terminal support is   still enabled by default because it works without them.
- Add Lua dependency to support TeX/Tikz terminal.

Approved by:	glewis (maintainer)

diff --git a/math/gnuplot/files/patch-configure b/math/gnuplot/files/patch-configure
--- a/math/gnuplot/files/patch-configure
+++ b/math/gnuplot/files/patch-configure
@@ -1,6 +1,6 @@
---- configure.orig
-+++ configure
-@@ -5919,7 +5919,7 @@
+--- configure.orig	2014-09-22 03:26:10.000000000 +0900
++++ configure	2014-12-06 14:27:21.000000000 +0900
+@@ -5982,7 +5982,7 @@
  fi
  
  
@@ -9,3 +9,100 @@
  then
    CC=${CC-${host_alias-gcc}}
    CFLAGS=${CFLAGS-"-g -O2"}
+@@ -10844,12 +10844,12 @@
+         pkg_cv_LUA_CFLAGS="$LUA_CFLAGS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua5.1\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "lua5.1") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua-${LUA_VER}\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "lua-${LUA_VER}") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_LUA_CFLAGS=`$PKG_CONFIG --cflags "lua5.1" 2>/dev/null`
++  pkg_cv_LUA_CFLAGS=`$PKG_CONFIG --cflags "lua-${LUA_VER}" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -10862,12 +10862,12 @@
+         pkg_cv_LUA_LIBS="$LUA_LIBS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua5.1\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "lua5.1") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua-${LUA_VER}\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "lua-${LUA_VER}") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_LUA_LIBS=`$PKG_CONFIG --libs "lua5.1" 2>/dev/null`
++  pkg_cv_LUA_LIBS=`$PKG_CONFIG --libs "lua-${LUA_VER}" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -10886,9 +10886,9 @@
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        LUA_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "lua5.1"`
++	        LUA_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "lua-${LUA_VER}"`
+         else
+-	        LUA_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "lua5.1"`
++	        LUA_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "lua-${LUA_VER}"`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$LUA_PKG_ERRORS" >&5
+@@ -10920,12 +10920,12 @@
+         pkg_cv_LUA_CFLAGS="$LUA_CFLAGS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua5.1\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "lua5.1") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua-${LUA_VER}\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "lua-${LUA_VER}") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_LUA_CFLAGS=`$PKG_CONFIG --cflags "lua5.1" 2>/dev/null`
++  pkg_cv_LUA_CFLAGS=`$PKG_CONFIG --cflags "lua-${LUA_VER}" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -10938,12 +10938,12 @@
+         pkg_cv_LUA_LIBS="$LUA_LIBS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua5.1\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "lua5.1") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua-${LUA_VER}\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "lua-${LUA_VER}") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_LUA_LIBS=`$PKG_CONFIG --libs "lua5.1" 2>/dev/null`
++  pkg_cv_LUA_LIBS=`$PKG_CONFIG --libs "lua-${LUA_VER}" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -10962,9 +10962,9 @@
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        LUA_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "lua5.1"`
++	        LUA_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "lua-${LUA_VER}"`
+         else
+-	        LUA_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "lua5.1"`
++	        LUA_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "lua-${LUA_VER}"`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$LUA_PKG_ERRORS" >&5
+@@ -11024,7 +11024,7 @@
+   return 0;
+ }
+ _ACEOF
+-for ac_lib in '' lua lua5.1; do
++for ac_lib in '' lua lua-${LUA_VER}; do
+   if test -z "$ac_lib"; then
+     ac_res="none required"
+   else
