Update to 2.14.1.

diff --git a/x11-toolkits/py-gnome-extras/files/patch-configure b/x11-toolkits/py-gnome-extras/files/patch-configure
--- a/x11-toolkits/py-gnome-extras/files/patch-configure
+++ b/x11-toolkits/py-gnome-extras/files/patch-configure
@@ -1,10 +1,19 @@
---- configure.orig	Fri Nov 11 21:36:37 2005
-+++ configure	Fri Nov 11 21:36:55 2005
-@@ -21713,6 +21713,7 @@
- case $mozpackage in
+--- configure.orig	Tue Jul 11 11:39:00 2006
++++ configure	Tue Jul 11 11:43:03 2006
+@@ -19275,7 +19275,7 @@ echo "${ECHO_T}$PYGTK_DEFSDIR" >&6
+ 
+ echo "$as_me:$LINENO: checking for gnome-python defs" >&5
+ echo $ECHO_N "checking for gnome-python defs... $ECHO_C" >&6
+-PYGTK_DEFSDIR=`$PKG_CONFIG --variable=defsdir gnome-python-2.0`
++GNOME_PYTHON_DEFSDIR=`$PKG_CONFIG --variable=defsdir gnome-python-2.0`
+ 
+ echo "$as_me:$LINENO: result: $GNOME_PYTHON_DEFSDIR" >&5
+ echo "${ECHO_T}$GNOME_PYTHON_DEFSDIR" >&6
+@@ -20762,6 +20762,7 @@ case $mozpackage in
+      xulrunner) mozpackage_required_version=1.8 ;;
       firefox) mozpackage_required_version=1.0 ;;
       mozilla) mozpackage_required_version=1.2b ;;
 +     seamonkey) mozpackage_required_version=1.2b ;;
-      *) { { echo "$as_me:$LINENO: error: --with-gtkmozembed argument must be either 'mozilla' or 'firefox'" >&5
- echo "$as_me: error: --with-gtkmozembed argument must be either 'mozilla' or 'firefox'" >&2;}
+      *) { { echo "$as_me:$LINENO: error: --with-gtkmozembed argument must be either 'mozilla', 'firefox', or 'xulrunner'" >&5
+ echo "$as_me: error: --with-gtkmozembed argument must be either 'mozilla', 'firefox', or 'xulrunner'" >&2;}
     { (exit 1); exit 1; }; }
