Fix build.
Submitted by:	QAT

diff --git a/databases/libmemcached/files/patch-configure b/databases/libmemcached/files/patch-configure
--- a/databases/libmemcached/files/patch-configure
+++ b/databases/libmemcached/files/patch-configure
@@ -1,5 +1,5 @@
 --- configure.orig	2009-03-30 13:26:57.000000000 +0800
-+++ configure	2009-03-31 15:55:57.000000000 +0800
++++ configure	2009-03-31 16:57:35.000000000 +0800
 @@ -21054,7 +21054,7 @@
  
      { $as_echo "$as_me:$LINENO: result: $have_htoll" >&5
@@ -26,7 +26,7 @@
    then
      MEMC_BINARY=memcached
    fi
-@@ -21454,7 +21454,7 @@
+@@ -21454,11 +21454,10 @@
  fi
  
  
@@ -34,4 +34,9 @@
 +if test $MEMC_BINARY = "no"
  then
    { { $as_echo "$as_me:$LINENO: error: \"could not find memcached binary\"" >&5
- $as_echo "$as_me: error: \"could not find memcached binary\"" >&2;}
+-$as_echo "$as_me: error: \"could not find memcached binary\"" >&2;}
+-   { (exit 1); exit 1; }; }
++$as_echo "$as_me: error: \"could not find memcached binary\"" >&2;} }
+ fi
+ 
+ 
