On system without ptex2 and platex, after doing ``make install'' in platex, ``make package'' in ptex2 failed.  It happend as:
``Make install'' led to ``make install'' in ptex2 and it installed old
LaTeX files which ptex2 doesn't seem to use.  However, they seem to be
necessary for platex to generate newer pLaTeX files.  Before
installing new files, pLaTex removes old files, and that causes some
files for ptex2 package to be missing.

To solve this problem, ptex2 now doesn't install old LaTeX files and
instead, platex port installs them.

The Bug Found by:	asami

Moved around some lines to standardize Makefile.

Simplify character code dependent conditionals.

diff --git a/japanese/ptex-base/Makefile b/japanese/ptex-base/Makefile
--- a/japanese/ptex-base/Makefile
+++ b/japanese/ptex-base/Makefile
@@ -3,7 +3,7 @@
 # Date created:		5 Nov 1995
 # Whom:			Hideaki Ohmon <ohmon@sfc.keio.ac.jp>
 #
-# $Id: Makefile,v 1.10 1996/09/17 15:07:50 max Exp $
+# $Id: Makefile,v 1.11 1996/11/02 20:23:57 max Exp $
 #
 
 DISTNAME=	ptex3.1415.p2.1.4
@@ -11,9 +11,8 @@ PKGNAME=	jp-ptex-2.1.4
 CATEGORIES+=	japanese print
 MASTER_SITES=			ftp://ftp.ascii.co.jp/pub/TeX/ascii-ptex/ \
 		ftp://ftp.ascii.co.jp/pub/TeX/ascii-ptex/corresponding-sources/ \
-ftp://bash.cc.keio.ac.jp/pub/TeX/ascii-ptex/ \
+		ftp://bash.cc.keio.ac.jp/pub/TeX/ascii-ptex/ \
 		ftp://bash.cc.keio.ac.jp/pub/TeX/ascii-ptex/corresponding-sources/ 
-
 # ptex-2.1.4.tar.gz, plib-jis.tar.gz,  plib-sj.tar.gz and  plib-euc.tar.gz 
 # are in */ascii-ptex/ and
 # web-6.1.tar.gz, web2c-6.1.tar.gz, web2c.kpathsea-2.6.help, 
@@ -30,6 +29,16 @@ MAINTAINER=	max@FreeBSD.ORG
 GNU_CONFIGURE=	yes
 WRKSRC=		${WRKDIR}/kpathsea-2.6
 STRIP=		# some shell scripts
+
+BINARIES=kpsewhich dvicopy dvitype pdvitype gftodvi gftopk \
+	mft pktogf pktype vftovp vptovf gftype pltotf tftopl initex \
+	virtex patgen iniptex virptex inimf virmf bibtex jbibtex \
+	tangle weave pooltype
+
+MANPAGES=amslatex.1 amstex.1 bibtex.1 dvitype.1 etex.1 gftodvi.1 \
+	gftopk.1 gftype.1 initex.1 lamstex.1 latex.1 mf.1 mft.1 \
+	patgen.1 pktogf.1 pktype.1 pltotf.1 pooltype.1 slitex.1 \
+	tangle.1 tex.1 tftopl.1 vftovp.1 virtex.1 vptovf.1 weave.1
 
 pre-fetch:
 .if !defined(KANJI-CODE)
@@ -50,100 +59,61 @@ pre-fetch:
 	        ;; \
 	  esac)
 .endif
-
 KANJI-CODE=	JIS
 .endif
 .if ${KANJI-CODE} == JIS
-DISTFILES+=	plib-jis.tar.gz
-EXTRACT_ONLY+=  plib-jis.tar.gz
-.endif
-.if ${KANJI-CODE} == SJIS
-DISTFILES+=	plib-sj.tar.gz
-EXTRACT_ONLY+=  plib-sj.tar.gz
-.endif
-.if ${KANJI-CODE} == EUC
-DISTFILES+=	plib-euc.tar.gz
-EXTRACT_ONLY+=  plib-euc.tar.gz
-.endif
-.if ${KANJI-CODE} != JIS && ${KANJI-CODE} != SJIS && ${KANJI-CODE} != EUC
+LIB_FILE=	plib-jis.tar.gz
+.elif ${KANJI-CODE} == SJIS
+LIB_FILE=	plib-sj.tar.gz
+.elif ${KANJI-CODE} == EUC
+LIB_FILE=	plib-euc.tar.gz
+.elifdef KANJI-CODE
 	@echo "Error: invalid value for KANJI-CODE: \"${KANJI-CODE}\""
 	@echo "Possible values are: JIS (default), SJIS, EUC."
-	exit 1
+	@false
 .endif
+DISTFILES+=	${LIB_FILE}
+EXTRACT_ONLY+=	${LIB_FILE}
 
 post-extract:
 	@mv ${WRKDIR}/web2c-6.1/web2c ${WRKDIR}/xdvik-18f
 	@mv ${WRKDIR}/xdvik-18f ${WRKDIR}/kpathsea-2.6
-	@rm -fr ${WRKDIR}/web2c-6.1 ${WRKDIR}/kpathsea-2.6/xdvik
+	@${RM} -fr ${WRKDIR}/web2c-6.1 ${WRKDIR}/kpathsea-2.6/xdvik
 
 pre-patch:
-	@(cd ${WRKSRC} ; \
-	patch -p -s < ${DISTDIR}/web2c.kpathsea-2.6.help)
+	@${PATCH} -p -s -d ${WRKSRC} < ${DISTDIR}/web2c.kpathsea-2.6.help
 
 pre-configure:
-.if ${KANJI-CODE} == JIS
-	@(cd ${WRKDIR}/ptex-2.1.4 ; ./pTeXsetup -jis)
-.endif
-.if ${KANJI-CODE} == SJIS
-	@(cd ${WRKDIR}/ptex-2.1.4 ; ./pTeXsetup -sjis)
-.endif
-.if ${KANJI-CODE} == EUC
-	@(cd ${WRKDIR}/ptex-2.1.4 ; ./pTeXsetup -euc)
-.endif
+	(cd ${WRKDIR}/ptex-2.1.4 ; \
+	  ./pTeXsetup -`echo ${KANJI-CODE} | tr A-Z a-z`)
 
 post-configure:
 	@touch ${WRKSRC}/web2c/web/tangleboot.p
 	@touch ${WRKSRC}/web2c/web/tangleboot.[ch]
 
 do-build:
-	(cd ${WRKSRC} ; make)
+	@(cd ${WRKSRC} ; ${MAKE})
 
 pre-install:
 .if !defined(BATCH)
-	@echo "***********************************************************"
-	@echo "*                      W a r n i n g                      *"
-	@echo "* This port will overwrite the existing tex installation. *"
-	@echo "***********************************************************"
-	@echo -n "Is this ok? (y/n) ==> "
-	@(read ans; \
-	  case x"$$ans" in \
-	    xy*|xY*) \
-	        return 0; \
-	        ;; \
-	    *) \
-	        echo "Okay, I won't install it then...."; \
-	        echo "(Don't worry about the following \"*** Error code 1\"s)"; \
-	        return 1; \
-	        ;; \
-	  esac)
+	@/bin/sh ${PKGDIR}/REQ ${PKGNAME} INSTALL || \
+	(echo "(Don't worry about the following \"*** Error code 1\"s)" ; \
+	 exit 1)
 .endif
-	@(cd ${PREFIX}/lib ; gzip -dc ${DISTDIR}/lib-6.9.tar.gz | tar xf -)
-.if ${KANJI-CODE} == JIS
-	@(cd ${PREFIX}/lib ; gzip -dc ${DISTDIR}/plib-jis.tar.gz | tar xf -)
-.endif
-.if ${KANJI-CODE} == SJIS
-	@(cd ${PREFIX}/lib ; gzip -dc ${DISTDIR}/plib-sj.tar.gz | tar xf -)
-.endif
-.if ${KANJI-CODE} == EUC
-	@(cd ${PREFIX}/lib ; gzip -dc ${DISTDIR}/plib-euc.tar.gz | tar xf -)
-.endif
-
-BINARIES=kpsewhich dvicopy dvitype pdvitype gftodvi gftopk \
-	mft pktogf pktype vftovp vptovf gftype pltotf tftopl initex \
-	virtex patgen iniptex virptex inimf virmf bibtex jbibtex \
-	tangle weave pooltype
-
-MANPAGES=amslatex.1 amstex.1 bibtex.1 dvitype.1 etex.1 gftodvi.1 \
-	gftopk.1 gftype.1 initex.1 lamstex.1 latex.1 mf.1 mft.1 \
-	patgen.1 pktogf.1 pktype.1 pltotf.1 pooltype.1 slitex.1 \
-	tangle.1 tex.1 tftopl.1 vftovp.1 virtex.1 vptovf.1 weave.1
+	@(cd ${PREFIX}/lib ; tar zxf ${DISTDIR}/lib-6.9.tar.gz)
+	@${RM} -rf ${PREFIX}/lib/texmf/tex/latex2e/base/*
+	@(cd ${PREFIX}/lib ; tar zxf ${DISTDIR}/${LIB_FILE})
 
 post-install:
+	@echo -n "Stripping the binary files...."
 .for bin in ${BINARIES}
-	strip ${PREFIX}/bin/${bin}
+	@strip ${PREFIX}/bin/${bin}
 .endfor
+	@echo "done."
+	@echo -n "Compressing the man pages...."
 .for man in ${MANPAGES}
-	${COMPRESS_MAN} ${PREFIX}/man/man1/${man}
+	@${COMPRESS_MAN} ${PREFIX}/man/man1/${man}
 .endfor
+	@echo "done."
 
 .include <bsd.port.mk>
