Upgrade, 2.1.4 -> 2.1.5.
Note: This port installs only the character code independent files for pTeX
and this replaces japanese/ptex2.
Note #2 : Japanese/ptex2 has been repository copied to ptex-common by
Satoshi.

diff --git a/japanese/ptex-base/pkg-req b/japanese/ptex-base/pkg-req
--- a/japanese/ptex-base/pkg-req
+++ b/japanese/ptex-base/pkg-req
@@ -1,19 +1,35 @@
 #!/bin/sh
-if [ "$2" != "INSTALL" ]; then
+
+if [ $2 != INSTALL ]; then exit 0; fi
+
+BINDIR=${PKG_PREFIX}/bin
+for f in ${BINDIR}/MakeTeXMF ${BINDIR}/MakeTeXPK ${BINDIR}/MakeTeXTFM ${PKG_PREFIX}/share/texmf/web2c/texmf.cnf; do
+  if [ -f $f ]; then files_exist="${files_exist} $f"; fi
+done
+
+if [ -z "${files_exist}" ]; then exit 0; fi
+
+echo '************************************************************************'
+echo
+if [ "x$3" = "xBATCH" ]; then
+  echo 'Following files will be renamed to *.old:'
+ else
+  echo 'Files listed below already exist on this system:'
+fi
+echo
+for f in ${files_exist}; do echo $f; done
+echo
+if [ "x$3" != "xBATCH" ]; then
+  echo 'If you proceed, these files will be renamed to *.old and new files'
+  echo 'will be installed.'
+  read  -p 'Would you like to proceed? (y/N)> ' ans
+  case x$ans in
+    xy*|xY*) for f in ${files_exist} ;do mv -f $f ${f}.old; done; exit 0
+  esac
+
+  echo 'Aborting the installation.'
+  exit 1
+ else
+  for f in ${files_exist}; do mv -f $f ${f}.old; done
   exit 0
 fi
-echo "***********************************************************"
-echo "*                      W a r n i n g                      *"
-echo "* This port will overwrite the existing tex installation. *"
-echo "***********************************************************"
-echo -n "Is this ok? (y/n) ==> "
-read ans;
-case x"$ans" in
-  xy*|xY*)
-    return 0;
-    ;;
-  *)
-    echo "Okay, I won't install it then....";
-    return 1;
-    ;;
-esac
