Revert "www/tt-rss: Update to g20210423 e8f78181f"
This reverts commit ca4d4d01cf0aaa7cac65c813b188687825a7cce2.

Requested by maintainer.

diff --git a/www/tt-rss/files/ttrssd.in b/www/tt-rss/files/ttrssd.in
--- a/www/tt-rss/files/ttrssd.in
+++ b/www/tt-rss/files/ttrssd.in
@@ -22,14 +22,12 @@ load_rc_config "${name}"
 : ${ttrssd_enable="NO"}
 : ${ttrssd_local_db:="YES"}
 
-initdb_php="%%WWWDIR%%/update.php"
 required_files="%%WWWDIR%%/config.php"
 pidfile="/var/run/${name}.pid"
-ppidfile="/var/run/${name}_parent.pid"
 phpcli="%%LOCALBASE%%/bin/php"
 command_interpreter=$phpcli
 long_name="Tiny Tiny RSS updating feeds daemon."
-phpupd="%%WWWDIR%%/update_daemon2.php"
+phpupd="update_daemon2.php"
 ttrssd_log="/var/log/${name}.log"
 ttrssd_user="%%WWWOWN%%"
 
@@ -39,49 +37,40 @@ stop_cmd=${name}_stop
 
 %%MYSQL%%CHECK_CMD="%%LOCALBASE%%/bin/mysqladmin -u mysqld ping"
 %%MYSQL%%CHECK_MSG="${name}: mysqladmin command failed; mysql not ready?"
-%%PGSQL%%CHECK_CMD="%%LOCALBASE%%/bin/pg_isready"
+# Waiting for pg_isready when 9.3 is the default
+%%PGSQL%%CHECK_CMD="%%LOCALBASE%%/etc/rc.d/postgresql status"
 %%PGSQL%%CHECK_MSG="${name}: postgresql status failed; postgresql not ready?"
 
 ttrssd_start() {
-	if ! [ -x $phpcli ]; then
-		echo "$phpcli not found"
-		exit 1
-	fi
-
-	if [ -f $pidfile ]; then
-		echo "$name already running?"
-		exit 2
-	fi
-
+	[ -x $phpcli ] || (echo "$phpcli not found"; exit 1)
+	[ -f $pidfile ] && (echo "$name already running?"; exit 2)
 	echo "Starting $long_name"
-	daemon -P "$ppidfile" -p "$pidfile" -u "$ttrssd_user" -o "$ttrssd_log" \
-		sh -c "${initdb_php} --update-schema=force-yes; $phpupd"
+	(cd %%WWWDIR%% && su -fm $ttrssd_user -c "./$phpupd" > $ttrssd_log &) && \
+	echo $$ > $pidfile
 }
 
 ttrssd_stop() {
-	if ! [ -f $pidfile ]; then
-		echo "$name not running?"
-		exit 1
-	fi
-
+	[ -f $pidfile ] || (echo "$name not running?"; exit 1)
 	echo "Stopping $long_name"
-	pkill -CHLD -F "$pidfile"
-	pkill -F "$pidfile"
-	pwait "$(cat $ppidfile)"
+	kill `ps ax | grep $phpupd | grep -v grep | awk '{print $1}'`
+	rm -f $pidfile
 }
 
 ttrssd_prestart() {
-	if checkyesno ttrssd_local_db; then
-		# Wait for the local database to be started
+  if checkyesno ttrssd_local_db; then
+	# Wait for the local database to be started
+	local _count=0
 
-		for n in $(seq 1 10); do
-			if $CHECK_CMD > /dev/null 2>&1; then
-			    return
-			fi
-			sleep 1
-		done
-		err 1 $CHECK_MSG
-	fi
+	while : ; do
+		$CHECK_CMD > /dev/null 2>&1 && return
+		_count=$(( $_count + 1 ))
+		if [ $_count -gt 10 ]; then
+			err 1 $CHECK_MSG
+		fi
+
+		sleep 1
+	done
+  fi
 }
 
 run_rc_command "$1"
