MFH: r477620
Removed fastcgi, this is no longer supported in seafile 6.3+
and previous installs 6.3+ prior to this revision are broken
when using the seahub_fastcgi option.

Approved by:	portmgr (miwi@)

diff --git a/www/seahub/files/seahub.in b/www/seahub/files/seahub.in
--- a/www/seahub/files/seahub.in
+++ b/www/seahub/files/seahub.in
@@ -29,8 +29,6 @@
 # seafile_logdir (str):		Set to "" by default will use the path
 #				%%PREFIX%%/%%HAIWENDIR%%/logs.
 #				Set it to a different path.
-# seahub_fastcgi (bool):	Set to "NO" by default.
-#				Set to "YES" to start the fastcgi mode.
 # seahub_host (int):		Default is 127.0.0.1.
 # seahub_port (int):		Default is 8000.
 
@@ -55,16 +53,13 @@ clearsessions_cmd="seahub_clearsessions"
 : ${seafile_conf:="%%PREFIX%%/%%HAIWENDIR%%/conf"}
 : ${seafile_datadir:="`cat ${seafile_ccnet}/seafile.ini 2>/dev/null`"}
 : ${seafile_logdir:="%%PREFIX%%/%%HAIWENDIR%%/logs"}
-: ${seahub_fastcgi="NO"}
 : ${seahub_host:="127.0.0.1"}
 : ${seahub_port:="8000"}
 
 manage_py=${seafile_path}/seahub/manage.py
 gunicorn_exe=%%PREFIX%%/bin/gunicorn
-gunicorn_conf=${seafile_path}/runtime/seahub.conf
-pidfile=${seafile_path}/runtime/seahub.pid
-errorlog=${seafile_path}/runtime/error.log
-accesslog=${seafile_path}/runtime/access.log
+gunicorn_conf=${seafile_conf}/gunicorn.conf
+pidfile=%%PREFIX%%/%%HAIWENDIR%%/pids/seahub.pid
 
 command="%%PREFIX%%/bin/%%PYTHON%%"
 
@@ -126,44 +121,21 @@ seahub_clearsessions() {
 seahub_start()
 {
 	if checkyesno seahub_enable; then
-		if checkyesno seahub_fastcgi; then
-			echo "Starting seahub service fastcgi mode"
-			check_required_before;
-			before_start;
-
-	# Returns 127.0.0.1 if SEAFILE_FASTCGI_HOST is unset or hasn't got any value,
-	# otherwise returns value of SEAFILE_FASTCGI_HOST environment variable
-
-			echo "Starting seahub (fastcgi) at ${seahub_host}:${seahub_port} ..."
-			su -m "${seafile_user}" -c "$command \"${manage_py}\" runfcgi host=\"${seahub_host}\" port=\"${seahub_port}\" pidfile=$pidfile \
-			outlog=${accesslog} errlog=${errorlog}"
+		check_required_before;
+		before_start;
+		echo "Starting seahub at port ${seahub_port} ..."
+		su -m "${seafile_user}" -c "$command \"${gunicorn_exe}\" seahub.wsgi:application -c \"${gunicorn_conf}\" -b \"0.0.0.0:${seahub_port}\" --preload --chdir \"$seafile_path/seahub\""
 
 	# Ensure seahub is started successfully
-			sleep 5
-			if ! pgrep -f "${manage_py}" 1>/dev/null; then
-				printf "\033[33mError:Seahub failed to start.\033[m\n"
-				exit 1;
-			fi
-			echo
-			echo "Seahub is started"
-			echo
-		else
-			check_required_before;
-			before_start;
-			echo "Starting seahub at port ${seahub_port} ..."
-			su -m "${seafile_user}" -c "$command \"${gunicorn_exe}\" seahub.wsgi:application -c \"${gunicorn_conf}\" -b \"0.0.0.0:${seahub_port}\" --preload --chdir \"$seafile_path/seahub\""
-
-	# Ensure seahub is started successfully
-			sleep 5
-			if ! pgrep -f "seahub.wsgi:application" 2>/dev/null 1>&2; then
-				printf "\033[33mError:Seahub failed to start.\033[m\n"
-				echo "Please try to run \"./seahub.sh start\" again"
-				exit 1;
-			fi
-			echo
-			echo "Seahub is started"
-			echo
+		sleep 5
+		if ! pgrep -f "seahub.wsgi:application" 2>/dev/null 1>&2; then
+			printf "\033[33mError:Seahub failed to start.\033[m\n"
+			echo "Please try to run \"./seahub.sh start\" again"
+			exit 1;
 		fi
+		echo
+		echo "Seahub is started"
+		echo
 		else
 			return 0
 	fi
