Fix a long-standing bug that required scrollkeeper to build as root. Instead, make configure check for a file installed by docbook-sk, and move the catalog creation to a pre-install target.
Prompted by:	Andrew J Caines <A.J.Caines@halplant.com>
Tested by:	myself
		Andrew J Caines <A.J.Caines@halplant.com>

diff --git a/textproc/scrollkeeper/files/patch-configure b/textproc/scrollkeeper/files/patch-configure
--- a/textproc/scrollkeeper/files/patch-configure
+++ b/textproc/scrollkeeper/files/patch-configure
@@ -1,5 +1,5 @@
 --- configure.orig	Wed Jul 24 22:26:07 2002
-+++ configure	Thu Jan 16 02:24:32 2003
++++ configure	Fri Jan 31 17:58:10 2003
 @@ -5299,6 +5299,7 @@
  
  # This can be used to rebuild libtool when needed
@@ -8,22 +8,19 @@
  
  # Always use our own libtool.
  LIBTOOL='$(SHELL) $(top_builddir)/libtool'
-@@ -6277,14 +6278,14 @@
- 	
-         ;;
+@@ -6279,12 +6280,12 @@
     *)
--	echo $ac_n "checking for docbook-dtd412-xml""... $ac_c" 1>&6
--echo "configure:6282: checking for docbook-dtd412-xml" >&5
+ 	echo $ac_n "checking for docbook-dtd412-xml""... $ac_c" 1>&6
+ echo "configure:6282: checking for docbook-dtd412-xml" >&5
 -	if xmlcatalog /etc/xml/catalog "-//OASIS//DTD DocBook XML V4.1.2//EN" | grep "No entry" >/dev/null ; then
-+	echo $ac_n "checking for docbook-dtd412-xml""... $ac_c" 1>&6
-+echo "configure:6282: checking for docbook-dtd412-xml" >&5
-+	if test ! -f $LOCALBASE/share/sk/docbook/catalog ; then
++if test ! -f $LOCALBASE/share/sk/docbook/4.1.2/docbook.cat ; then
  		echo "* ERROR * "
  		echo " "
- 		echo "Couldn't find the DocBook XML V4.1.2 DTD.  Please make sure that you have the docbook-dtd412-xml package installed. If it is installed, the package probably did not register the DTD in the catalog properly. Consult http://scrollkeeper.sourceforge.net/docbook.shtml for more information."
+-		echo "Couldn't find the DocBook XML V4.1.2 DTD.  Please make sure that you have the docbook-dtd412-xml package installed. If it is installed, the package probably did not register the DTD in the catalog properly. Consult http://scrollkeeper.sourceforge.net/docbook.shtml for more information."
++		echo "Couldn't find the DocBook XML V4.1.2 DTD.  Please make sure that you have the docbook-dtd412-xml package installed."
  		echo " "
 -		{ echo "configure: error: DocBook XML V4.1.2 DTD not present in /etc/xml/catalog. Make sure docbook-dtd412-xml is installed and registers DTD in catalog." 1>&2; exit 1; }
-+		{ echo "configure: error: DocBook XML V4.1.2 DTD not present in $LOCALBASE/share/sk. Make sure docbook-dtd412-xml is installed and registers DTD in catalog." 1>&2; exit 1; }
++		{ echo "configure: error: DocBook XML V4.1.2 DTD not present in $LOCALBASE/share/sk. Make sure docbook-dtd412-xml is installed." 1>&2; exit 1; }
  	fi
  	echo "$ac_t""found" 1>&6
  	;;
