Convert scrollkeeper over to use the system catalog location.  This helps to unbreak gtk-doc as well as removes a ton of gross hacks to support the old location.  Also, import some CVS patches from SK to fix some potential crashes when installing bad catalogs.
While I tested this with a full SK database rebuild, problems may still
occur.  Please let me know if you encounter any issues with OMF files
after this commit.

diff --git a/textproc/scrollkeeper/files/patch-configure b/textproc/scrollkeeper/files/patch-configure
--- a/textproc/scrollkeeper/files/patch-configure
+++ b/textproc/scrollkeeper/files/patch-configure
@@ -13,7 +13,7 @@
  	echo "$as_me:$LINENO: checking for docbook-dtd412-xml" >&5
  echo $ECHO_N "checking for docbook-dtd412-xml... $ECHO_C" >&6
 -	if xmlcatalog /etc/xml/catalog "-//OASIS//DTD DocBook XML V4.1.2//EN" | grep "No entry" >/dev/null ; then
-+	if test ! -f $LOCALBASE/share/sk/docbook/4.1.2/docbook.cat ; then
++	if test ! -f $LOCALBASE/share/xml/docbook/4.1.2/docbook.cat ; then
  		echo "* ERROR * "
  		echo " "
 -		echo "Couldn't find the DocBook XML V4.1.2 DTD.  Please make sure that you have the docbook-dtd412-xml package installed. If it is installed, the package probably did not register the DTD in the catalog properly. Consult http://scrollkeeper.sourceforge.net/docbook.shtml for more information."
@@ -21,8 +21,8 @@
  		echo " "
 -		{ { echo "$as_me:$LINENO: error: DocBook XML V4.1.2 DTD not present in /etc/xml/catalog. Make sure docbook-dtd412-xml is installed and registers DTD in catalog." >&5
 -echo "$as_me: error: DocBook XML V4.1.2 DTD not present in /etc/xml/catalog. Make sure docbook-dtd412-xml is installed and registers DTD in catalog." >&2;}
-+		{ { echo "$as_me:$LINENO: error: DocBook XML V4.1.2 DTD not present in $LOCALBASE/share/sk. Make sure docbook-dtd412-xml is installed and registers DTD in catalog." >&5
-+echo "$as_me: error: DocBook XML V4.1.2 DTD not present in $LOCALBASE/share/sk. Make sure docbook-dtd412-xml is installed and registers DTD in catalog." >&2;}
++		{ { echo "$as_me:$LINENO: error: DocBook XML V4.1.2 DTD not present in $LOCALBASE/share/xml. Make sure docbook-dtd412-xml is installed and registers DTD in catalog." >&5
++echo "$as_me: error: DocBook XML V4.1.2 DTD not present in $LOCALBASE/share/xml. Make sure docbook-dtd412-xml is installed and registers DTD in catalog." >&2;}
     { (exit 1); exit 1; }; }
  	fi
  	echo "$as_me:$LINENO: result: found" >&5
