Attempt to detect docbook-xml while package building.
Submitted by:	bento

diff --git a/textproc/scrollkeeper/files/patch-configure b/textproc/scrollkeeper/files/patch-configure
--- a/textproc/scrollkeeper/files/patch-configure
+++ b/textproc/scrollkeeper/files/patch-configure
@@ -1,5 +1,5 @@
---- configure.orig	Mon Jun  3 13:49:14 2002
-+++ configure	Mon Jun  3 13:50:53 2002
+--- configure.orig	Wed Jul 24 22:26:07 2002
++++ configure	Sun Jul 28 13:37:50 2002
 @@ -5299,6 +5299,7 @@
  
  # This can be used to rebuild libtool when needed
@@ -8,15 +8,21 @@
  
  # Always use our own libtool.
  LIBTOOL='$(SHELL) $(top_builddir)/libtool'
-@@ -6279,7 +6280,7 @@
+@@ -6279,12 +6280,12 @@
     *)
  	echo $ac_n "checking for docbook-dtd412-xml""... $ac_c" 1>&6
  echo "configure:6282: checking for docbook-dtd412-xml" >&5
 -	if xmlcatalog /etc/xml/catalog "-//OASIS//DTD DocBook XML V4.1.2//EN" | grep "No entry" >/dev/null ; then
-+	if xmlcatalog $LOCALBASE/share/xml/catalog "-//OASIS//DTD DocBook XML V4.1.2//EN" | grep "No entry" >/dev/null ; then
++	if test ! -f $LOCALBASE/share/xml/docbook/catalog ; then
  		echo "* ERROR * "
  		echo " "
  		echo "Couldn't find the DocBook XML V4.1.2 DTD.  Please make sure that you have the docbook-dtd412-xml package installed. If it is installed, the package probably did not register the DTD in the catalog properly. Consult http://scrollkeeper.sourceforge.net/docbook.shtml for more information."
+ 		echo " "
+-		{ echo "configure: error: DocBook XML V4.1.2 DTD not present in /etc/xml/catalog. Make sure docbook-dtd412-xml is installed and registers DTD in catalog." 1>&2; exit 1; }
++		{ echo "configure: error: DocBook XML V4.1.2 DTD not present in $LOCALBASE/share/xml. Make sure docbook-dtd412-xml is installed and registers DTD in catalog." 1>&2; exit 1; }
+ 	fi
+ 	echo "$ac_t""found" 1>&6
+ 	;;
 @@ -7181,7 +7182,7 @@
      else
              echo $ac_n "checking version of bison""... $ac_c" 1>&6
