x11/workrave: Update 1.10.50 => 1.10.53, take maintainership
Changelogs:
https://github.com/rcaelers/workrave/blob/v1_10_53/NEWS

PR:	289346

diff --git a/x11/workrave/files/patch-configure b/x11/workrave/files/patch-configure
--- a/x11/workrave/files/patch-configure
+++ b/x11/workrave/files/patch-configure
@@ -1,8 +1,8 @@
 Fix bashism and force GStreamer 1.x support
 
---- configure.orig	2020-03-08 02:42:31 UTC
+--- configure.orig	2025-08-25 23:15:55 UTC
 +++ configure
-@@ -20993,7 +20993,7 @@ then
+@@ -22713,7 +22713,7 @@ then
  
      loop=${enable_monitors},
  
@@ -11,23 +11,23 @@ Fix bashism and force GStreamer 1.x support
      do
          monitor=${loop%%\,*}
          loop=${loop#*\,}
-@@ -24438,44 +24438,9 @@ config_gstreamer=no
+@@ -26195,44 +26195,10 @@ config_gstreamer=no
  if test "x$enable_gstreamer" != "xno";
  then
  
 -pkg_failed=no
 +pkg_failed=yes
- { $as_echo "$as_me:${as_lineno-$LINENO}: checking for GSTREAMER" >&5
- $as_echo_n "checking for GSTREAMER... " >&6; }
--
+ { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for gstreamer-0.10" >&5
+ printf %s "checking for gstreamer-0.10... " >&6; }
+ 
 -if test -n "$GSTREAMER_CFLAGS"; then
 -    pkg_cv_GSTREAMER_CFLAGS="$GSTREAMER_CFLAGS"
 - elif test -n "$PKG_CONFIG"; then
 -    if test -n "$PKG_CONFIG" && \
--    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gstreamer-0.10\""; } >&5
+-    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gstreamer-0.10\""; } >&5
 -  ($PKG_CONFIG --exists --print-errors "gstreamer-0.10") 2>&5
 -  ac_status=$?
--  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+-  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
 -  test $ac_status = 0; }; then
 -  pkg_cv_GSTREAMER_CFLAGS=`$PKG_CONFIG --cflags "gstreamer-0.10" 2>/dev/null`
 -		      test "x$?" != "x0" && pkg_failed=yes
@@ -41,10 +41,10 @@ Fix bashism and force GStreamer 1.x support
 -    pkg_cv_GSTREAMER_LIBS="$GSTREAMER_LIBS"
 - elif test -n "$PKG_CONFIG"; then
 -    if test -n "$PKG_CONFIG" && \
--    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gstreamer-0.10\""; } >&5
+-    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gstreamer-0.10\""; } >&5
 -  ($PKG_CONFIG --exists --print-errors "gstreamer-0.10") 2>&5
 -  ac_status=$?
--  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+-  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
 -  test $ac_status = 0; }; then
 -  pkg_cv_GSTREAMER_LIBS=`$PKG_CONFIG --libs "gstreamer-0.10" 2>/dev/null`
 -		      test "x$?" != "x0" && pkg_failed=yes
