- rc script enhancements - pass maintainership - bump PORTREVISION
PR:		196090
Submitted by:	geoffroy desvernay <dgeo at centrale-marseille.fr>

diff --git a/mail/mailgraph/files/mailgraph.in b/mail/mailgraph/files/mailgraph.in
--- a/mail/mailgraph/files/mailgraph.in
+++ b/mail/mailgraph/files/mailgraph.in
@@ -17,14 +17,18 @@ rcvar=mailgraph_enable
 
 command=%%PREFIX%%/sbin/${name}.pl
 command_args='> /dev/null 2>&1'
-command_interpreter=/usr/bin/perl
+command_interpreter=%%PERL%%
 start_precmd=start_precmd
 stop_postcmd=stop_postcmd
 
 start_precmd()
 {
-    mkdir -p "%%DATADIR%%"
-    chown "%%MAILGRAPH_USER%%" "%%DATADIR%%"
+    mkdir -p "$mailgraph_chdir"
+    chown "$mailgraph_user" "$mailgraph_chdir"
+    if ! su -m '$mailgraph_user' -c 'sh -c "[ -r '$mailgraph_maillog' ]"'; then
+        echo "MAILGRAPH CANNOT RUN: $mailgraph_maillog not readable by $mailgraph_user"
+        return 1
+    fi
 }
 
 stop_postcmd()
@@ -35,10 +39,11 @@ stop_postcmd()
 load_rc_config $name
 
 : ${mailgraph_enable="NO"}
-: ${mailgraph_pidfile="%%DATADIR%%/mailgraph.pid"}
-: ${mailgraph_flags="--logfile /var/log/maillog --daemon-rrd=%%DATADIR%% --ignore-localhost --daemon --daemon-pid=${mailgraph_pidfile}"}
-: ${mailgraph_user="%%MAILGRAPH_USER%%"}
 : ${mailgraph_chdir="%%DATADIR%%"}
+: ${mailgraph_pidfile="$mailgraph_chdir/mailgraph.pid"}
+: ${mailgraph_maillog="/var/log/maillog"}
+: ${mailgraph_flags="--logfile $mailgraph_maillog --daemon-rrd=$mailgraph_chdir --ignore-localhost --daemon --daemon-pid=$mailgraph_pidfile"}
+: ${mailgraph_user="%%MAILGRAPH_USER%%"}
 
 pidfile=${mailgraph_pidfile}
 
