Security fix:  update to the latest versions:  7.1 for American English; and 7.02 for French, German, Japanese, and Brazilian Portuguese.  These are reportedly free of the onunload referrer bug (#145579 in bugzilla).
The Sun Java plugin is no longer available from the same places.
AIM is needed by the 7.02 versions.  The DOM inspector and "venkman"
JavaScript debugger are available for 7.1.

Compress generated files with bzip2; omit "linux-" from their names.

The RDF files provided by the ports are no longer needed.

Update references to Netscape 6.

Run chmod to fix permissions on extracted files (for the Portuguese
slave port).

Remove unneeded XXXchecksum target.

Change the configuration process, so that extraneous files are not
downloaded.  This resolves PR 44101, submitted by Fernan Aguero.

diff --git a/japanese/netscape7/scripts/configure b/japanese/netscape7/scripts/configure
--- a/japanese/netscape7/scripts/configure
+++ b/japanese/netscape7/scripts/configure
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $FreeBSD: /tmp/pcvs/ports/japanese/netscape7/scripts/Attic/configure,v 1.3 2002-10-14 13:50:20 trevor Exp $
+# $FreeBSD: /tmp/pcvs/ports/japanese/netscape7/scripts/Attic/configure,v 1.4 2003-07-03 09:55:02 trevor Exp $
 
 echo ${WRKSRC}/components.conf
 if [ -f ${WRKSRC}/components.conf ]; then
@@ -11,14 +11,13 @@ tempfile=`/usr/bin/mktemp -t checklist`
 
 if [ -z "${BATCH}" ]; then
 
-/usr/bin/dialog --title "Netscape 6 component selection" --clear \
+/usr/bin/dialog --title "Netscape 7 component selection" --clear \
 	--checklist "\n\
-Choose components of Netscape 6 to download and install. \n\
+Choose components of Netscape 7 to download and install. \n\
 Press the space bar to toggle selections." -1 -1 10 \
 "browser"	"Web browser"				ON \
 "defljajp"	"Japanese/Japan profile defaults"	ON \
 "flash"		"Flash plugin"				ON \
-"jre"		"Java plugin (requires linux_base-6"	ON \
 "langjajp"	"Japanese/Japan language pack"		ON \
 "mail"		"e-mail and news"			ON \
 "regjp"		"regional settings for Japan"		ON \
@@ -53,3 +52,7 @@ echo "$choice" \
 	| perl -pi -e "s/ /\n/g" \
 	> ${WRKSRC}/components.conf
 fi
+
+echo "* Your choices are saved.  You must run the \"make\" command again to"
+echo "* complete the build.  Ignore the \"Error code 1\" below."
+exit 1
diff --git a/www/netscape7/scripts/configure b/www/netscape7/scripts/configure
--- a/www/netscape7/scripts/configure
+++ b/www/netscape7/scripts/configure
@@ -14,18 +14,19 @@ if [ -z "${BATCH}" ]; then
 
 /usr/bin/dialog --title "Netscape 7 component selection" --clear \
 	--checklist "\n\
-Choose components of Netscape 7 to install. \n\
+Choose components of Netscape 7 to download and install. \n\
 Press the space bar to toggle selections." -1 -1 12 \
-"browser"	"Web browser (8448 kB)"				ON \
+"browser"	"Web browser (10016 kB)"			ON \
 "deflenus"	"American English profile defaults (26 kB)"	ON \
 "flash"		"Flash plugin (576 kB)"				ON \
-"jre"		"Java plugin (28592 kB) needs linux_base-6"	OFF \
-"langenus"	"American English language pack (800 kB)"	ON \
-"mail"		"e-mail and news (2064 kB)"			ON \
+"langenus"	"American English language pack (864 kB)"	ON \
+"mail"		"e-mail and news--requires browser (2064 kB)"	ON \
 "regca"		"regional settings for Canada (58 kB)"		ON \
 "regus"		"regional settings for the USA (60 kB)"		ON \
 "spellchecker"	"spell-checker (544 kB)"			ON \
 "talkback"	"sends bug reports to Netscape staff (832 kB)"	ON \
+"inspector"	"DOM inspector (154 kB)"			ON \
+"venkman"	"JavaScript debugger (224 kB)"			ON \
 2> /tmp/checklist.tmp.$$
 
 retval=$?
@@ -54,3 +55,7 @@ echo "$choice" \
 	| perl -pi -e "s/ /\n/g" \
 	> ${WRKSRC}/components.conf
 fi
+
+echo "* Your choices are saved.  You must run the \"make\" command again to"
+echo "* complete the build.  Ignore the \"Error code 1\" below."
+exit 1
