Don't try to look for the formail program, since it may fail if procmail is not present.
Submitted by:	Brett Taylor <brett@peloton.physics.montana.edu>

diff --git a/misc/dotfile/files/patch-ad b/misc/dotfile/files/patch-ad
--- a/misc/dotfile/files/patch-ad
+++ b/misc/dotfile/files/patch-ad
@@ -1,5 +1,5 @@
-*** Modules/procmail/configure.orig	Sun Dec 21 06:40:33 1997
---- Modules/procmail/configure	Sun Feb 22 18:11:20 1998
+*** Modules/procmail/configure.orig	Sun Dec 21 07:40:33 1997
+--- Modules/procmail/configure	Wed Feb 25 17:27:59 1998
 ***************
 *** 519,537 ****
   
@@ -29,3 +29,52 @@
   do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
   set dummy $ac_prog; ac_word=$2
+***************
+*** 571,616 ****
+  if test "$TCLSH" = no; then
+          { echo "configure: error: I couldn't find 'tclsh' please insert it into your pa
+  th and try again" 1>&2; exit 1; }
+- fi
+- 
+- for ac_prog in formail
+- do
+- # Extract the first word of "$ac_prog", so it can be a program name with args.
+- set dummy $ac_prog; ac_word=$2
+- echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+- echo "configure:582: checking for $ac_word" >&5
+- if eval "test \"`echo '$''{'ac_cv_path_FORMAIL'+set}'`\" = set"; then
+-   echo $ac_n "(cached) $ac_c" 1>&6
+- else
+-   case "$FORMAIL" in
+-   /*)
+-   ac_cv_path_FORMAIL="$FORMAIL" # Let the user override the test with a path.
+-   ;;
+-   *)
+-   IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
+-   for ac_dir in $PATH; do
+-     test -z "$ac_dir" && ac_dir=.
+-     if test -f $ac_dir/$ac_word; then
+-       ac_cv_path_FORMAIL="$ac_dir/$ac_word"
+-       break
+-     fi
+-   done
+-   IFS="$ac_save_ifs"
+-   ;;
+- esac
+- fi
+- FORMAIL="$ac_cv_path_FORMAIL"
+- if test -n "$FORMAIL"; then
+-   echo "$ac_t""$FORMAIL" 1>&6
+- else
+-   echo "$ac_t""no" 1>&6
+- fi
+- 
+- test -n "$FORMAIL" && break
+- done
+- 
+- if test "$FORMAIL" = ""; then
+-   { echo "configure: error: I couldn't find the program formail" 1>&2; exit 1; }
+  fi
+  
+  for ac_prog in sed
+--- 559,564 ----
