- Update to 20070218 - Make all cleanups and changes i made on security/clamav port - Add CURL and LDAP OPTION

diff --git a/security/clamav-devel/files/pkg-install.in b/security/clamav-devel/files/pkg-install.in
--- a/security/clamav-devel/files/pkg-install.in
+++ b/security/clamav-devel/files/pkg-install.in
@@ -2,69 +2,54 @@
 # $FreeBSD$
 
 PREFIX=${PKG_PREFIX:-%%PREFIX%%}
-DESTDIR=${PKG_DESTDIR:-}
 
 CLAMAVUSER=%%CLAMAVUSER%%
 CLAMAVGROUP=%%CLAMAVGROUP%%
 UID=106
 GID=$UID
 
-DBDIR=$DESTDIR%%DBDIR%%
-LOGDIR=$DESTDIR%%LOGDIR%%
-RUNDIR=$DESTDIR%%RUNDIR%%
+DBDIR=%%DBDIR%%
+LOGDIR=%%LOGDIR%%
+RUNDIR=%%RUNDIR%%
+
+PW="pw"
+CHOWN="chown"
+MKDIR="mkdir -p"
 
 if [ "$2" = "PRE-INSTALL" ]; then
 
-	if ! pw groupshow "$CLAMAVGROUP" 2>/dev/null 1>&2; then
-		if pw groupadd $CLAMAVGROUP -g $GID; then
-			echo "=> Added group \"$CLAMAVGROUP\"."
+	if ! ${PW} groupshow ${CLAMAVGROUP} 2>/dev/null 1>&2; then
+		if ${PW} groupadd ${CLAMAVGROUP} -g $GID; then
+			echo "=> Added group \"${CLAMAVGROUP}\"."
 		else
-			echo "=> Adding group \"$CLAMAVGROUP\" failed..."
+			echo "=> Adding group \"${CLAMAVGROUP}\" failed..."
 			exit 1
 		fi
 	fi
 
-	if ! pw usershow "$CLAMAVUSER" 2>/dev/null 1>&2; then
-		if pw useradd $CLAMAVUSER -u $UID -g $CLAMAVGROUP -h - \
+	if ! ${PW} usershow ${CLAMAVUSER} 2>/dev/null 1>&2; then
+		if ${PW} useradd ${CLAMAVUSER} -u $UID -g ${CLAMAVGROUP} -h - \
 			-s "/sbin/nologin" -d "/nonexistent" \
 			-c "Clam Antivirus"; \
 		then
-			pw groupmod mail -m $CLAMAVUSER
-			echo "=> Added user \"$CLAMAVUSER\"."
+			${PW} groupmod mail -m ${CLAMAVUSER}
+			echo "=> Added user \"${CLAMAVUSER}\"."
 		else
-			echo "=> Adding user \"$CLAMAVUSER\" failed..."
+			echo "=> Adding user \"${CLAMAVUSER}\" failed..."
 			exit 1
 		fi
 	fi
 
 elif [ "$2" = "POST-INSTALL" ]; then
 
-	if [ ! -d "$DBDIR" ]; then
-		mkdir -p "$DBDIR" || exit 1
-		chown "$CLAMAVUSER:$CLAMAVGROUP" "$DBDIR" || exit 1
-	fi
+	[ ! -d "${DBDIR}" ] && (${MKDIR} ${DBDIR} || exit 1)
+	${CHOWN} -R ${CLAMAVUSER}:${CLAMAVGROUP} ${DBDIR} || exit 1
 
-	if [ ! -d "$LOGDIR" ]; then
-		mkdir -p "$LOGDIR" || exit 1
-		chown "$CLAMAVUSER:$CLAMAVGROUP" "$LOGDIR" || exit 1
-	fi
+	[ ! -d "${LOGDIR}" ] && (${MKDIR} ${LOGDIR} || exit 1)
+	${CHOWN} -R ${CLAMAVUSER}:${CLAMAVGROUP} ${LOGDIR} || exit 1
 
-	if [ ! -d "$RUNDIR" ]; then
-		mkdir -p "$RUNDIR" || exit 1
-		chown "$CLAMAVUSER:$CLAMAVGROUP" "$RUNDIR" || exit 1
-	fi
-
-	if [ -f "$DESTDIR$PREFIX/etc/clamav.conf" ]; then
-		echo
-		echo "**************** WARNING ****************"
-		echo "*                                       *"
-		echo "*  The configuration file has changed:  *"
-		echo "* Please edit $PREFIX/etc/clamd.conf *"
-		echo "* and remove $PREFIX/etc/clamav.conf *"
-		echo "*                                       *"
-		echo "**************** WARNING ****************"
-		echo
-	fi
+	[ ! -d "${RUNDIR}" ] && (${MKDIR} ${RUNDIR} || exit 1)
+	${CHOWN} -R ${CLAMAVUSER}:${CLAMAVGROUP} ${RUNDIR} || exit 1
 
 fi
 
