Upgrade to 3.9.8

diff --git a/sysutils/screen/files/patch-ad b/sysutils/screen/files/patch-ad
--- a/sysutils/screen/files/patch-ad
+++ b/sysutils/screen/files/patch-ad
@@ -1,11 +1,50 @@
---- configure.orig	Mon Aug  2 15:26:53 1999
-+++ configure	Thu Oct 21 01:08:47 1999
-@@ -2706,7 +2706,7 @@
+--- configure.old	Wed Jun 14 18:04:30 2000
++++ configure	Tue Sep  5 19:26:25 2000
+@@ -2070,29 +2070,6 @@
+   cat conftest.$ac_ext >&5
+   rm -rf conftest*
+   olibs="$LIBS"
+-LIBS="-lcurses $olibs"
+-echo "checking libcurses" 1>&6
+-echo "configure:2076: checking libcurses" >&5
+-cat > conftest.$ac_ext <<EOF
+-#line 2078 "configure"
+-#include "confdefs.h"
+-
+-int main() {
+-
+-#ifdef __hpux
+-__sorry_hpux_libcurses_is_totally_broken_in_10_10();
+-#else
+-tgetent((char *)0, (char *)0);
+-#endif
+-
+-; return 0; }
+-EOF
+-if { (eval echo configure:2091: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+-  :
+-else
+-  echo "configure: failed program was:" >&5
+-  cat conftest.$ac_ext >&5
+-  rm -rf conftest*
+   LIBS="-ltermcap $olibs"
+ echo "checking libtermcap" 1>&6
+ echo "configure:2099: checking libtermcap" >&5
+@@ -2153,8 +2130,6 @@
+ rm -f conftest*
+ fi
+ rm -f conftest*
+-fi
+-rm -f conftest*
  
- _CUT_HERE_
+ if test "$cross_compiling" = yes; then
+     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
+@@ -2165,7 +2140,7 @@
  
--#if ((defined(hp300) && !defined(__hpux)) || defined(sun) || (defined(ultrix) && defined(mips)) || defined(_SEQUENT_) || defined(sgi) || defined(SVR4) || defined(sony_news) || !(defined(__osf__) && defined(__alpha)) || defined(_IBMR2) || defined(_AUX_SOURCE) || defined(AUX) || defined(m88k))
-+#if ((defined(hp300) && !defined(__hpux)) || defined(sun) || (defined(ultrix) && defined(mips)) || defined(_SEQUENT_) || defined(sgi) || defined(SVR4) || defined(sony_news) || defined(_IBMR2) || defined(_AUX_SOURCE) || defined(AUX) || defined(m88k))
- loadtype=long
- # if defined(apollo) || defined(_IBMR2) || defined(_AUX_SOURCE) || defined(AUX)
- loadscale=65536
+ main()
+ {
+- exit(strcmp(tgoto("%p1%d", 0, 1), "1") ? 0 : 1);
++ exit(strcmp(tgoto("%d%d", 0, 1), "1") ? 0 : 1);
+ }
+ EOF
+ if { (eval echo configure:2172: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
