security/tor: add multi-instance support
PR:		207129
Submitted by:	yuri@rawbw.com (maintainer)

diff --git a/security/tor/files/tor.in b/security/tor/files/tor.in
--- a/security/tor/files/tor.in
+++ b/security/tor/files/tor.in
@@ -11,10 +11,19 @@
 # they are command line options.
 #
 # tor_enable (bool):	Set it to "YES" to enable tor. Default: NO
+# tor_instances (str):	List of instances. Default: ""
 # tor_conf (str):	Points to your torrc file.
 #			Default: %%PREFIX%%/etc/tor/torrc
-# tor_user (str):	Tor daemon user. Default: _tor
+# tor_user (str):	Tor daemon user. Default: %%USER%%
+# tor_group (str):	Tor group. Default: %%GROUP%%
+# tor_pidfile (str):	Tor pid file.  Default: /var/run/tor/tor.pid
 # tor_datadir (str):	Tor datadir.  Default: /var/db/tor
+# tor_disable_default_instance (str):	Doesn't run the default instance.
+#			Only valid when tor_instances is used.
+#			Default: NO
+#
+# The instance definition that tor_instances expects:
+# inst_name{:inst_conf:inst_user:inst_group:inst_pidfile:inst_data_dir}
 #
 
 . /etc/rc.subr
@@ -25,10 +34,59 @@ rcvar=tor_enable
 load_rc_config ${name}
 
 : ${tor_enable="NO"}
+: ${tor_instances=""}
 : ${tor_conf="%%PREFIX%%/etc/tor/torrc"}
 : ${tor_user="%%USER%%"}
+: ${tor_group="%%GROUP%%"}
 : ${tor_pidfile="/var/run/tor/tor.pid"}
 : ${tor_datadir="/var/db/tor"}
+: ${tor_disable_default_instance="NO"}
+
+instance=${2}
+if [ -n "${instance}" ]; then
+  # extended instance: parameters are set explicitly
+  inst_def=${instance}
+  inst_name=${inst_def%%:*}
+  inst_def=${inst_def#$inst_name}
+  if [ -n "$inst_def" ]; then
+    inst_def=${inst_def#:}
+    tor_conf=${inst_def%%:*}
+    inst_def=${inst_def#$tor_conf:}
+    tor_user=${inst_def%%:*}
+    inst_def=${inst_def#$tor_user:}
+    tor_group=${inst_def%%:*}
+    inst_def=${inst_def#$tor_group:}
+    tor_pidfile=${inst_def%%:*}
+    tor_datadir=${inst_def#$tor_pidfile:}
+    if [ -z "${tor_conf}" -o -z "${tor_user}" -o -z "${tor_group}" -o -z "${tor_pidfile}" -o -z "${tor_datadir}" ]; then
+      warn "invalid tor instance ${inst_name} settings"
+      exit 1
+    fi
+  else
+    # regular instance: default parameters are used
+    tor_conf=${tor_conf}@${inst_name}
+    tor_pidfile=${tor_pidfile}@${inst_name}
+    tor_datadir=${tor_datadir}/instance@${inst_name}
+  fi
+  if ! [ -r ${tor_conf} ]; then
+    warn "tor instance ${inst_name} config file ${tor_conf} doesn't exist or isn't readable"
+    warn "you can copy the sample config %%PREFIX%%/etc/tor/torrc.sample and modify it"
+    exit 1
+  fi
+  if ! [ -d ${tor_datadir} ]; then
+    mkdir -p ${tor_datadir} &&
+    chown ${tor_user}:${tor_group} ${tor_datadir} &&
+    chmod 0700 ${tor_datadir} &&
+    echo "${name}: created the instance data directory ${tor_datadir}"
+  fi
+fi
+
+if [ -z "${instance}" -a -n "${tor_instances}" ]; then
+  for i in ${tor_instances}; do
+    %%PREFIX%%/etc/rc.d/tor $1 ${i} || warn "$1 failed for the tor instance $i"
+  done
+  checkyesno tor_disable_default_instance && return 0
+fi
 
 required_files=${tor_conf}
 required_dirs=${tor_datadir}
