lang/smlnj: Update to 110.99.6.1
Add python:env and shebangfix to USES.
Use target-OPTION-{on,off} instead of if-statements.
Add targets-recompile.customized file instead of echo commands.
Switch to DISTVERSION.
Pet portfmt.

Changelogs:
https://www.smlnj.org/dist/working/110.99.6.1/110.99.6.1-README.html
https://www.smlnj.org/dist/working/110.99.6/110.99.6-README.html
https://www.smlnj.org/dist/working/2024.1/2024.1-README.html
https://www.smlnj.org/dist/working/110.99.5/110.99.5-README.html
https://www.smlnj.org/dist/working/2023.1/2023.1-README.html
https://www.smlnj.org/dist/working/110.99.4/110.99.4-README.html
https://www.smlnj.org/dist/working/2022.1/2022.1-README.html
https://www.smlnj.org/dist/working/110.99.3/110.99.3-README.html
https://www.smlnj.org/dist/working/2021.1/2021.1-README.html
https://www.smlnj.org/dist/working/110.99.2/110.99.2-README.html
https://www.smlnj.org/dist/working/110.99.1/110.99.1-README.html
https://www.smlnj.org/dist/working/110.99/110.99-README.html

PR:		283301
Reported by:	Alexey Vyskubov <alexey@ocaml.nl>
Approved by:	submitter is maintainer

diff --git a/lang/smlnj/files/patch-config_unpack b/lang/smlnj/files/patch-config_unpack
--- a/lang/smlnj/files/patch-config_unpack
+++ b/lang/smlnj/files/patch-config_unpack
@@ -1,12 +1,26 @@
---- config/unpack.orig	2019-10-28 14:53:16 UTC
+--- config/unpack.orig	2024-10-25 16:47:18 UTC
 +++ config/unpack
-@@ -291,6 +291,9 @@ do
+@@ -204,6 +204,13 @@ unpack() {
+     tryfetch=yes
+     if [ -d "$2"/"$3" ]; then
+ 	vsay "$this: The $1 tree already exists."
++    elif [ x`uname` = xFreeBSD ]; then 
++	# XXX Mac OS X resource files (._*) cause tar to fail with
++	# "Cannot restore extended attributes: com.apple.metadata:..."
++	# We dont't have to use fetch_n_unpack here because the port
++	# already fetched the upstream tarballs to $ROOT.
++    	vsay "$this: Un-TAR-ing $1 archive."
++	tar -x -C "$2" --exclude "._*" -f "$ROOT"/"$4".t* || true
+     else
+ 	fetch_n_unpack "$1" "$2" "$3" "$4"
+     fi
+@@ -290,6 +297,9 @@ do
+ 	unpack "documentation" "$ROOT" doc doc
          # cd $ROOT/doc
  	# build $ROOT
- 	;;
++	;;
 +      asdl)
 +	unpack "Abstract Syntax Description Library" "$ROOT" asdl asdl
-+	;;
+ 	;;
        *)
  	echo Unknown package: ${i}.
- 	echo Trying default method...
