Fix build with new pilot-link.

diff --git a/palm/gnomepilot/files/patch-aa b/palm/gnomepilot/files/patch-aa
--- a/palm/gnomepilot/files/patch-aa
+++ b/palm/gnomepilot/files/patch-aa
@@ -1,8 +1,5 @@
-
-$FreeBSD$
-
---- configure.orig	Thu Apr 25 19:15:48 2002
-+++ configure	Thu Apr 25 19:17:00 2002
+--- configure.orig	Mon Apr 22 16:21:27 2002
++++ configure	Tue Sep 17 13:44:51 2002
 @@ -5388,6 +5388,7 @@
  
  # This can be used to rebuild libtool when needed
@@ -33,6 +30,51 @@ $FreeBSD$
  		
  		
  	else
+@@ -7531,7 +7532,7 @@
+   cat conftest.$ac_ext >&5
+   rm -rf conftest*
+   CATOBJEXT=.mo
+-		   DATADIRNAME=lib
++		   DATADIRNAME=share
+ fi
+ rm -f conftest*
+ 		INSTOBJEXT=.mo
+@@ -7701,7 +7702,7 @@
+ #		 USE_INCLUDED_LIBINTL=yes
+ #		 CATOBJEXT=.cat
+ #		 INSTOBJEXT=.cat
+-#		 DATADIRNAME=lib
++#		 DATADIRNAME=share
+ #		 INTLDEPS='$(top_builddir)/intl/libintl.a'
+ #		 INTLLIBS=$INTLDEPS
+ #		 LIBS=`echo $LIBS | sed -e 's/-lintl//'`
+@@ -8268,7 +8269,7 @@
+ 	else
+ 	    PISOCK_CFLAGS="-I$withval/include"
+ 	    incdir="$withval/include"
+-	    PISOCK_LIBS="-L$withval/lib -lpisock"
++	    PISOCK_LIBS="-L$withval/lib -lpisync -lpisock"
+ 	    echo $ac_n "checking "for existance of $withval/lib/libpisock.so"""... $ac_c" 1>&6
+ echo "configure:8274: checking "for existance of $withval/lib/libpisock.so"" >&5
+ 	    if test -r $withval/lib/libpisock.so; then
+@@ -8381,7 +8382,7 @@
+ 	                                                   piversion_include="$prefix/include/pi-version.h"
+ 						           if test x$PISOCK_LIBDIR = x; then
+ 							      incdir="$prefix/include"
+-							      PISOCK_LIBS="-L$prefix/lib -lpisock"
++							      PISOCK_LIBS="-L$prefix/lib -lpisock -lpisock"
+                                                            fi							  
+ else
+   echo "$ac_t""no" 1>&6
+@@ -8432,7 +8433,7 @@
+ fi
+ if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
+   echo "$ac_t""yes" 1>&6
+-   PISOCK_LIBS=-lpisock 
++   PISOCK_LIBS=-lpisync -lpisock 
+ else
+   echo "$ac_t""no" 1>&6
+  { echo "configure: error: "Unable to find libpisock. Try ftp://ryeham.ee.ryerson.ca/pub/PalmOS/."" 1>&2; exit 1; } 
 @@ -9022,8 +9023,8 @@
  fi
  
