- Update to 1.1
PR:		154382
Submitted by:	Marian Jamrich <jamrich.majo@gmail.com> (maintainer)
Feature safe:	yes

diff --git a/net-mgmt/nagios-check_hdd_health/src/check_hdd_health b/net-mgmt/nagios-check_hdd_health/src/check_hdd_health
--- a/net-mgmt/nagios-check_hdd_health/src/check_hdd_health
+++ b/net-mgmt/nagios-check_hdd_health/src/check_hdd_health
@@ -16,7 +16,7 @@ SMT=Smartmontools
 PROGNAME=`basename $0`
             
 # Version
-VERSION="Version 1.0.1"
+VERSION="Version 1.1"
         
 # Author
 AUTHOR="Marian Jamrich"
@@ -26,9 +26,9 @@ TMPFILE=/tmp/smart.nagios.$$
 # Clean up when done or when aborting
 trap "rm -f ${TMPFILE}" 0 1 2 3 15
 
-#print_version() {
-#    echo "$PROGNAME $VERSION $1"
-#}
+print_version() {
+    echo "Nagios-$PROGNAME ($VERSION)"
+}
 
 mini_help() {
         echo "Usage $0 --device $device --without [src rsc rec cps ou]"
@@ -36,9 +36,9 @@ mini_help() {
 
 print_help() {
     clear;
-    echo "*********************************************************************************"
-    echo "* $PROGNAME $VERSION $1""($AUTHOR) <jamrich.majo@gmail.com> (2011) *" 
-    echo "*********************************************************************************"
+    echo "**************************************************************************************"
+    echo "*  $PROGNAME $VERSION $1""($AUTHOR) <jamrich.majo@gmail.com> (2011)   *" 
+    echo "**************************************************************************************"
     echo "This is Nagios plugin to check HDD health from S.M.A.R.T. by Smartmontools."
     echo '
 The S.M.A.R.T. attributes are specific properties (parameters) of various parts of a disk. 
@@ -80,7 +80,7 @@ This is test provided by Smartmontools. If total disk state is "health", Smartmo
     echo "Critical - if some value is greater than \"0\" except \"Spin Retry Count (>=10)\" and \"Reallocated Event Count (>=10)\"."
     echo -e "\n---------------------------------------------------------------------"
     echo "Usage:"
-    echo "$0 --device /dev/ad0 [ --without [src rsc rec cps ou]]"
+    echo "$0 --device ad0 [ --without [src rsc rec cps ou]]"
     echo "---------------------------------------------------------------------"
     exit $ST_UN
 }
@@ -93,12 +93,12 @@ case "$1" in
         -d | --device)
             device=$2
             ;;
-        -V)
+        -v)
             print_version
-            exit
+            exit $ST_UN
             ;;
         *)
-            echo "Unknown argument: $1"
+	    echo "Unknown argument: $1"
             echo "For more information please try -h or --help!"
             exit $ST_UN
             ;;
@@ -108,26 +108,30 @@ shift
 test -z $device && echo -e "\nYou forgot to define device! Please try \"-h or --help\" to help." && exit $ST_UN
 test `uname` != "FreeBSD" && echo "This plugin is only for FreeBSD." && exit $ST_UN
 
+format_device=`echo $device | grep -w 'dev'`
+if [ -z $format_device ]; then
+        device=/dev/`echo $device`
+fi
+
 if [ ! -e $device ]; then
-        echo
-        echo "Unknown device \"$device\"!"
-        exit $ST_UN
+	echo "Unknown device \"$device\"!"
+	exit $ST_UN
 fi
 
 if [ -z $smartctl ]; then
-        echo -e "\nYou don't have installed $SMT. Please install it at http://smartmontools.sourceforge.net or pkg_add -r \"smartmontools\"..."
-        exit $ST_UN
+	echo -e "\nYou don't have installed $SMT. Please install it from 'http://smartmontools.sourceforge.net' or pkg_add -r \"smartmontools\"..."
+	exit $ST_UN
 fi
 
 $smartctl -a $device > ${TMPFILE}
 SMART_SUPPORT=`awk '/SMART support is/ {print $4}' ${TMPFILE} | tail -n 1`
 
 if [ "${SMART_SUPPORT}" = "Unavailable" ]; then
-        echo -e "\nS.M.A.R.T support is Unavailable for $device !!! You should enable it \"smartctl -s on $device\"."
-        exit $ST_UN
+	echo -e "\nS.M.A.R.T support is unavailable for $device !!! You should enable it \"smartctl -s on $device\"."
+	exit $ST_UN
 elif [ "${SMART_SUPPORT}" != "Enabled" ]; then
-        echo -e "\nMaybe you don't have enabled S.M.A.R.T support in $SMT! Please type \"smartctl -s on $device\" that you have it turned on. Or device does not support S.M.A.R.T function."
-        exit $ST_UN
+	echo -e "\nMaybe you don't have enabled S.M.A.R.T support in $SMT! Please type \"smartctl -s on $device\" that you have it turned on, or device does not support S.M.A.R.T function."
+	exit $ST_UN
 fi
 
 ## start S.M.A.R.T test and set variables
@@ -138,7 +142,7 @@ cps=`awk '/Current_Pending_Sector/ {print $10}' ${TMPFILE} `
 ou=`awk '/Offline_Uncorrectable/ {print $10}' ${TMPFILE} `
 pass=`awk -F\: '/test result/ { if ( $2 == " PASSED")  print "PASSED"; else print "FAILED" }' ${TMPFILE} `
 
-## if one or more S.M.A.R.T function is not supported by your HDD, then you define --without variable and then value is set to "0"
+## if one or more S.M.A.R.T function is not supported by your HDD, then you define --without variable and then value is set automatically to "0"
 args=`getopt w:without: $*`
 for arg; do
         case "$arg" in
@@ -150,16 +154,18 @@ for arg; do
         esac
 done
 
-# test if your HDD support all parameters:
-[ -z "$src" ] && echo -e "***********\n** ERROR **\n***********\n${device} don't support Spin_Retry_Count. Please try \"--without src\"." && mini_help && exit $ST_UN
-[ -z "$rsc" ] && echo -e "***********\n** ERROR **\n***********\n${device} don't support Reallocated_Sector_Ct. Please try \"--without rsc\"." && mini_help && exit $ST_UN
-[ -z "$rec" ] && echo -e "***********\n** ERROR **\n***********\n${device} don't support Reallocated_Event_Count. Please try --without rec." && mini_help && exit $ST_UN
-[ -z "$cps" ] && echo -e "***********\n** ERROR **\n***********\n${device} don't support Current_Pending_Sector. Please try --without cps." && mini_help && exit $ST_UN
-[ -z "$ou" ]  && echo -e "***********\n** ERROR **\n***********\n${device} don't support Offline_Uncorrectable. Please try \"--without ou\"." && mini_help && exit $ST_UN
+# test if your HDD support all this parameters:
+[ -z "$src" ] && echo -e "***********\n** ERROR **\n***********\n${device} don't support "Spin Retry Count". Please try \"--without src\"." && mini_help && exit $ST_UN
+[ -z "$rsc" ] && echo -e "***********\n** ERROR **\n***********\n${device} don't support "Reallocated Sector Ct". Please try \"--without rsc\"." && mini_help && exit $ST_UN
+[ -z "$rec" ] && echo -e "***********\n** ERROR **\n***********\n${device} don't support "Reallocated Event Count". Please try --without rec." && mini_help && exit $ST_UN
+[ -z "$cps" ] && echo -e "***********\n** ERROR **\n***********\n${device} don't support "Current Pending Sector". Please try --without cps." && mini_help && exit $ST_UN
+[ -z "$ou"  ] && echo -e "***********\n** ERROR **\n***********\n${device} don't support "Offline Uncorrectable". Please try \"--without ou\"." && mini_help && exit $ST_UN
 
 perfdata="smart=src=$src; rsc=$rsc; rec=$rec; cps=$cps; ou=$ou; pass=$pass"
 
+############################################################
 ##### finally run test, print result and set exit code #####
+############################################################
 if [ $src -eq 0 ] && [ $rsc -eq 0 ] && [ $rec -eq 0 ] && [ $cps -eq 0 ] && [ $ou -eq 0 ] && [ "$pass" = "PASSED" ]; then
         echo "OK - HDD S.M.A.R.T health: src=$src, rsc=$rsc, rec=$rec, cps=$cps, ou=$ou, HEALTH_STATUS=$pass for $device. |${perfdata}"
         exit $ST_OK
