net/linphone: update to 6.1.2
PR:		294162
Co-authored-by: Myokla K. <nikolaytihonov2022@gmail.com>

diff --git a/net/linphone/Makefile b/net/linphone/Makefile
--- a/net/linphone/Makefile
+++ b/net/linphone/Makefile
@@ -1,104 +1,115 @@
 PORTNAME=	linphone
-PORTVERSION=	5.3.2
-PORTEPOCH=	1
+DISTVERSION=	6.1.2
 CATEGORIES=	net
-EXTRACT_ONLY=	${DISTNAME}${EXTRACT_SUFX}
 
 MAINTAINER=	hiroo.ono+freebsd@gmail.com
-COMMENT=	SIP client supporting voice/video calls and text messaging
+COMMENT=	Qt 6 desktop SIP client for voice, video, and messaging
 WWW=		https://www.linphone.org/
 
 LICENSE=	GPLv3
+LICENSE_FILE=	${WRKSRC}/LICENSE.txt
 
-BUILD_DEPENDS=	patchelf:sysutils/patchelf
+RUN_DEPENDS=	xdg-screensaver:devel/xdg-utils
+
 LIB_DEPENDS=	libbctoolbox.so:net/bctoolbox \
 		libbelcard.so:deskutils/belcard \
+		libbelle-sip.so:net/belle-sip \
+		libbelr.so:textproc/belr \
+		libbzrtp.so:security/bzrtp \
+		libjsoncpp.so:devel/jsoncpp \
+		liblime.so:security/lime \
 		liblinphone++.so:net/liblinphone \
 		libmediastreamer2.so:net/mediastreamer \
-		libortp.so:net/ortp \
-		libqt5keychain.so:security/qtkeychain@qt5 \
-		libQt5Multimedia.so:multimedia/qt5-multimedia \
-		libxml2.so:textproc/libxml2 \
-		liblime.so:security/lime \
-		libjsoncpp.so:devel/jsoncpp \
-		libbelle-sip.so:net/belle-sip \
-		libbelr.so:textproc/belr
+		libortp.so:net/ortp
 
-USES=		cmake compiler:c++11-lib pkgconfig qt:5 tar:bzip2 xorg sqlite:3
+USES=		cmake compiler:c++17-lang desktop-file-utils gl gnome pkgconfig qt:6 sqlite:3 tar:bzip2 xorg
+USE_GL=		gl
+USE_GNOME=	libxml2
 USE_GITLAB=	yes
-USE_XORG=	x11
 GL_SITE=	https://gitlab.linphone.org/BC
-GL_ACCOUNT=	public \
-		public/external:ispell
-GL_PROJECT=	linphone-desktop \
-		ispell:ispell
-GL_TAGNAME=	${PORTVERSION} \
-		05574fe160222c3d0b6283c1433c9b087271fad1:ispell
-USE_QT=		concurrent core dbus declarative gui linguisttools network \
-		quickcontrols2 speech svg testlib widgets buildtools:build \
-		qmake:build graphicaleffects:run quickcontrols:run
+GL_ACCOUNT=	public
+GL_PROJECT=	linphone-desktop
+GL_TAGNAME=	${DISTVERSION}
+USE_QT=		base declarative networkauth shadertools:build svg tools:build
+USE_XORG=	x11
 
-# Linphone's plugin API is implemented in a shared object with rather generic
-# SONAME and filename, libapp-plugin.so. For classic installation in the
-# local tree, we better move it to its own subdirectory, so we need RPATH
-# here.
-# This will affect actual Linphone plugins as well if they get ported.
-CMAKE_ARGS+=	-DCMAKE_INSTALL_RPATH="${LOCALBASE}/lib/linphone" \
-		-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=NO \
+SUB_FILES=	linphone.desktop
+
+CMAKE_ARGS+=	-DLINPHONE_QT_ONLY=ON \
+		-DLINPHONE_OUTPUT_DIR=${LOCALBASE} \
 		-DLINPHONEAPP_INSTALL_PREFIX=${PREFIX} \
-		-DLINPHONEAPP_VERSION="${PORTVERSION}" \
+		-DLINPHONEAPP_VERSION=${DISTVERSION} \
+		-DMEDIASTREAMER2_PLUGINS_LOCATION=${LOCALBASE}/lib/mediastreamer/plugins \
+		-DCMAKE_PREFIX_PATH=${LOCALBASE} \
+		-DCMAKE_SKIP_INSTALL_RPATH=ON \
+		-DCMAKE_BUILD_WITH_INSTALL_RPATH=OFF \
+		-DENABLE_VIDEO=ON \
+		-DENABLE_QT_GL=ON \
+		-DENABLE_QT_KEYCHAIN=OFF \
+		-DENABLE_BUILD_APP_PLUGINS=OFF \
+		-DENABLE_CRASH_HANDLER=OFF \
+		-DENABLE_APP_PACKAGING=OFF \
+		-DENABLE_APP_PDF_VIEWER=OFF \
+		-DENABLE_APP_WEBVIEW=OFF \
+		-DENABLE_APP_PACKAGE_ROOTCA=OFF \
+		-DENABLE_UPDATE_CHECK=OFF \
+		-DENABLE_STRICT=OFF \
+		-DENABLE_RELATIVE_PREFIX=OFF \
+		-DENABLE_SCREENSHARING=OFF \
+		-DENABLE_OPENH264=OFF \
 		-DGIT_EXECUTABLE=NO
-CMAKE_ON=	ENABLE_VIDEO \
-		ENABLE_BUILD_VERBOSE \
-		ENABLE_QT_KEYCHAIN
-CMAKE_OFF=	ENABLE_BUILD_APP_PLUGINS
 
-ICONDIR=	${LOCALBASE}/share/icons/hicolor
+ICON_SIZES=	16x16 22x22 24x24 32x32 64x64 128x128 256x256
 
-post-extract:
-	${TAR} -x -C ${WRKSRC}/external/ispell \
-		-f ${DISTDIR}/${DISTFILE_ispell} \
-		--strip-components 1
-
-# override install because otherwise, it does a complete rebuild during stage
-do-install:
-	# Patchelf
-	patchelf --set-rpath "${LOCALBASE}/lib:${LOCALBASE}/lib/linphone" \
-		${BUILD_WRKSRC}/linphone-app/linphone
-	# Linphone
-	${MKDIR} ${STAGEDIR}${LOCALBASE}/lib/linphone \
-		${STAGEDIR}${LOCALBASE}/include/LinphoneApp \
-		${STAGEDIR}${DATADIR} \
-		${STAGEDIR}${ETCDIR} \
-		${STAGEDIR}${ICONDIR}
-	${INSTALL_PROGRAM} ${BUILD_WRKSRC}/linphone-app/linphone \
-		${STAGEDIR}${LOCALBASE}/bin
-	${INSTALL_LIB} ${BUILD_WRKSRC}/linphone-app/libapp-plugin.so \
-		${STAGEDIR}${LOCALBASE}/lib/linphone
-	${INSTALL_DATA} ${BUILD_WRKSRC}/linphone-app/qt.conf \
-		${STAGEDIR}${ETCDIR}
-	${INSTALL_DATA} ${WRKSRC}/linphone-app/include/LinphoneApp/* \
-		${STAGEDIR}${LOCALBASE}/include/LinphoneApp
-	${INSTALL_DATA} ${BUILD_WRKSRC}/linphone-app/linphone.desktop \
-		${STAGEDIR}${LOCALBASE}/share/applications/linphone.desktop
-	${MKDIR} ${STAGEDIR}${ICONDIR}/scalable/apps
-	${INSTALL_DATA} ${WRKSRC}/linphone-app/assets/images/linphone_logo.svg \
-		${STAGEDIR}${ICONDIR}/scalable/apps/linphone.svg
-	for idir in 16x16 22x22 24x24 32x32 64x64 128x128 256x256; do \
-		${MKDIR} ${STAGEDIR}${ICONDIR}/$${idir}/apps; \
-		${INSTALL_DATA} ${WRKSRC}/linphone-app/assets/icons/hicolor/$${idir}/apps/icon.png \
-			${STAGEDIR}${ICONDIR}/$${idir}/apps/linphone.png; \
-	done
-	${MKDIR} ${STAGEDIR}${DATADIR}/assistant
-	${INSTALL_DATA} ${WRKSRC}/linphone-app/assets/assistant/* \
-		${STAGEDIR}${DATADIR}/assistant
-	${INSTALL_DATA} ${WRKSRC}/linphone-app/assets/linphonerc-factory \
-		${STAGEDIR}${DATADIR}
-	# ISpell
-	${INSTALL_LIB} ${BUILD_WRKSRC}/external/ispell/libISpell.so \
-		${STAGEDIR}${LOCALBASE}/lib
-	${MKDIR} ${STAGEDIR}${DATADIR}/ispell_dictionaries
-	${INSTALL_DATA} ${WRKSRC}/external/ispell/ispell_dictionaries/* \
-		${STAGEDIR}${DATADIR}/ispell_dictionaries
+post-install:
+	${MKDIR} ${STAGEDIR}${PREFIX}/share/applications
+	${INSTALL_DATA} ${WRKDIR}/linphone.desktop \
+		${STAGEDIR}${PREFIX}/share/applications/linphone.desktop
+	${MKDIR} ${STAGEDIR}${PREFIX}/share/icons/hicolor/scalable/apps
+	${INSTALL_DATA} ${WRKSRC}/Linphone/data/image/logo.svg \
+		${STAGEDIR}${PREFIX}/share/icons/hicolor/scalable/apps/linphone.svg
+.for size in ${ICON_SIZES}
+	${MKDIR} ${STAGEDIR}${PREFIX}/share/icons/hicolor/${size}/apps
+	${INSTALL_DATA} ${WRKSRC}/Linphone/data/icon/hicolor/${size}/apps/icon.png \
+		${STAGEDIR}${PREFIX}/share/icons/hicolor/${size}/apps/linphone.png
+.endfor
+	# A Qt5 DT_NEEDED entry is an unconditional build failure for this port.
+	@if /usr/bin/readelf -d ${STAGEDIR}${PREFIX}/bin/linphone | \
+		${GREP} -Eq 'NEEDED.*libQt5'; then \
+		${ECHO_MSG} 'ERROR: linphone is directly linked against Qt5'; \
+		exit 1; \
+	fi
+	@${ECHO_MSG} '===> Qt linkage for staged linphone'
+	@/usr/bin/ldd ${STAGEDIR}${PREFIX}/bin/linphone
+	@if /usr/bin/ldd ${STAGEDIR}${PREFIX}/bin/linphone | \
+		${GREP} -Eq 'libQt5|/qt5/'; then \
+		${ECHO_MSG} 'ERROR: linphone has a direct or transitive Qt5 dependency'; \
+		exit 1; \
+	fi
+	@if ! /usr/bin/ldd ${STAGEDIR}${PREFIX}/bin/linphone | \
+		${GREP} -Eq 'libQt6(Core|Gui|Quick|Qml|OpenGL|Widgets)'; then \
+		${ECHO_MSG} 'ERROR: linphone Qt6 linkage was not detected'; \
+		exit 1; \
+	fi
+	@${ECHO_MSG} '===> Qt linkage for system MSQOGL'
+	@/usr/bin/ldd ${LOCALBASE}/lib/mediastreamer/plugins/libmsqogl.so
+	@if /usr/bin/ldd ${LOCALBASE}/lib/mediastreamer/plugins/libmsqogl.so | \
+		${GREP} -Eq 'libQt5|/qt5/'; then \
+		${ECHO_MSG} 'ERROR: system libmsqogl.so is linked against Qt5'; \
+		exit 1; \
+	fi
+	@if ! /usr/bin/ldd ${LOCALBASE}/lib/mediastreamer/plugins/libmsqogl.so | \
+		${GREP} -Eq 'libQt6(Core|Gui|Quick|Qml|OpenGL|Widgets)'; then \
+		${ECHO_MSG} 'ERROR: system libmsqogl.so Qt6 linkage was not detected'; \
+		exit 1; \
+	fi
+	# The package must not contain private copies of the system SDK or Qt.
+	@if ${FIND} ${STAGEDIR}${PREFIX} -type f \( \
+		-name 'libQt5*.so*' -o -name 'libQt6*.so*' -o \
+		-name 'liblinphone*.so*' -o -name 'libmediastreamer*.so*' \) | \
+		${GREP} -q .; then \
+		${ECHO_MSG} 'ERROR: staged tree contains bundled Qt/Liblinphone/Mediastreamer libraries'; \
+		exit 1; \
+	fi
 
 .include <bsd.port.mk>
