Update to 1.4.
Change the configuration process, so that extraneous files are not
downloaded.

diff --git a/www/linux-mozilla/scripts/configure b/www/linux-mozilla/scripts/configure
--- a/www/linux-mozilla/scripts/configure
+++ b/www/linux-mozilla/scripts/configure
@@ -16,11 +16,11 @@ echo "browser langenus regus xpcom" > /tmp/checklist.tmp.$$;
 Choose which components of Mozilla to download and install. \n\
 Press the space bar to toggle selections." -1 -1 6 \
 "deflenus"	"American English profile defaults (8 kB)"		ON \
-"inspector"	"DOM inspector (240 kB)"				ON \
-"mail"		"Mozilla Mail and News (1824 kB)"			ON \
+"inspector"	"DOM inspector (154 kB)"				ON \
+"mail"		"Mozilla Mail and News (1808 kB)"			ON \
 "psm"		"Personal Security Manager--recommended (768 kB)"	ON \
 "talkback"	"sends crash logs to Mozilla staff (832 kB)"		ON \
-"venkman"	"JavaScript debugger (256 kB)"				ON \
+"venkman"	"JavaScript debugger (224 kB)"				ON \
 2>> /tmp/checklist.tmp.$$
 
 retval=$?
@@ -42,3 +42,7 @@ echo "$choice" \
 	| sed -e "s/$/.xpi/g" \
 	| perl -pi -e "s/ /\n/g" \
 	> ${WRKSRC}/components.conf
+
+echo "* Your choices are saved.  You must run the \"make\" command again to"
+echo "* complete the build.  Ignore the \"Error code 1\" below."
+exit 1
