print/lilypond-devel: update 2.19.83 -> 2.20.0
- back in sync with print/lilypond

PR:		243970
Submitted by:	Martin Neubauer <m.ne@gmx.net> (maintainer)
Reviewed by:	adridg

diff --git a/print/lilypond-devel/files/patch-configure b/print/lilypond-devel/files/patch-configure
--- a/print/lilypond-devel/files/patch-configure
+++ b/print/lilypond-devel/files/patch-configure
@@ -1,24 +1,24 @@
---- configure.orig	2019-03-20 13:52:23 UTC
+--- configure.orig	2020-03-01 14:00:51 UTC
 +++ configure
-@@ -10512,13 +10512,8 @@ $as_echo_n "checking $r version... " >&6; }
+@@ -2298,13 +2298,8 @@ $as_echo_n "checking $r version... " >&6; }
      ## for compatibility reasons.
  
-     ## grab the first version number in  --version output.
+     ## grab the first version number in --version output.
 -    eval _ver=\"\`("$exe" --version || "$exe" -V) 2>&1 |
--		grep -E '(^| )[0-9][0-9]*\.[0-9]' |
--		head -n 1 |
--		tr ' ' '\n' |
--		sed 's/\([0-9][0-9]*\.[0-9][0-9.]*\).*/\1/g' |
--		grep -E '(^| )[0-9][0-9]*\.[0-9]' |
--		head -n 1\`\"
+-        grep -E '(^| )[0-9][0-9]*\.[0-9]' |
+-        head -n 1 |
+-        tr ' ' '\n' |
+-        sed 's/\([0-9][0-9]*\.[0-9][0-9.]*\).*/\1/g' |
+-        grep -E '(^| )[0-9][0-9]*\.[0-9]' |
+-        head -n 1\`\"
 +    eval _ver=\"\`("$exe" --version || "$exe" -V) 2>/dev/null |
-+		awk '$1 ~ "fontforge" { print $2 }'\`\"
++        awk '$1 ~ "fontforge" { print $2 }'\`\"
  
      if test -z "$_ver"; then
          ## If empty, try date [fontforge]
-@@ -11595,75 +11590,10 @@ test -n "$PKG_CONFIG" || PKG_CONFIG="no"
- 
-     if test $? -eq 0 -a -n "0.9.0"; then
+@@ -11631,71 +11626,10 @@ test -n "$PKG_CONFIG" || PKG_CONFIG="no"
+     if test $? -eq 0; then
+         if test -n "0.9.0" -o -n ""; then
  
 -    r="`eval echo '$'"PKG_CONFIG"`"
 -    { $as_echo "$as_me:$LINENO: checking $r version" >&5
@@ -31,10 +31,7 @@
 -    ## this test should work in ash, bash, pdksh (ksh), zsh
 -    type -p $r 2>/dev/null | tail -n 1 | awk '{print $NF}'
 -`
--    if test -n ""; then
--        ver=""
--    else
--        ver=`
+-    ver=`
 -    ## "$exe" --version 2>&1 | grep -v '^$' | head -n 1 | awk '{print $NF}'
 -    ##
 -    ## ARG.
@@ -50,26 +47,25 @@
 -    ## use eval trickery, because we cannot use multi-level $() instead of ``
 -    ## for compatibility reasons.
 -
--    ## grab the first version number in  --version output.
+-    ## grab the first version number in --version output.
 -    eval _ver=\"\`("$exe" --version || "$exe" -V) 2>&1 |
--		grep -E '(^| )[0-9][0-9]*\.[0-9]' |
--		head -n 1 |
--		tr ' ' '\n' |
--		sed 's/\([0-9][0-9]*\.[0-9][0-9.]*\).*/\1/g' |
--		grep -E '(^| )[0-9][0-9]*\.[0-9]' |
--		head -n 1\`\"
+-        grep -E '(^| )[0-9][0-9]*\.[0-9]' |
+-        head -n 1 |
+-        tr ' ' '\n' |
+-        sed 's/\([0-9][0-9]*\.[0-9][0-9.]*\).*/\1/g' |
+-        grep -E '(^| )[0-9][0-9]*\.[0-9]' |
+-        head -n 1\`\"
 -
 -    if test -z "$_ver"; then
 -        ## If empty, try date [fontforge]
 -        eval _ver=\"\`("$exe" --version || "$exe" -V) 2>&1 \
--	    | grep '\(^\|[^0-9a-f]\)[0-9]\{6,8\}\([^0-9a-f]\|$\)' \
--	    | head -n 1 \
--	    | sed -e 's/^[^.0-9]*//' -e 's/[^.0-9]*$//'\`\"
+-        | grep '\(^\|[^0-9a-f]\)[0-9]\{6,8\}\([^0-9a-f]\|$\)' \
+-        | head -n 1 \
+-        | sed -e 's/^[^.0-9]*//' -e 's/[^.0-9]*$//'\`\"
 -    fi
 -    echo "$_ver"
 -    #dnl
 -`
--    fi
 -    num=`
 -    echo "$ver" | awk -F. '
 -    {
@@ -78,7 +74,7 @@
 -    }
 -    {printf "%.0f\n", $1*1000000 + $2*1000 + three}'
 -`
--    req=`
+-    min=`
 -    echo "0.9.0" | awk -F. '
 -    {
 -      if ($3) {three = $3}
@@ -88,10 +84,32 @@
 -`
 -    { $as_echo "$as_me:$LINENO: result: $ver" >&5
 -$as_echo "$ver" >&6; }
--    if test "$num" -lt "$req"; then
+-    if test "$num" -lt "$min"; then
 -
 +    if test ! $?; then
 +    ver=`$PKG_CONFIG --version`
      eval "REQUIRED"=\"`eval echo \"'$'REQUIRED\" \""$r >= 0.9.0 (installed: $ver)"\"`\"
  
      fi
+@@ -15001,21 +14935,6 @@ $as_echo "$ver" >&6; }
+ 
+     eval "$DOCUMENTATION_REQUIRED"=\"`eval echo \"'$'$DOCUMENTATION_REQUIRED\" \""$r >= 1.82 (installed: $ver)"\"`\"
+ 
+-    fi
+-    if test -n "1.82"; then
+-        max=`
+-    echo "1.82" | awk -F. '
+-    {
+-      if ($3) {three = $3}
+-      else {three = 0}
+-    }
+-    {printf "%.0f\n", $1*1000000 + $2*1000 + three}'
+-`
+-        if test "$num" -gt "$max"; then
+-
+-    eval "$DOCUMENTATION_REQUIRED"=\"`eval echo \"'$'$DOCUMENTATION_REQUIRED\" \""$r <= 1.82 (installed: $ver)"\"`\"
+-
+-        fi
+     fi
+     vervar="`echo TEXI2HTML | tr 'a-z' 'A-Z'`_VERSION"
+     eval `echo $vervar=$num`
