- Update to version 2.2.2. - Use SF macro in MASTER_SITES. - Redefine EXTRACT_SUFX instead of DISTNAME to avoid changing WRKSRC. - Use NOT_FOR_ARCHS for sparc64 instead of checking ${ARCH}. - Use SUB_FILES for pkg-message instead of processing it manually. - Use patch for Makefile instead of REINPLACE_CMD. - Use FIND + MKDIR/INSTALL_DATA to install for avoiding too many commands. - Misc format to pkg-message. - Improve wrapper script: use "exec" to avoid wasting resources with the   script itself, take installation message from 'pkg_info -D' instead of   duplicating it inside the script, use SUB_LIST macros like DATADIR.
PR:		ports/109587
Submitted by:	alepulver (myself)
Approved by:	Travis Poppe <tlp@LiquidX.org> (maintainer)

diff --git a/games/wargus/files/wargus.in b/games/wargus/files/wargus.in
--- a/games/wargus/files/wargus.in
+++ b/games/wargus/files/wargus.in
@@ -6,46 +6,17 @@
 #
 # 2004 Travis Poppe <tlp@LiquidX.org>
 
-DATADIR=%%PREFIX%%/share/wargus/data.wc2
-
-if [ ! -d $DATADIR ]; then
-	echo "Warcraft 2 data not found in $DATADIR/"
-	echo ""
-	echo "Did you run build.sh yet?"
-	echo ""
-	echo "Giving you instructions in 5 seconds..."
-	sleep 5
-	echo ""
-	echo "The Wargus tool has been installed to %%PREFIX%%/share/wargus/"
-	echo ""
-	echo "You can now use this tool to extract Warcraft 2 data for use with the"
-	echo "Stratagus engine from the following CDs:"
-	echo ""
-	echo "* US Expansion (both MAC/DOS)"
-	echo "* US Original (both MAC/DOS)"
-	echo "* UK/Australian Original"
-	echo "* UK/Australian Expansion"
-	echo "* German Original"
-	echo "* German Expansion"
-	echo "* Spanish Original"
-	echo ""
-	echo "If you have one of the above CDs mounted on /cdrom, su to root and change to"
-	echo "the %%PREFIX%%/share/wargus/ directory and try executing:"
-	echo ""
-	echo "./build.sh -p /cdrom"
- 	echo ""
-	echo "After your Warcraft 2 data has been successfully extracted, run 'wargus' as the"
-	echo "user you intend to play the game with."
- 	echo ""
-	echo "For more information, please visit: http://wargus.sourceforge.net"
-	exit
-fi
+DATADIR="%%DATADIR%%/data.wc2"
 
 if [ -d $DATADIR ]; then
-	echo "Warcraft 2 data found in $DATADIR/"
+	echo "Running Stratagus with Warcraft 2 data found in \"$DATADIR\"."
 	echo ""
-	echo "Attempting to run Stratagus with Warcraft 2 data"
+	exec stratagus -d $DATADIR "$@"
+else
+	echo "ERROR: Warcraft 2 data not found in \"$DATADIR\"."
 	echo ""
-	stratagus -d $DATADIR $*
-	exit
+	echo "Please follow the instructions from the installation message:"
+	echo ""
+	pkg_info -D "wargus-[0-9]*"
+	exit 1
 fi
