block commit

diff --git a/CVSROOT/commitcheck b/CVSROOT/commitcheck
--- a/CVSROOT/commitcheck
+++ b/CVSROOT/commitcheck
@@ -1,6 +1,10 @@
 #! /bin/sh
 #
-# $Id: commitcheck,v 1.6 1997/05/21 15:58:59 peter Exp $
+# $Id: commitcheck,v 1.7 1997/05/26 04:07:36 peter Exp $
+
+echo "Freefall is half way through an upgrade and lots of things are broken.."
+echo "cvs is currently failing until the new kernel goes in."
+exit 1
 
 #
 # BEWARE:  If you are "borrowing" this code for use on another cvs
