update to zabbix 1.0beta10
PR:		56262
Submitted by:	Sergey Akifyev <asa@gascom.ru>

diff --git a/net-mgmt/zabbix/pkg-install b/net-mgmt/zabbix/pkg-install
--- a/net-mgmt/zabbix/pkg-install
+++ b/net-mgmt/zabbix/pkg-install
@@ -2,43 +2,44 @@
 # Script was taken from mysql323-server port, and modified
 # to suit zabbix needs
 
+[ -n "${PACKAGE_BUILDING}" ] && exit 0
+
+[ "${2}" = "POST-INSTALL" ] && exit 0
+
 PATH=/bin:/usr/sbin
 
-case $2 in
-POST-INSTALL)
-	USER=zabbix
-	GROUP=${USER}
-	UID=112
-	GID=${UID}
+USER=zabbix
+GROUP=${USER}
+UID=112
+GID=${UID}
 
-	if pw group show "${GROUP}" 2>/dev/null; then
-		echo "You already have a group \"${GROUP}\", so I will use it."
+if pw group show "${GROUP}" 2>/dev/null; then
+	echo "You already have a group \"${GROUP}\", so I will use it."
+else
+	if pw groupadd ${GROUP} -g ${GID}; then
+		echo "Added group \"${GROUP}\"."
 	else
-		if pw groupadd ${GROUP} -g ${GID}; then
-			echo "Added group \"${GROUP}\"."
-		else
-			echo "Adding group \"${GROUP}\" failed..."
-			exit 1
-		fi
+		echo "Adding group \"${GROUP}\" failed..."
+		exit 1
 	fi
+fi
 
-	if pw user show "${USER}" 2>/dev/null; then
-		echo "You already have a user \"${USER}\", so I will use it."
-		if pw usermod ${USER} -d /nonexistent
-		then
-			echo "Changed home directory of \"${USER}\" to /nonexistent"
-		else
-			echo "Changing home directory of \"${USER}\" to /nonexistent failed..."
-			exit 1
-		fi
+if pw user show "${USER}" 2>/dev/null; then
+	echo "You already have a user \"${USER}\", so I will use it."
+	if pw usermod ${USER} -d /nonexistent
+	then
+		echo "Changed home directory of \"${USER}\" to /nonexistent"
 	else
-		if pw useradd ${USER} -u ${UID} -g ${GROUP} -h - \
-			-d /nonexistent -s /sbin/nologin -c "MySQL Daemon"
-		then
-			echo "Added user \"${USER}\"."
-		else
-			echo "Adding user \"${USER}\" failed..."
-			exit 1
-		fi
+		echo "Changing home directory of \"${USER}\" to /nonexistent failed..."
+		exit 1
 	fi
-esac
+else
+	if pw useradd ${USER} -u ${UID} -g ${GROUP} -h - \
+		-d /nonexistent -s /sbin/nologin -c "Zabbix Sandbox"
+	then
+		echo "Added user \"${USER}\"."
+	else
+		echo "Adding user \"${USER}\" failed..."
+		exit 1
+	fi
+fi
