- Update to 1.9 [1] - Detection of insufficient memory [1] - Change %%  SUB vaes from fixed at python 27 to use any installed version of python [1] - Fix syntax of non system include "" vs <> [2]
PR:		ports/168974 [1]
Submitted by:	David Naylor <naylor.b.david@gmail.com> (maintainer) [1]
Reviewed by:	scheidel@ (me) [2]

diff --git a/lang/pypy/Makefile b/lang/pypy/Makefile
--- a/lang/pypy/Makefile
+++ b/lang/pypy/Makefile
@@ -6,8 +6,8 @@
 #
 
 PORTNAME=	pypy
-DISTVERSION=	1.8
-CATEGORIES=	lang python
+DISTVERSION=	1.9
+CATEGORIES=	lang python java
 MASTER_SITES=	https://bitbucket.org/pypy/pypy/get/
 DISTNAME=	release-${DISTVERSION}
 DIST_SUBDIR=	pypy
@@ -21,7 +21,8 @@ LICENSE_COMB=	multi
 LIB_DEPENDS=	expat:${PORTSDIR}/textproc/expat2 \
 		ffi:${PORTSDIR}/devel/libffi
 
-OPTIONS=	SANDBOX "Translate a sandboxed pypy" OFF
+OPTIONS_DEFINE=	SANDBOX
+SANDBOX_DESC=	"Translate a sandboxed pypy"
 
 BUILD_WRKSRC=	${WRKDIR}
 USE_BZIP2=	yes
@@ -29,17 +30,26 @@ USE_ICONV=	yes
 USE_GETTEXT=	yes
 PKGINSTALL=	${WRKDIR}/pkg-install
 PKGDEINSTALL=	${WRKDIR}/pkg-deinstall
-WRKSRC=		${WRKDIR}/pypy-pypy-2346207d9946
+WRKSRC=		${WRKDIR}/pypy-pypy-341e1e3821ff
 
-PYPYDIRS=	include lib-python lib_pypy site-packages
-PYPYPREFIX?=	${PREFIX}/${PORTNAME}-${DISTVERSION}
-PLIST_SUB+=	PYPYPREFIX="${PYPYPREFIX:S|^${PREFIX}/||g}" \
-		DISTVERSION="${DISTVERSION}"
+PYPY_VER=	${DISTVERSION}
+PYTHON_IMPL_VER=	2.7
+PYPY_LIBDIR=	lib/pypy${PYPY_VER}
+PYPY_INCLUDEDIR=	include/pypy${PYPY_VER}
+PYPYDIRS=	${PYPY_INCLUDEDIR} ${PYPY_LIBDIR}
+
+PLIST_SUB+=	PYPY_LIBDIR=${PYPY_LIBDIR} \
+		PYPY_INCLUDEDIR=${PYPY_INCLUDEDIR}
 
 MAKE_ENV+=	PYPY_LOCALBASE=${LOCALBASE}
+.if exists(/usr/bin/clang)
+MAKE_ARGS+=	CC=clang
+MAKE_JOBS_SAFE=	yes
+.endif
 
-.include <${.CURDIR}/files/bsd.pypy.inst.mk>
+# XXX !.include <bsd.port.pre.mk> as USE_* need to be set prior
 .include <bsd.port.options.mk>
+.include "${.CURDIR}/files/bsd.pypy.inst.mk"
 
 .if defined(PACKAGE_BUILDING)
 MANUAL_PACKAGE_BUILD=	fails to finish compilation on pointyhat, reason unknown
@@ -49,10 +59,11 @@ MANUAL_PACKAGE_BUILD=	fails to finish compilation on pointyhat, reason unknown
 .if !defined(PYPY_INST)
 PYPY_INST=	DEFAULT
 
-.if defined(WITH_SANDBOX)
+.if ${PORT_OPTIONS:MSANDBOX}
 PYPY_INST+=	SANDBOX
 .endif
-.endif
+
+.endif # !defined(PYPY_INST)
 
 PYPY_NAMES=
 .for inst in ${PYPY_INST}
@@ -60,11 +71,22 @@ PYPY_NAMES=
 PYPY_NAMES+=	${PYPY_${inst}_NAME}
 PYPY_PRIMARY?=	${PYPY_${inst}_NAME}
 
+# Check if the boehm GC will be used
 .if ${PYPY_${inst}_OPT} == 0 || ${PYPY_${inst}_OPT} == 1 || ${PYPY_${inst}_OPT} == size
 WITH_BOEHM_GC=	yes
 .endif
 
-.endfor
+# Check if the CLI (mono) backend will be used
+.if !empty(PYPY_${inst}_TRANSLATE_ARGS:M--backend=cli)
+WITH_CLI=	yes
+.endif
+
+# Check if the JVM (java) backend will be used
+.if !empty(PYPY_${inst}_TRANSLATE_ARGS:M--backend=jvm)
+WITH_JVM=	yes
+.endif
+
+.endfor # inst in ${PYPY_INST}
 
 # Use pypy if it is installed, else use python (to translate)
 .if !defined(PY)
@@ -74,17 +96,34 @@ PYPY!=		${WHICH} ${PYPY_PRIMARY} 2> /dev/null || true
 .else
 PYPY!=		${WHICH} ${PYPY_PRIMARY} 2> /dev/null || ${WHICH} pypy 2> /dev/null || true
 .endif
-.endif
+.endif # !defined(PYPY)
+
 .if exists(${PYPY})
 PY=		${PYPY}
 .else
 USE_PYTHON_BUILD=	2.5+
 PY=		${PYTHON_CMD}
 .endif
-.endif
+.endif # !defined(PY)
 
 .if defined(WITH_BOEHM_GC)
 LIB_DEPENDS+=	gc.1:${PORTSDIR}/devel/boehm-gc
+.endif
+
+.if defined(WITH_CLI)
+BUILD_DEPENDS+=	mono:${PORTSDIR}/lang/mono
+RUN_DEPENDS+=	mono:${PORTSDIR}/lang/mono
+ONLY_FOR_ARCHS=	i386 powerpc
+ONLY_FOR_ARCHS_REASON=	only translates on 32bit systems
+BROKEN=		CLI backend broken, unsupported upstream
+.endif
+
+.if defined(WITH_JVM)
+USE_JAVA=	yes
+JAVA_VERSION=	1.5+
+ONLY_FOR_ARCHS=	i386 powerpc
+ONLY_FOR_ARCHS_REASON=	only translates on 32bit systems
+BROKEN=		JVM backend broken, partially supported upstream
 .endif
 
 # Translate FreeBSD ARCH types to PyPy ARCH types
@@ -110,13 +149,13 @@ PLIST_SUB+=	PYPY_ARCH="${PYPY_ARCH}"
 .if ${PYPY_${inst}_OPT} == jit
 PYPY_${inst}_OPT=	2
 .endif
-.endfor
-.endif
+.endfor # inst in ${PYPY_INST}
+.endif # !defined(PYPY_JITTABLE)
 
 pre-fetch:
 	@${ECHO} "PyPy requires a large amount of free RAM and time to translate and compile."
 	@${ECHO}
-	@${ECHO} "To translate, PyPy requires on i386 3G (min 2G) free RAM and on amd64"
+	@${ECHO} "To translate, PyPy requires on 32bit 3G (min 2G) free RAM and on 64bit"
 	@${ECHO} "6G (min 4G) free RAM.  Also, to compile, PyPy on amd64 gcc requires an"
 	@${ECHO} "extra 4G however clang only requires 400M (CC=clang) but clang is slower"
 	@${ECHO} "in compiling PyPy."
@@ -126,7 +165,7 @@ pre-fetch:
 	@${ECHO} "consider forcing the build to use python (-DPYPY) however that makes the"
 	@${ECHO} "build much slower."
 	@${ECHO}
-	@${ECHO} "PyPy supports a large number of paramaters and customisations.  This port"
+	@${ECHO} "PyPy supports a large number of parameters and customisations.  This port"
 	@${ECHO} "supports building multiple instances of PyPy, for example:"
 	@${ECHO} "PYPY_INST=	SANDBOX CUSTOM"
 	@${ECHO} "PYPY_CUSTOM_NAME=		pypy-custom"
@@ -142,15 +181,32 @@ pre-fetch:
 	@${ECHO}
 	@${ECHO} "On a fast machine PyPy takes around 45 minutes to translate and compile,"
 	@${ECHO} "however an average machine takes in excess of 4 hours, per instance."
+.if !defined(PYPY_IGNORE_MEM) && (${PYPY_ARCH} == "i386" || ${PYPY_ARCH} == "ppc_32")
+	@if [ $$((`sysctl -n hw.physmem` / 1024 / 1024)) -le 2000 ]; then \
+		${ECHO}; \
+		${ECHO} "err: this system has insufficient memory, expected at least 2G RAM",; \
+		${ECHO} "err: to overwrite this error define -DPYPY_IGNORE_MEM and try again"; \
+		exit 1; \
+	fi
+.elif !defined(PYPY_IGNORE_MEM)
+	@if [ $$((`sysctl -n hw.physmem` / 1024 / 1024)) -le 4000 ]; then \
+		${ECHO}; \
+		${ECHO} "err: this system has insufficient memory, expected at least 4G RAM",; \
+		${ECHO} "err: to overwrite this error define -DPYPY_IGNORE_MEM and try again"; \
+		exit 1; \
+	fi
+.endif
 	@sleep 1
 
-post-patch:
-	@${RM} -f ${WRKSRC}/lib-python/2.7/SimpleXMLRPCServer.py.orig
+post-extract:
+	${MKDIR} ${WRKSRC}/lib
+	${MV} ${WRKSRC}/lib-python/${PYTHON_IMPL_VER} ${WRKSRC}/${PYPY_LIBDIR}
+	${MV} ${WRKSRC}/lib_pypy ${WRKSRC}/${PYPY_LIBDIR}/
 
 do-configure:
 	${SED} -e 's|%%PREFIX%%|${PREFIX}|g' \
-		-e 's|%%PYPYPREFIX%%|${PYPYPREFIX}|g' \
 		-e 's|%%PYPY_NAMES%%|${PYPY_NAMES}|g' \
+		-e 's|%%PYPY_VER%%|${PYPY_VER}|g' \
 		${FILESDIR}/use.pypy > ${WRKDIR}/use.pypy
 	${CP} ${WRKDIR}/use.pypy ${PKGINSTALL}
 	${CP} ${WRKDIR}/use.pypy ${PKGDEINSTALL}
@@ -176,26 +232,21 @@ do-configure:
 .endfor
 
 post-build:
-	-${FIND} ${PYPYDIRS:S|^|${WRKSRC}/|g} -type d | ${SETENV} PYTHON_PATH=${WRKSRC} ${XARGS} ${WRKDIR}/${PYPY_PRIMARY} -m compileall -fl
+	-${FIND} ${WRKSRC}/${PYPY_LIBDIR} -type d | \
+		${SETENV} PYTHON_PATH=${WRKSRC} ${XARGS} \
+		${WRKDIR}/${PYPY_PRIMARY} -m compileall -fl
+	${MV} ${WRKSRC}/include ${WRKSRC}/include~
+	${MKDIR} ${WRKSRC}/include
+	${MV} ${WRKSRC}/include~ ${WRKSRC}/${PYPY_INCLUDEDIR}
 
 do-install:
-	${MKDIR} ${PYPYPREFIX} ${PYPYPREFIX}/bin
 .for dir in ${PYPYDIRS}
-	cd ${WRKSRC} && ${COPYTREE_SHARE} ${dir} ${PYPYPREFIX}
-.endfor
-.for f in LICENSE README
-	${INSTALL_DATA} ${WRKSRC}/${f} ${PYPYPREFIX}/${f}
+	(cd ${WRKSRC}/${dir}; ${COPYTREE_SHARE} . ${PREFIX}/${dir})
 .endfor
 .for name in ${PYPY_NAMES:O}
-	${INSTALL_PROGRAM} ${WRKDIR}/${name} ${PYPYPREFIX}/bin/${name}
-	${LN} -fs ${PYPYPREFIX}/bin/${name} ${PREFIX}/bin/${name}${DISTVERSION}
-	${ECHO} bin/${name}${DISTVERSION} >> ${TMPPLIST}.prefix
+	${INSTALL_PROGRAM} ${WRKDIR}/${name} ${PREFIX}/bin/${name}${PYPY_VER}
+	${ECHO} bin/${name}${DISTVERSION} >> ${TMPPLIST}
 .endfor
-.for name in ${PYPY_NAMES:O}
-	${ECHO} ${PYPYPREFIX:S|${PREFIX}/||}/bin/${name} >> ${TMPPLIST}.prefix
-.endfor
-	${CAT} ${TMPPLIST} >> ${TMPPLIST}.prefix
-	${MV} ${TMPPLIST}.prefix ${TMPPLIST}
 
 post-install:
 	${SH} ${PKGINSTALL} ${PKGNAME} POST-INSTALL
@@ -203,7 +254,7 @@ post-install:
 test: patch
 .for inst in ${PYPY_INST}
 	@${WHICH} ${PYPY_${inst}_NAME} > /dev/null 2>&1 || (${ECHO} "Unable to find ${PYPY_${inst}_NAME}, please install port first!"; exit 1)
-	(${CD} ${WRKSRC}/lib-python; ${PYPY_${inst}_NAME} ../pypy/test_all.py)
+	(${CD} ${PYPY_LIBDIR}; ${PYPY_${inst}_NAME} ../../pypy/test_all.py)
 .endfor
 
 pkg-plist: build
@@ -212,13 +263,13 @@ pkg-plist: build
 	cd ${WRKSRC} && ${FIND} ${dir} -type f >> ${WRKDIR}/.plist-files-gen
 	cd ${WRKSRC} && ${FIND} ${dir} -type d >> ${WRKDIR}/.plist-dirs-gen
 .endfor
-.for f in LICENSE README
-	${ECHO} ${f} >> ${WRKDIR}/.plist-files-gen
-.endfor
-	${ECHO} 'bin' >> ${WRKDIR}/.plist-dirs-gen
-	${REINPLACE_CMD} -e 's|^|%%PYPYPREFIX%%/|g' -e 's|${PYPY_ARCH}|%%PYPY_ARCH%%|g' ${WRKDIR}/.plist-files-gen
-	${REINPLACE_CMD} -e 's|^|@dirrm %%PYPYPREFIX%%/|g' ${WRKDIR}/.plist-dirs-gen
-	${ECHO} '@dirrm %%PYPYPREFIX%%' >> ${WRKDIR}/.plist-dirs-gen
+	${REINPLACE_CMD} -e 's|^${PYPY_LIBDIR}|%%PYPY_LIBDIR%%|g' \
+		-e 's|^${PYPY_INCLUDEDIR}|%%PYPY_INCLUDEDIR%%|g' \
+		-e 's|${PYPY_ARCH}|%%PYPY_ARCH%%|g' \
+			${WRKDIR}/.plist-files-gen
+	${REINPLACE_CMD} -e 's|^${PYPY_LIBDIR}|@dirrm %%PYPY_LIBDIR%%|g' \
+		-e 's|^${PYPY_INCLUDEDIR}|@dirrm %%PYPY_INCLUDEDIR%%|g' \
+			${WRKDIR}/.plist-dirs-gen
 	${SORT} ${WRKDIR}/.plist-files-gen > ${WRKDIR}/pkg-plist
 	${SORT} -r ${WRKDIR}/.plist-dirs-gen >> ${WRKDIR}/pkg-plist
 	${CP} ${WRKDIR}/pkg-plist ${.CURDIR}/pkg-plist
