- In managed mode the script does not return the proper value due to $?   is reset by the if command. Therefore, the script does not fail when   starts with broken configuration files - While I'm here, use %%RC_SUBR%% instead of /etc/rc.subr
PR:		ports/110320
Submitted by:	Dominic Fandrey <lon_kamikaze at gmx.de>
Approved by:	maintainer timeout (6 months)

diff --git a/security/vpnc/files/vpnc.in b/security/vpnc/files/vpnc.in
--- a/security/vpnc/files/vpnc.in
+++ b/security/vpnc/files/vpnc.in
@@ -20,7 +20,7 @@
 : ${vpnc_conf_dir="%%PREFIX%%/etc"}
 : ${vpnc_record="$vpnc_pid_dir/vpnc.record"}
 
-. /etc/rc.subr
+. %%RC_SUBR%%
 
 name="vpnc"
 rcvar=`set_rcvar`
@@ -43,9 +43,12 @@ vpnc_start() {
 		current="$vpnc_conf_dir/$config"
 
 		# Start vpnc.
-		if ! $command $current $vpnc_flags; then
-			status=$?
-			echo "Running 'vpnc $current $vpnc_flags' failed."
+		$command --local-port 0 $current $vpnc_flags
+		status=$?
+		if [ $status != 0 ]; then
+			# VPNC does not print a newline after an error.
+			echo
+			echo "Running 'vpnc $current --local-port 0 $vpnc_flags' failed."
 			return $status
 		fi
 
