Upgrade to 4.26 (working, but not cleanly configured)

diff --git a/security/drweb-sendmail/files/patch-aa b/security/drweb-sendmail/files/patch-aa
--- a/security/drweb-sendmail/files/patch-aa
+++ b/security/drweb-sendmail/files/patch-aa
@@ -1,12 +1,55 @@
---- configure.bak	Fri Jun 29 09:06:30 2001
-+++ configure	Fri Aug 24 23:19:25 2001
-@@ -21,6 +21,9 @@
- 	"Linux"*)
- 		OS="Linux"
- 		;;
-+	"FreeBSD 5"*)
-+		OS="FreeBSD"
-+        ;;
- 	"FreeBSD 4"*)
- 		OS="FreeBSD"
-         ;;
+--- configure.orig	Thu Sep 27 01:00:45 2001
++++ configure	Wed Oct  3 07:59:17 2001
+@@ -105,6 +105,9 @@
+     if [ $MILTER_VER = "STD" ] ; then
+         SM_LIB="libsm"
+         SM_LIB_CMD="-lsm"
++    elif [ $OS = "FreeBSD_DW" ] ; then
++        SM_LIB="libsmutil"
++        SM_LIB_CMD="-lsmutil"
+     elif [ $OS = "Linux_DW" ] ; then
+         SM_LIB="libsmutil"
+         SM_LIB_CMD="-lsmutil"
+@@ -140,40 +143,13 @@
+     rm -f configure.cache
+     echo $n "${SM_DIR}${c}" >> configure.cache
+     
+-    OBJ_DIR=`ls -1 "$SM_DIR" | grep "obj.*"`
+-    if [ ! -d "$SM_DIR/$OBJ_DIR" ] ; then 
+-        echo
+-        echo "Cannot found directory in that Sendmail puts results of compilation"
+-        echo "Please re-build Sendmail or enter name (not a path) of this directory"
+-        echo $n ">$c"
+-        read INPUT
+-        if [ "x$INPUT" = "x" ] ; then
+-            echo "Try later."
+-            exit 2
+-        elif [ ! -d "$SM_DIR/$INPUT" ] ; then
+-            echo "$SM_DIR/$INPUT not found"
+-            exit 1
+-        fi
+-        OBJ_DIR="$INPUT"
+-    fi   
+-
+-    if [ ! -f "$SM_DIR/$OBJ_DIR/libmilter/libmilter.a" ] ; then
+-        echo "Cannot found Milter library (libmilter.a)"
+-        echo "Please go to $SM_DIR/libmilter and build it"
+-        exit 1
+-    fi
+-    if [ "x$SM_LIB" != "x" -a ! -f "$SM_DIR/$OBJ_DIR/$SM_LIB/$SM_LIB.a" ] ; then
+-        echo "Cannot found additional library ($SM_LIB.a)"
+-        echo "Please go to $SM_DIR and check it"
+-        exit 1    
+-    fi
+     rm -dfr include/libmilter
+     rm -f lib/libmilter.a           
+     ln -s "$SM_DIR/include/libmilter" include/libmilter
+-    ln -s "$SM_DIR/$OBJ_DIR/libmilter/libmilter.a" lib/libmilter.a           
++    ln -s "../libmilter/libmilter.a" lib/libmilter.a
+     if [  "x$SM_LIB" != "x" ] ; then
+         rm -f "lib/$SM_LIB.a"
+-        ln -s "$SM_DIR/$OBJ_DIR/$SM_LIB/$SM_LIB.a" "lib/$SM_LIB.a"
++	ln -s "../libsmutil/$SM_LIB.a" "lib/$SM_LIB.a"
+     fi
+ else
+     DRWEB_SM=""
