Disable obsolete Musicbrainz support.
PR:		165839
Submitted by:	Jason E. Hale <bsdkaffee@gmail.com>

diff --git a/audio/rhythmbox/files/patch-configure b/audio/rhythmbox/files/patch-configure
--- a/audio/rhythmbox/files/patch-configure
+++ b/audio/rhythmbox/files/patch-configure
@@ -1,6 +1,83 @@
---- configure.orig	2009-03-21 13:56:32.000000000 -0400
-+++ configure	2009-03-21 13:57:17.000000000 -0400
-@@ -20763,7 +20763,7 @@ else
+--- ./configure.orig	2010-03-28 05:06:14.000000000 -0400
++++ ./configure	2012-03-07 16:27:36.000000000 -0500
+@@ -15627,76 +15627,7 @@
+ 	have_musicbrainz3=yes
+ fi
+ 
+-pkg_failed=no
+-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for MUSICBRAINZ" >&5
+-$as_echo_n "checking for MUSICBRAINZ... " >&6; }
+-
+-if test -n "$PKG_CONFIG"; then
+-    if test -n "$MUSICBRAINZ_CFLAGS"; then
+-        pkg_cv_MUSICBRAINZ_CFLAGS="$MUSICBRAINZ_CFLAGS"
+-    else
+-        if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libmusicbrainz >= \$MUSICBRAINZ_REQS\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "libmusicbrainz >= $MUSICBRAINZ_REQS") 2>&5
+-  ac_status=$?
+-  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+-  test $ac_status = 0; }; then
+-  pkg_cv_MUSICBRAINZ_CFLAGS=`$PKG_CONFIG --cflags "libmusicbrainz >= $MUSICBRAINZ_REQS" 2>/dev/null`
+-else
+-  pkg_failed=yes
+-fi
+-    fi
+-else
+-	pkg_failed=untried
+-fi
+-if test -n "$PKG_CONFIG"; then
+-    if test -n "$MUSICBRAINZ_LIBS"; then
+-        pkg_cv_MUSICBRAINZ_LIBS="$MUSICBRAINZ_LIBS"
+-    else
+-        if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libmusicbrainz >= \$MUSICBRAINZ_REQS\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "libmusicbrainz >= $MUSICBRAINZ_REQS") 2>&5
+-  ac_status=$?
+-  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+-  test $ac_status = 0; }; then
+-  pkg_cv_MUSICBRAINZ_LIBS=`$PKG_CONFIG --libs "libmusicbrainz >= $MUSICBRAINZ_REQS" 2>/dev/null`
+-else
+-  pkg_failed=yes
+-fi
+-    fi
+-else
+-	pkg_failed=untried
+-fi
+-
+-
+-
+-if test $pkg_failed = yes; then
+-
+-if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+-        _pkg_short_errors_supported=yes
+-else
+-        _pkg_short_errors_supported=no
+-fi
+-        if test $_pkg_short_errors_supported = yes; then
+-	        MUSICBRAINZ_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libmusicbrainz >= $MUSICBRAINZ_REQS"`
+-        else
+-	        MUSICBRAINZ_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libmusicbrainz >= $MUSICBRAINZ_REQS"`
+-        fi
+-	# Put the nasty error message in config.log where it belongs
+-	echo "$MUSICBRAINZ_PKG_ERRORS" >&5
+-
+-	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+-$as_echo "no" >&6; }
+-                have_musicbrainz=no
+-elif test $pkg_failed = untried; then
+ 	have_musicbrainz=no
+-else
+-	MUSICBRAINZ_CFLAGS=$pkg_cv_MUSICBRAINZ_CFLAGS
+-	MUSICBRAINZ_LIBS=$pkg_cv_MUSICBRAINZ_LIBS
+-        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+-$as_echo "yes" >&6; }
+-	have_musicbrainz=yes
+-fi
+ 
+ 
+ 
+@@ -18954,7 +18885,7 @@
  fi
  
  
