sysutils/debootstrap: Update to 1.0.143
PR:		295265

Approved by:	nc (maintainer timeout)

diff --git a/sysutils/debootstrap/files/patch-debootstrap b/sysutils/debootstrap/files/patch-debootstrap
--- a/sysutils/debootstrap/files/patch-debootstrap
+++ b/sysutils/debootstrap/files/patch-debootstrap
@@ -1,4 +1,4 @@
---- debootstrap.orig	2022-10-14 11:16:30 UTC
+--- debootstrap.orig	2025-10-14 09:32:18 UTC
 +++ debootstrap
 @@ -1,4 +1,4 @@
 -#!/bin/sh
@@ -6,7 +6,7 @@
  set -e
  
  VERSION='@VERSION@'
-@@ -14,7 +14,7 @@ if [ -z "$DEBOOTSTRAP_DIR" ]; then
+@@ -14,7 +14,7 @@ if [ -z "${DEBOOTSTRAP_DIR-}" ]; then
  	if [ -x /debootstrap/debootstrap ]; then
  		DEBOOTSTRAP_DIR=/debootstrap
  	else
@@ -15,18 +15,18 @@
  	fi
  fi
  
-@@ -379,8 +379,8 @@ if [ $# != 0 ] ; then
+@@ -385,8 +385,8 @@ if [ $# != 0 ] ; then
  		shift
  		;;
  	    --keyring|--keyring=?*)
--		if ! gpgv --version >/dev/null 2>&1; then
--			error 1 NEEDGPGV "gpgv not installed, but required for Release verification"
-+		if ! gpgv2 --version >/dev/null 2>&1; then
-+			error 1 NEEDGPGV "gpgv2 not installed, but required for Release verification"
+-		if ! in_path sopv && ! in_path sqv && ! in_path gpgv; then
+-			error 1 NEEDPGPV "none of sopv, sqv or gpgv are installed, but required for Release verification"
++		if ! in_path sopv && ! in_path sqv && ! in_path gpgv2; then
++			error 1 NEEDPGPV "none of sopv, sqv or gpgv2 are installed, but required for Release verification"
  		fi
  		if [ "$1" = "--keyring" ] && [ -n "$2" ]; then
  			KEYRING="$2"
-@@ -536,13 +536,7 @@ fi
+@@ -560,13 +560,7 @@ fi
  
  ###########################################################################
  
@@ -41,8 +41,8 @@
  	HOST_ARCH=$(cat "$DEBOOTSTRAP_DIR/arch")
  fi
  HOST_OS="$HOST_ARCH"
-@@ -562,6 +556,14 @@ if [ -z "$HOST_OS" ]; then
- 			HOST_OS=freebsd
+@@ -589,6 +583,14 @@ if [ -z "$HOST_OS" ]; then
+ 			HOST_OS=darwin
  		;;
  	esac
 +fi
diff --git a/sysutils/debootstrap/files/patch-functions b/sysutils/debootstrap/files/patch-functions
--- a/sysutils/debootstrap/files/patch-functions
+++ b/sysutils/debootstrap/files/patch-functions
@@ -1,24 +1,37 @@
---- functions.orig	2024-12-29 18:30:24 UTC
+--- functions.orig	2026-03-26 22:58:30 UTC
 +++ functions
-@@ -658,7 +658,7 @@ download_release_sig () {
+@@ -700,10 +700,10 @@ download_release_sig () {
+ 
  		info RELEASESIG "Checking Release signature"
- 		# Don't worry about the exit status from gpgv; parsing the output will
- 		# take care of that.
--		(gpgv --status-fd 1 --keyring "$KEYRING" --ignore-time-conflict \
-+		(gpgv2 --status-fd 1 --keyring "$KEYRING" --ignore-time-conflict \
- 		 "$relsigdest" "$reldest" || true) | read_gpg_status
+ 		# If everything is installed, prefer gpgv for now
+-		if in_path gpgv; then
++		if in_path gpgv2; then
+ 			# Don't worry about the exit status from gpgv; parsing the output will
+ 			# take care of that.
+-			(gpgv --status-fd 1 --keyring "$KEYRING" --ignore-time-conflict \
++			(gpgv2 --status-fd 1 --keyring "$KEYRING" --ignore-time-conflict \
+ 			 "$relsigdest" "$reldest" || true) | read_gpg_status
+ 		elif in_path sopv; then
+ 			local rc=0
+@@ -715,7 +715,7 @@ download_release_sig () {
+ 			check_sqv_status "$rc"
+ 		else
+ 			# This is already checked at argument parsing time, so shouldn't happen here
+-			error 1 NEEDPGPV "none of sopv, sqv or gpgv are installed, but required for Release verification"
++			error 1 NEEDPGPV "none of sopv, sqv or gpgv2 are installed, but required for Release verification"
+ 		fi
  		progress 100 100 DOWNRELSIG "Downloading Release file signature"
  	fi
-@@ -978,7 +978,7 @@ extract_dpkg_deb_field () {
+@@ -1045,7 +1045,7 @@ extract_dpkg_deb_data () {
  extract_dpkg_deb_data () {
  	local pkg="$1"
  
--	dpkg-deb --fsys-tarfile "$pkg" | tar $EXTRACT_DEB_TAR_OPTIONS -xf - || error 1 FILEEXIST "Tried to extract package, but file already exists. Exit..."
-+	dpkg-deb --fsys-tarfile "$pkg" | gtar $EXTRACT_DEB_TAR_OPTIONS -xf - || error 1 FILEEXIST "Tried to extract package, but file already exists. Exit..."
+-	dpkg-deb --fsys-tarfile "$pkg" | tar $EXTRACT_DEB_TAR_OPTIONS -xf - || error 1 FILEEXIST "Tried to extract package, but tar failed. Exit..."
++	dpkg-deb --fsys-tarfile "$pkg" | gtar $EXTRACT_DEB_TAR_OPTIONS -xf - || error 1 FILEEXIST "Tried to extract package, but tar failed. Exit..."
  }
  
  # Raw .deb extractors
-@@ -998,7 +998,7 @@ extract_ar_deb_field () {
+@@ -1065,7 +1065,7 @@ extract_ar_deb_field () {
  
  	if in_path $cat_cmd; then
  		ar -p "$pkg" "$tarball" | $cat_cmd |
@@ -27,7 +40,7 @@
  		    grep -i "^$field:" | sed -e 's/[^:]*: *//' | head -n 1
  	else
  		error 1 UNPACKCMDUNVL "Extracting %s requires the %s command, which is not available" "$pkg" "$cat_cmd"
-@@ -1020,7 +1020,7 @@ extract_ar_deb_data () {
+@@ -1087,7 +1087,7 @@ extract_ar_deb_data () {
  	esac
  
  	if in_path "$cat_cmd"; then
@@ -36,16 +49,16 @@
  	else
  		error 1 UNPACKCMDUNVL "Extracting %s requires the %s command, which is not available" "$pkg" "$cat_cmd"
  	fi
-@@ -1614,7 +1614,7 @@ while (read STDIN, $x, 1) {
+@@ -1696,7 +1696,7 @@ while (read STDIN, $x, 1) {
  }' "$@"
  		elif [ "$1" = "GETDEPS" ]; then
  			local pkgdest="$2"; shift; shift
--LC_ALL=C grep "$gropt" '^$|^Package:|^Depends:|^Pre-Depends:'  $pkgdest | perl -e '
-+LC_ALL=C pcre2grep '^$|^Package:|^Depends:|^Pre-Depends:' $pkgdest | perl -e '
+-LC_ALL=C grep "$gropt" '^$|^Package:|^Depends:|^Pre-Depends:' "${pkgdest}" | perl -e '
++LC_ALL=C pcre2grep '^$|^Package:|^Depends:|^Pre-Depends:' "${pkgdest}" | perl -e '
  %seen = map { $_ => 1 } @ARGV;
  while (<STDIN>) {
  	if (/^Package: (.*)$/) {
-@@ -1642,13 +1642,13 @@ while (<STDIN>) {
+@@ -1724,13 +1724,13 @@ while (<STDIN>) {
  			local m="$2"
  			local p="$3"
  			shift; shift; shift
@@ -56,12 +69,12 @@
  			local m="$3"
  			local p="$4"
  			shift; shift; shift; shift
--			LC_ALL=C grep "$gropt" '^$|^Package:|^Priority:' "$p" | pkgdetails_field 0 "$f" "$m" "$@"
-+			LC_ALL=C pcre2grep '^$|^Package:|^Priority:' "$p" | pkgdetails_field 0 "$f" "$m" "$@"
+-			LC_ALL=C grep "$gropt" '^$|^Package:|^Priority:|^Essential:' "$p" | pkgdetails_field 0 "$f" "$m" "$@"
++			LC_ALL=C pcre2grep '^$|^Package:|^Priority:|^Essential:' "$p" | pkgdetails_field 0 "$f" "$m" "$@"
  		elif [ "$1" = "STANZAS" ]; then
  			local pkgdest="$2"; shift; shift
  			perl -e '
-@@ -1805,7 +1805,7 @@ read_gpg_status () {
+@@ -1941,7 +1941,7 @@ read_gpg_status () {
  	elif [ "$unkkey" ]; then
  		error 1 UNKNOWNRELSIG "Release signed by unknown key (key id %s)\n   The specified keyring $KEYRING may be incorrect or out of date.\n   You can find the latest Debian release key at https://ftp-master.debian.org/keys.html" "$unkkey"
  	else
