o  Makefile: polish MASTER_SITES;  [1] o  rc_subr script: check up using of /usr/sbin/daemon and support <user>    to run command as.  [1] o  while I'm here: replace spaces to tabs at Makefile after variables.
PR:		101792  [1]
Submitted by:	Alexander Logvinov <ports@logvinov.com> (maintainer)  [1]
Approved by:	netchild (mentor, implicit)

diff --git a/games/utserver/files/ucc.in b/games/utserver/files/ucc.in
--- a/games/utserver/files/ucc.in
+++ b/games/utserver/files/ucc.in
@@ -35,12 +35,21 @@ ucc_startcmd()
         return 1
     fi
     echo Starting ${name}.
+    if [ ! -x /usr/sbin/daemon ]; then
+	err 1 "/usr/sbin/daemon required"
+    fi
+    if ! /usr/sbin/daemon 2>&1 | grep pidfile > /dev/null; then
+	err 1 "/usr/sbin/daemon with -p option required"
+    fi
     if ! kldstat -v | grep -E 'linux(aout|elf)' > /dev/null; then
         err 1 "Linux support required"
-        return
     fi
     cd %%UTDIR%%/System/
-    /usr/sbin/daemon -p ${ucc_pidfile} ${command} ${command_args} 2>&1 >> ${ucc_logfile}
+    cmd="/usr/sbin/daemon -p ${ucc_pidfile} ${command} ${command_args}"
+    if [ -n "$ucc_user" ]; then
+	cmd="su -m $ucc_user -c '$cmd'"
+    fi
+    eval "$cmd 2>&1 >> ${ucc_logfile}"
 }
        
 run_rc_command "$1"
