Upgrade to 3.0.
Partial changelog at
<https://sourceforge.net/project/shownotes.php?group_id=91526&release_id=478524>

diff --git a/math/freemat/files/patch-configure b/math/freemat/files/patch-configure
--- a/math/freemat/files/patch-configure
+++ b/math/freemat/files/patch-configure
@@ -1,20 +1,472 @@
---- configure.orig	Wed Mar 16 16:39:00 2005
-+++ configure	Sun Mar 27 23:34:08 2005
-@@ -7731,7 +7731,7 @@
-     PICFLAG=0
-     SHAREDSUFFIX=""
-     FLUID="fluid"
--    LINKSHARED="-L../lib -lfltk_images -lfltk_forms -lfltk"
-+    LINKSHARED="-lfltk_images -lfltk_forms -lfltk"
+--- configure.orig	Tue Jan  9 05:33:15 2007
++++ configure	Fri Feb  9 23:53:27 2007
+@@ -6083,234 +6083,6 @@
+   LIBS="-lamd $LIBS"
  fi
  
+-echo "$as_me:$LINENO: checking for umfpack_zl_solve in -lumfpack" >&5
+-echo $ECHO_N "checking for umfpack_zl_solve in -lumfpack... $ECHO_C" >&6
+-if test "${ac_cv_lib_umfpack_umfpack_zl_solve+set}" = set; then
+-  echo $ECHO_N "(cached) $ECHO_C" >&6
+-else
+-  ac_check_lib_save_LIBS=$LIBS
+-LIBS="-lumfpack  $LIBS"
+-cat >conftest.$ac_ext <<_ACEOF
+-/* confdefs.h.  */
+-_ACEOF
+-cat confdefs.h >>conftest.$ac_ext
+-cat >>conftest.$ac_ext <<_ACEOF
+-/* end confdefs.h.  */
+-
+-/* Override any gcc2 internal prototype to avoid an error.  */
+-#ifdef __cplusplus
+-extern "C"
+-#endif
+-/* We use char because int might match the return type of a gcc2
+-   builtin and then its argument prototype would still apply.  */
+-char umfpack_zl_solve ();
+-int
+-main ()
+-{
+-umfpack_zl_solve ();
+-  ;
+-  return 0;
+-}
+-_ACEOF
+-rm -f conftest.$ac_objext conftest$ac_exeext
+-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+-  (eval $ac_link) 2>conftest.er1
+-  ac_status=$?
+-  grep -v '^ *+' conftest.er1 >conftest.err
+-  rm -f conftest.er1
+-  cat conftest.err >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); } &&
+-	 { ac_try='test -z "$ac_c_werror_flag"
+-			 || test ! -s conftest.err'
+-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+-  (eval $ac_try) 2>&5
+-  ac_status=$?
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); }; } &&
+-	 { ac_try='test -s conftest$ac_exeext'
+-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+-  (eval $ac_try) 2>&5
+-  ac_status=$?
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); }; }; then
+-  ac_cv_lib_umfpack_umfpack_zl_solve=yes
+-else
+-  echo "$as_me: failed program was:" >&5
+-sed 's/^/| /' conftest.$ac_ext >&5
+-
+-ac_cv_lib_umfpack_umfpack_zl_solve=no
+-fi
+-rm -f conftest.err conftest.$ac_objext \
+-      conftest$ac_exeext conftest.$ac_ext
+-LIBS=$ac_check_lib_save_LIBS
+-fi
+-echo "$as_me:$LINENO: result: $ac_cv_lib_umfpack_umfpack_zl_solve" >&5
+-echo "${ECHO_T}$ac_cv_lib_umfpack_umfpack_zl_solve" >&6
+-if test $ac_cv_lib_umfpack_umfpack_zl_solve = yes; then
+-  found_umfpack="yes"
+-else
+-  found_umfpack="no"
+-fi
+-
+-if test "${ac_cv_header_umfpack_h+set}" = set; then
+-  echo "$as_me:$LINENO: checking for umfpack.h" >&5
+-echo $ECHO_N "checking for umfpack.h... $ECHO_C" >&6
+-if test "${ac_cv_header_umfpack_h+set}" = set; then
+-  echo $ECHO_N "(cached) $ECHO_C" >&6
+-fi
+-echo "$as_me:$LINENO: result: $ac_cv_header_umfpack_h" >&5
+-echo "${ECHO_T}$ac_cv_header_umfpack_h" >&6
+-else
+-  # Is the header compilable?
+-echo "$as_me:$LINENO: checking umfpack.h usability" >&5
+-echo $ECHO_N "checking umfpack.h usability... $ECHO_C" >&6
+-cat >conftest.$ac_ext <<_ACEOF
+-/* confdefs.h.  */
+-_ACEOF
+-cat confdefs.h >>conftest.$ac_ext
+-cat >>conftest.$ac_ext <<_ACEOF
+-/* end confdefs.h.  */
+-$ac_includes_default
+-#include <umfpack.h>
+-_ACEOF
+-rm -f conftest.$ac_objext
+-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+-  (eval $ac_compile) 2>conftest.er1
+-  ac_status=$?
+-  grep -v '^ *+' conftest.er1 >conftest.err
+-  rm -f conftest.er1
+-  cat conftest.err >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); } &&
+-	 { ac_try='test -z "$ac_c_werror_flag"
+-			 || test ! -s conftest.err'
+-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+-  (eval $ac_try) 2>&5
+-  ac_status=$?
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); }; } &&
+-	 { ac_try='test -s conftest.$ac_objext'
+-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+-  (eval $ac_try) 2>&5
+-  ac_status=$?
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); }; }; then
+-  ac_header_compiler=yes
+-else
+-  echo "$as_me: failed program was:" >&5
+-sed 's/^/| /' conftest.$ac_ext >&5
+-
+-ac_header_compiler=no
+-fi
+-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+-echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+-echo "${ECHO_T}$ac_header_compiler" >&6
+-
+-# Is the header present?
+-echo "$as_me:$LINENO: checking umfpack.h presence" >&5
+-echo $ECHO_N "checking umfpack.h presence... $ECHO_C" >&6
+-cat >conftest.$ac_ext <<_ACEOF
+-/* confdefs.h.  */
+-_ACEOF
+-cat confdefs.h >>conftest.$ac_ext
+-cat >>conftest.$ac_ext <<_ACEOF
+-/* end confdefs.h.  */
+-#include <umfpack.h>
+-_ACEOF
+-if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+-  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+-  ac_status=$?
+-  grep -v '^ *+' conftest.er1 >conftest.err
+-  rm -f conftest.er1
+-  cat conftest.err >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); } >/dev/null; then
+-  if test -s conftest.err; then
+-    ac_cpp_err=$ac_c_preproc_warn_flag
+-    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+-  else
+-    ac_cpp_err=
+-  fi
+-else
+-  ac_cpp_err=yes
+-fi
+-if test -z "$ac_cpp_err"; then
+-  ac_header_preproc=yes
+-else
+-  echo "$as_me: failed program was:" >&5
+-sed 's/^/| /' conftest.$ac_ext >&5
+-
+-  ac_header_preproc=no
+-fi
+-rm -f conftest.err conftest.$ac_ext
+-echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+-echo "${ECHO_T}$ac_header_preproc" >&6
+-
+-# So?  What about this header?
+-case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+-  yes:no: )
+-    { echo "$as_me:$LINENO: WARNING: umfpack.h: accepted by the compiler, rejected by the preprocessor!" >&5
+-echo "$as_me: WARNING: umfpack.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: umfpack.h: proceeding with the compiler's result" >&5
+-echo "$as_me: WARNING: umfpack.h: proceeding with the compiler's result" >&2;}
+-    ac_header_preproc=yes
+-    ;;
+-  no:yes:* )
+-    { echo "$as_me:$LINENO: WARNING: umfpack.h: present but cannot be compiled" >&5
+-echo "$as_me: WARNING: umfpack.h: present but cannot be compiled" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: umfpack.h:     check for missing prerequisite headers?" >&5
+-echo "$as_me: WARNING: umfpack.h:     check for missing prerequisite headers?" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: umfpack.h: see the Autoconf documentation" >&5
+-echo "$as_me: WARNING: umfpack.h: see the Autoconf documentation" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: umfpack.h:     section \"Present But Cannot Be Compiled\"" >&5
+-echo "$as_me: WARNING: umfpack.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: umfpack.h: proceeding with the preprocessor's result" >&5
+-echo "$as_me: WARNING: umfpack.h: proceeding with the preprocessor's result" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: umfpack.h: in the future, the compiler will take precedence" >&5
+-echo "$as_me: WARNING: umfpack.h: in the future, the compiler will take precedence" >&2;}
+-    (
+-      cat <<\_ASBOX
+-## ------------------------------------------ ##
+-## Report this to the AC_PACKAGE_NAME lists.  ##
+-## ------------------------------------------ ##
+-_ASBOX
+-    ) |
+-      sed "s/^/$as_me: WARNING:     /" >&2
+-    ;;
+-esac
+-echo "$as_me:$LINENO: checking for umfpack.h" >&5
+-echo $ECHO_N "checking for umfpack.h... $ECHO_C" >&6
+-if test "${ac_cv_header_umfpack_h+set}" = set; then
+-  echo $ECHO_N "(cached) $ECHO_C" >&6
+-else
+-  ac_cv_header_umfpack_h=$ac_header_preproc
+-fi
+-echo "$as_me:$LINENO: result: $ac_cv_header_umfpack_h" >&5
+-echo "${ECHO_T}$ac_cv_header_umfpack_h" >&6
+-
+-fi
+-if test $ac_cv_header_umfpack_h = yes; then
+-  :
+-else
+-  found_umfpack="no"
+-fi
+-
+-
+-
+-if test x"$found_umfpack" == xyes; then
+-  LIBS="-lumfpack $LIBS"
+-fi
+-if test x"$found_amd" == xyes; then
+-	if test x"$found_umfpack" == xyes; then
+-
+-cat >>confdefs.h <<\_ACEOF
+-#define HAVE_UMFPACK 1
+-_ACEOF
+-
+-	fi
+-fi
+-
+ echo "$as_me:$LINENO: checking for fftwf_malloc in -lfftw3f" >&5
+ echo $ECHO_N "checking for fftwf_malloc in -lfftw3f... $ECHO_C" >&6
+ if test "${ac_cv_lib_fftw3f_fftwf_malloc+set}" = set; then
+@@ -8149,6 +7921,234 @@
+ 	LIBS="$BLAS_LIBS $LIBS"
+    fi
  
-@@ -16937,7 +16937,7 @@
-           ac_config_headers="$ac_config_headers config.h:configh.in"
++# FreeBSD: umfpack requires blas.
++echo "$as_me:$LINENO: checking for umfpack_zl_solve in -lumfpack" >&5
++echo $ECHO_N "checking for umfpack_zl_solve in -lumfpack... $ECHO_C" >&6
++if test "${ac_cv_lib_umfpack_umfpack_zl_solve+set}" = set; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++else
++  ac_check_lib_save_LIBS=$LIBS
++LIBS="-lumfpack  $LIBS"
++cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++
++/* Override any gcc2 internal prototype to avoid an error.  */
++#ifdef __cplusplus
++extern "C"
++#endif
++/* We use char because int might match the return type of a gcc2
++   builtin and then its argument prototype would still apply.  */
++char umfpack_zl_solve ();
++int
++main ()
++{
++umfpack_zl_solve ();
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext conftest$ac_exeext
++if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
++  (eval $ac_link) 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } &&
++	 { ac_try='test -z "$ac_c_werror_flag"
++			 || test ! -s conftest.err'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; } &&
++	 { ac_try='test -s conftest$ac_exeext'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; }; then
++  ac_cv_lib_umfpack_umfpack_zl_solve=yes
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++ac_cv_lib_umfpack_umfpack_zl_solve=no
++fi
++rm -f conftest.err conftest.$ac_objext \
++      conftest$ac_exeext conftest.$ac_ext
++LIBS=$ac_check_lib_save_LIBS
++fi
++echo "$as_me:$LINENO: result: $ac_cv_lib_umfpack_umfpack_zl_solve" >&5
++echo "${ECHO_T}$ac_cv_lib_umfpack_umfpack_zl_solve" >&6
++if test $ac_cv_lib_umfpack_umfpack_zl_solve = yes; then
++  found_umfpack="yes"
++else
++  found_umfpack="no"
++fi
++
++if test "${ac_cv_header_umfpack_h+set}" = set; then
++  echo "$as_me:$LINENO: checking for umfpack.h" >&5
++echo $ECHO_N "checking for umfpack.h... $ECHO_C" >&6
++if test "${ac_cv_header_umfpack_h+set}" = set; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++fi
++echo "$as_me:$LINENO: result: $ac_cv_header_umfpack_h" >&5
++echo "${ECHO_T}$ac_cv_header_umfpack_h" >&6
++else
++  # Is the header compilable?
++echo "$as_me:$LINENO: checking umfpack.h usability" >&5
++echo $ECHO_N "checking umfpack.h usability... $ECHO_C" >&6
++cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++$ac_includes_default
++#include <umfpack.h>
++_ACEOF
++rm -f conftest.$ac_objext
++if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
++  (eval $ac_compile) 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } &&
++	 { ac_try='test -z "$ac_c_werror_flag"
++			 || test ! -s conftest.err'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; } &&
++	 { ac_try='test -s conftest.$ac_objext'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; }; then
++  ac_header_compiler=yes
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++ac_header_compiler=no
++fi
++rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
++echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
++echo "${ECHO_T}$ac_header_compiler" >&6
++
++# Is the header present?
++echo "$as_me:$LINENO: checking umfpack.h presence" >&5
++echo $ECHO_N "checking umfpack.h presence... $ECHO_C" >&6
++cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++#include <umfpack.h>
++_ACEOF
++if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
++  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } >/dev/null; then
++  if test -s conftest.err; then
++    ac_cpp_err=$ac_c_preproc_warn_flag
++    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
++  else
++    ac_cpp_err=
++  fi
++else
++  ac_cpp_err=yes
++fi
++if test -z "$ac_cpp_err"; then
++  ac_header_preproc=yes
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++  ac_header_preproc=no
++fi
++rm -f conftest.err conftest.$ac_ext
++echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
++echo "${ECHO_T}$ac_header_preproc" >&6
++
++# So?  What about this header?
++case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
++  yes:no: )
++    { echo "$as_me:$LINENO: WARNING: umfpack.h: accepted by the compiler, rejected by the preprocessor!" >&5
++echo "$as_me: WARNING: umfpack.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
++    { echo "$as_me:$LINENO: WARNING: umfpack.h: proceeding with the compiler's result" >&5
++echo "$as_me: WARNING: umfpack.h: proceeding with the compiler's result" >&2;}
++    ac_header_preproc=yes
++    ;;
++  no:yes:* )
++    { echo "$as_me:$LINENO: WARNING: umfpack.h: present but cannot be compiled" >&5
++echo "$as_me: WARNING: umfpack.h: present but cannot be compiled" >&2;}
++    { echo "$as_me:$LINENO: WARNING: umfpack.h:     check for missing prerequisite headers?" >&5
++echo "$as_me: WARNING: umfpack.h:     check for missing prerequisite headers?" >&2;}
++    { echo "$as_me:$LINENO: WARNING: umfpack.h: see the Autoconf documentation" >&5
++echo "$as_me: WARNING: umfpack.h: see the Autoconf documentation" >&2;}
++    { echo "$as_me:$LINENO: WARNING: umfpack.h:     section \"Present But Cannot Be Compiled\"" >&5
++echo "$as_me: WARNING: umfpack.h:     section \"Present But Cannot Be Compiled\"" >&2;}
++    { echo "$as_me:$LINENO: WARNING: umfpack.h: proceeding with the preprocessor's result" >&5
++echo "$as_me: WARNING: umfpack.h: proceeding with the preprocessor's result" >&2;}
++    { echo "$as_me:$LINENO: WARNING: umfpack.h: in the future, the compiler will take precedence" >&5
++echo "$as_me: WARNING: umfpack.h: in the future, the compiler will take precedence" >&2;}
++    (
++      cat <<\_ASBOX
++## ------------------------------------------ ##
++## Report this to the AC_PACKAGE_NAME lists.  ##
++## ------------------------------------------ ##
++_ASBOX
++    ) |
++      sed "s/^/$as_me: WARNING:     /" >&2
++    ;;
++esac
++echo "$as_me:$LINENO: checking for umfpack.h" >&5
++echo $ECHO_N "checking for umfpack.h... $ECHO_C" >&6
++if test "${ac_cv_header_umfpack_h+set}" = set; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++else
++  ac_cv_header_umfpack_h=$ac_header_preproc
++fi
++echo "$as_me:$LINENO: result: $ac_cv_header_umfpack_h" >&5
++echo "${ECHO_T}$ac_cv_header_umfpack_h" >&6
++
++fi
++if test $ac_cv_header_umfpack_h = yes; then
++  :
++else
++  found_umfpack="no"
++fi
++
++
++
++if test x"$found_umfpack" == xyes; then
++  LIBS="-lumfpack $LIBS"
++fi
++if test x"$found_amd" == xyes; then
++	if test x"$found_umfpack" == xyes; then
++
++cat >>confdefs.h <<\_ACEOF
++#define HAVE_UMFPACK 1
++_ACEOF
++
++	fi
++fi
  
+ acx_lapack_ok=no
  
--LAPACK_LIBS="-L\${top_builddir}/libs/libMiniLAPACK -lMiniLAPACK"
-+LAPACK_LIBS="-llapack"
- 
- 
- LIBS="$LAPACK_LIBS $BLAS_LIBS $LIBS $FLIBS $CURSES_LIB $MPILIBS"
