net/vnstat: Update to 2.0
Changelog:	https://humdi.net/vnstat/CHANGES

diff --git a/net/vnstat/files/vnstat.in b/net/vnstat/files/vnstat.in
--- a/net/vnstat/files/vnstat.in
+++ b/net/vnstat/files/vnstat.in
@@ -35,8 +35,8 @@ create_iface_database()
 {
 	local iface="$1"
 	local descr="$2"
-	su -m ${vnstat_user} -c "${user_cmd} --create --iface $iface" >/dev/null 2>&1 ||
-	  ! echo "$name: Failed to create database for the $descr interface $iface" || return 1
+	su -m ${vnstat_user} -c "${user_cmd} --add --iface $iface" >/dev/null 2>&1 ||
+	  ! echo "$name: Failed to add database for the $descr interface $iface" || return 1
 	echo "$name: Created the database for the $descr interface $iface"
 }
 
