Update to 1.3.5.
PR:		ports/95595
Submitted by:	KATO Tsuguru <tkato432 (at) yahoo.com>

diff --git a/net/linphone-base/files/patch-configure b/net/linphone-base/files/patch-configure
--- a/net/linphone-base/files/patch-configure
+++ b/net/linphone-base/files/patch-configure
@@ -1,6 +1,6 @@
---- configure.orig	Sat Mar  4 01:55:47 2006
-+++ configure	Sat Mar 11 01:28:23 2006
-@@ -23532,23 +23532,6 @@
+--- configure.orig	Sat Apr  1 01:54:31 2006
++++ configure	Sat Apr  1 01:54:31 2006
+@@ -23542,23 +23542,6 @@
  fi
  
  
@@ -23,4 +23,63 @@
 -
  found_sound=no
  
+ 
+@@ -27917,12 +27900,12 @@
+         pkg_cv_SPEEX_CFLAGS="$SPEEX_CFLAGS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"speex >= 1.1.12\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "speex >= 1.1.12") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"speex >= 1.0.5\"") >&5
++  ($PKG_CONFIG --exists --print-errors "speex >= 1.0.5") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_SPEEX_CFLAGS=`$PKG_CONFIG --cflags "speex >= 1.1.12" 2>/dev/null`
++  pkg_cv_SPEEX_CFLAGS=`$PKG_CONFIG --cflags "speex >= 1.0.5" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -27935,12 +27918,12 @@
+         pkg_cv_SPEEX_LIBS="$SPEEX_LIBS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"speex >= 1.1.12\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "speex >= 1.1.12") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"speex >= 1.0.5\"") >&5
++  ($PKG_CONFIG --exists --print-errors "speex >= 1.0.5") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_SPEEX_LIBS=`$PKG_CONFIG --libs "speex >= 1.1.12" 2>/dev/null`
++  pkg_cv_SPEEX_LIBS=`$PKG_CONFIG --libs "speex >= 1.0.5" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -27959,14 +27942,14 @@
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        SPEEX_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "speex >= 1.1.12"`
++	        SPEEX_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "speex >= 1.0.5"`
+         else
+-	        SPEEX_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "speex >= 1.1.12"`
++	        SPEEX_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "speex >= 1.0.5"`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$SPEEX_PKG_ERRORS" >&5
+ 
+-	{ { echo "$as_me:$LINENO: error: Package requirements (speex >= 1.1.12) were not met:
++	{ { echo "$as_me:$LINENO: error: Package requirements (speex >= 1.0.5) were not met:
+ 
+ $SPEEX_PKG_ERRORS
+ 
+@@ -27977,7 +27960,7 @@
+ and SPEEX_LIBS to avoid the need to call pkg-config.
+ See the pkg-config man page for more details.
+ " >&5
+-echo "$as_me: error: Package requirements (speex >= 1.1.12) were not met:
++echo "$as_me: error: Package requirements (speex >= 1.0.5) were not met:
+ 
+ $SPEEX_PKG_ERRORS
  
