Update to version 0.31.
PR:		12781 (13 of 19)
Submitted by:	Ade Lovett <ade@lovett.com>

diff --git a/math/gnumeric/files/patch-aa b/math/gnumeric/files/patch-aa
--- a/math/gnumeric/files/patch-aa
+++ b/math/gnumeric/files/patch-aa
@@ -1,6 +1,6 @@
---- configure.orig	Tue May 18 18:00:05 1999
-+++ configure	Sat May 22 15:59:03 1999
-@@ -2860,7 +2860,7 @@
+--- configure.orig	Fri Jul  9 22:12:23 1999
++++ configure	Mon Jul 12 16:48:09 1999
+@@ -2786,7 +2786,7 @@
  fi
  if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
    echo "$ac_t""yes" 1>&6
@@ -9,16 +9,16 @@
  else
    echo "$ac_t""no" 1>&6
  echo $ac_n "checking for pthread_create""... $ac_c" 1>&6
-@@ -3405,7 +3405,7 @@
+@@ -3356,7 +3356,7 @@
    echo $ac_n "(cached) $ac_c" 1>&6
  else
    ac_save_LIBS="$LIBS"
 -LIBS="-lxml `gnome-config --libs xml` $LIBS"
 +LIBS="`xml-config --libs` $LIBS"
  cat > conftest.$ac_ext <<EOF
- #line 3411 "configure"
+ #line 3362 "configure"
  #include "confdefs.h"
-@@ -3436,7 +3436,7 @@
+@@ -3387,7 +3387,7 @@
    
  		
  		
@@ -27,7 +27,7 @@
  	
  else
    echo "$ac_t""no" 1>&6
-@@ -5657,15 +5657,15 @@
+@@ -5616,15 +5616,15 @@
  fi
  
          
@@ -42,28 +42,26 @@
  	LIBS=`echo $LIBS | sed -e 's/-lintl//'`
 -        nls_cv_header_intl=intl/libintl.h
 -        nls_cv_header_libgt=intl/libgettext.h
-+#        nls_cv_header_intl=intl/libintl.h
-+#        nls_cv_header_libgt=intl/libgettext.h
++#       nls_cv_header_intl=intl/libintl.h
++#       nls_cv_header_libgt=intl/libgettext.h
        fi
  
              if test "$XGETTEXT" != ":"; then
-@@ -6249,7 +6249,7 @@
- test -n "$AWK" && break
- done
+@@ -6053,14 +6053,14 @@
  
--GDK_KEYSYMS="`$GTK_CONFIG --prefix`/include/gdk/gdkkeysyms.h"
-+GDK_KEYSYMS="`$GTK_CONFIG --prefix`/include/gtk12/gdk/gdkkeysyms.h"
- 
- cat >> confdefs.h <<\EOF
- #define ENABLE_GNOME 1
-@@ -6273,8 +6273,8 @@
-   LIBGLADE_FULLDIST_TRUE='#'
-   LIBGLADE_FULLDIST_FALSE=
+ echo $ac_n "checking For Glade libraries""... $ac_c" 1>&6
+ echo "configure:6056: checking For Glade libraries" >&5
+-if gnome-config --libs libglade > /dev/null 2>&1; then 
++if libglade-config --libs > /dev/null 2>&1; then 
+     echo "$ac_t""found" 1>&6
+ else
+     { echo "configure: error: Did not find libGlade installed" 1>&2; exit 1; }
  fi
--XML_LIBS=`gnome-config --libs xml`
--XML_CFLAGS=`gnome-config --cflags xml`/gnome-xml
-+XML_LIBS=`xml-config --libs`
-+XML_CFLAGS=`xml-config --cflags`
+ 
+-EXTRA_GNOME_LIBS=`gnome-config --libs gnomeui print libglade $bonobo`
+-EXTRA_GNOME_CFLAGS=`gnome-config --cflags gnomeui print libglade $bonobo`
++EXTRA_GNOME_LIBS="`gnome-config --libs gnomeui print` `libglade-config --libs gnome` $bonobo"
++EXTRA_GNOME_CFLAGS="`gnome-config --cflags gnomeui print` `libglade-config --cflags gnome` $bonobo"
  
  
- if false; then
+ 
