update to 0.60.4 the vpopmail support was removed with 0.60.3 (because none felt responsible for maintaining it in courier-authlib) - this commit adds - togehter with this update - a patch which patches the vpopmail support back into 0.60.4 (because at least I need the interaction with vpopmail!).

diff --git a/security/courier-authlib/files/patch-configure b/security/courier-authlib/files/patch-configure
--- a/security/courier-authlib/files/patch-configure
+++ b/security/courier-authlib/files/patch-configure
@@ -1,6 +1,16 @@
---- configure.orig	2007-09-29 16:43:43.000000000 +0200
-+++ configure	2007-10-03 13:14:36.000000000 +0200
-@@ -942,7 +942,11 @@
+--- configure.orig	2008-06-12 20:25:13.000000000 +0200
++++ configure	2008-06-12 20:23:39.000000000 +0200
+@@ -907,6 +907,9 @@
+ SHADOWLIBS
+ LIBAUTHSHADOW
+ LIBAUTHPWD
++vpopmail_home
++VPOPMAILLIBS
++LIBAUTHVCHKPW
+ authpgsqlrc
+ PG_CONFIG
+ PGSQL_LIBS
+@@ -937,7 +940,11 @@
  HAVE_SGML_FALSE
  subdirs
  LIBOBJS
@@ -13,7 +23,24 @@
  ac_subst_files=''
        ac_precious_vars='build_alias
  host_alias
-@@ -21215,8 +21219,12 @@
+@@ -1561,6 +1568,7 @@
+  --with-authldaprc=filename         Expect to find authldaprc here
+  --without-authpwd                  Do not include the authpwd module
+  --without-authshadow               Do not include the authshadow module
++ --without-authvchkpw               Do not include the authvchkpw module
+  --with-authpgsqlrc=filename        Expect to find authpgsql here
+  --without-authpgsql               Do not include the authpgsql module
+  --with-pgsql-libs=DIR		Look for pgsql libs in this dir
+@@ -2502,7 +2510,7 @@
+ fi
+ 
+ fi
+-INSTALL_STRIP_PROGRAM="\$(install_sh) -c -s"
++INSTALL_STRIP_PROGRAM="${INSTALL_PROGRAM} -s"
+ 
+ # We need awk for the "check" target.  The system "awk" is bad on
+ # some platforms.
+@@ -21290,8 +21298,12 @@
  
  if test "$doauthuserdb" = "no"
  then
@@ -26,7 +53,7 @@
  	AUTHUSERDB="authuserdb"
  	LIBAUTHUSERDB="libauthuserdb.la"
  
-@@ -22894,6 +22902,20 @@
+@@ -22969,6 +22981,20 @@
  fi
  
  
@@ -47,190 +74,294 @@
  
   if test "$HAVE_LDAP" = 1; then
    HAVE_LDAP_TRUE=
-@@ -24180,9 +24202,9 @@
- if test "$doauthmysql" = ""
- then
- 	LIBS="$MYSQL_LIBS $LIBS"
--	{ echo "$as_me:$LINENO: checking for mysql_connect" >&5
--echo $ECHO_N "checking for mysql_connect... $ECHO_C" >&6; }
--if test "${ac_cv_func_mysql_connect+set}" = set; then
-+	{ echo "$as_me:$LINENO: checking for mysql_real_connect" >&5
-+echo $ECHO_N "checking for mysql_real_connect... $ECHO_C" >&6; }
-+if test "${ac_cv_func_mysql_real_connect+set}" = set; then
-   echo $ECHO_N "(cached) $ECHO_C" >&6
- else
-   cat >conftest.$ac_ext <<_ACEOF
-@@ -24191,12 +24213,12 @@
- cat confdefs.h >>conftest.$ac_ext
- cat >>conftest.$ac_ext <<_ACEOF
- /* end confdefs.h.  */
--/* Define mysql_connect to an innocuous variant, in case <limits.h> declares mysql_connect.
-+/* Define mysql_real_connect to an innocuous variant, in case <limits.h> declares mysql_real_connect.
-    For example, HP-UX 11i <limits.h> declares gettimeofday.  */
--#define mysql_connect innocuous_mysql_connect
-+#define mysql_real_connect innocuous_mysql_real_connect
+@@ -23617,6 +23643,256 @@
  
- /* System header to define __stub macros and hopefully few prototypes,
--    which can conflict with char mysql_connect (); below.
-+    which can conflict with char mysql_real_connect (); below.
-     Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
-     <limits.h> exists even on freestanding compilers.  */
  
-@@ -24206,7 +24228,7 @@
- # include <assert.h>
- #endif
  
--#undef mysql_connect
-+#undef mysql_real_connect
- 
- /* Override any GCC internal prototype to avoid an error.
-    Use char because int might match the return type of a GCC
-@@ -24214,18 +24236,18 @@
- #ifdef __cplusplus
- extern "C"
- #endif
--char mysql_connect ();
-+char mysql_real_connect ();
- /* The GNU C library defines this for functions which it implements
-     to always fail with ENOSYS.  Some functions are actually named
-     something starting with __ and the normal name is an alias.  */
--#if defined __stub_mysql_connect || defined __stub___mysql_connect
-+#if defined __stub_mysql_real_connect || defined __stub___mysql_real_connect
- choke me
- #endif
- 
- int
- main ()
- {
--return mysql_connect ();
-+return mysql_real_connect ();
-   ;
-   return 0;
- }
-@@ -24248,20 +24270,20 @@
- 	 test ! -s conftest.err
-        } && test -s conftest$ac_exeext &&
-        $as_test_x conftest$ac_exeext; then
--  ac_cv_func_mysql_connect=yes
-+  ac_cv_func_mysql_real_connect=yes
- else
-   echo "$as_me: failed program was:" >&5
- sed 's/^/| /' conftest.$ac_ext >&5
- 
--	ac_cv_func_mysql_connect=no
-+	ac_cv_func_mysql_real_connect=no
- fi
- 
- rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-       conftest$ac_exeext conftest.$ac_ext
- fi
--{ echo "$as_me:$LINENO: result: $ac_cv_func_mysql_connect" >&5
--echo "${ECHO_T}$ac_cv_func_mysql_connect" >&6; }
--if test $ac_cv_func_mysql_connect = yes; then
-+{ echo "$as_me:$LINENO: result: $ac_cv_func_mysql_real_connect" >&5
-+echo "${ECHO_T}$ac_cv_func_mysql_real_connect" >&6; }
-+if test $ac_cv_func_mysql_real_connect = yes; then
-   doauthmysql="yes"
- 
- fi
-@@ -24362,9 +24384,9 @@
- else
- 	saveLIBS="$LIBS"
- 	LIBS="$MYSQL_LIBS $LIBS"
--	{ echo "$as_me:$LINENO: checking for mysql_connect" >&5
--echo $ECHO_N "checking for mysql_connect... $ECHO_C" >&6; }
--if test "${ac_cv_func_mysql_connect+set}" = set; then
-+	{ echo "$as_me:$LINENO: checking for mysql_real_connect" >&5
-+echo $ECHO_N "checking for mysql_real_connect... $ECHO_C" >&6; }
-+if test "${ac_cv_func_mysql_real_connect+set}" = set; then
-   echo $ECHO_N "(cached) $ECHO_C" >&6
- else
-   cat >conftest.$ac_ext <<_ACEOF
-@@ -24373,12 +24395,12 @@
- cat confdefs.h >>conftest.$ac_ext
- cat >>conftest.$ac_ext <<_ACEOF
- /* end confdefs.h.  */
--/* Define mysql_connect to an innocuous variant, in case <limits.h> declares mysql_connect.
-+/* Define mysql_real_connect to an innocuous variant, in case <limits.h> declares mysql_real_connect.
-    For example, HP-UX 11i <limits.h> declares gettimeofday.  */
--#define mysql_connect innocuous_mysql_connect
-+#define mysql_real_connect innocuous_mysql_real_connect
- 
- /* System header to define __stub macros and hopefully few prototypes,
--    which can conflict with char mysql_connect (); below.
-+    which can conflict with char mysql_real_connect (); below.
-     Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
-     <limits.h> exists even on freestanding compilers.  */
- 
-@@ -24388,7 +24410,7 @@
- # include <assert.h>
- #endif
- 
--#undef mysql_connect
-+#undef mysql_real_connect
- 
- /* Override any GCC internal prototype to avoid an error.
-    Use char because int might match the return type of a GCC
-@@ -24396,18 +24418,18 @@
- #ifdef __cplusplus
- extern "C"
- #endif
--char mysql_connect ();
-+char mysql_real_connect ();
- /* The GNU C library defines this for functions which it implements
-     to always fail with ENOSYS.  Some functions are actually named
-     something starting with __ and the normal name is an alias.  */
--#if defined __stub_mysql_connect || defined __stub___mysql_connect
-+#if defined __stub_mysql_real_connect || defined __stub___mysql_real_connect
- choke me
- #endif
- 
- int
- main ()
- {
--return mysql_connect ();
-+return mysql_real_connect ();
-   ;
-   return 0;
- }
-@@ -24430,20 +24452,20 @@
- 	 test ! -s conftest.err
-        } && test -s conftest$ac_exeext &&
-        $as_test_x conftest$ac_exeext; then
--  ac_cv_func_mysql_connect=yes
-+  ac_cv_func_mysql_real_connect=yes
- else
-   echo "$as_me: failed program was:" >&5
- sed 's/^/| /' conftest.$ac_ext >&5
- 
--	ac_cv_func_mysql_connect=no
-+	ac_cv_func_mysql_real_connect=no
- fi
- 
- rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-       conftest$ac_exeext conftest.$ac_ext
- fi
--{ echo "$as_me:$LINENO: result: $ac_cv_func_mysql_connect" >&5
--echo "${ECHO_T}$ac_cv_func_mysql_connect" >&6; }
--if test $ac_cv_func_mysql_connect = yes; then
-+{ echo "$as_me:$LINENO: result: $ac_cv_func_mysql_real_connect" >&5
-+echo "${ECHO_T}$ac_cv_func_mysql_real_connect" >&6; }
-+if test $ac_cv_func_mysql_real_connect = yes; then
-   LIBAUTHMYSQL="libauthmysql.la"
- 		HAVE_AUTHMYSQL=1
- else
-@@ -26915,9 +26937,12 @@
- subdirs!$subdirs$ac_delim
- LIBOBJS!$LIBOBJS$ac_delim
- LTLIBOBJS!$LTLIBOBJS$ac_delim
++
++vpopmail_home=`$PERL -e '@a=getpwnam("vpopmail"); print "$a[7]";'`
++
++
++
++
++# Check whether --with-authvchkpw was given.
++if test "${with_authvchkpw+set}" = set; then
++  withval=$with_authvchkpw; doauthvchkpw="$withval"
++else
++  doauthvchkpw=no
++	if test "$vpopmail_home" != ""
++	then
++		doauthvchkpw=yes
++	fi
++fi
++
++
++if test "$doauthvchkpw" = "no"
++then
++	HAVE_VCHKPW=0
++	vpopmail_home=.
++else
++	HAVE_VCHKPW=1
++
++
++	cat  <<EOF
++----------------------------------------------------
++                     NOTE
++
++
++All questions regarding ANY vpopmail-related problems,
++such as compiling/building failures, or login errors
++should be referred to the vpopmail mailing list.
++Vpopmail questions sent to the Courier mailing lists
++will be IGNORED.
++----------------------------------------------------
++
++EOF
++	sleep 5
++
++	if test -f ${vpopmail_home}/etc/lib_deps
++	then
++		CFLAGS="`cat ${vpopmail_home}/etc/inc_deps` $CFLAGS"
++		VPOPMAILLIBS="`cat ${vpopmail_home}/etc/lib_deps`"
++	else
++		{ { echo "$as_me:$LINENO: error: ${vpopmail_home}/etc/lib_deps does not exist - upgrade vpopmail to the current version or fix the permissions on this file" >&5
++echo "$as_me: error: ${vpopmail_home}/etc/lib_deps does not exist - upgrade vpopmail to the current version or fix the permissions on this file" >&2;}
++   { (exit 1); exit 1; }; }
++	fi
++fi
++
++
++
++LIBAUTHVCHKPW=""
++if test "$HAVE_VCHKPW" = 1
++then
++	LIBAUTHVCHKPW="libauthvchkpw.la"
++	HAVE_VCHKPW="1"
++
++
++	_SAVE_LIBS=$LIBS
++	LIBS="$VPOPMAILLIBS $CRYPTLIBS $LIBS"
++	{ echo "$as_me:$LINENO: checking for open_smtp_relay" >&5
++echo $ECHO_N "checking for open_smtp_relay... $ECHO_C" >&6; }
++if test "${ac_cv_func_open_smtp_relay+set}" = set; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++else
++  cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++/* Define open_smtp_relay to an innocuous variant, in case <limits.h> declares open_smtp_relay.
++   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
++#define open_smtp_relay innocuous_open_smtp_relay
++
++/* System header to define __stub macros and hopefully few prototypes,
++    which can conflict with char open_smtp_relay (); below.
++    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
++    <limits.h> exists even on freestanding compilers.  */
++
++#ifdef __STDC__
++# include <limits.h>
++#else
++# include <assert.h>
++#endif
++
++#undef open_smtp_relay
++
++/* Override any GCC internal prototype to avoid an error.
++   Use char because int might match the return type of a GCC
++   builtin and then its argument prototype would still apply.  */
++#ifdef __cplusplus
++extern "C"
++#endif
++char open_smtp_relay ();
++/* The GNU C library defines this for functions which it implements
++    to always fail with ENOSYS.  Some functions are actually named
++    something starting with __ and the normal name is an alias.  */
++#if defined __stub_open_smtp_relay || defined __stub___open_smtp_relay
++choke me
++#endif
++
++int
++main ()
++{
++return open_smtp_relay ();
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext conftest$ac_exeext
++if { (ac_try="$ac_link"
++case "(($ac_try" in
++  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
++  *) ac_try_echo=$ac_try;;
++esac
++eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
++  (eval "$ac_link") 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } && {
++	 test -z "$ac_c_werror_flag" ||
++	 test ! -s conftest.err
++       } && test -s conftest$ac_exeext &&
++       $as_test_x conftest$ac_exeext; then
++  ac_cv_func_open_smtp_relay=yes
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++	ac_cv_func_open_smtp_relay=no
++fi
++
++rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
++      conftest$ac_exeext conftest.$ac_ext
++fi
++{ echo "$as_me:$LINENO: result: $ac_cv_func_open_smtp_relay" >&5
++echo "${ECHO_T}$ac_cv_func_open_smtp_relay" >&6; }
++if test $ac_cv_func_open_smtp_relay = yes; then
++
++cat >>confdefs.h <<\_ACEOF
++#define HAVE_OPEN_SMTP_RELAY 1
++_ACEOF
++
++fi
++
++	{ echo "$as_me:$LINENO: checking for vset_lastauth" >&5
++echo $ECHO_N "checking for vset_lastauth... $ECHO_C" >&6; }
++if test "${ac_cv_func_vset_lastauth+set}" = set; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++else
++  cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++/* Define vset_lastauth to an innocuous variant, in case <limits.h> declares vset_lastauth.
++   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
++#define vset_lastauth innocuous_vset_lastauth
++
++/* System header to define __stub macros and hopefully few prototypes,
++    which can conflict with char vset_lastauth (); below.
++    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
++    <limits.h> exists even on freestanding compilers.  */
++
++#ifdef __STDC__
++# include <limits.h>
++#else
++# include <assert.h>
++#endif
++
++#undef vset_lastauth
++
++/* Override any GCC internal prototype to avoid an error.
++   Use char because int might match the return type of a GCC
++   builtin and then its argument prototype would still apply.  */
++#ifdef __cplusplus
++extern "C"
++#endif
++char vset_lastauth ();
++/* The GNU C library defines this for functions which it implements
++    to always fail with ENOSYS.  Some functions are actually named
++    something starting with __ and the normal name is an alias.  */
++#if defined __stub_vset_lastauth || defined __stub___vset_lastauth
++choke me
++#endif
++
++int
++main ()
++{
++return vset_lastauth ();
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext conftest$ac_exeext
++if { (ac_try="$ac_link"
++case "(($ac_try" in
++  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
++  *) ac_try_echo=$ac_try;;
++esac
++eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
++  (eval "$ac_link") 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } && {
++	 test -z "$ac_c_werror_flag" ||
++	 test ! -s conftest.err
++       } && test -s conftest$ac_exeext &&
++       $as_test_x conftest$ac_exeext; then
++  ac_cv_func_vset_lastauth=yes
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++	ac_cv_func_vset_lastauth=no
++fi
++
++rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
++      conftest$ac_exeext conftest.$ac_ext
++fi
++{ echo "$as_me:$LINENO: result: $ac_cv_func_vset_lastauth" >&5
++echo "${ECHO_T}$ac_cv_func_vset_lastauth" >&6; }
++if test $ac_cv_func_vset_lastauth = yes; then
++
++cat >>confdefs.h <<\_ACEOF
++#define HAVE_VSET_LASTAUTH 1
++_ACEOF
++
++fi
++
++	LIBS=$_SAVE_LIBS
++fi
++
++
++
++
++
++
++
+ # Check whether --with-authpgsqlrc was given.
+ if test "${with_authpgsqlrc+set}" = set; then
+   withval=$with_authpgsqlrc; authpgsqlrc="$withval"
+@@ -26616,9 +26892,13 @@
+ CXXFLAGS!$CXXFLAGS$ac_delim
+ ac_ct_CXX!$ac_ct_CXX$ac_delim
+ CXXDEPMODE!$CXXDEPMODE$ac_delim
 +HAVE_BASE_TRUE!$HAVE_BASE_TRUE$ac_delim
 +HAVE_BASE_FALSE!$HAVE_BASE_FALSE$ac_delim
 +HAVE_USERDB_TRUE!$HAVE_USERDB_TRUE$ac_delim
 +HAVE_USERDB_FALSE!$HAVE_USERDB_FALSE$ac_delim
  _ACEOF
--
--  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 77; then
-+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 81; then
+ 
+-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
++  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 101; then
+     break
+   elif $ac_last_try; then
+     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
+@@ -26698,6 +26978,9 @@
+ SHADOWLIBS!$SHADOWLIBS$ac_delim
+ LIBAUTHSHADOW!$LIBAUTHSHADOW$ac_delim
+ LIBAUTHPWD!$LIBAUTHPWD$ac_delim
++vpopmail_home!$vpopmail_home$ac_delim
++VPOPMAILLIBS!$VPOPMAILLIBS$ac_delim
++LIBAUTHVCHKPW!$LIBAUTHVCHKPW$ac_delim
+ authpgsqlrc!$authpgsqlrc$ac_delim
+ PG_CONFIG!$PG_CONFIG$ac_delim
+ PGSQL_LIBS!$PGSQL_LIBS$ac_delim
+@@ -26731,7 +27014,7 @@
+ LTLIBOBJS!$LTLIBOBJS$ac_delim
+ _ACEOF
+ 
+-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 72; then
++  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 75; then
      break
    elif $ac_last_try; then
      { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
