- Allow user to specify a Tomcat deamon user/group through TOMCAT_USER and   TOMCAT_GROUP (www/www by default) - Make it possible to add user/group even if UID/GID number is reserved
PR:		85761
Submitted by:	Pawel Wieleba <P.Wieleba@iem.pw.edu.pl>
Approved by:	maintainer

diff --git a/www/jakarta-tomcat55/pkg-install b/www/jakarta-tomcat55/pkg-install
--- a/www/jakarta-tomcat55/pkg-install
+++ b/www/jakarta-tomcat55/pkg-install
@@ -1,9 +1,9 @@
 #!/bin/sh
 #
-# Checks if the 'www' user and group exist. If they don't, then
+# Checks if the '%%USER%%' user and %%GROUP%% group exist. If they don't, then
 # an attempt is made to create both.
 #
-# $FreeBSD: /tmp/pcvs/ports/www/jakarta-tomcat55/Attic/pkg-install,v 1.2 2005-06-13 14:08:34 hq Exp $
+# $FreeBSD: /tmp/pcvs/ports/www/jakarta-tomcat55/Attic/pkg-install,v 1.3 2005-09-29 15:08:23 hq Exp $
 #
 
 # Make sure we're called during the 'make install' process
@@ -12,34 +12,39 @@ if [ "$2" != "PRE-INSTALL" ]; then
 fi
 
 # Set some constants
-USER=www
-GROUP=${USER}
 UID=80
 GID=${UID}
 
 # See if the group already exists
-if ! pw groupshow "${GROUP}" 2>/dev/null 1>&2; then
+if ! pw groupshow "%%GROUP%%" 2>/dev/null 1>&2; then
 
 	# If not, try to create it
-	if pw groupadd ${GROUP} -g ${GID}; then
-		echo "Added group \"${GROUP}\"."
+	if pw groupadd "%%GROUP%%" -g ${GID}; then
+		echo "Added group \"%%GROUP%%\"."
+	elif pw groupadd "%%GROUP%%"; then
+		echo "Added group \"%%GROUP%%\"."
 	else
-		echo "Adding group \"${GROUP}\" failed..."
+		echo "Adding group \"%%GROUP%%\" failed..."
 		exit 1
 	fi
 fi
 
 # See if the user already exists
-if ! pw usershow "${USER}" 2>/dev/null 1>&2; then
+if ! pw usershow "%%USER%%" 2>/dev/null 1>&2; then
 
 	# If not, try to create it
-	if pw useradd ${USER} -u ${UID} -g ${GROUP} -h - \
-		-s "/sbin/nologin" -d "/nonexistent" \
-		-c "World Wide Web Owner"; \
+	if pw useradd "%%USER%%" -u ${UID} -g "%%GROUP%%" -h - \
+                -s "/sbin/nologin" -d "/nonexistent" \
+                -c "World Wide Web Owner";
 	then
-		echo "Added user \"${USER}\"."
+		echo "Added user \"%%USER%%\"."
+	elif pw useradd "%%USER%%" -g "%%GROUP%%" -h - \
+                -s "/sbin/nologin" -d "/nonexistent" \
+                -c "World Wide Web Owner";
+	then
+		echo "Added user \"%%USER%%\"."
 	else
-		echo "Adding user \"${USER}\" failed..."
+		echo "Adding user \"%%USER%%\" failed..."
 		exit 1
 	fi
 fi
