- Update to 2.1.4 - Unbreak on 5.x - Update MASTER_SITES
PR:		ports/60751
Submitted by:	Patrick Atamaniuk <atamaniuk-ports@frobs.net> (maintainer)

diff --git a/print/lilypond-devel/scripts/pre-configure b/print/lilypond-devel/scripts/pre-configure
--- a/print/lilypond-devel/scripts/pre-configure
+++ b/print/lilypond-devel/scripts/pre-configure
@@ -3,7 +3,11 @@ outdir=out
 cd ${WRKSRC} || exit 2
 echo "Patching for FlexLexer.h <->gcc3 issues"
 
-file=/usr/include/g++/FlexLexer.h
+file=""
+candidates=`find /usr/include/ -name FlexLexer.h`
+#take first found file.
+for d in $candidates; do if [ -f $d ]; then file=$d; break; fi; done
+if [ -z "${file}" ]; then echo "Cannot find FlexLexer.h"; exit 2; fi
 
 echo -n "Copying and fixing $file... "
 mkdir -p lily/$outdir
