- Update to 2.3.2 - OPTIONS'fy

diff --git a/sysutils/gkrellm2/files/patch-src::configure b/sysutils/gkrellm2/files/patch-src::configure
--- a/sysutils/gkrellm2/files/patch-src::configure
+++ b/sysutils/gkrellm2/files/patch-src::configure
@@ -1,19 +1,19 @@
 Index: src/configure
 diff -u src/configure.orig src/configure
---- src/configure.orig	Mon May  7 08:45:55 2007
-+++ src/configure	Sun Jul 22 03:01:53 2007
-@@ -61,8 +62,8 @@
- 	}
- EOF
+--- src/configure.orig	2008-10-04 07:44:08.000000000 +0900
++++ src/configure	2008-10-04 23:01:57.000000000 +0900
+@@ -19,6 +19,10 @@
+ 	then
+ 		without_libsensors=yes
+ 	fi
++	if [ "$i" = "--without-ntlm" ]
++	then
++		without_ntlm=yes
++	fi
+ done
  
--$CC ${CFLAGS} ${PKG_INCLUDE} -c test.c -o test.o 2>& 5
--$CC test.o -o test ${LINK_FLAGS} ${PKG_LIBS} -lgnutls-openssl 2>& 5
-+$CC ${PKG_INCLUDE} -I${GNUTLSINC} -c test.c -o test.o 2>& 5
-+$CC test.o -o test ${LINK_FLAGS} ${PKG_LIBS} -L${GNUTLSLIB} -lgnutls-openssl 2>& 5
- 
- if [ -x ./test ] && ./test
- then
-@@ -101,8 +102,8 @@
+ PKG_INCLUDE=`pkg-config gtk+-2.0 --cflags`
+@@ -56,8 +60,8 @@
  	}
  EOF
  
@@ -24,7 +24,46 @@ diff -u src/configure.orig src/configure
  
  if [ -x ./test ] && ./test
  then
-@@ -141,7 +142,7 @@
+@@ -102,8 +106,8 @@
+ 	}
+ EOF
+ 
+-$CC ${CFLAGS} ${PKG_INCLUDE} -c test.c -o test.o 2>& 5
+-$CC test.o -o test ${LINK_FLAGS} ${PKG_LIBS} -lgnutls-openssl 2>& 5
++$CC ${PKG_INCLUDE} -I${GNUTLSINC} -c test.c -o test.o 2>& 5
++$CC test.o -o test ${LINK_FLAGS} ${PKG_LIBS} -L${GNUTLSLIB} -lgnutls-openssl 2>& 5
+ 
+ if [ -x ./test ] && ./test
+ then
+@@ -121,6 +125,8 @@
+ 
+ rm -f test test.exe test.o test.c
+ 
++if [ "$without_ntlm" != "yes" ]
++then
+ # echo "Checking for libntlm... " 1>& 2
+ echo "Checking for libntlm... " 1>& 5
+ 
+@@ -136,7 +142,7 @@
+ 	}
+ EOF
+ 
+-$CC ${CFLAGS} ${PKG_INCLUDE} -c test.c -o test.o 2>& 5
++$CC ${PKG_INCLUDE} -c test.c -o test.o 2>& 5
+ $CC test.o -o test ${LINK_FLAGS} ${PKG_LIBS} -lntlm 2>& 5
+ 
+ if [ -x ./test ] && ./test
+@@ -148,7 +154,8 @@
+ #	echo "Not found, mail check will not have ntlm support..." 1>& 2
+ 	echo "Not found, mail check will not have ntlm support..." 1>& 5
+ fi
+-
++fi
++# end of ntlm check
+ 
+ 
+ rm -f test test.exe test.o test.c
+@@ -181,7 +188,7 @@
  	}
  EOF
  
