Update to 2.2.9.
  * Change ACLs correctly when renaming a user
  * Do not abandon std{in,out,err} file descriptors; syslog assumes it
    can use stderr if syslogd isn't running.
  * Clean up imap magic plus to avoid buffer overrun (CAN-2004-1011)
  * Fix lack of bounds checking in PARTIAL and FETCH (CAN-2004-1012,
    CAN-2004-1013)
  * Do not attempt to reuse a freed connection in lmtpproxyd.
  * Allow login without authentication with -N switch in proxyd.
  * Fix use of xrealloc and fold pointers in lmtpengine.

diff --git a/mail/cyrus-imapd24/files/patch-ac b/mail/cyrus-imapd24/files/patch-ac
--- a/mail/cyrus-imapd24/files/patch-ac
+++ b/mail/cyrus-imapd24/files/patch-ac
@@ -1,7 +1,7 @@
 Index: configure
 diff -u configure.orig configure
---- configure.orig	Fri Jun 18 03:55:49 2004
-+++ configure	Wed Jul 21 04:21:05 2004
+--- configure.orig	Tue Nov 23 06:30:19 2004
++++ configure	Tue Nov 23 13:32:12 2004
 @@ -309,6 +309,7 @@
  #endif"
  
@@ -10,30 +10,32 @@ diff -u configure.orig configure
  ac_subst_files=''
  
  # Initialize some variables set by options.
-@@ -6551,7 +6552,7 @@
- 	    BDB_LIBADD=""
+@@ -6611,7 +6612,7 @@
  	fi
  
+ 	saved_LIBS=$LIBS
 -        for dbname in db-4.2 db4.2 db42 db-4.1 db4.1 db41 db-4.0 db4.0 db-4 db40 db4 db-3.3 db3.3 db33 db-3.2 db3.2 db32 db-3.1 db3.1 db31 db-3 db30 db3 db
 +        for dbname in ${with_bdb} db-4.2 db4.2 db42 db-4.1 db4.1 db41 db-4.0 db4.0 db-4 db40 db4 db-3.3 db3.3 db33 db-3.2 db3.2 db32 db-3.1 db3.1 db31 db-3 db30 db3 db
            do
-             as_ac_Lib=`echo "ac_cv_lib_$dbname''_db_create" | $as_tr_sh`
- echo "$as_me:$LINENO: checking for db_create in -l$dbname" >&5
-@@ -6575,11 +6576,11 @@
- #endif
- /* We use char because int might match the return type of a gcc2
-    builtin and then its argument prototype would still apply.  */
--char db_create ();
-+#include <db.h>
+ 	    LIBS="$saved_LIBS -l$dbname"
+ 	    cat >conftest.$ac_ext <<_ACEOF
+@@ -6621,6 +6622,7 @@
+ cat confdefs.h >>conftest.$ac_ext
+ cat >>conftest.$ac_ext <<_ACEOF
+ /* end confdefs.h.  */
++#include <stdio.h>
+ #include <db.h>
  int
  main ()
- {
--db_create ();
-+db_create (0, 0, 0);
-   ;
-   return 0;
- }
-@@ -13502,6 +13503,7 @@
+@@ -6643,6 +6645,7 @@
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+   BDB_LIBADD="$BDB_LIBADD -l$dbname"; dblib="berkeley"; dbname=db
++  break
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
+@@ -13531,6 +13534,7 @@
      EXTRA_SUBDIRS="${EXTRA_SUBDIRS} perl"
      PERL_SUBDIRS="imap"
      PERL="${with_perl}"
@@ -41,7 +43,7 @@ diff -u configure.orig configure
      PERL_CCCDLFLAGS="$cccdlflags"
  
  fi
-@@ -14020,7 +14022,9 @@
+@@ -14049,7 +14053,9 @@
  
      if test -n "$SNMP_LIBS" && test -n "$SNMP_PREFIX"; then
        CPPFLAGS="$CPPFLAGS -I${SNMP_PREFIX}/include"
@@ -52,7 +54,7 @@ diff -u configure.orig configure
  
  cat >>confdefs.h <<\_ACEOF
  #define HAVE_NETSNMP 1
-@@ -14251,7 +14255,7 @@
+@@ -14280,7 +14286,7 @@
  #define HAVE_UCDSNMP 1
  _ACEOF
  
@@ -61,7 +63,7 @@ diff -u configure.orig configure
        echo "$as_me:$LINENO: checking for rpmdbOpen in -lrpm" >&5
  echo $ECHO_N "checking for rpmdbOpen in -lrpm... $ECHO_C" >&6
  if test "${ac_cv_lib_rpm_rpmdbOpen+set}" = set; then
-@@ -15067,6 +15071,7 @@
+@@ -15096,6 +15102,7 @@
  s,@LIB_WRAP@,$LIB_WRAP,;t t
  s,@SNMP_CONFIG@,$SNMP_CONFIG,;t t
  s,@LIB_UCDSNMP@,$LIB_UCDSNMP,;t t
