Finished security, ports-mgmt, and news OpenRC scripts

diff --git a/security/tor-devel/files/openrc-tor.in b/security/tor-devel/files/openrc-tor.in
--- a/security/tor-devel/files/openrc-tor.in
+++ b/security/tor-devel/files/openrc-tor.in
@@ -1,20 +1,30 @@
 #!/sbin/openrc-run
-# Copyright (c) 2007-2015 The OpenRC Authors.
-# See the Authors file at the top-level directory of this distribution and
-# https://github.com/OpenRC/openrc/blob/master/AUTHORS
 #
-# This file is part of OpenRC. It is subject to the license terms in
-# the LICENSE file found in the top-level directory of this
-# distribution and at https://github.com/OpenRC/openrc/blob/master/LICENSE
-# This file may not be copied, modified, propagated, or distributed
-# except according to the terms contained in the LICENSE file.
+# Add the following lines to /etc/rc.conf to enable tor.
+# All these options will overide any settings in your local torrc as
+# they are command line options.
+#
+# tor_instances (str):	List of instances. Default: ""
+# tor_conf (str):	Points to your torrc file.
+#			Default: %%PREFIX%%/etc/tor/torrc
+# tor_user (str):	Tor daemon user. Default: %%USER%%
+# tor_group (str):	Tor group. Default: %%GROUP%%
+# tor_pidfile (str):	Tor pid file.  Default: /var/run/tor/tor.pid
+# tor_datadir (str):	Tor datadir.  Default: /var/db/tor
+# tor_disable_default_instance (str):	Doesn't run the default instance.
+#			Only valid when tor_instances is used.
+#			Default: NO
+#
+# The instance definition that tor_instances expects:
+# inst_name{:inst_conf:inst_user:inst_group:inst_pidfile:inst_data_dir}
 
 name="tor"
+exit_code=0
 
 : ${tor_instances=""}
-: ${tor_conf="/usr/local/etc/tor/torrc"}
-: ${tor_user="_tor"}
-: ${tor_group="_tor"}
+: ${tor_conf="%%PREFIX%%/etc/tor/torrc"}
+: ${tor_user="%%USER%%"}
+: ${tor_group="%%GROUP%%"}
 : ${tor_pidfile="/var/run/tor/tor.pid"}
 : ${tor_datadir="/var/db/tor"}
 : ${tor_disable_default_instance="NO"}
@@ -23,7 +33,7 @@ instance=${slave_instance}
 if [ -n "${instance}" ]; then
   inst_def=${instance}
   inst_name=${inst_def%%:*}
-  [ "${inst_name}" != "main" ] || err 1 "${name} instance can't be named 'main'"
+  [ "${inst_name}" != "main" ] || eerror "${name} instance can't be named 'main'"
   inst_def=${inst_def#$inst_name}
   if [ -n "$inst_def" ]; then
     # extended instance: parameters are set explicitly
@@ -48,7 +58,7 @@ if [ -n "${instance}" ]; then
   fi
   if ! [ -r ${tor_conf} ]; then
     ewarn "tor instance ${inst_name} config file ${tor_conf} doesn't exist or isn't readable"
-    ewarn "you can copy the sample config /usr/local/etc/tor/torrc.sample and modify it"
+    ewarn "you can copy the sample config %%PREFIX%%/etc/tor/torrc.sample and modify it"
     exit 1
   fi
   if ! [ -d ${tor_datadir} ]; then
@@ -66,7 +76,7 @@ if [ -z "${instance}" -a -n "${tor_instances}" ]; then
     inst_name=${i%%:*}
     if [ -z "${inst_only}" -o "${inst_name}" = "${inst_only}" ]; then
       echo -n "${name} instance ${inst_name}: "
-      if ! slave_instance=${i} /usr/local/etc/rc.d/tor "$1"; then
+      if ! slave_instance=${i} %%PREFIX%%/etc/rc.d/tor "$1"; then
         exit_code=1
       fi
       inst_done=$((inst_done+1))
@@ -84,6 +94,5 @@ fi
 required_files=${tor_conf}
 required_dirs=${tor_datadir}
 pidfile=${tor_pidfile}
-command="/usr/local/bin/${name}"
+command="%%PREFIX%%/bin/${name}"
 command_args="-f ${tor_conf} --PidFile ${tor_pidfile} --RunAsDaemon 1 --DataDirectory ${tor_datadir}"
-command_user="_tor"
