Tk v8.0.4.  As with Tcl80 checked w/maintainer.

diff --git a/x11-toolkits/tk80/files/patch-aa b/x11-toolkits/tk80/files/patch-aa
--- a/x11-toolkits/tk80/files/patch-aa
+++ b/x11-toolkits/tk80/files/patch-aa
@@ -1,10 +1,10 @@
---- configure.orig	Fri Aug 15 22:17:52 1997
-+++ configure	Wed Oct  1 10:50:54 1997
-@@ -662,14 +662,14 @@
- if test -n "$withval"; then
+--- configure.orig	Wed Nov 18 14:54:54 1998
++++ configure		Tue Dec  1 14:49:37 1998
+@@ -842,14 +842,14 @@
+   withval="$with_tcl"
    TCL_BIN_DIR=$withval
  else
--  TCL_BIN_DIR=`cd ../../tcl8.0/unix; pwd`
+-  TCL_BIN_DIR=`cd ../../tcl8.0$TK_PATCH_LEVEL/unix; pwd`
 +  TCL_BIN_DIR=${prefix}/lib/tcl8.0
  fi
  
@@ -14,24 +14,24 @@
 -if test ! -f $TCL_BIN_DIR/Makefile; then
 -    { echo "configure: error: There's no Makefile in $TCL_BIN_DIR;  perhaps you didn't specify the Tcl *build* directory (not the toplevel Tcl directory) or you forgot to configure Tcl?" 1>&2; exit 1; }
 +if test ! -f $TCL_BIN_DIR/tclConfig.sh; then
-+    { echo "configure: error: There's no tclConfig.sh in $TCL_BIN_DIR;  perhaps you didn't specify the Tcl *build* directory (not the toplevel Tcl directory) or you forgot to configure Tcl?" 1>&2; exit 1; }
++    { echo "configure: error: There's no tclConfig.sh in $TCL_BIN_DIR;  perhaps your Tcl installation has been corrupted.  Verify the installation of Tcl8.0 and try again." 1>&2; exit 1; }
  fi
  
  #--------------------------------------------------------------------
-@@ -688,6 +688,8 @@
- DL_LIBS=$TCL_DL_LIBS
- LD_FLAGS=$TCL_LD_FLAGS
- 
+@@ -889,6 +889,7 @@
+ CFLAGS_DEBUG=$TCL_CFLAGS_DEBUG
+ CFLAGS_OPTIMIZE=$TCL_CFLAGS_OPTIMIZE
+ EXTRA_CFLAGS=$TCL_EXTRA_CFLAGS
 +TCL_SRC_DIR=${prefix}/include/tcl${TCL_VERSION}
-+
+ 
  LIB_RUNTIME_DIR='${LIB_RUNTIME_DIR}'
  
- # If Tcl and Tk are installed in different places, adjust the library
-@@ -2271,6 +2273,7 @@
- s%@SHLIB_VERSION@%$SHLIB_VERSION%g
- s%@TCL_BIN_DIR@%$TCL_BIN_DIR%g
- s%@TCL_BUILD_LIB_SPEC@%$TCL_BUILD_LIB_SPEC%g
-+s%@TCL_LIB_SPEC@%$TCL_LIB_SPEC%g
- s%@TCL_SRC_DIR@%$TCL_SRC_DIR%g
- s%@TCL_VERSION@%$TCL_VERSION%g
- s%@TK_BUILD_LIB_SPEC@%$TK_BUILD_LIB_SPEC%g
+@@ -2344,7 +2345,7 @@
+ if test "$ok" = "yes" -a "${SHLIB_SUFFIX}" != ""; then
+     TK_SHARED_BUILD=1
+     TK_SHLIB_CFLAGS="${SHLIB_CFLAGS}"
+-    TK_LIB_FILE=libtk${TCL_SHARED_LIB_SUFFIX}
++    TK_LIB_FILE=${TK_LIB_FILE}
+     MAKE_LIB="\${SHLIB_LD} -o \${TK_LIB_FILE} \${OBJS} \$(TK_LD_SEARCH_FLAGS) ${SHLIB_LD_LIBS}"
+     RANLIB=":"
+ else
