Update to 1.4.3
PR:		ports/66307
Submitted by:	c0decafe.net
Approved by:	maintainer timeout

diff --git a/net/jabber/pkg-install b/net/jabber/pkg-install
--- a/net/jabber/pkg-install
+++ b/net/jabber/pkg-install
@@ -1,151 +1,56 @@
-#! /bin/sh
+#!/bin/sh
 
-chmods_done=" "
+if [ "$2" != "POST-INSTALL" ]; then
+    exit 0
+fi
 
-ask() {
-    local question default answer
+USER=jabber
+GROUP=${USER}
+UID=93
+GID=${UID}
+SPOOLDIR="/var/spool/jabber"
+ETCDIR=${PREFIX:-$PKG_PREFIX}/etc
 
-    question=$1
-    default=$2
-    if [ -z "${PACKAGE_BUILDING}" ]; then
-	read -p "${question} [${default}]? " answer
-    fi
-    if [ x${answer} = x ]; then
-	answer=${default}
-    fi
-    echo ${answer}
-}
-
-yesno() {
-    local dflt question answer
-
-    question=$1
-    dflt=$2
-    while :; do
-	answer=$(ask "${question}" "${dflt}")
-	case "${answer}" in
-	[Yy]*)		return 0;;
-	[Nn]*)		return 1;;
-	esac
-	echo "Please answer yes or no."
-    done
-}
-
-make_account() {
-    local u g gcos homeopt home
-
-    u=$1
-    g=$2
-    gcos=$3
-    homeopt=${4:+"-d $4"}
-
-    if pw group show "${g}" >/dev/null 2>&1; then
-	echo "You already have a group \"${g}\", so I will use it."
-    else
-	echo "You need a group \"${g}\"."
-	if which -s pw && yesno "Would you like me to create it" y; then
-	    pw groupadd ${g} || exit
-	    echo "Done."
+if ! pw groupshow "${GROUP}" 2>/dev/null 1>&2; then
+	if pw groupadd ${GROUP} -g ${GID}; then
+		echo "Added group \"${GROUP}\"."
 	else
-	    echo "Please create it, and try again."
-	    if ! grep -q "^${u}:" /etc/passwd; then
-		echo "While you're at it, please create a user \"${u}\" too,"
-		echo "with a default group of \"${g}\"."
-	    fi
-	    exit 1
-	fi
-    fi
-    
-    if pw user show "${u}" >/dev/null 2>&1; then
-	echo "You already have a user \"${u}\", so I will use it."
-    else
-	echo "You need a user \"${u}\"."
-	if which -s pw && yesno "Would you like me to create it" y; then
-	    pw useradd ${u} -g ${g} -h - ${homeopt} \
-		-s /nonexistent -c "${gcos}" || exit
-	    echo "Done."
-	else
-	    echo "Please create it, and try again."
-	    exit 1
-	fi
-    fi
-
-    if [ x"$homeopt" = x ]; then
-	eval home=~${u}
-	if [ ! -d "${home}" ]; then
-	    if yesno \
-		"Would you like me to create ${u}'s home directory (${home})" y
-	    then
-		(umask 77 && \
-		    mkdir -p ${home}) || exit
-		chown -R ${u}:${g} ${home} || exit
-	    else
-		echo "Please create it, and try again."
+		echo "Adding group \"${GROUP}\" failed..."
 		exit 1
-	    fi
 	fi
-    fi
-}
+fi
 
-case $2 in
+if ! pw usershow "${USER}" 2>/dev/null 1>&2; then
+	if pw useradd ${USER} -u ${UID} -g ${GROUP} -h - \
+		-s "/sbin/nologin" -d "/nonexistent" \
+		-c "Jabber Daemon"; \
+	then
+		echo "Added user \"${USER}\"."
+	else
+		echo "Adding user \"${USER}\" failed..."
+		exit 1
+	fi
+fi
 
-POST-INSTALL)
-    if which -s pw && which -s lockf; then
-	:
-    else
-	cat <<EOF
+if [ ! -d ${SPOOLDIR} ]; then
+	echo "Creating \"${SPOOLDIR}\"."
+	mkdir -p ${SPOOLDIR}
+fi
 
-This system looks like a pre-2.2 version of FreeBSD.  I see that it
-is missing the "lockf" and/or "pw" utilities.  I need these utilities.
-Please get them and install them, and try again.  You can get the
-sources from:
+echo "Fixing ownerships and modes in \"${SPOOLDIR}\"."
+chown -R ${USER}:${GROUP} ${SPOOLDIR}
+chmod -R go= ${SPOOLDIR}
 
-  ftp://ftp.freebsd.org/pub/FreeBSD/FreeBSD-current/src/usr.bin/lockf.tar.gz
-  ftp://ftp.freebsd.org/pub/FreeBSD/FreeBSD-current/src/usr.sbin/pw.tar.gz
+if [ ! -f ${ETCDIR}/jabber.xml ]; then
+	echo "Creating \"${ETCDIR}/jabber.xml\"."
+	cp -p ${ETCDIR}/jabber.xml.sample ${ETCDIR}/jabber.xml
+fi
 
-EOF
-	exit 1
-    fi
+echo "Fixing config files ownerships and modes."
+chown root:${GROUP} ${ETCDIR}/jabber.xml ${ETCDIR}/jabber.xml.sample
+chmod 640 ${ETCDIR}/jabber.xml ${ETCDIR}/jabber.xml.sample
 
-    user=jabber
-    group=jabber
-    spooldir="/var/spool/jabber"
-    etcdir=${PREFIX:-$PKG_PREFIX}/etc
-
-    echo ""
-    make_account ${user} ${group} "Jabber Daemon" "/nonexistent"
-
-    if [ ! -d ${spooldir} ]; then
-	echo "Creating \"${spooldir}\"."
-	mkdir -p ${spooldir}
-    fi
-
-    echo "Fixing ownerships and modes in \"${spooldir}\"."
-    chown -R ${user}:${group} ${spooldir}
-    chmod -R go= ${spooldir}
-
-    if [ ! -f ${etcdir}/jabber.xml ]; then
-	echo "Creating \"${etcdir}/jabber.xml\"."
-	cp -p ${etcdir}/jabber.xml.sample ${etcdir}/jabber.xml
-    fi
-
-    echo "Fixing config files ownerships and modes."
-    chown root:${group} ${etcdir}/jabber.xml ${etcdir}/jabber.xml.sample
-    chmod 640 ${etcdir}/jabber.xml ${etcdir}/jabber.xml.sample
-
-    if [ ! -f /var/log/jabber.error ]; then
-	echo "Creating \"/var/log/jabber.error\"."
-	cp /dev/null /var/log/jabber.error
-    fi
-
-    if [ ! -f /var/log/jabber.record ]; then
-	echo "Creating \"/var/log/jabber.record\"."
-	cp /dev/null /var/log/jabber.record
-    fi
-
-    echo "Fixing log files ownerships and modes."
-    chown ${user}:${group} /var/log/jabber.error /var/log/jabber.record
-    chmod 640 /var/log/jabber.error /var/log/jabber.record
-
-    ;;
-esac
+echo "Fixing log files, ownerships and modes."
+touch /var/log/jabber.error /var/log/jabber.record
+chown ${USER}:${GROUP} /var/log/jabber.error /var/log/jabber.record
+chmod 640 /var/log/jabber.error /var/log/jabber.record
