- Update 0.0.20
PR:		ports/102907
Submitted by:	Marcus von Appen <mva at sysfault.org> (maintainer)

diff --git a/games/tmw/files/patch-configure b/games/tmw/files/patch-configure
--- a/games/tmw/files/patch-configure
+++ b/games/tmw/files/patch-configure
@@ -1,11 +1,22 @@
---- configure.orig	Sun Oct  2 13:27:45 2005
-+++ configure	Thu Nov 24 00:58:05 2005
-@@ -6363,7 +6363,7 @@
+--- configure.orig	Tue Sep  5 13:47:45 2006
++++ configure	Tue Sep  5 13:48:14 2006
+@@ -7533,7 +7533,7 @@
  
  # Search for sdl-config
  # Extract the first word of "sdl-config", so it can be a program name with args.
 -set dummy sdl-config; ac_word=$2
-+set dummy `basename ${SDL_CONFIG}`; ac_word=$2
- echo "$as_me:$LINENO: checking for $ac_word" >&5
- echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
++set dummy sdl11-config; ac_word=$2
+ { echo "$as_me:$LINENO: checking for $ac_word" >&5
+ echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
  if test "${ac_cv_path_LIBSDL_CONFIG+set}" = set; then
+@@ -7590,8 +7590,8 @@
+ #define HAVE_LIBSDL 0
+ _ACEOF
+ 
+-  { { echo "$as_me:$LINENO: error: Could not find sdl-config, check http://www.libsdl.org" >&5
+-echo "$as_me: error: Could not find sdl-config, check http://www.libsdl.org" >&2;}
++  { { echo "$as_me:$LINENO: error: Could not find sdl11-config, check http://www.libsdl.org" >&5
++echo "$as_me: error: Could not find sdl11-config, check http://www.libsdl.org" >&2;}
+    { (exit 1); exit 1; }; }
+ fi
+ 
