Upgrade to version 4.07 (note this is the Linux binary).

diff --git a/www/netscape4-communicator.us/files/patch-aa b/www/netscape4-communicator.us/files/patch-aa
--- a/www/netscape4-communicator.us/files/patch-aa
+++ b/www/netscape4-communicator.us/files/patch-aa
@@ -1,41 +1,77 @@
-*** ns-install.orig	Tue Jul  1 23:22:18 1997
---- ns-install	Wed Jul  2 22:55:02 1997
-***************
-*** 103,108 ****
---- 103,109 ----
-  # Even though the user has already used gzip to extract the file (or
-  # we wouldn't be here), make sure we can find it.
-  #
-+ unset GZIP
-  GZIP="gzip"
-  flag=1
-  while test ${flag} -eq 1
-***************
-*** 264,276 ****
-  	# Is this a virgin install?  If so, create the .netscape dir
-  	# and put the default bookmark file in it.
-  	#
-! 	if test ! -d ${HOME}/.netscape
-! 	then
-! 		# New install, or upgrade from 0.x or 1.x.
-! 		mkdir ${HOME}/.netscape
-! 		cp ${TARGET}/bookmark.htm ${HOME}/.netscape/bookmarks.html
-! 		echo "${HOME}/.netscape/bookmarks.html" >> ${LOGFILE}
-! 	fi
-  fi
-  
-  echo ""
---- 265,277 ----
-  	# Is this a virgin install?  If so, create the .netscape dir
-  	# and put the default bookmark file in it.
-  	#
-! #        if test ! -d ${HOME}/.netscape
-! #        then
-! #                # New install, or upgrade from 0.x or 1.x.
-! #                mkdir ${HOME}/.netscape
-! #                cp ${TARGET}/bookmark.htm ${HOME}/.netscape/bookmarks.html
-! #                echo "${HOME}/.netscape/bookmarks.html" >> ${LOGFILE}
-! #        fi
-  fi
-  
-  echo ""
+--- ns-install.orig	Tue Sep 29 20:59:31 1998
++++ ns-install	Wed Oct  7 06:11:53 1998
+@@ -120,6 +120,7 @@
+ # Even though the user has already used gzip to extract the file (or
+ # we wouldn't be here), make sure we can find it.
+ #
++unset GZIP
+ GZIP="gzip"
+ flag=1
+ while test ${flag} -eq 1
+@@ -288,10 +289,10 @@
+ 	# avoid users having to set MOZILLA_JAVA_FONT_PROPERTY_PATH, or
+ 	# just assuming Java font-handling is broken.
+ 	#
+-	if test ! -z "`ls /bin/uname`"
++	if test ! -z "`ls /usr/bin/uname`"
+ 	then
+ 		MOVE_FONTS="TRUE"
+-		case `/bin/uname` in
++		case `/usr/bin/uname` in
+ 			AIX)
+ 				PLATFORM="aix"
+ 				;;
+@@ -318,14 +319,14 @@
+ 	# Is this a virgin install?  If so, create the .netscape dir
+ 	# and put the default bookmark file in it.
+ 	#
+-	if test ! -d ${HOME}/.netscape
+-	then
+-		# New install, or upgrade from 0.x or 1.x.
+-		mkdir ${HOME}/.netscape
+-		cp ${TARGET}/bookmark.htm ${HOME}/.netscape/bookmarks.html
+-		chmod 644 ${HOME}/.netscape/bookmarks.html
+-		echo "${HOME}/.netscape/bookmarks.html" >> ${LOGFILE}
+-	fi
++#	if test ! -d ${HOME}/.netscape
++#	then
++#		# New install, or upgrade from 0.x or 1.x.
++#		mkdir ${HOME}/.netscape
++#		cp ${TARGET}/bookmark.htm ${HOME}/.netscape/bookmarks.html
++#		chmod 644 ${HOME}/.netscape/bookmarks.html
++#		echo "${HOME}/.netscape/bookmarks.html" >> ${LOGFILE}
++#	fi
+ fi
+ 
+ echo ""
+@@ -387,18 +388,18 @@
+ then
+ 	echo "ERROR: Installation completed, but unable to update/create the product"
+ 	echo "       version registry."
+-	echo ""
+-	echo "       If you are installing ${PRODUCT} from a platform other than"
+-	echo "       that for which this package is intended, 'vreg' will not be"
+-	echo "       able to run.  If this is the case, you may run 'vreg' manually"
+-	echo "       (to enable ASD) on the appropriate platform using the following"
+-	echo "       commands:"
+-	echo ""
+-	awk '{printf("\techo \"%s\" >>/tmp/infile\n", $0)}' ${REG_INFILE}
+-	echo "	${TARGET}/vreg ${TARGET}/${VREGISTRY} /tmp/infile"
+-	echo ""
+-	/bin/rm -f ns-install ${PACKAGE} ${REG_INFILE} core
+-	exit 3
++#	echo ""
++#	echo "       If you are installing ${PRODUCT} from a platform other than"
++#	echo "       that for which this package is intended, 'vreg' will not be"
++#	echo "       able to run.  If this is the case, you may run 'vreg' manually"
++#	echo "       (to enable ASD) on the appropriate platform using the following"
++#	echo "       commands:"
++#	echo ""
++#	awk '{printf("\techo \"%s\" >>/tmp/infile\n", $0)}' ${REG_INFILE}
++#	echo "	${TARGET}/vreg ${TARGET}/${VREGISTRY} /tmp/infile"
++#	echo ""
++#	/bin/rm -f ns-install ${PACKAGE} ${REG_INFILE} core
++#	exit 3
+ fi
+ 
+ echo ""
