Update to 0.96.

diff --git a/graphics/dia/files/patch-ad b/graphics/dia/files/patch-ad
--- a/graphics/dia/files/patch-ad
+++ b/graphics/dia/files/patch-ad
@@ -1,6 +1,15 @@
---- configure.orig	Thu Aug 19 23:59:15 2004
-+++ configure	Fri Aug 20 00:02:09 2004
-@@ -21542,7 +21542,7 @@
+--- configure.orig	Sun Mar 25 15:18:59 2007
++++ configure	Sun Mar 25 15:20:01 2007
+@@ -20515,7 +20515,7 @@ if test "${with_freetype+set}" = set; th
+ else
+   with_freetype=yes
+ fi;
+-if test "x$with_freetype" == "xyes"; then
++if test "x$with_freetype" = "xyes"; then
+ 
+ pkg_failed=no
+ echo "$as_me:$LINENO: checking for PANGOFT2" >&5
+@@ -20835,7 +20835,7 @@ _ACEOF
  
  
  cat >>confdefs.h <<_ACEOF
@@ -9,7 +18,25 @@
  _ACEOF
  
      have_gnome=true
-@@ -25231,7 +25231,7 @@
+@@ -20989,7 +20989,7 @@ if test "${with_gnomeprint+set}" = set; 
+ else
+   with_gnomeprint=no
+ fi;
+-if test "x$with_gnomeprint" == "xyes"; then
++if test "x$with_gnomeprint" = "xyes"; then
+ 
+ pkg_failed=no
+ echo "$as_me:$LINENO: checking for GNOMEPRINT" >&5
+@@ -21927,7 +21927,7 @@ else
+ echo "${ECHO_T}no" >&6
+ fi
+ 
+-if test "$XGETTEXT" == none ; then
++if test "$XGETTEXT" = none ; then
+    { { echo "$as_me:$LINENO: error: xgettext program not found: $XGETTEXT." >&5
+ echo "$as_me: error: xgettext program not found: $XGETTEXT." >&2;}
+    { (exit 1); exit 1; }; }
+@@ -25011,7 +25011,7 @@ echo $ECHO_N "checking local Python conf
  
    fi
  
@@ -18,7 +45,7 @@
  
    PYTHON_PLATFORM=`$PYTHON -c "import sys; print sys.platform"`
  
-@@ -25293,12 +25293,12 @@
+@@ -25073,12 +25073,12 @@ except ImportError:
  except:
          sys.exit(0)
  sys.exit(0)"
