- Don't abort installation when we fail to make device
PR:		ports/80592
Submitted by:	Frank W. Josellis <frank@dynamical-systems.org> (maintainer)

diff --git a/sysutils/pcfclock/pkg-install b/sysutils/pcfclock/pkg-install
--- a/sysutils/pcfclock/pkg-install
+++ b/sysutils/pcfclock/pkg-install
@@ -2,6 +2,19 @@
 
 case $2 in
     POST-INSTALL)
-    [ -c /dev/pcfclock0 ] || ( cd /dev && ./MAKEDEV pcfclock0 )
+    if [ ! -c /dev/pcfclock0 ]; then
+	rv=1
+	if [ -x /dev/MAKEDEV ]; then
+	    ( cd /dev && ./MAKEDEV pcfclock0 )
+	    rv=$?
+	fi
+
+	if [ ${rv} = 0 ]; then
+	    echo "$2: Device special file /dev/pcfclock0 created"
+	else
+	    echo "$2: Unexpected failure creating /dev/pcfclock0"
+	    echo "$2: Try 'cd /dev ; mknod pcfclock0 c 140 0 root:wheel'"
+	fi
+    fi
     ;;
 esac
