- Update MASTER_SITES - Move default cache and log directories from $PREFIX/squid/ to /var/squid/
PR:		145675
Submitted by:	Thomas-Martin Seck <tmseck@web.de> (maintainer)

diff --git a/www/squid31/files/pkg-deinstall.in b/www/squid31/files/pkg-deinstall.in
--- a/www/squid31/files/pkg-deinstall.in
+++ b/www/squid31/files/pkg-deinstall.in
@@ -4,12 +4,21 @@
 #
 
 PATH=/bin:/usr/bin:/usr/sbin
+squid_base="/var/squid"
+squid_cachedir="${squid_base}/cache"
+squid_confdir=${PKG_PREFIX}/etc/squid
+squid_logdir="/var/log/squid"
+squid_rundir="/var/run/squid"
 
 case $2 in
 DEINSTALL)
-	cd ${PKG_PREFIX}/etc/squid || exit 1
+	cd ${squid_confdir} || exit 1
 	for f in cachemgr.conf errorpage.css mime.conf msntauth.conf squid.conf; do
 		cmp -s -z ${f} ${f}.default && rm ${f}
+	done
+	# try to cleanup directories in /var:
+	for d in ${squid_cachedir} ${squid_base} ${squid_logdir} ${squid_rundir}; do
+		rmdir ${d} 2>/dev/null
 	done
 	;;
 POST-DEINSTALL)
@@ -22,7 +31,7 @@ POST-DEINSTALL)
 	echo "     created by a default installation of this package, run"
 	echo ""
 	echo "     pw userdel -n %%SQUID_UID%% -u 100"
-	if  [ -d ${PKG_PREFIX}/squid -o -d ${PKG_PREFIX}/etc/squid ] ; then
+	if  [ -d ${squid_base} -o -d ${squid_confdir} -o -d ${squid_logdir} -o -d ${squid_rundir} ] ; then
 		echo ""
 		echo "     In order to ease updates the cache and log directories"
 		echo "     and all configuration files modified by you were preserved."
