- Update to 0.93
This version fixes lock problem reported at ports/122534

Most important changes:
 *libclamav:
   - New logic in scan limits: provides much more efficient protection against
     DoS attacks but also results in different command line and config options
     to clamscan and clamd (see below)
   - New/improved modules: unzip, SIS, cabinet, CHM, SZDD, text normalisator,
     entity converter
   - Improved filetype detection; filetype definitions can be remotely updated
   - Support for .cld containers (which replace .inc directories)
   - Improved pattern matcher and signature formats
   - More efficient scanning of HTML files
   - Many other improvements

 * clamd:
   - NEW CONFIG FILE OPTIONS: MaxScanSize, MaxFileSize, MaxRecursion, MaxFiles
   - ** THE FOLLOWING OPTIONS ARE NO LONGER SUPPORTED **: MailMaxRecursion,
     ArchiveMaxFileSize, ArchiveMaxRecursion, ArchiveMaxFiles,
     ArchiveMaxCompressionRatio, ArchiveBlockMax

 * clamscan:
   - NEW CMDLINE OPTIONS: --max-filesize, --max-scansize
   - REMOVED OPTIONS: --block-max, --max-space, --max-ratio

 * freshclam:
   - NEW CONFIG OPTION CompressLocalDatabase
   - NEW CMDLINE SWITCH --no-warnings
   - main.inc and daily.inc directories are no longer used by ClamAV; please
     remove them manually from your database directory

PR:		ports/122770 [1] (based on)
		ports/122534 [2]
Submitted by:	Michael Scheidell <scheidell@secnap.net> [1]
		Sebastian Inacker <inacker@fmsweb.de> [2]
Security:	http://secunia.com/advisories/29000

diff --git a/security/clamav/files/clamav-clamd.in b/security/clamav/files/clamav-clamd.in
--- a/security/clamav/files/clamav-clamd.in
+++ b/security/clamav/files/clamav-clamd.in
@@ -32,4 +32,14 @@ load_rc_config "$name"
 : ${clamav_clamd_flags=""}
 : ${clamav_clamd_socket="%%CLAMAV_CLAMD_SOCKET%%"}
 
+start_precmd=clamav_clamd_precmd
+
+#clamav .93 won't start without a valid main.cvd file
+clamav_clamd_precmd() {
+	if [ ! -f %%DBDIR%%/main.cvd ];then
+		echo "Missing %%DBDIR%%/clamav/*.cvd files.  You must run freshclam first"
+		exit 1
+	fi
+}
+
 run_rc_command "$1"
