- Update to v1.9.8
PR:		129593
Submitted by:	Ganael Laplanche <ganael dot laplanche at martymac dot com> (maintainer)

diff --git a/deskutils/notecase/files/patch-Makefile b/deskutils/notecase/files/patch-Makefile
--- a/deskutils/notecase/files/patch-Makefile
+++ b/deskutils/notecase/files/patch-Makefile
@@ -1,14 +1,18 @@
---- Makefile.orig	2008-10-28 13:39:40.000000000 +0100
-+++ Makefile	2008-11-04 15:51:07.000000000 +0100
-@@ -13,6 +13,7 @@
- prefix=/usr
+--- Makefile.orig	2008-12-09 11:07:06.000000000 +0100
++++ Makefile	2008-12-12 09:15:50.220188108 +0100
+@@ -10,9 +10,10 @@
+ VERSION=1.9.8
+ 
+ # define install target dirs
+-prefix=/usr
++prefix=/usr/local
  bindir=$(prefix)/bin
  datadir=$(prefix)/share
-+docsdir=
++docsdir=/usr/local/share/doc/notecase
  
  # define top of RPM build area
  topdir=/usr/src/redhat
-@@ -592,18 +593,21 @@
+@@ -601,18 +602,21 @@
  pouninstall:
  	@rm -vf $(DESTDIR)$(datadir)/locale/*/LC_MESSAGES/notecase.mo
  	@echo done uninstalling translations
@@ -22,7 +26,7 @@
  #
  # install application
  #
- install: notecase$(EXE) poinstall
+ install: $(BIN)/notecase$(EXE) poinstall
  	install -d -m 755 $(DESTDIR)$(bindir)
 -	install -d -m 755 $(DESTDIR)$(datadir)/doc/notecase/
  	install -d -m 755 $(DESTDIR)$(datadir)/applications/
@@ -33,7 +37,20 @@
  	$(INSTALL) -m 644 docs/notecase.xml "$(DESTDIR)$(datadir)/mime/packages/notecase.xml"
  	$(Q)if [ -n "$(NOKIA_MAEMO_BUILD)" ]; then \
  		$(INSTALL) -m 644 docs/notecase.desktop "$(DESTDIR)$(datadir)/applications/hildon/notecase.desktop"; \
-@@ -800,7 +804,7 @@
+@@ -694,12 +698,6 @@
+ 		echo 'pkg-config error detected $(shell pkg-config --cflags $(LIBS))';\
+ 		exit 1;\
+ 	fi;  
+-	$(Q)if [ "$(HAVE_GTKSOURCEVIEW)" = "1" ]; then \
+-		if [[ "$(TEST_SRCVIEW_VER)" < "2.4.1" ]]; then \
+-		echo 'ERROR: gtksourceview package is too old ($(shell pkg-config --modversion gtksourceview-2.0))!';\
+-		exit 1;\
+-		fi;\
+-	fi;
+ 	$(Q)echo 'Configuration: GNOME_VFS=$(HAVE_GNOME_VFS);GTKSOURCEVIEW=$(HAVE_GTKSOURCEVIEW);DEBUG=$(DEBUG);PROFILE=$(PROFILE);BYTE_ORDER=$(BYTE_ORDER);PLATFORM=$(PLATFORM)' 
+ 	$(Q)$(SED) 's/^Version:.*/Version:        $(VERSION)/' ./docs/notecase.spec
+ 	$(Q)$(SED) 's/^Source:.*/Source:         $(archive)_src.tar.gz/' ./docs/notecase.spec
+@@ -820,7 +818,7 @@
  #
  # Note: first "make" command forces generating correct help file path in "config.h"
  #
