Update to 2.0.1.
PR:		117085
Submitted by:	Greg Larkin <glarkin@sourcehosting.net>
Approved by:	maintainer

diff --git a/devel/cvs2svn/Makefile b/devel/cvs2svn/Makefile
--- a/devel/cvs2svn/Makefile
+++ b/devel/cvs2svn/Makefile
@@ -5,9 +5,10 @@
 # $FreeBSD$
 
 PORTNAME=	cvs2svn
-PORTVERSION=	1.5.0
+PORTVERSION=	2.0.1
 CATEGORIES=	devel
-MASTER_SITES=	ftp://ftp.rewt.org.uk/pub/distfiles/ \
+MASTER_SITES=	http://cvs2svn.tigris.org/files/documents/1462/39919/ \
+		ftp://ftp.rewt.org.uk/pub/distfiles/ \
 		http://gentoo.nedlinux.nl/distfiles/ \
 		${MASTER_SITE_LOCAL}
 MASTER_SITE_SUBDIR=	jkoshy
@@ -16,7 +17,7 @@ MAINTAINER=	joe@joeholden.co.uk
 COMMENT=	CVS to Subversion Repository Converter
 
 BUILD_DEPENDS=	${PYTHON_SITELIBDIR}/gdbm.so:${PORTSDIR}/databases/py-gdbm
-RUN_DEPENDS=	svn:${PORTSDIR}/devel/subversion \
+RUN_DEPENDS=	${LOCALBASE}/bin/svn:${PORTSDIR}/devel/subversion \
 		${BUILD_DEPENDS}
 
 DISABLE_SIZE=	yes
@@ -25,6 +26,19 @@ USE_PYTHON=	2.3+
 USE_PYDISTUTILS=	yes
 
 MAN1=		cvs2svn.1
+
+# The only thing different in this target vs. the one found in bsd.port.mk
+# is that the extract command exit code is ignored.  tar exits with status
+# 1 because the distfile contains a symlink that points nowhere.
+do-extract:
+	@${RM} -rf ${WRKDIR}
+	@${MKDIR} ${WRKDIR}
+	@-for file in ${EXTRACT_ONLY}; do \
+		if ! (cd ${WRKDIR} && ${EXTRACT_CMD} ${EXTRACT_BEFORE_ARGS} ${_DISTDIR}/$$file ${EXTRACT_AFTER_ARGS});\
+		then \
+			exit 1; \
+		fi; \
+	done
 
 post-install:
 	${INSTALL_MAN} ${WRKSRC}/cvs2svn.1 ${PREFIX}/man/man1/
