update to 2.2.15
- new switch WITH_DYNAMIC_BACKENDS
- WITH_ODBC has to be specified, even when WITH_ODBC_TYPE is set
- 5.x users: when you need to start the daemon early, build with
  WITH_RCORDER=yes to put the start script into /etc/rc.d

diff --git a/net/openldap24-server/files/patch-configure b/net/openldap24-server/files/patch-configure
--- a/net/openldap24-server/files/patch-configure
+++ b/net/openldap24-server/files/patch-configure
@@ -1,20 +1,29 @@
---- configure.orig	Wed May  5 11:55:48 2004
-+++ configure	Wed May  5 11:56:33 2004
-@@ -20220,7 +20220,7 @@
+--- configure.orig	Tue Jul 27 18:33:12 2004
++++ configure	Sat Aug 14 17:05:23 2004
+@@ -19497,7 +19497,7 @@
+ 
+ 
+ 	if test $ol_cv_bdb_compat = yes ; then
+-		ol_enable_bdb=yes
++		ol_enable_bdb=${ol_enable_bdb-yes}
+ 	elif test $ol_enable_bdb = yes ; then
+ 		{ echo "configure: error: BDB: BerkeleyDB version incompatible" 1>&2; exit 1; }
+ 	else
+@@ -20349,7 +20349,7 @@
    echo $ac_n "(cached) $ac_c" 1>&6
  else
    ac_save_LIBS="$LIBS"
 -LIBS="-liodbc  $LIBS"
 +LIBS="-liodbc  $LIBS  $LTHREAD_LIBS"
  cat > conftest.$ac_ext <<EOF
- #line 20226 "configure"
+ #line 20355 "configure"
  #include "confdefs.h"
-@@ -20264,7 +20264,7 @@
+@@ -20393,7 +20393,7 @@
    echo $ac_n "(cached) $ac_c" 1>&6
  else
    ac_save_LIBS="$LIBS"
 -LIBS="-lodbc  $LIBS"
 +LIBS="-lodbc  $LIBS  $LTHREAD_LIBS"
  cat > conftest.$ac_ext <<EOF
- #line 20270 "configure"
+ #line 20399 "configure"
  #include "confdefs.h"
