x11/cde: Update to 2.3.2
Make a few fixes for head, and add appropriate messages for dtlogin

diff --git a/x11/cde/files/dtlogin.in b/x11/cde/files/dtlogin.in
--- a/x11/cde/files/dtlogin.in
+++ b/x11/cde/files/dtlogin.in
@@ -6,7 +6,7 @@
 # REQUIRE: LOGIN dbus dtspc
 # KEYWORD: shutdown
 #
-# Add the following line to /etc/rc.conf to enable slim:
+# Add the following line to /etc/rc.conf to enable dtlogin:
 # dtlogin_enable="YES"
 #
 
@@ -22,5 +22,15 @@ load_rc_config dtlogin
 
 command=%%PREFIX%%/dt/bin/dtlogin
 command_args=-daemon
+
+start_precmd=dtlogin_prestart
+
+dtlogin_prestart()
+{
+	if ! [ -f "%%PREFIX%%/etc/X11/Xwrapper.config" ]; then
+		echo "If dtlogin fails to start:"
+		echo "# echo allowed_users=anybody >> %%PREFIX%%/etc/X11/Xwrapper.config"
+	fi
+}
 
 run_rc_command $1
