Oops, forgot to commit the fix

diff --git a/security/cyrus-sasl2/files/patch-saslauthd::configure b/security/cyrus-sasl2/files/patch-saslauthd::configure
--- a/security/cyrus-sasl2/files/patch-saslauthd::configure
+++ b/security/cyrus-sasl2/files/patch-saslauthd::configure
@@ -1,8 +1,15 @@
-Index: saslauthd/configure
-diff -u saslauthd/configure.orig saslauthd/configure
---- saslauthd/configure.orig	Sun May 15 14:59:04 2005
-+++ saslauthd/configure	Tue May 17 14:57:49 2005
-@@ -1525,6 +1525,7 @@
+--- saslauthd/configure.orig	2006-05-19 03:30:20.000000000 +0800
++++ saslauthd/configure	2008-05-21 10:00:20.000000000 +0800
+@@ -1234,7 +1234,7 @@
+       ac_cache_corrupted=: ;;
+     ,);;
+     *)
+-      if test "x$ac_old_val" != "x$ac_new_val"; then
++      if test "`echo $ac_old_val`" != "`echo $ac_new_val`"; then
+         { echo "$as_me:$LINENO: error: \`$ac_var' has changed since the previous run:" >&5
+ echo "$as_me: error: \`$ac_var' has changed since the previous run:" >&2;}
+         { echo "$as_me:$LINENO:   former value:  $ac_old_val" >&5
+@@ -1526,6 +1526,7 @@
  fi
  echo "$as_me:$LINENO: result: yes" >&5
  echo "${ECHO_T}yes" >&6
@@ -10,7 +17,7 @@ diff -u saslauthd/configure.orig saslauthd/configure
  test "$program_prefix" != NONE &&
    program_transform_name="s,^,$program_prefix,;$program_transform_name"
  # Use a double $ so make ignores it.
-@@ -6782,7 +6783,7 @@
+@@ -6843,7 +6844,7 @@
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
    ac_check_lib_save_LIBS=$LIBS
@@ -19,8 +26,8 @@ diff -u saslauthd/configure.orig saslauthd/configure
  cat >conftest.$ac_ext <<_ACEOF
  #line $LINENO "configure"
  /* confdefs.h.  */
-@@ -7132,7 +7133,7 @@
-     GSSAPIBASE_STATIC_LIBS="$GSSAPIBASE_LIBS $gssapi_dir/libgssapi_krb5.a $gssapi_dir/libkrb5.a $gssapi_dir/libk5crypto.a $gssapi_dir/libcom_err.a"
+@@ -7253,7 +7254,7 @@
+     GSSAPIBASE_STATIC_LIBS="$GSSAPIBASE_LIBS $gssapi_dir/libgssapi_krb5.a $gssapi_dir/libkrb5.a $gssapi_dir/libk5crypto.a $gssapi_dir/libcom_err.a ${K5SUPSTATIC}"
    elif test "$gss_impl" = "heimdal"; then
      CPPFLAGS="$CPPFLAGS -DKRB5_HEIMDAL"
 -    GSSAPIBASE_LIBS="$GSSAPIBASE_LIBS -lgssapi -lkrb5 -lasn1 -lroken ${LIB_CRYPT} ${LIB_DES} -lcom_err"
@@ -28,7 +35,7 @@ diff -u saslauthd/configure.orig saslauthd/configure
      GSSAPIBASE_STATIC_LIBS="$GSSAPIBASE_STATIC_LIBS $gssapi_dir/libgssapi.a $gssapi_dir/libkrb5.a $gssapi_dir/libasn1.a $gssapi_dir/libroken.a $gssapi_dir/libcom_err.a ${LIB_CRYPT}"
    elif test "$gss_impl" = "cybersafe03"; then
  # Version of CyberSafe with two libraries
-@@ -7889,7 +7890,7 @@
+@@ -8010,7 +8011,7 @@
  	fi
  
  	saved_LIBS=$LIBS
@@ -37,7 +44,7 @@ diff -u saslauthd/configure.orig saslauthd/configure
            do
  	    LIBS="$saved_LIBS -l$dbname"
  	    cat >conftest.$ac_ext <<_ACEOF
-@@ -7899,6 +7900,7 @@
+@@ -8020,6 +8021,7 @@
  cat confdefs.h >>conftest.$ac_ext
  cat >>conftest.$ac_ext <<_ACEOF
  /* end confdefs.h.  */
@@ -45,7 +52,7 @@ diff -u saslauthd/configure.orig saslauthd/configure
  #include <db.h>
  int
  main ()
-@@ -8646,7 +8648,7 @@
+@@ -8767,7 +8769,7 @@
  	fi
  
  	saved_LIBS=$LIBS
@@ -54,7 +61,7 @@ diff -u saslauthd/configure.orig saslauthd/configure
            do
  	    LIBS="$saved_LIBS -l$dbname"
  	    cat >conftest.$ac_ext <<_ACEOF
-@@ -8656,6 +8658,7 @@
+@@ -8777,6 +8779,7 @@
  cat confdefs.h >>conftest.$ac_ext
  cat >>conftest.$ac_ext <<_ACEOF
  /* end confdefs.h.  */
