Add all freebsd ports overlay from freenas repo

diff --git a/emulators/virtualbox-ose-kmod/files/vboxnet.in b/emulators/virtualbox-ose-kmod/files/vboxnet.in
--- a/emulators/virtualbox-ose-kmod/files/vboxnet.in
+++ b/emulators/virtualbox-ose-kmod/files/vboxnet.in
@@ -22,45 +22,56 @@ rcvar=vboxnet_enable
 start_cmd="vboxnet_start"
 stop_cmd="vboxnet_stop"
 
-vboxnet_modules="vboxdrv vboxnetflt:ng_vboxnetflt vboxnetadp"
-
 vboxnet_start()
 {
-	local _k _m
-
-	for _m in ${vboxnet_modules}; do
-		_k=${_m%:*}
-		_m=${_m#*:}
-		if ! kldstat -q -m ${_m}; then
-			if ! kldload ${_k} > /dev/null 2>&1; then
-				warn "Can't load ${_k} module."
-				return 1
-			fi
+	if ! kldstat -q -m ng_vboxnetflt;
+	then
+		if ! kldload vboxnetflt > /dev/null 2>&1;
+		then
+			warn "Can't load vboxnetflt module."
+			return 1
 		fi
-	done
+	fi
+
+	if ! kldstat -q -m vboxnetadp;
+	then
+		if ! kldload vboxnetadp > /dev/null 2>&1;
+		then
+			warn "Can't load vboxnetadp module."
+			return 1
+		fi
+	fi
 
 	# initialize configured host-only interfaces
-	LD_LIBRARY_PATH=%%PREFIX%%/lib %%PREFIX%%/bin/VBoxManage list hostonlyifs >/dev/null
+	# Only do this if running in a jail
+	# On FreeNAS the kernel modules need to be loaded
+	# from the host environment, but the host only
+	# interfaces are created in the vbox jail.
+	jail=$(sysctl -n security.jail.jailed)
+	if [ ${jail} -ne 0 ]; then
+		LD_LIBRARY_PATH=%%PREFIX%%/lib %%PREFIX%%/bin/VBoxManage list hostonlyifs >/dev/null
+	fi
 }
 
 vboxnet_stop()
 {
-	local _k _m _r
-
-	_r=
-	for _m in ${vboxnet_modules}; do
-		_r="${_m} ${_r}"
-	done
-	for _m in ${_r}; do
-		_k=${_m%:*}
-		_m=${_m#*:}
-		if kldstat -q -m ${_m}; then
-			if ! kldunload ${_k} > /dev/null 2>&1; then
-				warn "Can't unload ${_k} module."
-				return 1
-			fi
+	if kldstat -q -m vboxnetadp;
+	then
+		if ! kldunload vboxnetadp > /dev/null 2>&1;
+		then
+			warn "Can't unload vboxnetadp module."
+			return 1
 		fi
-	done
+	fi
+
+	if kldstat -q -m ng_vboxnetflt;
+	then
+		if ! kldunload vboxnetflt > /dev/null 2>&1;
+		then
+			warn "Can't unload vboxnetflt module."
+			return 1
+		fi
+	fi
 }
 
 load_rc_config $name
