Upgrade to 8.0.4.
PR:		11254
Submitted by:	Glenn Johnson <gljohns@bellsouth.net>

diff --git a/x11-toolkits/tkstep80/files/patch-aa b/x11-toolkits/tkstep80/files/patch-aa
--- a/x11-toolkits/tkstep80/files/patch-aa
+++ b/x11-toolkits/tkstep80/files/patch-aa
@@ -1,53 +1,78 @@
---- configure.orig	Sun Oct  4 13:14:37 1998
-+++ configure	Sun Oct  4 13:26:21 1998
-@@ -877,14 +877,14 @@
-   withval="$with_tcl"
-   TCL_BIN_DIR=$withval
- else
--  TCL_BIN_DIR=`cd ../../tcl8.0/unix; pwd`
-+  TCL_BIN_DIR=${prefix}/lib/tcl8.0
- fi
- 
- if test ! -d $TCL_BIN_DIR; then
-     { echo "configure: error: Tcl directory $TCL_BIN_DIR doesn't exist" 1>&2; exit 1; }
- fi
--if test ! -f $TCL_BIN_DIR/Makefile; then
--    { echo "configure: error: There's no Makefile in $TCL_BIN_DIR;  perhaps you didn't specify the Tcl *build* directory (not the toplevel Tcl directory) or you forgot to configure Tcl?" 1>&2; exit 1; }
-+if test ! -f $TCL_BIN_DIR/tclConfig.sh; then
-+    { echo "configure: error: There's no tclConfig.sh in $TCL_BIN_DIR;  perhaps you didn't specify the Tcl *build* directory (not the toplevel Tcl directory) or you forgot to configure Tcl?" 1>&2; exit 1; }
- fi
- 
- #--------------------------------------------------------------------
-@@ -903,6 +903,8 @@
- DL_LIBS=$TCL_DL_LIBS
- LD_FLAGS=$TCL_LD_FLAGS
- 
-+TCL_SRC_DIR=${prefix}/include/tcl${TCL_VERSION}
-+
- LIB_RUNTIME_DIR='${LIB_RUNTIME_DIR}'
- 
- # If Tcl and Tk are installed in different places, adjust the library
-@@ -2428,8 +2430,13 @@
- if test "$ok" = "yes" -a "${SHLIB_SUFFIX}" != ""; then
-     TK_SHARED_BUILD=1
-     TK_SHLIB_CFLAGS="${SHLIB_CFLAGS}"
--    eval "TK_LIB_FILE=libtkstep${TCL_SHARED_LIB_SUFFIX}"
--    MAKE_LIB="\${SHLIB_LD} -o ${TK_LIB_FILE} \${OBJS} \$(TK_LD_SEARCH_FLAGS) ${SHLIB_LD_LIBS}"
-+    if [ "$PORTOBJFORMAT" = "elf" ]; then
-+	eval "TK_LIB_FILE=libtkstep`echo ${VERSION} | tr -d .`.so.1"
-+	MAKE_LIB="\${SHLIB_LD} -soname ${TK_LIB_FILE} -o ${TK_LIB_FILE} \${OBJS} \$(TK_LD_SEARCH_FLAGS) ${SHLIB_LD_LIBS}"
-+    else
-+	eval "TK_LIB_FILE=libtkstep`echo ${VERSION} | tr -d .`.so.1.2"
-+	MAKE_LIB="\${SHLIB_LD} -o ${TK_LIB_FILE} \${OBJS} \$(TK_LD_SEARCH_FLAGS) ${SHLIB_LD_LIBS}"
-+    fi
-     RANLIB=":"
- else
-     TK_SHARED_BUILD=0
-@@ -2736,6 +2743,7 @@
- s%@SHLIB_VERSION@%$SHLIB_VERSION%g
- s%@TCL_BIN_DIR@%$TCL_BIN_DIR%g
- s%@TCL_BUILD_LIB_SPEC@%$TCL_BUILD_LIB_SPEC%g
-+s%@TCL_LIB_SPEC@%$TCL_LIB_SPEC%g
- s%@TCL_SRC_DIR@%$TCL_SRC_DIR%g
- s%@TCL_VERSION@%$TCL_VERSION%g
- s%@TK_BUILD_LIB_SPEC@%$TK_BUILD_LIB_SPEC%g
+*** configure.orig	Mon Apr 19 21:28:50 1999
+--- configure	Mon Apr 19 21:30:27 1999
+***************
+*** 891,904 ****
+    withval="$with_tcl"
+    TCL_BIN_DIR=$withval
+  else
+!   TCL_BIN_DIR=`cd ../../tcl8.0$TK_PATCH_LEVEL/unix; pwd`
+  fi
+  
+  if test ! -d $TCL_BIN_DIR; then
+      { echo "configure: error: Tcl directory $TCL_BIN_DIR doesn't exist" 1>&2; exit 1; }
+  fi
+! if test ! -f $TCL_BIN_DIR/Makefile; then
+!     { echo "configure: error: There's no Makefile in $TCL_BIN_DIR;  perhaps you didn't specify the Tcl *build* directory (not the toplevel Tcl directory) or you forgot to configure Tcl?" 1>&2; exit 1; }
+  fi
+  
+  #--------------------------------------------------------------------
+--- 891,904 ----
+    withval="$with_tcl"
+    TCL_BIN_DIR=$withval
+  else
+!   TCL_BIN_DIR=${prefix}/lib/tcl8.0
+  fi
+  
+  if test ! -d $TCL_BIN_DIR; then
+      { echo "configure: error: Tcl directory $TCL_BIN_DIR doesn't exist" 1>&2; exit 1; }
+  fi
+! if test ! -f $TCL_BIN_DIR/tclConfig.sh; then
+!     { echo "configure: error: There's no tclConfig.sh in $TCL_BIN_DIR;  perhaps you didn't specify the Tcl *build* directory (not the toplevel Tcl directory) or you forgot to configure Tcl?" 1>&2; exit 1; }
+  fi
+  
+  #--------------------------------------------------------------------
+***************
+*** 936,943 ****
+  DL_LIBS=$TCL_DL_LIBS
+  LD_FLAGS=$TCL_LD_FLAGS
+  CFLAGS_DEBUG=$TCL_CFLAGS_DEBUG
+! CFLAGS_OPTIMIZE=$TCL_CFLAGS_OPTIMIZE
+  EXTRA_CFLAGS=$TCL_EXTRA_CFLAGS
+  
+  LIB_RUNTIME_DIR='${LIB_RUNTIME_DIR}'
+  
+--- 936,944 ----
+  DL_LIBS=$TCL_DL_LIBS
+  LD_FLAGS=$TCL_LD_FLAGS
+  CFLAGS_DEBUG=$TCL_CFLAGS_DEBUG
+! CFLAGS_OPTIMIZE=$CFLAGS
+  EXTRA_CFLAGS=$TCL_EXTRA_CFLAGS
++ TCL_SRC_DIR=${prefix}/include/tcl${TCL_VERSION}
+  
+  LIB_RUNTIME_DIR='${LIB_RUNTIME_DIR}'
+  
+***************
+*** 2480,2487 ****
+  if test "$ok" = "yes" -a "${SHLIB_SUFFIX}" != ""; then
+      TK_SHARED_BUILD=1
+      TK_SHLIB_CFLAGS="${SHLIB_CFLAGS}"
+!     eval "TK_LIB_FILE=libtk${STEP}${TCL_SHARED_LIB_SUFFIX}"
+!     MAKE_LIB="\${SHLIB_LD} -o \${TK_LIB_FILE} \${OBJS} \$(TK_LD_SEARCH_FLAGS) ${SHLIB_LD_LIBS}"
+      RANLIB=":"
+  else
+      TK_SHARED_BUILD=0
+--- 2481,2494 ----
+  if test "$ok" = "yes" -a "${SHLIB_SUFFIX}" != ""; then
+      TK_SHARED_BUILD=1
+      TK_SHLIB_CFLAGS="${SHLIB_CFLAGS}"
+!     if [ "$PORTOBJFORMAT" = "elf" ]; then
+!        eval "TK_LIB_FILE=libtkstep`echo ${VERSION} | tr -d .`.so.1"
+!        MAKE_LIB="\${SHLIB_LD} -soname ${TK_LIB_FILE} -o ${TK_LIB_FILE} \${OBJS} \$(TK_LD_SEARCH_FLAGS) ${SHLIB_LD_LIBS}"
+!     else
+!        eval "TK_LIB_FILE=libtkstep`echo ${VERSION} | tr -d .`.so.1.4"
+!        MAKE_LIB="\${SHLIB_LD} -o ${TK_LIB_FILE} \${OBJS} \$(TK_LD_SEARCH_FLAGS) ${SHLIB_LD_LIBS}"
+!     fi
+! 
+      RANLIB=":"
+  else
+      TK_SHARED_BUILD=0
