Portlint(1) fixes. Makefile unwanted spaces and changes to the tab and remove unwanted comments. Files are not installed. UID / GID immobilized.
PR:		151298
Submitted by:	Takefu <takefu@airport.fm>
Approved by:	itetcu - Maintainer timeout (Mark Foster mark@foster.cc)

diff --git a/audio/firefly/files/pkg-install.in b/audio/firefly/files/pkg-install.in
--- a/audio/firefly/files/pkg-install.in
+++ b/audio/firefly/files/pkg-install.in
@@ -1,33 +1,53 @@
 #!/bin/sh
 #
-# $FreeBSD: /tmp/pcvs/ports/audio/firefly/files/Attic/pkg-install.in,v 1.1 2008-10-19 15:59:16 miwi Exp $
-# formerly $ FreeBSD: ports/audio/mt-daapd/pkg-install,v 1.1 2004/08/05 23:00:09 edwin Exp $
+# $FreeBSD: /tmp/pcvs/ports/audio/firefly/files/Attic/pkg-install.in,v 1.2 2010-11-26 23:07:50 beech Exp $
 #
 
-PATH=/bin:/usr/bin:/usr/sbin
+if [ "$2" != "PRE-INSTALL" ]; then
+	exit 0
+fi
 
-case $2 in
+SC_GROUP=%%GROUP%%
+SC_USER=%%USER%%
+SC_SHELL=/sbin/nologin
+SC_HOME=/nonexistent
+PW=`which pw`
 
-PRE-INSTALL)
-  echo "---> Starting pre-install script:"
+if ! ${PW} show group ${SC_GROUP} -q >/dev/null; then
+	gid=3689
+	while ${PW} show group -g ${gid} -q >/dev/null; do
+		gid=`expr ${gid} + 1`
+	done
+	if ! ${PW} add group ${SC_GROUP} -g ${gid}; then
+		e=$?
+		echo "*** Failed to add group \`${SC_GROUP}'. Please add it manually."
+		exit ${e}
+	fi
+	echo "*** Added group \`${SC_GROUP}' (id ${gid})"
+else
+	gid=`${PW} show group ${SC_GROUP} 2>/dev/null | cut -d: -f3`
+fi
 
-  if pw showgroup "daapd" 2>/dev/null; then
-    echo "---> Using existing group \"daapd\""
-  else
-    echo "---> Adding group \"daapd\""
-    pw addgroup daapd -h - || exit 1
-  fi
-
-
-  # Create user if required
-  if pw showuser "daapd" 2>/dev/null; then
-    echo "---> Using existing user \"daapd\""
-  else
-    echo "---> Adding user \"daapd\""
-    pw adduser daapd -g daapd -h - \
-      -d "/nonexistent" -s "/sbin/nologin" -c "daapd User" || exit 1
-  fi
-
-  ;;
-
-esac
+if ! ${PW} show user ${SC_USER} -q >/dev/null; then
+	uid=3689
+	while ${PW} show user -u ${uid} -q >/dev/null; do
+		uid=`expr ${uid} + 1`
+	done
+	if ! ${PW} add user ${SC_USER} -u ${uid} -g ${gid} -d "${SC_HOME}" \
+	-c "daapd User" -s "${SC_SHELL}" -p "*" \
+	; then
+		e=$?
+		echo "*** Failed to add user \`${SC_USER}'. Please add it manually."
+		exit ${e}
+	fi
+	echo "*** Added user \`${SC_USER}' (id ${uid})"
+else
+	if ! ${PW} mod user ${SC_USER} -g ${gid} -d "${SC_HOME}" \
+	-c "daapd User" -s "${SC_SHELL}" -p "*" \
+	; then
+		e=$?
+		echo "*** Failed to update user \`${SC_USER}'."
+		exit ${e}
+	fi
+		echo "*** Updated user \`${SC_USER}'."
+fi
