www/varnish4: Fix race condition on start
varnishlog and varnishncsa had a race condition with varnishd on
startup as they will notice varnishd's leftover _.vsm file and try to
connect to varnishd but occasionally fail due to varnishd not being
fully operational yet. By adding "-t off" flag as default to varnishncsa
and varnishlog they will wait indefinitely for varnishd to start up
instead of just exiting.

Other bugs fixed:

* varnishncsa_logformat in rc.conf mostly works

Unfortunately due to shell expansion we still cannot pass
quotes (") so if you need those in your log format you will have to
manage varnishncsa startup yourself. I apologize, but there's not much
we can do at the moment. I'm working with upstream to allow loading
configuration from a file. Note that Debian has complained too...

* Default permissions for log and pidfiles have been corrected

They are now correctly set to 664 for pidfiles and 644 for log files

* Description of default flags for varnishncsa and varnishlog have been
adjusted to reflect reality

New features:

* We now support "checkconfig" and "reload" options like on RedHat
distributions

You can do "service varnishd checkconfig" to validate your vcl is
functional. Doing a "service varnishd reload" also works without
interrupting service and creates a new vcl reflecting the date+timestamp.
Varnishd now does a checkconfig before starting and will also prevent
you from breaking a running instance by doing a "restart" with an
invalid vcl.

Thanks to many for the reports and testing.

Differential Revision:	https://reviews.freebsd.org/D4016

diff --git a/www/varnish4/files/varnishd.in b/www/varnish4/files/varnishd.in
--- a/www/varnish4/files/varnishd.in
+++ b/www/varnish4/files/varnishd.in
@@ -65,11 +65,64 @@ load_rc_config ${name}
 
 command="%%PREFIX%%/sbin/${name}"
 pidfile="${varnishd_pidfile}"
+configtest_cmd="varnishd_checkconfig"
+reload_cmd="varnishd_reload"
+restart_precmd="varnishd_checkconfig"
+start_precmd="varnishd_precmd"
+extra_commands="status reload configtest"
 
 if [ -n "${varnishd_config}" ] ; then
 	: ${varnishd_flags:="-j unix,user=${varnishd_jailuser} -P ${varnishd_pidfile} -a ${varnishd_listen} -T ${varnishd_admin} -f ${varnishd_config} -s ${varnishd_storage} -h ${varnishd_hash} ${varnishd_extra_flags}"}
 else
 	: ${varnishd_flags:="-j unix,user=${varnishd_jailuser} -P ${varnishd_pidfile} -a ${varnishd_listen} -T ${varnishd_admin} -b ${varnishd_backend} -s ${varnishd_storage} -h ${varnishd_hash} ${varnishd_extra_flags}"}
 fi
+
+varnishd_checkconfig()
+{
+	if [ -z "${varnishd_config}" ]; then
+		echo "${name}: nothing to check, no configuration file defined, builtin VCL used"
+	else
+		echo "Performing sanity check on ${name} configuration:"
+		if eval ${command} -C -f "${varnishd_config}" 2> /dev/null ; then
+			echo "${name}: the configuration file ${varnishd_config} syntax is ok"
+		else
+			err 1 "${name}: the configuration file ${varnishd_config} syntax is NOT ok"
+		fi
+	fi
+}
+
+# Adapted from work done by Ingvar Hagelund <ingvar@redpill-linpro.com> (see redhat/varnish_reload_vcl)
+varnishd_reload()
+{
+	local _current_config_name _new_config_name _varnishadm_cmd
+
+	if [ -z "${varnishd_config}" ]; then
+		echo "${name}: nothing to reload, no configuration file defined, builtin VCL used"
+	else
+		_new_config_name="rc.d_reloaded@$(date +%Y%m%d%H%M%S)"
+		_varnishadm_cmd="%%PREFIX%%/bin/varnishadm ${varnish_cli_flags}"
+		if ! eval ${_varnishadm_cmd} vcl.list > /dev/null; then
+			err 1 "${name}: can't connect to varnishadm"
+		fi
+		_current_config_name=$(${_varnishadm_cmd} vcl.list | awk ' /^active/ { print $3 } ')
+		if ! eval ${_varnishadm_cmd} vcl.load ${_new_config_name} ${varnishd_config} > /dev/null; then
+			err 1 "${name}: vcl.load failed, you're still using previous rules (${_current_config_name})"
+		fi
+		if eval ${_varnishadm_cmd} vcl.use ${_new_config_name} > /dev/null; then
+			echo "VCL file \"${varnishd_config}\" has been successfully loaded as \"${_new_config_name}\""
+			echo "To remove previous loaded configurations, you should run \"${_varnishadm_cmd} vcl.discard <configname>\" by yourself"
+		else
+			err 1 "${name}: vcl.use failed, you're still using previous rules (${_current_config_name})"
+		fi
+	fi
+
+	return 0
+}
+
+varnishd_precmd()
+{
+	# Check config before starting
+	varnishd_checkconfig
+}
 
 run_rc_command "$1"
