- Update tor to 1.1.20 (former development branch) - Submitter becomes new maintainer (approved by old maintainer) - Use rc.subr
PR:		98373
Submitted by:	Peter Thoenen
Approved by:	flz (mentor)

diff --git a/security/tor/pkg-install b/security/tor/pkg-install
--- a/security/tor/pkg-install
+++ b/security/tor/pkg-install
@@ -1,35 +1,42 @@
-#!/bin/sh
+#! /bin/sh
+#
+# taken from devel/perforce
 
-if [ x"$2" = xPRE-INSTALL ]; then
-    USER="_tor"
-    UID="256"
-    GROUP="_tor"
-    GID="256"
+PATH=/bin:/usr/sbin
 
-	if /usr/sbin/pw groupshow "${GROUP}" 2>/dev/null; then
+TOR_USER=${TOR_USER:-_tor}
+TOR_GROUP=${TOR_GROUP:-_tor}
+
+case $2 in
+PRE-INSTALL)
+	USER=${TOR_USER}
+	UID="256"
+	GROUP=${TOR_GROUP}
+	GID="256"
+
+	if pw group show "${GROUP}" 2>/dev/null; then
 		echo "You already have a group \"${GROUP}\", so I will use it."
 	else
-		if /usr/sbin/pw groupadd ${GROUP} -g ${GID}; then
-		    echo "Added group \"${GROUP}\"."
-	    else
-		    echo "Adding group \"${GROUP}\" failed..."
-			echo "Please create it, and try again."
-	    	exit 1
+		if pw groupadd ${GROUP} -g ${GID}; then
+			echo "Added group \"${GROUP}\"."
+		else
+			echo "Adding group \"${GROUP}\" failed..."
+			exit 1
 		fi
 	fi
 
-	if /usr/sbin/pw user show "${USER}" 2>/dev/null; then
+	if pw user show "${USER}" 2>/dev/null; then
 		echo "You already have a user \"${USER}\", so I will use it."
 	else
-		if /usr/sbin/pw useradd ${USER} -u ${UID} -g ${GROUP} -h - \
-           -d /var/db/tor \
-           -s /bin/sh \
-           -c "Tor anonymising router"; then
-	        echo "Added user \"${USER}\"."
-	    else
-	        echo "Adding user \"${USER}\" failed..."
-	        echo "Please create it, and try again."
-	        exit 1
-	    fi
+		if pw useradd ${USER} -u ${UID} -g ${GROUP} -h - \
+			-d /var/db/tor -c "Tor Daemon" -s /bin/sh
+		then
+			echo "Added user \"${USER}\"."
+		else
+			echo "Adding user \"${USER}\" failed..."
+			exit 1
+		fi
 	fi
-fi
+
+	;;
+esac
