net-mgmt/aircrack-ng:
- Update to 1.3
- Remove timestamps from patchfiles

diff --git a/net-mgmt/aircrack-ng/files/patch-scripts_airodump-ng-oui-update b/net-mgmt/aircrack-ng/files/patch-scripts_airodump-ng-oui-update
--- a/net-mgmt/aircrack-ng/files/patch-scripts_airodump-ng-oui-update
+++ b/net-mgmt/aircrack-ng/files/patch-scripts_airodump-ng-oui-update
@@ -1,4 +1,4 @@
---- scripts/airodump-ng-oui-update.orig	2015-07-02 23:53:33 UTC
+--- scripts/airodump-ng-oui-update.orig
 +++ scripts/airodump-ng-oui-update
 @@ -44,50 +44,37 @@ if [ ! -d "${OUI_PATH}" ]; then
  	mkdir -p ${OUI_PATH}
@@ -16,45 +16,30 @@
 -	else
 -		${CURL} -L ${OUI_DOWNLOAD_URL} > ${OUI_IEEE} 2>/dev/null
 -	fi
-+# Delete previous partially downloaded file (if the script was aborted)
-+rm -f ${OUI_IEEE} >/dev/null 2>/dev/null
- 
+-
 -	if [ "${?}" -ne 0 ]; then
 -		echo "[*] Error: Failed to download OUI list, aborting..."
 -		exit 1
 -	fi
-+# Download it
-+echo "[*] Downloading IEEE OUI file..."
- 
+-
 -	# Parse the downloaded OUI list
 -	echo "[*] Parsing OUI file..."
-+fetch -o "${OUI_IEEE}" ${OUI_DOWNLOAD_URL}
- 
+-
 -	# Keep the previous file
 -	if [ -f "${OUI_DOWNLOADED}" ]; then
 -		mv ${AIRODUMP_NG_OUI} ${OUI}-old
 -	fi
-+if [ "${?}" -ne 0 ]; then
-+	echo "[*] Error: Failed to download OUI list, aborting..."
-+	exit 1
-+fi
- 
+-
 -	# Parse it
 -	grep "(hex)" ${OUI_IEEE} | sed 's/^[ \t]*//g;s/[ \t]*$//g' > ${AIRODUMP_NG_OUI}
 -	if [ "${?}" -ne 0 ]; then
 -		echo "[*] Error: Failed to parse OUI, aborting..."
 -		exit 1
 -	fi
-+# Parse the downloaded OUI list
-+echo "[*] Parsing OUI file..."
- 
+-
 -	# Cleanup
 -	rm -f ${OUI_IEEE}
-+# Keep the previous file
-+if [ -f "${OUI_DOWNLOADED}" ]; then
-+	mv ${AIRODUMP_NG_OUI} ${OUI}-old
-+fi
- 
+-
 -	echo "[*] Airodump-ng OUI file successfully updated"
 -else
 -	if [ -f "${OUI}" ]; then
@@ -62,13 +47,34 @@
 -	else
 -		echo "[*] Please install curl or wget to install OUI list"
 -	fi
++# Delete previous partially downloaded file (if the script was aborted)
++rm -f ${OUI_IEEE} >/dev/null 2>/dev/null
++
++# Download it
++echo "[*] Downloading IEEE OUI file..."
++
++fetch -o "${OUI_IEEE}" ${OUI_DOWNLOAD_URL}
++
++if [ "${?}" -ne 0 ]; then
++	echo "[*] Error: Failed to download OUI list, aborting..."
+ 	exit 1
+ fi
+ 
++# Parse the downloaded OUI list
++echo "[*] Parsing OUI file..."
++
++# Keep the previous file
++if [ -f "${OUI_DOWNLOADED}" ]; then
++	mv ${AIRODUMP_NG_OUI} ${OUI}-old
++fi
++
 +# Parse it
 +grep "(hex)" ${OUI_IEEE} | sed 's/^[ \t]*//g;s/[ \t]*$//g' > ${AIRODUMP_NG_OUI}
 +if [ "${?}" -ne 0 ]; then
 +	echo "[*] Error: Failed to parse OUI, aborting..."
- 	exit 1
- fi
- 
++	exit 1
++fi
++
 +# Cleanup
 +rm -f ${OUI_IEEE}
 +
