- Chase checksum for sasl-1.5.27-ldap-ssl-filter-mysql-patch4.tgz   author fixed bug in patch but didn't increment version. - Fix problem when openldap v1 is selected. - Bump PORTREVISION
PR:		ports/39800
Submitted by:	maintainer

diff --git a/security/cyrus-sasl/pkg-install b/security/cyrus-sasl/pkg-install
--- a/security/cyrus-sasl/pkg-install
+++ b/security/cyrus-sasl/pkg-install
@@ -67,9 +67,12 @@ create_user() {
 		fi
 		echo "*** Updated user \`${USER}'."
 	fi
-	if ! ${PW} group mod ${USER} -m daemon; then
-		echo "*** can't add user \`${USER}' to group \`${GROUP}'"
-	fi
+# Don't know why we need the daemon user in the cyrus group
+# hopefully this doesn't affect anyone. It's a leftover from
+# the pre-SASL cyrus-imapd server.
+#	if ! ${PW} group mod ${GROUP} -m daemon; then
+#		echo "*** can't add user \`daemon' to group \`${GROUP}'"
+#	fi
 }
 
 create_sasldb() {
