Upgrade to 1.1.

diff --git a/graphics/imlib2-tmp/files/patch-aa b/graphics/imlib2-tmp/files/patch-aa
--- a/graphics/imlib2-tmp/files/patch-aa
+++ b/graphics/imlib2-tmp/files/patch-aa
@@ -1,14 +1,22 @@
---- configure.orig	Tue Feb 17 17:22:20 1998
-+++ configure	Tue Feb 17 17:23:31 1998
-@@ -2462,14 +2462,14 @@
- echo "********** Disabling libpng support ************"
- fi
+--- configure.orig	Fri Feb 20 09:42:49 1998
++++ configure	Tue Mar 10 09:40:36 1998
+@@ -826,6 +826,7 @@
+ # AFS /usr/afsws/bin/install, which mishandles nonexistent args
+ # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
+ # ./install, which can be erroneously created by make from ./install.sh.
++INSTALL='/usr/bin/install -c'
+ echo $ac_n "checking for a BSD compatible install""... $ac_c" 1>&6
+ echo "configure:831: checking for a BSD compatible install" >&5
+ if test -z "$INSTALL"; then
+@@ -2590,14 +2591,14 @@
+     fi
  
--echo $ac_n "checking for TIFFOpen in -ltiff""... $ac_c" 1>&6
--echo "configure:2467: checking for TIFFOpen in -ltiff" >&5
+ 
+-    echo $ac_n "checking for TIFFOpen in -ltiff""... $ac_c" 1>&6
+-echo "configure:2595: checking for TIFFOpen in -ltiff" >&5
 -ac_lib_var=`echo tiff'_'TIFFOpen | sed 'y%./+-%__p_%'`
-+echo $ac_n "checking for TIFFOpen in -ltiff34""... $ac_c" 1>&6
-+echo "configure:2467: checking for TIFFOpen in -ltiff34" >&5
++    echo $ac_n "checking for TIFFOpen in -ltiff34""... $ac_c" 1>&6
++echo "configure:2595: checking for TIFFOpen in -ltiff34" >&5
 +ac_lib_var=`echo tiff34'_'TIFFOpen | sed 'y%./+-%__p_%'`
  if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
    echo $ac_n "(cached) $ac_c" 1>&6
@@ -16,20 +24,56 @@
    ac_save_LIBS="$LIBS"
 -LIBS="-ltiff \
 +LIBS="-ltiff34 \
- -L/usr/lib -L/lib -L/usr/local/lib -L/usr/X11/lib -L/usr/local/X11/lib \
- -L/usr/openwin/lib -lc -lm $LIBS"
+ -L/usr/lib -L/lib -L/usr/local/lib -L/usr/X11/lib -L/usr/X11R6/lib \
+ -L/usr/local/X11/lib -L/usr/openwin/lib -lc -lm $LIBS"
  cat > conftest.$ac_ext <<EOF
-@@ -2500,11 +2500,11 @@
+@@ -2627,13 +2628,13 @@
+ fi
  if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
    echo "$ac_t""yes" 1>&6
-   \
--extras="$extras -DBUILTIN_TIFF"; LIBS="$LIBS -lm -ltiff"
-+extras="$extras -DBUILTIN_TIFF"; LIBS="$LIBS -lm -ltiff34"
+-    ac_tr_lib=HAVE_LIB`echo tiff | sed -e 's/[^a-zA-Z0-9_]/_/g' \
++    ac_tr_lib=HAVE_LIB`echo tiff34 | sed -e 's/[^a-zA-Z0-9_]/_/g' \
+     -e 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'`
+   cat >> confdefs.h <<EOF
+ #define $ac_tr_lib 1
+ EOF
+ 
+-  LIBS="-ltiff $LIBS"
++  LIBS="-ltiff34 $LIBS"
+ 
  else
    echo "$ac_t""no" 1>&6
- \
--echo "********** Disabling libtiff support ************"
-+echo "********** Disabling libtiff34 support ************"
- fi
+@@ -2642,7 +2643,7 @@
+     if test "" != ""; then
+ 	enl_lib_subdir=
+     else
+-	enl_lib_subdir=tiff
++	enl_lib_subdir=tiff34
+     fi
+     enl_cur_var=tiff_TIFFOpen
+     echo $ac_n "checking for tiffio.h""... $ac_c" 1>&6
+@@ -2673,11 +2674,11 @@
+ 	fi
+ 	echo "$ac_t""$enl_tmp_var" 1>&6
+ 	\
+-extras="$extras -DBUILTIN_TIFF"; LIBS="$LIBS -lm -ltiff"
++extras="$extras -DBUILTIN_TIFF"; LIBS="$LIBS -lm -ltiff34"
+     else
+ 	echo "$ac_t""no" 1>&6
+ 	\
+-{ echo "configure: error: ********** Disabling libtiff support ************" 1>&2; exit 1; }
++{ echo "configure: error: ********** Disabling libtiff34 support ************" 1>&2; exit 1; }
+     fi
  
- echo $ac_n "checking for DGifOpenFileName in -lgif""... $ac_c" 1>&6
+ 
+@@ -2788,8 +2789,8 @@
+ if test $GIFTOPPM = "/usr/local/bin/tgatoppm"; then
+   NETPBM_PATH=/usr/local/bin
+ fi
+-if test $GIFTOPPM = "/usr/openwin/bin/tgatoppm"; then
+-  NETPBM_PATH=/usr/openwin/bin
++if test $GIFTOPPM = "/usr/X11R6/bin/tgatoppm"; then
++  NETPBM_PATH=/usr/X11R6/bin
+ fi
+ if test $DJPEG = "/usr/bin/djpeg"; then
+   JPEG_PATH=/usr/bin
