Update to version 1.0. The maintainer forgot to fix patches, I fixed them.
PR: 19834
Submitted by: Eric S <eric@cybernut.com>

diff --git a/security/lsh/files/patch-ac b/security/lsh/files/patch-ac
--- a/security/lsh/files/patch-ac
+++ b/security/lsh/files/patch-ac
@@ -1,5 +1,5 @@
---- src/lsh-authorize.orig	Sun Feb  6 09:39:43 2000
-+++ src/lsh-authorize	Sun Apr 16 13:32:57 2000
+--- src/lsh-authorize.orig	Tue Jul 11 13:56:07 2000
++++ src/lsh-authorize	Tue Jul 11 14:00:58 2000
 @@ -1,4 +1,4 @@
 -#! /bin/sh
 +#!/bin/sh
@@ -15,7 +15,7 @@
      if mkdir $1 2>/dev/null; then
  	echo Created $1
  	chmod $2 $1 || exit 1
-@@ -37,22 +37,27 @@
+@@ -37,26 +37,27 @@
  }
  
  # Create directories
@@ -24,10 +24,14 @@
 +create-dir ~/.lsh 0700
 +create-dir ~/.lsh/authorized_keys_sha1 0700
  
--SEXP_CONV=`PATH=$PATH:. \type -path sexp_conv`
+-if type sexp-conv ; then
+-    SEXP_CONV=sexp_conv
+-else
+-    SEXP_CONV=./sexp_conv
+-fi
 +PATH=$PATH:`dirname $0`
  
--if [ -z $SEXP_CONV ] ; then
+-if ! type $SEXP_CONV ; then
 -    echo "Can't find the sexp_conv program"
 -    exit 1
 -fi
@@ -41,11 +45,11 @@
 +    if [ -f $1 ]; then
 +      hash=`$SEXP_CONV < $1 --once --hash sha1 --raw-hash`
 +      if [ $? = 127 ]; then
-+        echo "Can't find the sexp_conv program"
-+	exit 1
++	echo "Can't find the sexp_conv program"
++       exit 1
 +      fi
 +      if [ -z "$hash" ] ; then
-+	echo $0: File $1 not readable.
++	echo $0: File $1 not readable
 +      else
          $SEXP_CONV < $1 -f canonical --once > ~/.lsh/authorized_keys_sha1/$hash
 +      fi
