- Update to 1.26 - Use OPTIONS for optional dependencies - Change pkg-{,de}install to avoid risk of data loss when upgrading - Patch files instead of regexps in Makefile
added a work around for PR 63293

PR:		63230
Submitted by:	Lars Thegler <lars@thegler.dk> (maintainer)
Reviewed by:	clement

diff --git a/net-mgmt/smokeping/pkg-deinstall b/net-mgmt/smokeping/pkg-deinstall
--- a/net-mgmt/smokeping/pkg-deinstall
+++ b/net-mgmt/smokeping/pkg-deinstall
@@ -3,84 +3,53 @@
 # $FreeBSD$
 #
 
-ask() {
-    local question default answer
-
-    question=$1
-    default=$2
-    if [ -z "${PACKAGE_BUILDING}" ]; then
-	read -p "${question} [${default}]? " answer
-    fi
-    if [ x${answer} = x ]; then
-	answer=${default}
-    fi
-    echo ${answer}
-}
-
-yesno() {
-    local dflt question answer
-
-    question=$1
-    dflt=$2
-    while :; do
-	answer=$(ask "${question}" "${dflt}")
-	case "${answer}" in
-	[Yy]*)		return 0;;
-	[Nn]*)		return 1;;
-	esac
-	echo "Please answer yes or no."
-    done
-}
-
-delete_account() {
-    local u g home
-
-    u=$1
-    g=$2
-    if yesno "Do you want me to remove group \"${g}\"" y; then
-        pw groupdel -n ${g}
-        echo "Done."
-    fi
-    if yesno "Do you want me to remove user \"${u}\"" y; then
-        eval home=~${u}
-        pw userdel -n ${u}
-        echo "Done."
-        if [ -d "${home}" ]; then
-            echo "Please remember to check if there's any unsent mail left"
-            echo "in the home directory \"${home}\""
-        fi
-
-    fi
-}
-
+echo 'Stopping Smokeping daemon.'
 if [ -f ${PKG_PREFIX}/var/smokeping/smokeping.pid ]; then
-    if [ -x ${PKG_PREFIX}/etc/rc.d/smokeping.sh ]; then
-        ${PKG_PREFIX}/etc/rc.d/smokeping.sh stop > /dev/null
-    fi
-    rm ${PKG_PREFIX}/var/smokeping/smokeping.pid
-fi
-
-if [ "$2" != "POST-DEINSTALL" ]; then
-    exit 0
-fi
-
-if [ ! -n "$BATCH" ]; then
-
-    if [ -d ${PKG_PREFIX}/etc/smokeping ]; then
-	echo "You have some custom SmokePing configuration in \"${PKG_PREFIX}/etc/smokeping/\"."
-	if yesno "Would you like me to remove it" y; then
-	    rm -R ${PKG_PREFIX}/etc/smokeping
-	    echo "Done."
+	if [ -x ${PKG_PREFIX}/etc/rc.d/smokeping.sh ]; then
+		${PKG_PREFIX}/etc/rc.d/smokeping.sh stop > /dev/null
 	fi
-    fi
-
-    if [ -d ${PKG_PREFIX}/var/smokeping ]; then
-	echo "You have some collected data in \"${PKG_PREFIX}/var/smokeping/\"."
-	if yesno "Would you like me to remove it" y; then
-	    rm -R ${PKG_PREFIX}/var/smokeping
-	    echo "Done."
-	fi
-    fi
-
-    delete_account smokeping smokeping
+	rm ${PKG_PREFIX}/var/smokeping/smokeping.pid
 fi
+
+case $2 in
+POST-DEINSTALL)
+
+	if [ ! -n "$BATCH" ]; then
+
+		if [ -d ${PKG_PREFIX}/etc/smokeping -o -d ${PKG_PREFIX}/var/smokeping ]; then
+			echo '================================================================='
+			echo
+			echo 'You seem to have some custom config and data.'
+			echo 'The "%%USER%%" user and "%%GROUP%%" group were therefore not deleted.'
+			echo
+			echo 'You may delete them with:'
+			echo
+			echo '  pw groupdel %%GROUP%%'
+			echo '  pw userdel %%USER%%'
+			echo
+			echo 'The config and data can be deleted with:'
+			echo
+			echo "  rm -R ${PKG_PREFIX}/etc/smokeping"
+			echo "  rm -R ${PKG_PREFIX}/var/smokeping"
+			echo
+			echo '================================================================='
+		else
+			if pw groupdel -n %%GROUP%%; then
+				echo 'Removed group "%%GROUP%%".'
+			else
+				echo 'Removing group "%%GROUP%%" failed...'
+				exit 1
+			fi
+
+			if pw userdel -n %%USER%%; then
+				echo 'Removed user "%%USER%%".'
+			else
+				echo 'Removing user "%%USER%%" failed...'
+				exit 1
+			fi
+		fi
+	fi
+
+	exit 0
+	;;
+esac
