Upgrade to 4.50, the latest from UW; which includes better threading support, enhanced rule patterns, role-based smtp server, better character set support, and most importantly, a fix for the DoS recently reported on bugtraq. There are other fixes and improvements as well, check out the release notes for more information.
* Usual round of patch re-generation
* Add a makefile.bsf fix and a patch for pine/strings.c not being able to
find utf8.h

diff --git a/mail/pine4/files/patch-al b/mail/pine4/files/patch-al
--- a/mail/pine4/files/patch-al
+++ b/mail/pine4/files/patch-al
@@ -1,81 +1,81 @@
-*** build.orig	Wed Oct 31 16:01:04 2001
---- build	Sun Dec  2 23:17:05 2001
+*** build.orig	Tue Nov  5 18:17:56 2002
+--- build	Tue Nov 26 03:16:11 2002
 ***************
-*** 332,351 ****
+*** 350,411 ****
   	  echo "Including SSL functionality"
   	fi
   
-!         if [ -s c-client ] ; then rm -f c-client ; fi
-!         ln -s imap/c-client c-client
-!         if [ -s mtest    ] ; then rm -f mtest    ; fi
-!         ln -s imap/mtest mtest
-!         if [ -s imapd    ] ; then rm -f imapd    ; fi
-!         ln -s imap/imapd imapd
-!         if [ -s ipopd    ] ; then rm -f ipopd    ; fi
-!         ln -s imap/ipopd ipopd
-!         echo "Making c-client library, imapd, and ipopd"
-! 	echo $S1 $S2 $S3 $S4 $K1 > imap/SPECIALS
-!         cd $PHOME/imap
-!         eval echo eval make "$makeargs" "$SSL" "SPECIALS=`cat SPECIALS`" "$K2" $ccltarg
-!         eval make "$makeargs" "$SSL" "SPECIALS=`cat SPECIALS`" "$K2" $ccltarg
-!         echo ''
-  
+-         if [ -s c-client ] ; then rm -f c-client ; fi
+-         ln -s imap/c-client c-client
+-         if [ -s mtest    ] ; then rm -f mtest    ; fi
+-         ln -s imap/mtest mtest
+-         if [ -s mailutil ] ; then rm -f mailutil ; fi
+-         ln -s imap/mailutil mailutil
+-         if [ -s imapd    ] ; then rm -f imapd    ; fi
+-         ln -s imap/imapd imapd
+-         if [ -s ipopd    ] ; then rm -f ipopd    ; fi
+-         ln -s imap/ipopd ipopd
+-         echo "Making c-client library, imapd, and ipopd"
+- 	echo $S1 $S2 $S3 $S4 $K1 > imap/SPECIALS
+-         cd "$PHOME/imap"
+- # This "touch" tells the IMAP make not to give any warnings about IESG compliance.
+- 	if [ "$NOSSL" = "1" -o "$SSL" != "none" ] ; then touch ssl$SSL ; fi
+- 	if [ "$NOSSL" != "1" -a "$SSL" = "none" -a ! -f sslnone ]
+- 	then
+- 	   echo "+-----------------------------------------------------------+"
+- 	   echo "| It appears that you do not have OpenSSL or equivalent     |"
+- 	   echo "| installed on this system.                                 |"
+- 	   echo "|                                                           |"
+- 	   echo "| Building PINE without SSL support will possibly introduce |"
+- 	   echo "| problems when communicating with IMAP, POP3, or SMTP      |"
+- 	   echo "| servers that require TLS or SSL authentication.           |"
+- 	   echo "| In addition, your password may be vulnerable to a         |"
+- 	   echo "| snooping attack since it may be sent over the network     |"
+- 	   echo "| unencrypted.                                              |"
+- 	   echo "+-----------------------------------------------------------+"
+- 	   echo ""
+- 	   echo "Do you want to continue this build anyway? Type y or n please:"
+- 	   read ans
+- 	   case "$ans" in
+- 	       y)   echo "Building without SSL ..."
+- 		    touch sslnone
+- 		    ;;
+- 
+- 	       *)   echo "Terminating build"
+- 		    exit 1
+- 		    ;;
+- 	   esac
+- 	fi
+-         eval echo eval make "$makeargs" "SSLTYPE=$SSL" "SPECIALS=`cat SPECIALS`" "$K2" $ccltarg
+-         eval make "$makeargs" "SSLTYPE=$SSL" "SPECIALS=`cat SPECIALS`" "$K2" $ccltarg
+- 	if [ $? != "0" ]
+- 	then
+- 	    echo "+---------------------------------------------+"
+- 	    echo "| Problems building c-client                  |"
+- 	    echo "|                                             |"
+- 	    echo "| Please check the output above for a         |"
+- 	    echo "| possible explanation for this failure       |"
+- 	    echo "+---------------------------------------------+"
+- 	    echo ""
+- 	    exit $?
+- 	fi
+-         echo ''
+- 
           echo "Making Pico and Pilot"
-          cd $PHOME/pico
---- 332,351 ----
-  	  echo "Including SSL functionality"
-  	fi
-  
-! #        if [ -s c-client ] ; then rm -f c-client ; fi
-! #        ln -s imap/c-client c-client
-! #        if [ -s mtest    ] ; then rm -f mtest    ; fi
-! #        ln -s imap/mtest mtest
-! #        if [ -s imapd    ] ; then rm -f imapd    ; fi
-! #        ln -s imap/imapd imapd
-! #        if [ -s ipopd    ] ; then rm -f ipopd    ; fi
-! #        ln -s imap/ipopd ipopd
-! #        echo "Making c-client library, imapd, and ipopd"
-! #	echo $S1 $S2 $S3 $S4 $K1 > imap/SPECIALS
-! #        cd $PHOME/imap
-! #        eval echo eval make "$makeargs" "$SSL" "SPECIALS=`cat SPECIALS`" "$K2" $ccltarg
-! #        eval make "$makeargs" "$SSL" "SPECIALS=`cat SPECIALS`" "$K2" $ccltarg
-! #        echo ''
-  
-          echo "Making Pico and Pilot"
-          cd $PHOME/pico
+          cd "$PHOME/pico"
+          eval echo make "$makeargs" -f makefile.$picotarg
+--- 350,355 ----
 ***************
-*** 362,379 ****
-          cd $PHOME/bin
-          rm -f pine mtest imapd pico pilot rpload rpdump ipop2d ipop3d
-          if [ -s ../pine/pine ] ;      then ln ../pine/pine  pine      ; fi
-!         if [ -s ../mtest/mtest ] ;    then ln ../mtest/mtest mtest    ; fi
-!         if [ -s ../imapd/imapd ] ;    then ln ../imapd/imapd imapd    ; fi
-!         if [ -s ../ipopd/ipop2d ] ;   then ln ../ipopd/ipop2d ipop2d  ; fi
-!         if [ -s ../ipopd/ipop3d ] ;   then ln ../ipopd/ipop3d ipop3d  ; fi
-          if [ -s ../pico/pico ] ;      then ln ../pico/pico pico       ; fi
-          if [ -s ../pico/pilot ] ;     then ln ../pico/pilot pilot     ; fi
-!         if [ -s ../pine/rpload ] ;    then ln ../pine/rpload rpload   ; fi
-!         if [ -s ../pine/rpdump ] ;    then ln ../pine/rpdump rpdump   ; fi
-          cd $PHOME
+*** 435,441 ****
+          cd "$PHOME"
           echo ''
           echo "Links to executables are in bin directory:"
-!         size bin/pine bin/mtest bin/imapd bin/pico bin/pilot bin/rpdump bin/rpload bin/ipop2d bin/ipop3d
+!         size bin/pine bin/mtest bin/imapd bin/pico bin/pilot bin/rpdump bin/rpload bin/mailutil bin/ipop2d bin/ipop3d
   	case $maketarg in
   	    mnt)    echo "Fixing stacksizes ..."
   		    fixstk 64K bin/pine bin/pico bin/imapd bin/mtest bin/pilot
---- 362,379 ----
-          cd $PHOME/bin
-          rm -f pine mtest imapd pico pilot rpload rpdump ipop2d ipop3d
-          if [ -s ../pine/pine ] ;      then ln ../pine/pine  pine      ; fi
-! #        if [ -s ../mtest/mtest ] ;    then ln ../mtest/mtest mtest    ; fi
-! #        if [ -s ../imapd/imapd ] ;    then ln ../imapd/imapd imapd    ; fi
-! #        if [ -s ../ipopd/ipop2d ] ;   then ln ../ipopd/ipop2d ipop2d  ; fi
-! #        if [ -s ../ipopd/ipop3d ] ;   then ln ../ipopd/ipop3d ipop3d  ; fi
-          if [ -s ../pico/pico ] ;      then ln ../pico/pico pico       ; fi
-          if [ -s ../pico/pilot ] ;     then ln ../pico/pilot pilot     ; fi
-! #        if [ -s ../pine/rpload ] ;    then ln ../pine/rpload rpload   ; fi
-! #        if [ -s ../pine/rpdump ] ;    then ln ../pine/rpdump rpdump   ; fi
-          cd $PHOME
+--- 379,385 ----
+          cd "$PHOME"
           echo ''
           echo "Links to executables are in bin directory:"
 !         size bin/pine bin/pico bin/pilot
@@ -83,35 +83,25 @@
   	    mnt)    echo "Fixing stacksizes ..."
   		    fixstk 64K bin/pine bin/pico bin/imapd bin/mtest bin/pilot
 ***************
-*** 410,424 ****
-  
-      clean) # This only sort of works 
-          rm -f c-client mtest imapd ipopd
-!         echo "Cleaning c-client and imapd"
-! 	cd $PHOME/imap
-! 	make clean
+*** 469,478 ****
+  	rm -f sslnopwd sslunix.nopwd sslsco.nopwd sslunix sslsco sslnone
           echo "Cleaning Pine"
-          cd $PHOME/pine
+          cd "$PHOME/pine"
 !         make -f makefile.ult clean
           echo "Cleaning pico"
-          cd $PHOME/pico
+          cd "$PHOME/pico"
 !         make $makeargs -f makefile.ult clean
           echo "Done"
-          cd $PHOME
+          cd "$PHOME"
           ;;
---- 410,424 ----
-  
-      clean) # This only sort of works 
-          rm -f c-client mtest imapd ipopd
-! #        echo "Cleaning c-client and imapd"
-! #	cd $PHOME/imap
-! #	make clean
+--- 413,422 ----
+  	rm -f sslnopwd sslunix.nopwd sslsco.nopwd sslunix sslsco sslnone
           echo "Cleaning Pine"
-          cd $PHOME/pine
+          cd "$PHOME/pine"
 !         make -f makefile.bsf clean
           echo "Cleaning pico"
-          cd $PHOME/pico
+          cd "$PHOME/pico"
 !         make $makeargs -f makefile.bsf clean
           echo "Done"
-          cd $PHOME
+          cd "$PHOME"
           ;;
