Provide a master site for this, since the original one has vanished. Partially update it, since no other ports use GTK+ 1.0 or GDK 1.0. Take maintainership. Mark BROKEN. More patches will follow.
Approved by:	will

diff --git a/x11-fm/workplace/files/patch-aa b/x11-fm/workplace/files/patch-aa
--- a/x11-fm/workplace/files/patch-aa
+++ b/x11-fm/workplace/files/patch-aa
@@ -1,16 +1,30 @@
---- configure.in.orig	Fri Jan 22 16:21:28 1999
-+++ configure.in	Fri Jan 22 16:22:59 1999
-@@ -37,10 +37,10 @@
+--- configure.orig	Wed Apr  8 02:48:44 1998
++++ configure	Thu Oct  5 02:42:18 2000
+@@ -1807,14 +1807,14 @@
  
          LDFLAGS="$saved_ldflags $X_LDFLAGS $X_LIBS"
  
--        AC_CHECK_LIB(gtk, gtk_widget_new,
--                X_LIBS="$X_LIBS -lgtk -lgdk -lglib $x_libs -lm",
-+        AC_CHECK_LIB(gtk10, gtk_widget_new,
-+                X_LIBS="$X_LIBS -lgtk10 -lgdk10 -lglib10 $x_libs -lm",
-                 [AC_MSG_ERROR(Can not link with gtk/gdk/glib)],
--                -lgdk -lglib $x_libs -lm)
-+                -lgdk10 -lglib10 $x_libs -lm)
- 
-         CFLAGS="$saved_cflags"
-         LDFLAGS="$saved_ldflags"
+-        echo $ac_n "checking for gtk_widget_new in -lgtk""... $ac_c" 1>&6
+-echo "configure:1812: checking for gtk_widget_new in -lgtk" >&5
+-ac_lib_var=`echo gtk'_'gtk_widget_new | sed 'y%./+-%__p_%'`
++        echo $ac_n "checking for gtk_widget_new in -lgtk12""... $ac_c" 1>&6
++echo "configure:1812: checking for gtk_widget_new in -lgtk12" >&5
++ac_lib_var=`echo gtk12'_'gtk_widget_new | sed 'y%./+-%__p_%'`
+ if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+   echo $ac_n "(cached) $ac_c" 1>&6
+ else
+   ac_save_LIBS="$LIBS"
+-LIBS="-lgtk -lgdk -lglib $x_libs -lm $LIBS"
++LIBS="-lgtk12 -lgdk12 -lglib12 $x_libs -lm $LIBS"
+ cat > conftest.$ac_ext <<EOF
+ #line 1820 "configure"
+ #include "confdefs.h"
+@@ -1842,7 +1842,7 @@
+ fi
+ if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
+   echo "$ac_t""yes" 1>&6
+-  X_LIBS="$X_LIBS -lgtk -lgdk -lglib $x_libs -lm"
++  X_LIBS="$X_LIBS -lgtk12 -lgdk12 -lglib12 $x_libs -lm"
+ else
+   echo "$ac_t""no" 1>&6
+ { echo "configure: error: Can not link with gtk/gdk/glib" 1>&2; exit 1; }
