Try to fix on 4.x.
Since I'm there, switch to USE_LDCONFIG.

Reported by:	pointyhat via Kris

diff --git a/net/mpich2/files/patch-configure b/net/mpich2/files/patch-configure
--- a/net/mpich2/files/patch-configure
+++ b/net/mpich2/files/patch-configure
@@ -1,6 +1,6 @@
---- configure.orig	Wed Nov 23 19:41:50 2005
-+++ configure	Mon Jul 17 00:46:50 2006
-@@ -24963,8 +24963,8 @@
+--- configure.orig	Sun Jul 30 20:04:37 2006
++++ configure	Tue Aug  8 16:50:50 2006
+@@ -28147,8 +28147,8 @@
  rm -f conftest.err conftest.$ac_objext \
        conftest$ac_exeext conftest.$ac_ext
  if test "$ac_cv_search_pthread_key_create" = no; then
@@ -11,3 +11,12 @@
      cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
+@@ -28192,7 +28192,7 @@
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  ac_cv_search_pthread_key_create="-l$ac_lib"
++  ac_cv_search_pthread_key_create="$ac_lib"
+ break
+ else
+   echo "$as_me: failed program was:" >&5
