Update to 0.8, and fix a problem where policy updates were not processed dynamically.

diff --git a/sysutils/policykit/files/patch-configure b/sysutils/policykit/files/patch-configure
--- a/sysutils/policykit/files/patch-configure
+++ b/sysutils/policykit/files/patch-configure
@@ -1,9 +1,9 @@
---- configure.bak	2007-11-30 20:42:54.000000000 -0500
-+++ configure	2007-12-23 00:35:53.000000000 -0500
-@@ -929,10 +929,16 @@ OS_TYPE_GENTOO_TRUE
- OS_TYPE_GENTOO_FALSE
- OS_TYPE_PARDUS_TRUE
+--- configure.orig	2008-04-18 01:07:38.000000000 -0400
++++ configure	2008-04-18 01:07:47.000000000 -0400
+@@ -938,10 +938,16 @@ OS_TYPE_PARDUS_TRUE
  OS_TYPE_PARDUS_FALSE
+ OS_TYPE_SALARIS_TRUE
+ OS_TYPE_SALARIS_FALSE
 +OS_TYPE_FREEBSD_TRUE
 +OS_TYPE_FREEBSD_FALSE
  PAM_FILE_INCLUDE_AUTH
@@ -17,186 +17,214 @@
  INTLTOOL_DESKTOP_RULE
  INTLTOOL_DIRECTORY_RULE
  INTLTOOL_KEYS_RULE
-@@ -6544,7 +6550,7 @@ ia64-*-hpux*)
+@@ -6555,7 +6561,7 @@ ia64-*-hpux*)
    ;;
  *-*-irix6*)
    # Find out which ABI we are using.
--  echo '#line 6547 "configure"' > conftest.$ac_ext
-+  echo '#line 6553 "configure"' > conftest.$ac_ext
+-  echo '#line 6558 "configure"' > conftest.$ac_ext
++  echo '#line 6564 "configure"' > conftest.$ac_ext
    if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
    (eval $ac_compile) 2>&5
    ac_status=$?
-@@ -8882,11 +8888,11 @@ else
+@@ -8893,11 +8899,11 @@ else
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:8885: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:8891: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:8896: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:8902: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>conftest.err)
     ac_status=$?
     cat conftest.err >&5
--   echo "$as_me:8889: \$? = $ac_status" >&5
-+   echo "$as_me:8895: \$? = $ac_status" >&5
+-   echo "$as_me:8900: \$? = $ac_status" >&5
++   echo "$as_me:8906: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s "$ac_outfile"; then
       # The compiler can only warn and ignore the option if not recognized
       # So say no if there are warnings other than the usual output.
-@@ -9172,11 +9178,11 @@ else
+@@ -9183,11 +9189,11 @@ else
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:9175: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:9181: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:9186: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:9192: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>conftest.err)
     ac_status=$?
     cat conftest.err >&5
--   echo "$as_me:9179: \$? = $ac_status" >&5
-+   echo "$as_me:9185: \$? = $ac_status" >&5
+-   echo "$as_me:9190: \$? = $ac_status" >&5
++   echo "$as_me:9196: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s "$ac_outfile"; then
       # The compiler can only warn and ignore the option if not recognized
       # So say no if there are warnings other than the usual output.
-@@ -9276,11 +9282,11 @@ else
+@@ -9287,11 +9293,11 @@ else
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:9279: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:9285: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:9290: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:9296: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>out/conftest.err)
     ac_status=$?
     cat out/conftest.err >&5
--   echo "$as_me:9283: \$? = $ac_status" >&5
-+   echo "$as_me:9289: \$? = $ac_status" >&5
+-   echo "$as_me:9294: \$? = $ac_status" >&5
++   echo "$as_me:9300: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s out/conftest2.$ac_objext
     then
       # The compiler can only warn and ignore the option if not recognized
-@@ -11627,7 +11633,7 @@ else
+@@ -11638,7 +11644,7 @@ else
    lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
    lt_status=$lt_dlunknown
    cat > conftest.$ac_ext <<EOF
--#line 11630 "configure"
-+#line 11636 "configure"
+-#line 11641 "configure"
++#line 11647 "configure"
  #include "confdefs.h"
  
  #if HAVE_DLFCN_H
-@@ -11727,7 +11733,7 @@ else
+@@ -11738,7 +11744,7 @@ else
    lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
    lt_status=$lt_dlunknown
    cat > conftest.$ac_ext <<EOF
--#line 11730 "configure"
-+#line 11736 "configure"
+-#line 11741 "configure"
++#line 11747 "configure"
  #include "confdefs.h"
  
  #if HAVE_DLFCN_H
-@@ -14147,11 +14153,11 @@ else
+@@ -14158,11 +14164,11 @@ else
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:14150: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:14156: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:14161: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:14167: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>conftest.err)
     ac_status=$?
     cat conftest.err >&5
--   echo "$as_me:14154: \$? = $ac_status" >&5
-+   echo "$as_me:14160: \$? = $ac_status" >&5
+-   echo "$as_me:14165: \$? = $ac_status" >&5
++   echo "$as_me:14171: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s "$ac_outfile"; then
       # The compiler can only warn and ignore the option if not recognized
       # So say no if there are warnings other than the usual output.
-@@ -14251,11 +14257,11 @@ else
+@@ -14262,11 +14268,11 @@ else
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:14254: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:14260: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:14265: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:14271: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>out/conftest.err)
     ac_status=$?
     cat out/conftest.err >&5
--   echo "$as_me:14258: \$? = $ac_status" >&5
-+   echo "$as_me:14264: \$? = $ac_status" >&5
+-   echo "$as_me:14269: \$? = $ac_status" >&5
++   echo "$as_me:14275: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s out/conftest2.$ac_objext
     then
       # The compiler can only warn and ignore the option if not recognized
-@@ -15815,11 +15821,11 @@ else
+@@ -15826,11 +15832,11 @@ else
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:15818: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:15824: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:15829: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:15835: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>conftest.err)
     ac_status=$?
     cat conftest.err >&5
--   echo "$as_me:15822: \$? = $ac_status" >&5
-+   echo "$as_me:15828: \$? = $ac_status" >&5
+-   echo "$as_me:15833: \$? = $ac_status" >&5
++   echo "$as_me:15839: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s "$ac_outfile"; then
       # The compiler can only warn and ignore the option if not recognized
       # So say no if there are warnings other than the usual output.
-@@ -15919,11 +15925,11 @@ else
+@@ -15930,11 +15936,11 @@ else
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:15922: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:15928: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:15933: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:15939: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>out/conftest.err)
     ac_status=$?
     cat out/conftest.err >&5
--   echo "$as_me:15926: \$? = $ac_status" >&5
-+   echo "$as_me:15932: \$? = $ac_status" >&5
+-   echo "$as_me:15937: \$? = $ac_status" >&5
++   echo "$as_me:15943: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s out/conftest2.$ac_objext
     then
       # The compiler can only warn and ignore the option if not recognized
-@@ -18108,11 +18114,11 @@ else
+@@ -18119,11 +18125,11 @@ else
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:18111: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:18117: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:18122: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:18128: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>conftest.err)
     ac_status=$?
     cat conftest.err >&5
--   echo "$as_me:18115: \$? = $ac_status" >&5
-+   echo "$as_me:18121: \$? = $ac_status" >&5
+-   echo "$as_me:18126: \$? = $ac_status" >&5
++   echo "$as_me:18132: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s "$ac_outfile"; then
       # The compiler can only warn and ignore the option if not recognized
       # So say no if there are warnings other than the usual output.
-@@ -18398,11 +18404,11 @@ else
+@@ -18409,11 +18415,11 @@ else
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:18401: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:18407: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:18412: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:18418: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>conftest.err)
     ac_status=$?
     cat conftest.err >&5
--   echo "$as_me:18405: \$? = $ac_status" >&5
-+   echo "$as_me:18411: \$? = $ac_status" >&5
+-   echo "$as_me:18416: \$? = $ac_status" >&5
++   echo "$as_me:18422: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s "$ac_outfile"; then
       # The compiler can only warn and ignore the option if not recognized
       # So say no if there are warnings other than the usual output.
-@@ -18502,11 +18508,11 @@ else
+@@ -18513,11 +18519,11 @@ else
     -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
     -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
     -e 's:$: $lt_compiler_flag:'`
--   (eval echo "\"\$as_me:18505: $lt_compile\"" >&5)
-+   (eval echo "\"\$as_me:18511: $lt_compile\"" >&5)
+-   (eval echo "\"\$as_me:18516: $lt_compile\"" >&5)
++   (eval echo "\"\$as_me:18522: $lt_compile\"" >&5)
     (eval "$lt_compile" 2>out/conftest.err)
     ac_status=$?
     cat out/conftest.err >&5
--   echo "$as_me:18509: \$? = $ac_status" >&5
-+   echo "$as_me:18515: \$? = $ac_status" >&5
+-   echo "$as_me:18520: \$? = $ac_status" >&5
++   echo "$as_me:18526: \$? = $ac_status" >&5
     if (exit $ac_status) && test -s out/conftest2.$ac_objext
     then
       # The compiler can only warn and ignore the option if not recognized
-@@ -22501,7 +22507,9 @@ fi
+@@ -22510,7 +22516,11 @@ fi
  
  
  
 -for ac_func in getgrouplist
 +
 +
-+for ac_func in getgrouplist clearenv strndup getline readdir64
++
++
++for ac_func in getgrouplist readdir64
  do
  as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
  { echo "$as_me:$LINENO: checking for $ac_func" >&5
-@@ -24087,6 +24095,14 @@ else
-   OS_TYPE_PARDUS_FALSE=
+@@ -23072,13 +23082,13 @@ echo "${ECHO_T}$ac_cv_func_pthread_creat
+ if test $ac_cv_func_pthread_create = yes; then
+   :
+ else
+-  { echo "$as_me:$LINENO: checking for pthread_create in -pthread" >&5
+-echo $ECHO_N "checking for pthread_create in -pthread... $ECHO_C" >&6; }
++  { echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
++echo $ECHO_N "checking for pthread_create in -lpthread... $ECHO_C" >&6; }
+ if test "${ac_cv_lib_pthread_pthread_create+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+-LIBS="-pthread  $LIBS"
++LIBS="-lpthread  $LIBS"
+ cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+ _ACEOF
+@@ -23134,7 +23144,7 @@ fi
+ { echo "$as_me:$LINENO: result: $ac_cv_lib_pthread_pthread_create" >&5
+ echo "${ECHO_T}$ac_cv_lib_pthread_pthread_create" >&6; }
+ if test $ac_cv_lib_pthread_pthread_create = yes; then
+-  SELINUX_THREAD_LIBS="-pthread"
++  SELINUX_THREAD_LIBS="-lpthread"
+ fi
+ 
+ fi
+@@ -24202,6 +24212,14 @@ else
+   OS_TYPE_SALARIS_FALSE=
  fi
  
 + if test x$with_os_type = xfreebsd; then
@@ -210,7 +238,7 @@
  
  
  # Check whether --with-pam-include was given.
-@@ -24111,6 +24127,11 @@ elif test x$with_os_type = xsuse ; then
+@@ -24226,6 +24244,11 @@ elif test x$with_os_type = xsuse -o x$wi
     PAM_FILE_INCLUDE_ACCOUNT=common-account
     PAM_FILE_INCLUDE_PASSWORD=common-password
     PAM_FILE_INCLUDE_SESSION=common-session
@@ -222,10 +250,19 @@
  else
     PAM_FILE_INCLUDE_AUTH=system-auth
     PAM_FILE_INCLUDE_ACCOUNT=system-auth
-@@ -24143,6 +24164,430 @@ cat >>confdefs.h <<_ACEOF
+@@ -24268,7 +24291,438 @@ cat >>confdefs.h <<\_ACEOF
  _ACEOF
  
- 
+ 	;;
++  *freebsd*)
++
++cat >>confdefs.h <<\_ACEOF
++#define HAVE_FREEBSD 1
++_ACEOF
++
++	;;
++esac
++
 +have_inotify=no
 +
 +for ac_header in linux/inotify.h
@@ -595,7 +632,7 @@
 +case "(($ac_try" in
 +  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
 +  *) ac_try_echo=$ac_try;;
-+esac
+ esac
 +eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 +  (eval "$ac_link") 2>conftest.er1
 +  ac_status=$?
@@ -649,11 +686,41 @@
 +_ACEOF
 +
 +fi
-+
+ 
  # ********************
  # Internationalisation
- # ********************
-@@ -26232,6 +26677,27 @@ echo "$as_me: error: conditional \"OS_TY
+@@ -24678,12 +25132,12 @@ echo "${ECHO_T}$ac_cv_func_bind_textdoma
+ if test $ac_cv_func_bind_textdomain_codeset = yes; then
+   DATADIRNAME=share
+ else
+-  DATADIRNAME=share
++  DATADIRNAME=lib
+ fi
+ 
+     ;;
+     *)
+-    DATADIRNAME=share
++    DATADIRNAME=lib
+     ;;
+     esac
+ fi
+@@ -26102,13 +26556,13 @@ if test $ac_cv_func_bind_textdomain_code
+                DATADIRNAME=share
+ else
+   CATOBJEXT=.mo
+-               DATADIRNAME=share
++               DATADIRNAME=lib
+ fi
+ 
+ 	    ;;
+ 	    *)
+ 	    CATOBJEXT=.mo
+-            DATADIRNAME=share
++            DATADIRNAME=lib
+ 	    ;;
+ 	    esac
+ fi
+@@ -26522,6 +26976,27 @@ echo "$as_me: error: conditional \"OS_TY
  Usually this means the macro was only invoked conditionally." >&2;}
     { (exit 1); exit 1; }; }
  fi
@@ -681,10 +748,10 @@
  
    ac_config_commands="$ac_config_commands po/stamp-it"
  
-@@ -26995,10 +27461,16 @@ OS_TYPE_GENTOO_TRUE!$OS_TYPE_GENTOO_TRUE
- OS_TYPE_GENTOO_FALSE!$OS_TYPE_GENTOO_FALSE$ac_delim
- OS_TYPE_PARDUS_TRUE!$OS_TYPE_PARDUS_TRUE$ac_delim
+@@ -27294,10 +27769,16 @@ OS_TYPE_PARDUS_TRUE!$OS_TYPE_PARDUS_TRUE
  OS_TYPE_PARDUS_FALSE!$OS_TYPE_PARDUS_FALSE$ac_delim
+ OS_TYPE_SALARIS_TRUE!$OS_TYPE_SALARIS_TRUE$ac_delim
+ OS_TYPE_SALARIS_FALSE!$OS_TYPE_SALARIS_FALSE$ac_delim
 +OS_TYPE_FREEBSD_TRUE!$OS_TYPE_FREEBSD_TRUE$ac_delim
 +OS_TYPE_FREEBSD_FALSE!$OS_TYPE_FREEBSD_FALSE$ac_delim
  PAM_FILE_INCLUDE_AUTH!$PAM_FILE_INCLUDE_AUTH$ac_delim
@@ -698,38 +765,38 @@
  INTLTOOL_DESKTOP_RULE!$INTLTOOL_DESKTOP_RULE$ac_delim
  INTLTOOL_DIRECTORY_RULE!$INTLTOOL_DIRECTORY_RULE$ac_delim
  INTLTOOL_KEYS_RULE!$INTLTOOL_KEYS_RULE$ac_delim
-@@ -27022,12 +27494,6 @@ INTLTOOL_EXTRACT!$INTLTOOL_EXTRACT$ac_de
- INTLTOOL_MERGE!$INTLTOOL_MERGE$ac_delim
- INTLTOOL_UPDATE!$INTLTOOL_UPDATE$ac_delim
- INTLTOOL_PERL!$INTLTOOL_PERL$ac_delim
--ALL_LINGUAS!$ALL_LINGUAS$ac_delim
--DATADIRNAME!$DATADIRNAME$ac_delim
--GETTEXT_PACKAGE!$GETTEXT_PACKAGE$ac_delim
--USE_NLS!$USE_NLS$ac_delim
--MSGFMT!$MSGFMT$ac_delim
--MSGFMT_OPTS!$MSGFMT_OPTS$ac_delim
+@@ -27312,12 +27793,6 @@ INTLTOOL_XAM_RULE!$INTLTOOL_XAM_RULE$ac_
+ INTLTOOL_KBD_RULE!$INTLTOOL_KBD_RULE$ac_delim
+ INTLTOOL_XML_RULE!$INTLTOOL_XML_RULE$ac_delim
+ INTLTOOL_XML_NOMERGE_RULE!$INTLTOOL_XML_NOMERGE_RULE$ac_delim
+-INTLTOOL_CAVES_RULE!$INTLTOOL_CAVES_RULE$ac_delim
+-INTLTOOL_SCHEMAS_RULE!$INTLTOOL_SCHEMAS_RULE$ac_delim
+-INTLTOOL_THEME_RULE!$INTLTOOL_THEME_RULE$ac_delim
+-INTLTOOL_SERVICE_RULE!$INTLTOOL_SERVICE_RULE$ac_delim
+-INTLTOOL_POLICY_RULE!$INTLTOOL_POLICY_RULE$ac_delim
+-XGETTEXT!$XGETTEXT$ac_delim
  _ACEOF
  
    if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
-@@ -27069,6 +27535,12 @@ _ACEOF
+@@ -27359,6 +27834,12 @@ _ACEOF
  ac_delim='%!_!# '
  for ac_last_try in false false false false false :; do
    cat >conf$$subs.sed <<_ACEOF
-+ALL_LINGUAS!$ALL_LINGUAS$ac_delim
-+DATADIRNAME!$DATADIRNAME$ac_delim
-+GETTEXT_PACKAGE!$GETTEXT_PACKAGE$ac_delim
-+USE_NLS!$USE_NLS$ac_delim
-+MSGFMT!$MSGFMT$ac_delim
-+MSGFMT_OPTS!$MSGFMT_OPTS$ac_delim
- GMSGFMT!$GMSGFMT$ac_delim
- XGETTEXT!$XGETTEXT$ac_delim
- CATALOGS!$CATALOGS$ac_delim
-@@ -27085,7 +27557,7 @@ LIBOBJS!$LIBOBJS$ac_delim
++INTLTOOL_CAVES_RULE!$INTLTOOL_CAVES_RULE$ac_delim
++INTLTOOL_SCHEMAS_RULE!$INTLTOOL_SCHEMAS_RULE$ac_delim
++INTLTOOL_THEME_RULE!$INTLTOOL_THEME_RULE$ac_delim
++INTLTOOL_SERVICE_RULE!$INTLTOOL_SERVICE_RULE$ac_delim
++INTLTOOL_POLICY_RULE!$INTLTOOL_POLICY_RULE$ac_delim
++XGETTEXT!$XGETTEXT$ac_delim
+ MSGMERGE!$MSGMERGE$ac_delim
+ MSGFMT!$MSGFMT$ac_delim
+ INTLTOOL_EXTRACT!$INTLTOOL_EXTRACT$ac_delim
+@@ -27385,7 +27866,7 @@ LIBOBJS!$LIBOBJS$ac_delim
  LTLIBOBJS!$LTLIBOBJS$ac_delim
  _ACEOF
  
--  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 14; then
-+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 20; then
+-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 24; then
++  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 30; then
      break
    elif $ac_last_try; then
      { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
