o update to 0.50 pre 1 o add script to "autodetect" some machine features such as 3DNow! o it is no longer limitted to i386 arch (e.g., alpha, hurray :) o make it CFLAGS safe o add several WITH{,OUT} options o depend on win32-codecs as of rev 1.12 win32-codecs/Makefile   instead of mplayer-codecs o Makefile style: rearrange the file a bit to make it ports' style   compliant (easier to maintain) o simplify targets with for/endfor constructs in post-install o due to new features, update: COMMENT, DESCR, PKGMESSAGE o fix all URI to include a trailing / o support NOPORTDOCS in PLIST
Submitted by:	MAINTAINER et al

diff --git a/multimedia/mplayerxp/files/patch-ad b/multimedia/mplayerxp/files/patch-ad
--- a/multimedia/mplayerxp/files/patch-ad
+++ b/multimedia/mplayerxp/files/patch-ad
@@ -1,104 +1,96 @@
-*** configure.orig	Fri Jul  6 23:00:22 2001
---- configure	Sat Aug 18 22:25:58 2001
-***************
-*** 181,187 ****
-  
-  system_name=`uname -s 2>&1`
-  if [ "$system_name" = "FreeBSD" ]; then
-! _archlibs="-rdynamic -pthread"
-  else
-  _archlibs="-ldl -lpthread"
-  fi
---- 181,187 ----
-  
-  system_name=`uname -s 2>&1`
-  if [ "$system_name" = "FreeBSD" ]; then
-! _archlibs="-rdynamic ${PTHREAD_LIBS}"
-  else
-  _archlibs="-ldl -lpthread"
-  fi
-***************
-*** 587,593 ****
-  $_cc $_extraincdir $_extralibdir $TMPC -o $TMPO -lvgagl -lvga > /dev/null 2>&1 && _svga=yes
-  
-  if [ "$system_name" = "FreeBSD" ]; then
-! $_cc $TMPC -o $TMPO -pthread > /dev/null 2>&1 || \
-   { echo "Lib pthread not found."; rm -f $TMPC $TMPO $TMPS ; exit 1; }
-  else
-  $_cc $TMPC -o $TMPO -lpthread > /dev/null 2>&1 || \
---- 587,593 ----
-  $_cc $_extraincdir $_extralibdir $TMPC -o $TMPO -lvgagl -lvga > /dev/null 2>&1 && _svga=yes
-  
-  if [ "$system_name" = "FreeBSD" ]; then
-! $_cc $TMPC -o $TMPO ${PTHREAD_LIBS} > /dev/null 2>&1 || \
-   { echo "Lib pthread not found."; rm -f $TMPC $TMPO $TMPS ; exit 1; }
-  else
-  $_cc $TMPC -o $TMPO -lpthread > /dev/null 2>&1 || \
-***************
-*** 669,675 ****
-  $_cc $TMPC -o $TMPO $_x11libdir -lX11 -lXext -lXxf86vm $_socklib > /dev/null 2>&1 && _vm=yes
-  
-  if [ "$system_name" = "FreeBSD" ]; then
-! $_cc $TMPC -o $TMPO $_x11libdir -lX11 -lXext -lGL -pthread $_socklib > /dev/null 2>&1 && _gl=yes
-  else
-  $_cc $TMPC -o $TMPO $_x11libdir -lX11 -lXext -lGL $_socklib > /dev/null 2>&1 && _gl=yes
-  fi
---- 669,675 ----
-  $_cc $TMPC -o $TMPO $_x11libdir -lX11 -lXext -lXxf86vm $_socklib > /dev/null 2>&1 && _vm=yes
-  
-  if [ "$system_name" = "FreeBSD" ]; then
-! $_cc $TMPC -o $TMPO $_x11libdir -lX11 -lXext -lGL ${PTHREAD_LIBS} $_socklib > /dev/null 2>&1 && _gl=yes
-  else
-  $_cc $TMPC -o $TMPO $_x11libdir -lX11 -lXext -lGL $_socklib > /dev/null 2>&1 && _gl=yes
-  fi
-***************
-*** 679,685 ****
-  int main( void ) { return 0; }
-  EOF
-  if [ "$system_name" = "FreeBSD" ]; then
-! $_cc $_x11incdir $TMPC -o $TMPO $_x11libdir -lX11 -lXext -lGL -pthread $_socklib > /dev/null 2>&1 || \
-   { _gl=no; echo "GL includes not found!";}
-  else
-  $_cc $TMPC -o $TMPO $_x11libdir -lX11 -lXext -lGL $_socklib > /dev/null 2>&1 || \
---- 679,685 ----
-  int main( void ) { return 0; }
-  EOF
-  if [ "$system_name" = "FreeBSD" ]; then
-! $_cc $_x11incdir $TMPC -o $TMPO $_x11libdir -lX11 -lXext -lGL ${PTHREAD_LIBS} $_socklib > /dev/null 2>&1 || \
-   { _gl=no; echo "GL includes not found!";}
-  else
-  $_cc $TMPC -o $TMPO $_x11libdir -lX11 -lXext -lGL $_socklib > /dev/null 2>&1 || \
-***************
-*** 1162,1168 ****
-     if [ "$system_name" = "FreeBSD" ]; then
-        # Under XFree86 4.x GL port is poorly designed
-        if [ -r /usr/X11R6/bin/XFree86 ]; then
-!          _gllib='-lGL -pthread'
-        else
-           _gllib='-lGL'
-        fi
---- 1162,1168 ----
-     if [ "$system_name" = "FreeBSD" ]; then
-        # Under XFree86 4.x GL port is poorly designed
-        if [ -r /usr/X11R6/bin/XFree86 ]; then
-!          _gllib="-lGL ${PTHREAD_LIBS}"
-        else
-           _gllib='-lGL'
-        fi
-***************
-*** 1329,1335 ****
-  # Under FreeBSD (maybe other systems as well?) we have to add to CFLAGS
-  # for MT applications: 
-  if [ "$system_name" = "FreeBSD" ]; then
-! CFLAGS="$CFLAGS -D_THREAD_SAFE"
-  fi
-  
-  # echo 'CFLAGS=$(OPTFLAGS) -Wall -DMPG12PLAY' >> config.mak
---- 1329,1335 ----
-  # Under FreeBSD (maybe other systems as well?) we have to add to CFLAGS
-  # for MT applications: 
-  if [ "$system_name" = "FreeBSD" ]; then
-! CFLAGS="$CFLAGS ${PTHREAD_CFLAGS}"
-  fi
-  
-  # echo 'CFLAGS=$(OPTFLAGS) -Wall -DMPG12PLAY' >> config.mak
+--- configure.orig	Fri Sep 28 19:21:08 2001
++++ configure	Fri Sep 28 19:33:35 2001
+@@ -299,7 +299,7 @@
+ _confcygwin="TARGET_CYGWIN=no"
+ _confwin32=
+ if [ "$system_name" = "FreeBSD" -o "$system_name" = "OpenBSD" ]; then
+-    _archlibs="-rdynamic -pthread"
++    _archlibs="-rdynamic ${PTHREAD_LIBS}"
+ elif [ `echo $system_name | sed 's/[cC][yY][gG][wW][iI][nN].*/CYGWIN/'` = "CYGWIN" ]; then
+     _confcygwin="TARGET_CYGWIN=yes"
+     _confwin32="#define WIN32"
+@@ -766,7 +766,7 @@
+ $_cc $_extraincdir $_extralibdir $TMPC -o $TMPO -lvgagl -lvga > /dev/null 2>&1 && _svga=yes
+ 
+ if [ "$system_name" = "FreeBSD" -o "$system_name" = "OpenBSD" ]; then
+-$_cc $TMPC -o $TMPO -pthread > /dev/null 2>&1 || \
++$_cc $TMPC -o $TMPO ${PTHREAD_LIBS} > /dev/null 2>&1 || \
+  { echo "Lib pthread not found."; rm -f $TMPC $TMPO $TMPS ; exit 1; }
+ else
+ $_cc $TMPC -o $TMPO -lpthread > /dev/null 2>&1 || \
+@@ -861,7 +861,7 @@
+ 
+ # this is not yet checked with OpenBSD - atmos
+ if [ "$system_name" = "FreeBSD" -o "$system_name" = "OpenBSD" ]; then
+-$_cc $TMPC -o $TMPO $_x11libdir -lX11 -lXext -lGL -pthread $_socklib > /dev/null 2>&1 && _gl=yes
++$_cc $TMPC -o $TMPO $_x11libdir -lX11 -lXext -lGL ${PTHREAD_LIBS} $_socklib > /dev/null 2>&1 && _gl=yes
+ else
+ $_cc $TMPC -o $TMPO $_x11libdir -lX11 -lXext -lGL $_socklib > /dev/null 2>&1 && _gl=yes
+ fi
+@@ -872,7 +872,7 @@
+ EOF
+ # this is not yet checked with OpenBSD - atmos
+ if [ "$system_name" = "FreeBSD" -o "$system_name" = "OpenBSD" ]; then
+-$_cc $_x11incdir $TMPC -o $TMPO $_x11libdir -lX11 -lXext -lGL -pthread $_socklib > /dev/null 2>&1 || \
++$_cc $_x11incdir $TMPC -o $TMPO $_x11libdir -lX11 -lXext -lGL ${PTHREAD_LIBS} $_socklib > /dev/null 2>&1 || \
+  { _gl=no; echo "GL includes not found!";}
+ else
+ $_cc $TMPC -o $TMPO $_x11libdir -lX11 -lXext -lGL $_socklib > /dev/null 2>&1 || \
+@@ -1613,33 +1613,33 @@
+ 
+ echo
+ echo $_echo_n "Checking for gtk version ... $_echo_c"
+-_gtk=`gtk-config --version 2>&1`
++_gtk=`${GTK_CONFIG} --version 2>&1`
+ [ -z "$_gtk" ] && { echo 'gtk not found.'; exit 1; }
+ echo "$_gtk"
+ 
+ echo $_echo_n "Checking for gtk includes ... $_echo_c"
+-_gtkinc=`gtk-config --cflags 2>&1`
++_gtkinc=`${GTK_CONFIG} --cflags 2>&1`
+ [ -z "$_gtkinc" ] && { echo 'gtk not found.'; exit 1; }
+ echo "done"
+ 
+ echo $_echo_n "Checking for gtk libs ... $_echo_c"
+-_gtklib=`gtk-config --libs 2>&1`
++_gtklib=`${GTK_CONFIG} --libs 2>&1`
+ [ -z "$_gtklib" ] && { echo 'gtk not found.'; exit 1; }
+ echo "done"
+ 
+ echo
+ echo $_echo_n "Checking for glib version ... $_echo_c"
+-_glib=`glib-config --version 2>&1`
++_glib=`${GLIB_CONFIG} --version 2>&1`
+ [ -z "$_glib" ] && { echo 'glib not found.'; exit 1; }
+ echo "$_glib"
+ 
+ echo $_echo_n "Checking for glib includes ... $_echo_c"
+-_glibinc=`glib-config --cflags 2>&1`
++_glibinc=`${GLIB_CONFIG} --cflags 2>&1`
+ [ -z "$_glibinc" ] && { echo 'glib not found.'; exit 1; }
+ echo "done"
+ 
+ echo $_echo_n "Checking for glib libs ... $_echo_c"
+-_gliblib=`glib-config --libs 2>&1`
++_gliblib=`${GLIB_CONFIG} --libs 2>&1`
+ [ -z "$_gliblib" ] && { echo 'glib not found.'; exit 1; }
+ echo "done"
+ 
+@@ -1668,7 +1668,7 @@
+    if [ "$system_name" = "FreeBSD" -o "$system_name" = "OpenBSD" ]; then
+       # Under XFree86 4.x GL port is poorly designed
+       if [ -r /usr/X11R6/bin/XFree86 ]; then
+-         _gllib='-lGL -pthread'
++         _gllib='-lGL ${PTHREAD_LIBS}'
+       else
+          _gllib='-lGL'
+       fi
+@@ -1895,7 +1895,7 @@
+ # Under FreeBSD (maybe other systems as well?) we have to add to CFLAGS
+ # for MT applications: 
+ if [ "$system_name" = "FreeBSD" ]; then
+-CFLAGS="$CFLAGS -D_THREAD_SAFE"
++CFLAGS="$CFLAGS ${PTHREAD_CFLAGS}"
+ fi
+ 
+ # 64 bit file offsets?
