- Add periodic script that reports raid status - Update pkg-message - Correct prerequisite checks in script - Bump PORTREVISION
PR:		ports/109753
Submitted by:	Bjoern A. Zeeb <bzeeb+freebsdports at zabbadoz.net>
Approved by:	Ruben van Staveren <ruben at verweg.com> (maintainer)

diff --git a/sysutils/linux-megacli/files/megacli.sh.in b/sysutils/linux-megacli/files/megacli.sh.in
--- a/sysutils/linux-megacli/files/megacli.sh.in
+++ b/sysutils/linux-megacli/files/megacli.sh.in
@@ -4,17 +4,23 @@
 #
 if [ `id -u` -ne 0 ]
 then
-	echo You must be root to run `basename $0`.
+	echo "You must be root to run `basename $0`." >&2
 	exit 1
 fi
 
 if ! [ `sysctl -n compat.linux.osrelease` = "2.6.12" ]; then
-	echo You need to set compat.linux.osrelease to 2.6.12 to run `basename $0`.
+	echo "You need to set compat.linux.osrelease to 2.6.12 to run `basename $0`." >&2
 	exit 1
 fi
 
-if ! [ -d /usr/compat/linux/sys ]; then
-	echo You need to mount linsysfs to run `basename $0`.
+lpfs=`mount -t linprocfs | wc -l | awk '{ print $1 }'`
+if [ ${lpfs} -le 0 ]; then
+	echo "You need to mount linprocfs to run `basename $0`." >&2
+	exit 1
+fi
+lsfs=`mount -t linsysfs | wc -l | awk '{ print $1 }'`
+if [ ${lsfs} -le 0 ]; then
+	echo "You need to mount linsysfs to run `basename $0`." >&2
 	exit 1
 fi
 
@@ -24,11 +30,16 @@ if ! kldstat -q -m mfi_linux
 then
 	if kldload mfi_linux
 	then
-		echo 'mfi_linux module loaded.'
+		echo 'mfi_linux module loaded.' >&2
 	else
-		echo 'mfi_linux module failed to load.'
+		echo 'mfi_linux module failed to load.' >&2
 		exit 1
 	fi
+fi
+
+if [ $# -le 0 ]; then
+	echo "usage: `basename $0` [options]" >&2
+	exec %%PREFIX%%/libexec/MegaCli -h
 fi
 
 exec %%PREFIX%%/libexec/MegaCli ${*}
