Update to 2.6.1.
PR:		85216

diff --git a/x11-toolkits/wxgtk29/files/patch-configure b/x11-toolkits/wxgtk29/files/patch-configure
--- a/x11-toolkits/wxgtk29/files/patch-configure
+++ b/x11-toolkits/wxgtk29/files/patch-configure
@@ -1,6 +1,6 @@
---- configure.orig	Thu Apr 21 00:32:34 2005
-+++ configure	Thu May  5 16:17:57 2005
-@@ -33918,7 +33918,7 @@
+--- configure.orig	Thu Jun  2 23:03:05 2005
++++ configure	Wed Aug 31 23:48:02 2005
+@@ -34396,7 +34396,7 @@
                  fi
                  ;;
            *-*-freebsd*)
@@ -9,7 +9,7 @@
                  ;;
            *-*-darwin* | *-*-cygwin* )
                                                  THREAD_OPTS=""
-@@ -33955,6 +33955,12 @@
+@@ -34433,6 +34433,12 @@
  echo $ECHO_N "checking whether pthreads work without any flags... $ECHO_C" >&6
                      ;;
  
@@ -22,7 +22,16 @@
                  -*)
                      echo "$as_me:$LINENO: checking whether pthreads work with $flag" >&5
  echo $ECHO_N "checking whether pthreads work with $flag... $ECHO_C" >&6
-@@ -35210,6 +35216,7 @@
+@@ -34515,7 +34521,7 @@
+           { echo "$as_me:$LINENO: WARNING: No thread support on this system... disabled" >&5
+ echo "$as_me: WARNING: No thread support on this system... disabled" >&2;}
+       else
+-                              LDFLAGS="$THREADS_CFLAGS $LDFLAGS"
++                              LDFLAGS="$THREADS_CFLAGS $THREADS_LINK $LDFLAGS"
+           LIBS="$THREADS_LINK $LIBS"
+ 
+           echo "$as_me:$LINENO: checking if more special flags are required for pthreads" >&5
+@@ -35701,6 +35707,7 @@
      fi
    fi
  fi
@@ -30,7 +39,7 @@
  
  if test "$WXGTK20" = 1 ; then
    cat >>confdefs.h <<_ACEOF
-@@ -35330,7 +35337,7 @@
+@@ -35823,7 +35830,7 @@
          OPTIMISE="-O"
      fi
  fi
