- Revert previous USERS fix until reworked and tested - Revert MAIL_GROUP change for Postfix - Reset maintainership
Approved by:	tabthorpe (co-mentor), wxs (maintainer)

diff --git a/mail/mailman/pkg-install b/mail/mailman/pkg-install
--- a/mail/mailman/pkg-install
+++ b/mail/mailman/pkg-install
@@ -6,10 +6,48 @@ PATH=/bin:/usr/bin:/usr/sbin
 
 case $2 in
 
+PRE-INSTALL)
+  echo "---> Starting install script:"
+
+  if [ -z "%%MAILMANDIR%%" -o \
+       -z "%%USER%%" -o -z "%%GROUP%%" -o \
+       -z "%%UID%%" -o -z "%%GID%%" ]; then
+    echo "ERROR: A required pragma was empty"
+    exit 1
+  fi
+
+  # Create group if required
+  if pw group show "%%GROUP%%" >/dev/null 2>&1; then
+    echo "---> Using existing group \"%%GROUP%%\""
+  else
+    echo "---> Adding group \"%%GROUP%%\" (%%GID%%)"
+    /usr/sbin/pw groupadd %%GROUP%% -g %%GID%% || exit 1
+  fi
+
+  # Create user if required
+  if pw user show "%%USER%%" >/dev/null 2>&1; then
+    echo "---> Using existing user \"%%USER%%\""
+  else
+    echo "---> Adding user \"%%USER%%\" (%%UID%%)"
+    pw useradd "%%USER%%" -u "%%UID%%" -g "%%GROUP%%" -h - \
+      -d "%%MAILMANDIR%%" -s "/sbin/nologin" -c "Mailman Owner" || exit 1
+  fi
+
+  # Create home directory if required
+  if [ -d "%%MAILMANDIR%%" ]; then
+    echo "---> Using existing Mailman directory (%%MAILMANDIR%%)"
+    echo "     (There may be existing active mailing lists - this installation will"
+    echo "     attempt to preserve them.)"
+  else
+    echo "---> Creating Mailman directory (%%MAILMANDIR%%)"
+    (umask 002 && /bin/mkdir -p "%%MAILMANDIR%%") || exit 1
+    /usr/sbin/chown -R "%%USER%%:%%GROUP%%" "%%MAILMANDIR%%" || exit 1
+    /bin/chmod g+s "%%MAILMANDIR%%" || exit 1
+  fi
+  ;;
+
 POST-INSTALL)
   echo "---> Starting post-install script:"
-
-  /bin/chmod g+s "%%MAILMANDIR%%" || exit 1
 
   echo "---> Checking crontab(5) file for user \"%%USER%%\""
 
