Update to version 1.30.
PR:		51969
Submitted by:	Dan Langille <dan@langille.org>

diff --git a/sysutils/bacula/files/patch-configure b/sysutils/bacula/files/patch-configure
--- a/sysutils/bacula/files/patch-configure
+++ b/sysutils/bacula/files/patch-configure
@@ -1,15 +1,15 @@
---- configure.orig	Mon Feb 24 12:03:22 2003
-+++ configure	Mon Feb 24 12:04:31 2003
-@@ -3944,9 +3944,9 @@
-                    { echo "configure: error: Unable to find sqlite.h in standard locations" 1>&2; exit 1; }
-                 fi
-         else
--                if test -f $withval/sqlite.h; then
--                        SQLITE_INCDIR=$withval
--                        SQLITE_LIBDIR=$withval
-+                if test -f $withval/include/sqlite.h; then
-+                        SQLITE_INCDIR=$withval/include
-+                        SQLITE_LIBDIR=$withval/lib
-                         SQLITE_BINDIR=$withval
-                 else
-                    echo "$ac_t""no" 1>&6
+--- configure~	Thu May  8 07:23:27 2003
++++ configure	Thu May  8 07:26:21 2003
+@@ -4038,9 +4038,9 @@
+ 		   { echo "configure: error: Unable to find sqlite.h in standard locations" 1>&2; exit 1; }
+ 		fi
+ 	else
+-		if test -f $withval/sqlite.h; then
+-			SQLITE_INCDIR=$withval
+-			SQLITE_LIBDIR=$withval
++		if test -f $withval/include/sqlite.h; then
++			SQLITE_INCDIR=$withval/include
++			SQLITE_LIBDIR=$withval/lib
+ 			SQLITE_BINDIR=$withval
+ 		else
+ 		   echo "$ac_t""no" 1>&6
