Security fix:  update to the latest versions:  7.1 for American English; and 7.02 for French, German, Japanese, and Brazilian Portuguese.  These are reportedly free of the onunload referrer bug (#145579 in bugzilla).
The Sun Java plugin is no longer available from the same places.
AIM is needed by the 7.02 versions.  The DOM inspector and "venkman"
JavaScript debugger are available for 7.1.

Compress generated files with bzip2; omit "linux-" from their names.

The RDF files provided by the ports are no longer needed.

Update references to Netscape 6.

Run chmod to fix permissions on extracted files (for the Portuguese
slave port).

Remove unneeded XXXchecksum target.

Change the configuration process, so that extraneous files are not
downloaded.  This resolves PR 44101, submitted by Fernan Aguero.

diff --git a/french/netscape7/scripts/configure b/french/netscape7/scripts/configure
--- a/french/netscape7/scripts/configure
+++ b/french/netscape7/scripts/configure
@@ -20,7 +20,6 @@ sélectionné et désélectionné." -1 -1 10 \
 "browser"	"navigateur"						ON \
 "deflfrfr"	"profil français par défaut"			ON \
 "flash"		"plugin Flash"						ON \
-"jre"		"plugin Java"						ON \
 "langfrfr"	"locale français"					ON \
 "mail"		"lecteur de courrier et de nouvelles"			ON \
 "regfr"		"configurations régionales pour la France"		ON \
@@ -55,3 +54,7 @@ echo "$choice" \
 	| perl -pi -e "s/ /\n/g" \
 	> ${WRKSRC}/components.conf
 fi
+
+echo "Maintenant vous devez courir <<make>> encore."
+echo "Veuillez ignorer le message <<Error code 1>>."
+exit 1
diff --git a/german/netscape7/scripts/configure b/german/netscape7/scripts/configure
--- a/german/netscape7/scripts/configure
+++ b/german/netscape7/scripts/configure
@@ -11,14 +11,13 @@ tempfile=`/usr/bin/mktemp -t checklist`
 
 if [ -z "${BATCH}" ]; then
 
-/usr/bin/dialog --title "Netscape 6 component selection" --clear \
+/usr/bin/dialog --title "Netscape 7 component selection" --clear \
 	--checklist "\n\
-Choose components of Netscape 6 to download and install. \n\
+Choose components of Netscape 7 to download and install. \n\
 Press the space bar to toggle selections." -1 -1 11 \
 "browser"	"browser"				ON \
 "defldede"	"German profile defaults"		ON \
 "flash"		"Flash plugin"				ON \
-"jre"		"Java plugin (requires linux_base-6"	ON \
 "langdede"	"German language pack"			ON \
 "mail"		"e-mail and news"			ON \
 "regde"		"regional settings for Germany"		ON \
@@ -53,3 +52,7 @@ echo "$choice" \
 	| perl -pi -e "s/ /\n/g" \
 	> ${WRKSRC}/components.conf
 fi
+
+echo "* Your choices are saved.  You must run the \"make\" command again to"
+echo "* complete the build.  Ignore the \"Error code 1\" below."
+exit 1
