Presenting GNOME 2.28.1 for FreeBSD.  The official release notes for this release can be found at http://library.gnome.org/misc/release-notes/2.28/ . Officially, this is mostly a polishing release in preparation for GNOME 3.0 due in about a year.
On the FreeBSD front, though, a lot went into this release.  Major thanks
goes to kwm and avl who did a lot of the porting work for this release.
In particular, kwm brought in Evolution MAPI support for better Microsoft
Exchange integration.  Avl made sure that the new gobject introspection
repository ports were nicely compartmentalized so that large dependencies
aren't brought in wholesale.

But, every GNOME team member (ahze, avl, bland, kwm, mezz, and myself)
contributed to this release.

Other major improvements include an updated HAL with better volume
probing code, ufsid integration, and support for volume names containing
spaces (big thanks to J.R. Oldroyd); a new WebKit; updated AbiWord;
an updated Gimp; and a preview of the new GNOME Shell project (thanks to
Pawel Worach).

The FreeBSD GNOME Team would like to that the following additional
contributors to this release whose patches and testing really helped
make it a success:

Andrius Morkunas
Dominique Goncalves
Eric L. Chen
J.R. Oldroyd
Joseph S. Atkinson
Li
Pawel Worach
Romain TartiÃ¨re
Thomas Vogt
Yasuda Keisuke
Rui Paulo
Martin Wilke
(and an extra shout out to miwi and pav for pointyhat runs)

We would like to send this release out to Alexander Loginov (avl) in
hopes that he feels better soon.

PR:		136676
		136967
		138872 (obsolete with new epiphany-webkit)
		139160
		134737
		139941
		140097
		140838
		140929

diff --git a/x11/gdm/files/patch-configure b/x11/gdm/files/patch-configure
--- a/x11/gdm/files/patch-configure
+++ b/x11/gdm/files/patch-configure
@@ -1,68 +1,137 @@
---- configure.orig	2009-05-02 22:45:53.000000000 -0400
-+++ configure	2009-05-02 22:47:16.000000000 -0400
-@@ -19163,15 +19163,18 @@ if test -n "$DAEMON_CFLAGS"; then
-     if test -n "$PKG_CONFIG" && \
-     { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"dbus-glib-1 >= \$DBUS_GLIB_REQUIRED_VERSION
+--- configure.orig	2009-09-22 12:26:34.000000000 +0200
++++ configure	2009-09-22 12:29:51.000000000 +0200
+@@ -22494,10 +22494,12 @@
+     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"dbus-glib-1 >= \$DBUS_GLIB_REQUIRED_VERSION
          gobject-2.0 >= \$GLIB_REQUIRED_VERSION
+         gio-2.0 >= \$GLIB_REQUIRED_VERSION
 +	hal
  \"") >&5
    ($PKG_CONFIG --exists --print-errors "dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
          gobject-2.0 >= $GLIB_REQUIRED_VERSION
+         gio-2.0 >= $GLIB_REQUIRED_VERSION
 +	hal
  ") 2>&5
    ac_status=$?
-   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
-   (exit $ac_status); }; then
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+@@ -22519,10 +22521,12 @@
+     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"dbus-glib-1 >= \$DBUS_GLIB_REQUIRED_VERSION
+         gobject-2.0 >= \$GLIB_REQUIRED_VERSION
+         gio-2.0 >= \$GLIB_REQUIRED_VERSION
++	hal
+ \"") >&5
+   ($PKG_CONFIG --exists --print-errors "dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
+         gobject-2.0 >= $GLIB_REQUIRED_VERSION
+         gio-2.0 >= $GLIB_REQUIRED_VERSION
++	hal
+ ") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+@@ -22530,6 +22534,7 @@
+   pkg_cv_COMMON_LIBS=`$PKG_CONFIG --libs "dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
+         gobject-2.0 >= $GLIB_REQUIRED_VERSION
+         gio-2.0 >= $GLIB_REQUIRED_VERSION
++	hal
+ " 2>/dev/null`
+ else
+   pkg_failed=yes
+@@ -22551,11 +22556,13 @@
+ 	        COMMON_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
+         gobject-2.0 >= $GLIB_REQUIRED_VERSION
+         gio-2.0 >= $GLIB_REQUIRED_VERSION
++	hal
+ " 2>&1`
+         else
+ 	        COMMON_PKG_ERRORS=`$PKG_CONFIG --print-errors "dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
+         gobject-2.0 >= $GLIB_REQUIRED_VERSION
+         gio-2.0 >= $GLIB_REQUIRED_VERSION
++	hal
+ " 2>&1`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+@@ -22564,6 +22571,7 @@
+ 	{ { echo "$as_me:$LINENO: error: Package requirements (dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
+         gobject-2.0 >= $GLIB_REQUIRED_VERSION
+         gio-2.0 >= $GLIB_REQUIRED_VERSION
++	hal
+ ) were not met:
+ 
+ $COMMON_PKG_ERRORS
+@@ -22578,6 +22586,7 @@
+ echo "$as_me: error: Package requirements (dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
+         gobject-2.0 >= $GLIB_REQUIRED_VERSION
+         gio-2.0 >= $GLIB_REQUIRED_VERSION
++	hal
+ ) were not met:
+ 
+ $COMMON_PKG_ERRORS
+@@ -22634,10 +22643,12 @@
+     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"dbus-glib-1 >= \$DBUS_GLIB_REQUIRED_VERSION
+         gobject-2.0 >= \$GLIB_REQUIRED_VERSION
+         gio-2.0 >= \$GLIB_REQUIRED_VERSION
++	hal
+ \"") >&5
+   ($PKG_CONFIG --exists --print-errors "dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
+         gobject-2.0 >= $GLIB_REQUIRED_VERSION
+         gio-2.0 >= $GLIB_REQUIRED_VERSION
++	hal
+ ") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+@@ -22645,6 +22656,7 @@
    pkg_cv_DAEMON_CFLAGS=`$PKG_CONFIG --cflags "dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
          gobject-2.0 >= $GLIB_REQUIRED_VERSION
+         gio-2.0 >= $GLIB_REQUIRED_VERSION
 +	hal
  " 2>/dev/null`
  else
    pkg_failed=yes
-@@ -19185,15 +19188,18 @@ if test -n "$DAEMON_LIBS"; then
-     if test -n "$PKG_CONFIG" && \
-     { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"dbus-glib-1 >= \$DBUS_GLIB_REQUIRED_VERSION
+@@ -22659,10 +22671,12 @@
+     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"dbus-glib-1 >= \$DBUS_GLIB_REQUIRED_VERSION
          gobject-2.0 >= \$GLIB_REQUIRED_VERSION
+         gio-2.0 >= \$GLIB_REQUIRED_VERSION
 +	hal
  \"") >&5
    ($PKG_CONFIG --exists --print-errors "dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
          gobject-2.0 >= $GLIB_REQUIRED_VERSION
+         gio-2.0 >= $GLIB_REQUIRED_VERSION
 +	hal
  ") 2>&5
    ac_status=$?
-   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
-   (exit $ac_status); }; then
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+@@ -22670,6 +22684,7 @@
    pkg_cv_DAEMON_LIBS=`$PKG_CONFIG --libs "dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
          gobject-2.0 >= $GLIB_REQUIRED_VERSION
+         gio-2.0 >= $GLIB_REQUIRED_VERSION
 +	hal
  " 2>/dev/null`
  else
    pkg_failed=yes
-@@ -19214,10 +19220,12 @@ fi
-         if test $_pkg_short_errors_supported = yes; then
+@@ -22691,11 +22706,13 @@
  	        DAEMON_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
          gobject-2.0 >= $GLIB_REQUIRED_VERSION
+         gio-2.0 >= $GLIB_REQUIRED_VERSION
 +	hal
  " 2>&1`
          else
  	        DAEMON_PKG_ERRORS=`$PKG_CONFIG --print-errors "dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
          gobject-2.0 >= $GLIB_REQUIRED_VERSION
+         gio-2.0 >= $GLIB_REQUIRED_VERSION
 +	hal
  " 2>&1`
          fi
  	# Put the nasty error message in config.log where it belongs
-@@ -19225,6 +19233,7 @@ fi
- 
- 	{ { $as_echo "$as_me:$LINENO: error: Package requirements (dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
+@@ -22704,6 +22721,7 @@
+ 	{ { echo "$as_me:$LINENO: error: Package requirements (dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
          gobject-2.0 >= $GLIB_REQUIRED_VERSION
+         gio-2.0 >= $GLIB_REQUIRED_VERSION
 +	hal
  ) were not met:
  
  $DAEMON_PKG_ERRORS
-@@ -19238,6 +19247,7 @@ See the pkg-config man page for more det
- " >&5
- $as_echo "$as_me: error: Package requirements (dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
+@@ -22718,6 +22736,7 @@
+ echo "$as_me: error: Package requirements (dbus-glib-1 >= $DBUS_GLIB_REQUIRED_VERSION
          gobject-2.0 >= $GLIB_REQUIRED_VERSION
+         gio-2.0 >= $GLIB_REQUIRED_VERSION
 +	hal
  ) were not met:
  
diff --git a/x11/gnome-panel/files/patch-configure b/x11/gnome-panel/files/patch-configure
--- a/x11/gnome-panel/files/patch-configure
+++ b/x11/gnome-panel/files/patch-configure
@@ -1,11 +1,61 @@
---- configure.orig	Wed Jan 14 15:54:42 2004
-+++ configure	Wed Jan 14 15:55:13 2004
-@@ -5536,7 +5536,7 @@
+--- configure.orig	2009-10-04 17:26:08.000000000 -0400
++++ configure	2009-10-04 17:31:11.000000000 -0400
+@@ -14954,12 +14955,12 @@ if test -n "$CLOCK_CFLAGS"; then
+     pkg_cv_CLOCK_CFLAGS="$CLOCK_CFLAGS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"pango >= \$PANGO_REQUIRED gtk+-2.0 >= \$GTK_REQUIRED glib-2.0 >= \$GLIB_REQUIRED gio-2.0 >= \$GLIB_REQUIRED \$LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= \$GWEATHER_REQUIRED\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "pango >= $PANGO_REQUIRED gtk+-2.0 >= $GTK_REQUIRED glib-2.0 >= $GLIB_REQUIRED gio-2.0 >= $GLIB_REQUIRED $LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= $GWEATHER_REQUIRED") 2>&5
++    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"pango >= \$PANGO_REQUIRED gtk+-2.0 >= \$GTK_REQUIRED glib-2.0 >= \$GLIB_REQUIRED gio-2.0 >= \$GLIB_REQUIRED \$LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= \$GWEATHER_REQUIRED gnome-desktop-2.0 >= \$LIBGNOME_DESKTOP_REQUIRED\"") >&5
++  ($PKG_CONFIG --exists --print-errors "pango >= $PANGO_REQUIRED gtk+-2.0 >= $GTK_REQUIRED glib-2.0 >= $GLIB_REQUIRED gio-2.0 >= $GLIB_REQUIRED $LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= $GWEATHER_REQUIRED gnome-desktop-2.0 >= $LIBGNOME_DESKTOP_REQUIRED") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_CLOCK_CFLAGS=`$PKG_CONFIG --cflags "pango >= $PANGO_REQUIRED gtk+-2.0 >= $GTK_REQUIRED glib-2.0 >= $GLIB_REQUIRED gio-2.0 >= $GLIB_REQUIRED $LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= $GWEATHER_REQUIRED" 2>/dev/null`
++  pkg_cv_CLOCK_CFLAGS=`$PKG_CONFIG --cflags "pango >= $PANGO_REQUIRED gtk+-2.0 >= $GTK_REQUIRED glib-2.0 >= $GLIB_REQUIRED gio-2.0 >= $GLIB_REQUIRED $LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= $GWEATHER_REQUIRED gnome-desktop-2.0 >= $LIBGNOME_DESKTOP_REQUIRED" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -14970,12 +14971,12 @@ if test -n "$CLOCK_LIBS"; then
+     pkg_cv_CLOCK_LIBS="$CLOCK_LIBS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"pango >= \$PANGO_REQUIRED gtk+-2.0 >= \$GTK_REQUIRED glib-2.0 >= \$GLIB_REQUIRED gio-2.0 >= \$GLIB_REQUIRED \$LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= \$GWEATHER_REQUIRED\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "pango >= $PANGO_REQUIRED gtk+-2.0 >= $GTK_REQUIRED glib-2.0 >= $GLIB_REQUIRED gio-2.0 >= $GLIB_REQUIRED $LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= $GWEATHER_REQUIRED") 2>&5
++    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"pango >= \$PANGO_REQUIRED gtk+-2.0 >= \$GTK_REQUIRED glib-2.0 >= \$GLIB_REQUIRED gio-2.0 >= \$GLIB_REQUIRED \$LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= \$GWEATHER_REQUIRED gnome-desktop-2.0 >= \$LIBGNOME_DESKTOP_REQUIRED\"") >&5
++  ($PKG_CONFIG --exists --print-errors "pango >= $PANGO_REQUIRED gtk+-2.0 >= $GTK_REQUIRED glib-2.0 >= $GLIB_REQUIRED gio-2.0 >= $GLIB_REQUIRED $LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= $GWEATHER_REQUIRED gnome-desktop-2.0 >= $LIBGNOME_DESKTOP_REQUIRED") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_CLOCK_LIBS=`$PKG_CONFIG --libs "pango >= $PANGO_REQUIRED gtk+-2.0 >= $GTK_REQUIRED glib-2.0 >= $GLIB_REQUIRED gio-2.0 >= $GLIB_REQUIRED $LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= $GWEATHER_REQUIRED" 2>/dev/null`
++  pkg_cv_CLOCK_LIBS=`$PKG_CONFIG --libs "pango >= $PANGO_REQUIRED gtk+-2.0 >= $GTK_REQUIRED glib-2.0 >= $GLIB_REQUIRED gio-2.0 >= $GLIB_REQUIRED $LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= $GWEATHER_REQUIRED gnome-desktop-2.0 >= $LIBGNOME_DESKTOP_REQUIRED" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -14993,14 +14994,14 @@ else
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        CLOCK_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "pango >= $PANGO_REQUIRED gtk+-2.0 >= $GTK_REQUIRED glib-2.0 >= $GLIB_REQUIRED gio-2.0 >= $GLIB_REQUIRED $LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= $GWEATHER_REQUIRED" 2>&1`
++	        CLOCK_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "pango >= $PANGO_REQUIRED gtk+-2.0 >= $GTK_REQUIRED glib-2.0 >= $GLIB_REQUIRED gio-2.0 >= $GLIB_REQUIRED $LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= $GWEATHER_REQUIRED gnome-desktop-2.0 >= $LIBGNOME_DESKTOP_REQUIRED" 2>&1`
+         else
+-	        CLOCK_PKG_ERRORS=`$PKG_CONFIG --print-errors "pango >= $PANGO_REQUIRED gtk+-2.0 >= $GTK_REQUIRED glib-2.0 >= $GLIB_REQUIRED gio-2.0 >= $GLIB_REQUIRED $LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= $GWEATHER_REQUIRED" 2>&1`
++	        CLOCK_PKG_ERRORS=`$PKG_CONFIG --print-errors "pango >= $PANGO_REQUIRED gtk+-2.0 >= $GTK_REQUIRED glib-2.0 >= $GLIB_REQUIRED gio-2.0 >= $GLIB_REQUIRED $LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= $GWEATHER_REQUIRED gnome-desktop-2.0 >= $LIBGNOME_DESKTOP_REQUIRED" 2>&1`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$CLOCK_PKG_ERRORS" >&5
  
+-	{ { $as_echo "$as_me:$LINENO: error: Package requirements (pango >= $PANGO_REQUIRED gtk+-2.0 >= $GTK_REQUIRED glib-2.0 >= $GLIB_REQUIRED gio-2.0 >= $GLIB_REQUIRED $LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= $GWEATHER_REQUIRED) were not met:
++	{ { $as_echo "$as_me:$LINENO: error: Package requirements (pango >= $PANGO_REQUIRED gtk+-2.0 >= $GTK_REQUIRED glib-2.0 >= $GLIB_REQUIRED gio-2.0 >= $GLIB_REQUIRED $LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= $GWEATHER_REQUIRED gnome-desktop-2.0 >= $LIBGNOME_DESKTOP_REQUIRED) were not met:
  
- for ac_header in sys/types.h sys/stat.h stdlib.h string.h memory.h strings.h \
--		  inttypes.h stdint.h unistd.h
-+		  inttypes.h stdint.h unistd.h langinfo.h
- do
- as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
- echo "$as_me:$LINENO: checking for $ac_header" >&5
+ $CLOCK_PKG_ERRORS
+ 
+@@ -15011,7 +15012,7 @@ Alternatively, you may set the environme
+ and CLOCK_LIBS to avoid the need to call pkg-config.
+ See the pkg-config man page for more details.
+ " >&5
+-$as_echo "$as_me: error: Package requirements (pango >= $PANGO_REQUIRED gtk+-2.0 >= $GTK_REQUIRED glib-2.0 >= $GLIB_REQUIRED gio-2.0 >= $GLIB_REQUIRED $LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= $GWEATHER_REQUIRED) were not met:
++$as_echo "$as_me: error: Package requirements (pango >= $PANGO_REQUIRED gtk+-2.0 >= $GTK_REQUIRED glib-2.0 >= $GLIB_REQUIRED gio-2.0 >= $GLIB_REQUIRED $LIBECAL_REQUIREMENT librsvg-2.0 dbus-glib-1 gweather >= $GWEATHER_REQUIRED gnome-desktop-2.0 >= $LIBGNOME_DESKTOP_REQUIRED) were not met:
+ 
+ $CLOCK_PKG_ERRORS
+ 
