Update to 0.12. Unfortunately it still doesn't work, even with fixed oaf, however it goes further that earlier and instead of hanging solidly at startup tries to launch its components, but goes kaboom (i.e. sig 12) and dies in agony. Therefore, brave souls with loaded debuggers are welcome to fix this fscking crap and submit their patches to gnome@FreeBSD.org.

diff --git a/mail/evolution/files/patch-aa b/mail/evolution/files/patch-aa
--- a/mail/evolution/files/patch-aa
+++ b/mail/evolution/files/patch-aa
@@ -1,6 +1,36 @@
---- configure.orig	Wed Sep 13 09:43:40 2000
-+++ configure	Wed Sep 13 13:19:42 2000
-@@ -5709,8 +5709,8 @@
+
+$FreeBSD$
+
+--- configure.orig	Tue Sep  4 17:59:26 2001
++++ configure	Tue Sep  4 18:11:25 2001
+@@ -5667,7 +5667,7 @@
+ 
+ CPPFLAGS_save="$CPPFLAGS"
+ CPPFLAGS="$CPPFLAGS $DB3_CFLAGS"
+-for ac_hdr in db.h db3/db.h
++for ac_hdr in db3/db.h
+ do
+ ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
+ echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
+@@ -5741,7 +5741,7 @@
+   echo "configure: failed program was:" >&5
+   cat conftest.$ac_ext >&5
+   rm -rf conftest*
+-  { echo "configure: error: Found db.h is not version $evolution_db_version" 1>&2; exit 1; }
++#  { echo "configure: error: Found db.h is not version $evolution_db_version" 1>&2; exit 1; }
+ fi
+ rm -f conftest*
+ 
+@@ -5852,7 +5852,7 @@
+ 
+ echo "$ac_t""$ac_cv_db3_lib_version_match" 1>&6
+ if test "$ac_cv_db3_lib_version_match" = no; then
+-	{ echo "configure: error: db3 headers and library do not match... multiple copies installed?" 1>&2; exit 1; }
++#	{ echo "configure: error: db3 headers and library do not match... multiple copies installed?" 1>&2; exit 1; }
+ fi
+ 
+ CPPFLAGS="$CPPFLAGS_save"
+@@ -6333,8 +6333,8 @@
  fi
  
  
@@ -11,9 +41,9 @@
  
  
  
-@@ -5837,8 +5837,8 @@
-     { echo "configure: error: Did not find gdkpixbuf installed" 1>&2; exit 1; }
- fi
+@@ -6894,8 +6894,8 @@
+ 	fi
+ 
  
 -GLIB_CFLAGS="`glib-config --cflags`"
 -GLIB_LIBS="`glib-config --libs`"
@@ -22,7 +52,7 @@
  
  
  
-@@ -7915,10 +7915,10 @@
+@@ -9415,10 +9415,10 @@
        *) # Relative path.
          ac_sub_cache_file="$ac_dots$cache_file" ;;
        esac
