On Alpha, the osf1 module must be loaded before the linux module. Do this.
Add ID tag.

diff --git a/emulators/linux_base/pkg-install b/emulators/linux_base/pkg-install
--- a/emulators/linux_base/pkg-install
+++ b/emulators/linux_base/pkg-install
@@ -1,8 +1,20 @@
 #!/bin/sh
+# $FreeBSD$
 # an installation script for linux_base
 
 case "$2" in
 PRE-INSTALL)
+	if [ "`uname -m`" = alpha ]; then
+		if [ -z "`kldstat -v | grep osf1`" ]; then
+			echo 'OSF1 mode is not enabled.'
+			echo 'Trying to load osf1 kernel module now...'
+			if ! kldload osf1; then
+				echo 'The osf1 kernel module could not be'
+				echo 'loaded; please fix this and retry.'
+				exit 1
+			fi
+		fi
+	fi
 	if [ -z "`kldstat -v | grep linux`" ]; then
 		echo 'Linux mode is not enabled.'
 		echo 'Loading linux kernel module now...'
