- obey CFLAGS - put pid files in /var/run - make start-up script work on different PREFIX

diff --git a/net/netatalk-asun/files/patch-ab b/net/netatalk-asun/files/patch-ab
--- a/net/netatalk-asun/files/patch-ab
+++ b/net/netatalk-asun/files/patch-ab
@@ -1,28 +1,31 @@
-diff -crP ../netatalk-1.4b2/rc.atalk.freebsd ./rc.atalk.freebsd
-*** ../netatalk-1.4b2/rc.atalk.freebsd	Thu Jan  1 01:00:00 1970
---- ./rc.atalk.freebsd	Thu Jul 24 02:14:39 1997
-***************
-*** 0 ****
---- 1,22 ----
-+ #
-+ # AppleTalk daemons. Make sure not to start atalkd in the background:
-+ # its data structures must have time to stablize before running the
-+ # other processes.
-+ #
-+ 
-+ case $1 in
-+ 	start)	echo -n ' netatalk'
-+ 		:SBINDIR:/atalkd
-+ 		:BINDIR:/nbprgstr -p 4 `hostname|sed 's/\..*$//'`:Workstation
-+ 		:BINDIR:/nbprgstr -p 4 `hostname|sed 's/\..*$//'`:netatalk
-+ 		:SBINDIR:/papd
-+ 		:SBINDIR:/afpd
-+ 		;;
-+ 	stop)	killall afpd
-+ 		killall papd
-+ 		killall atalkd
-+ 		;;
-+ 	*)	echo "usage: $0 {start|stop}"
-+ 		exit 64
-+ 		;;
-+ esac
+--- rc.atalk.freebsd.orig	Tue Nov 24 13:08:44 1998
++++ rc.atalk.freebsd	Tue Nov 24 13:56:05 1998
+@@ -0,0 +1,28 @@
++#
++# AppleTalk daemons. Make sure not to start atalkd in the background:
++# its data structures must have time to stablize before running the
++# other processes.
++#
++PREFIX=/`expr $0 : '/\(.*\)/etc/rc.d/netatalk.sh'`
++if [ "x${PREFIX}" = "x/" ]; then
++	printf "\nnetatalk: Cannot determine PREFIX.\n" >&2
++	exit 64
++fi
++HOSTNAME=`hostname|sed 's/\..*$//'`
++
++case $1 in
++	start)	echo -n ' netatalk'
++		${PREFIX}/libexec/atalkd
++		${PREFIX}/bin/nbprgstr -p 4 ${HOSTNAME}:Workstation &
++		${PREFIX}/bin/nbprgstr -p 4 ${HOSTNAME}:netatalk &
++		${PREFIX}/libexec/papd
++		${PREFIX}/libexec/afpd -s ${PREFIX}/etc/AppleVolumes.system \
++		-f ${PREFIX}/etc/AppleVolumes.default
++		;;
++	stop)	for i in afpd papd atalkd; do
++			if [ -f /var/run/$i.pid ]; then
++				kill `cat /var/run/$i.pid`
++			fi
++		done
++		;;
++esac
