- Fix QAT by not touching DATADIR until pre-install target. - Fix pkg-install to give a warning that the rules need to be installed if they   don't already exist.
Submitted by:	wxs@
Approved by:	Michael Scheidell <scheidell@secnap.net> (maintainer)
Feature safe:	yes

diff --git a/mail/p5-Mail-SpamAssassin/pkg-install b/mail/p5-Mail-SpamAssassin/pkg-install
--- a/mail/p5-Mail-SpamAssassin/pkg-install
+++ b/mail/p5-Mail-SpamAssassin/pkg-install
@@ -1,5 +1,10 @@
 #!/bin/sh
 PKG_PREFIX=${PKG_PREFIX:-/usr/local}
+USER=spamd
+GROUP=${USER}
+UID=58
+GID=${UID}
+HOME=/var/spool/${USER}
 
 if [ "$2" = "POST-INSTALL" ];then
 ask() {
@@ -28,52 +33,74 @@ yesno() {
         done
 }
 
-
-   if yesno "Do you wish to run sa-update to fetch new rules" "N";then
-       ${PKG_PREFIX}/bin/sa-update || true
-   fi
-   grep '^load.*Rule2XSBody' ${PKG_PREFIX}/etc/mail/spamassassin/v320.pre > /dev/null
-   if [ $? -eq 0 ];then
-     if yesno "Do you wish to compile rules with re2c (will take a long time)" "N";then
-       ${PKG_PREFIX}/bin/sa-compile || true
-     fi
-   fi
+    if [ ! -e ${PKG_PREFIX}/etc/mail/spamassassin/v320.pre ]; then
+       echo "***********************************************"
+       echo "*__        ___    ____  _   _ ___ _   _  ____ *"
+       echo "*\ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|*"
+       echo "* \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ *"
+       echo "*  \ V  V / ___ \|  _ <| |\  || || |\  | |_| |*"
+       echo "*   \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|*"
+       echo "*                                             *"
+       echo "*You must install rules before starting spamd!*"
+       echo "***********************************************"
+       if [ -z "${PACKAGE_BUILDING}" -a -z "${BATCH}" ]; then
+           sleep 10;
+       fi
+       if yesno "Do you wish to run sa-update to fetch new rules" "N";then
+           ${PKG_PREFIX}/bin/sa-update || true
+       fi
+       grep '^load.*Rule2XSBody' ${PKG_PREFIX}/etc/mail/spamassassin/v320.pre > /dev/null
+       if [ $? -eq 0 ];then
+         if yesno "Do you wish to compile rules with re2c (will take a long time)" "N";then
+           ${PKG_PREFIX}/bin/sa-compile || true
+         fi
+       fi
+    fi
+    
+    if ! pw groupshow "${GROUP}" 2>/dev/null 1>&2; then
+    	if pw groupadd ${GROUP} -g ${GID}; then
+    		echo "Added group \"${GROUP}\"."
+    	else
+    		echo "Adding group \"${GROUP}\" failed..."
+    		exit 1
+    	fi
+    fi
+    
+    if ! pw usershow "${USER}" 2>/dev/null 1>&2; then
+    	if pw useradd ${USER} -u ${UID} -g ${GROUP} -h - \
+    		-s "/sbin/nologin" -d "${HOME}" \
+    		-c "SpamAssassin user"; \
+    	then
+    		echo "Added user \"${USER}\"."
+    		mkdir ${HOME} && chown ${USER}:${GROUP} ${HOME}
+    	else
+    		echo "Adding user \"${USER}\" failed..."
+    		exit 1
+    	fi
+    fi
+    
+    # Create pid directory
+    mkdir /var/run/spamd 2> /dev/null && chown ${USER}:${GROUP} /var/run/spamd
+    
    exit 0
 fi  # post-install
 
-if [ "$2" != "PRE-INSTALL" ]; then
+if [ "$2" = "PRE-INSTALL" ]; then
+    if [ ! -e ${PKG_PREFIX}/etc/mail/spamassassin/v320.pre ]; then
+        echo "***********************************************"
+        echo "*__        ___    ____  _   _ ___ _   _  ____ *"
+        echo "*\ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|*"
+        echo "* \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ *"
+        echo "*  \ V  V / ___ \|  _ <| |\  || || |\  | |_| |*"
+        echo "*   \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|*"
+        echo "*                                             *"
+        echo "*You must install rules before starting spamd!*"
+        echo "***********************************************"
+        if [ -z "${PACKAGE_BUILDING}" -a -z "${BATCH}" ]; then
+            sleep 10;
+        fi
+    fi
     exit 0
 fi
-
-USER=spamd
-GROUP=${USER}
-UID=58
-GID=${UID}
-HOME=/var/spool/${USER}
-
-if ! pw groupshow "${GROUP}" 2>/dev/null 1>&2; then
-	if pw groupadd ${GROUP} -g ${GID}; then
-		echo "Added group \"${GROUP}\"."
-	else
-		echo "Adding group \"${GROUP}\" failed..."
-		exit 1
-	fi
-fi
-
-if ! pw usershow "${USER}" 2>/dev/null 1>&2; then
-	if pw useradd ${USER} -u ${UID} -g ${GROUP} -h - \
-		-s "/sbin/nologin" -d "${HOME}" \
-		-c "SpamAssassin user"; \
-	then
-		echo "Added user \"${USER}\"."
-		mkdir ${HOME} && chown ${USER}:${GROUP} ${HOME}
-	else
-		echo "Adding user \"${USER}\" failed..."
-		exit 1
-	fi
-fi
-
-# Create pid directory
-mkdir /var/run/spamd 2> /dev/null && chown ${USER}:${GROUP} /var/run/spamd
 
 exit 0
