Use tcl-7.6/tk-4.2.

diff --git a/x11-toolkits/tix/files/patch-aa b/x11-toolkits/tix/files/patch-aa
--- a/x11-toolkits/tix/files/patch-aa
+++ b/x11-toolkits/tix/files/patch-aa
@@ -1,24 +1,32 @@
---- configure.orig	Sun Feb 16 06:12:44 1997
-+++ configure	Fri Feb 21 10:18:12 1997
-@@ -1047,7 +1047,7 @@
+--- configure.orig	Sat Jun 28 02:49:27 1997
++++ configure	Wed Aug 20 13:33:21 1997
+@@ -1060,6 +1060,7 @@
+ 
+ if test "$val" != ""; then
+     TCL_SRC_DIR=$val
++    tclsrcdir=$val
+     if test ! -d $TCL_SRC_DIR; then
+         { echo "configure: error: Directory $TCL_SRC_DIR doesn't exist" 1>&2; exit 1; }
+         { echo "configure: error: Please install the source code of Tcl 7.6" 1>&2; exit 1; }
+@@ -1082,7 +1083,7 @@
  fi
  echo "$ac_t""$TCL_SRC_DIR" 1>&6
  
 -TCL_BIN_DIR=$TCL_SRC_DIR/unix
-+TCL_BIN_DIR=$TCL_SRC_DIR/../../lib/tcl7.5
++TCL_BIN_DIR=$TCL_SRC_DIR/../../lib/tcl7.6
  
  #--------------------------------------------------------------------
  #	See if there was a command-line option for where Tk is;  if
-@@ -1089,7 +1089,7 @@
+@@ -1124,7 +1125,7 @@
  fi
  echo "$ac_t""$TK_SRC_DIR" 1>&6
  
 -TK_BIN_DIR=$TK_SRC_DIR/unix
-+TK_BIN_DIR=$TK_SRC_DIR/../../lib/tk4.1
++TK_BIN_DIR=$TK_SRC_DIR/../../lib/tk4.2
  
  #--------------------------------------------------------------------
  #	Find out the top level source directory of the Tix package.
-@@ -1671,12 +1671,12 @@
+@@ -1707,12 +1708,12 @@
  s%@SHLIB_VERSION@%$SHLIB_VERSION%g
  s%@DL_LIBS@%$DL_LIBS%g
  s%@LD_FLAGS@%$LD_FLAGS%g
@@ -26,14 +34,15 @@
 +s%@TCL_LIB_SPEC@%$TCL_LIB_SPEC%g
  s%@TCL_LIBS@%$TCL_LIBS%g
  s%@TCL_VERSION@%$TCL_VERSION%g
- s%@TCL_SRC_DIR@%$TCL_SRC_DIR%g
+-s%@TCL_SRC_DIR@%$TCL_SRC_DIR%g
++s%@TCL_SRC_DIR@%$tclsrcdir%g
  s%@TCL_BIN_DIR@%$TCL_BIN_DIR%g
 -s%@TK_BUILD_LIB_SPEC@%$TK_BUILD_LIB_SPEC%g
 +s%@TK_LIB_SPEC@%$TK_LIB_SPEC%g
  s%@TK_LIBS@%$TK_LIBS%g
  s%@TK_VERSION@%$TK_VERSION%g
  s%@TK_SRC_DIR@%$TK_SRC_DIR%g
-@@ -1702,8 +1702,8 @@
+@@ -1738,8 +1739,8 @@
  s%@TIX_SAM_FILE@%$TIX_SAM_FILE%g
  s%@TIX_MAKE_SAM@%$TIX_MAKE_SAM%g
  s%@TIX_DEFS@%$TIX_DEFS%g
