Update to use Tcl/Tk version 8.2.
Submitted by:	Ade Lovett <ade@lovett.com>

diff --git a/x11-toolkits/tix/files/patch-aa b/x11-toolkits/tix/files/patch-aa
--- a/x11-toolkits/tix/files/patch-aa
+++ b/x11-toolkits/tix/files/patch-aa
@@ -1,40 +1,58 @@
---- configure.orig	Tue Sep 23 16:57:21 1997
-+++ configure	Sat Apr 24 14:13:14 1999
-@@ -1060,6 +1060,7 @@
+--- configure.orig	Sun Feb 14 21:20:06 1999
++++ configure	Wed Nov  3 14:21:25 1999
+@@ -1006,13 +1006,14 @@
  
  if test "$val" != ""; then
      TCL_SRC_DIR=$val
 +    tclsrcdir=$val
      if test ! -d $TCL_SRC_DIR; then
          { echo "configure: error: Directory $TCL_SRC_DIR doesn't exist" 1>&2; exit 1; }
-         { echo "configure: error: Please install the source code of Tcl 8.0" 1>&2; exit 1; }
-@@ -1082,7 +1083,7 @@
+-        { echo "configure: error: Please install the source code of Tcl 8.0" 1>&2; exit 1; }
++        { echo "configure: error: Please install the source code of Tcl 8.2" 1>&2; exit 1; }
+         exit 1
+     fi
+ else
+-    dirs="../../../tcl8.0"
++    dirs="../../../tcl8.2"
+     TCL_SRC_DIR="no-no"
+     for i in $dirs; do
+         if test -d $i; then
+@@ -1028,7 +1029,7 @@
  fi
  echo "$ac_t""$TCL_SRC_DIR" 1>&6
  
 -TCL_BIN_DIR=$TCL_SRC_DIR/unix
-+TCL_BIN_DIR=$TCL_SRC_DIR/../../lib/tcl8.0
++TCL_BIN_DIR=$TCL_SRC_DIR/../../lib/tcl8.2
  
  #--------------------------------------------------------------------
  #	See if there was a command-line option for where Tk is;  if
-@@ -1102,6 +1103,7 @@
+@@ -1048,13 +1049,14 @@
  
  if test "$val" != ""; then
      TK_SRC_DIR=$val
 +    tksrcdir=$val
      if test ! -d $TK_SRC_DIR; then
          { echo "configure: error: Directory $TK_SRC_DIR doesn't exist" 1>&2; exit 1; }
-         { echo "configure: error: Please install the source code of Tk 8.0" 1>&2; exit 1; }
-@@ -1124,7 +1126,7 @@
+-        { echo "configure: error: Please install the source code of Tk 8.0" 1>&2; exit 1; }
++        { echo "configure: error: Please install the source code of Tk 8.2" 1>&2; exit 1; }
+         exit 1
+     fi
+ else
+-    dirs="../../../tk8.0"
++    dirs="../../../tk8.2"
+     TK_SRC_DIR="no-no"
+     for i in $dirs; do
+         if test -d $i; then
+@@ -1070,7 +1072,7 @@
  fi
  echo "$ac_t""$TK_SRC_DIR" 1>&6
  
 -TK_BIN_DIR=$TK_SRC_DIR/unix
-+TK_BIN_DIR=$TK_SRC_DIR/../../lib/tk8.0
++TK_BIN_DIR=$TK_SRC_DIR/../../lib/tk8.2
  
  #--------------------------------------------------------------------
  #	Find out the top level source directory of the Tix package.
-@@ -1195,17 +1197,19 @@
+@@ -1141,17 +1143,19 @@
  # up the Tcl library.
  
  if test "${TCL_LIB_VERSIONS_OK}" = "ok"; then
@@ -44,7 +62,7 @@
      TCL_BUILD_SAM_SPEC="-L`pwd` -ltclsam${TCL_VERSION}"
      TK_BUILD_SAM_SPEC="-L`pwd` -ltksam${TK_VERSION}"
      TIX_LIB_SPEC="-L${exec_prefix}/lib -ltix${VERSION}"
-+	LIB_VERSION="${VERSION}"
++    LIBVERSION="${VERSION}"
  else
 -    TIX_BUILD_LIB_SPEC="-L`pwd` -ltix`echo ${VERSION} | tr -d .`"
 +    TIX_BUILD_LIB_SPEC="`pwd`/libtix`echo ${VERSION} | tr -d .`.so.1"
@@ -52,11 +70,11 @@
      TCL_BUILD_SAM_SPEC="-L`pwd` -ltclsam`echo ${TCL_VERSION} | tr -d .`"
      TK_BUILD_SAM_SPEC="-L`pwd` -ltksam`echo ${TK_VERSION} | tr -d .`"
      TIX_LIB_SPEC="-L${exec_prefix}/lib -ltix`echo ${VERSION} | tr -d .`"
-+	LIB_VERSION="`echo ${VERSION} | tr -d .`"
++    LIB_VERSION="`echo ${VERSION} | tr -d .`"
  fi
  
  #--------------------------------------------------------------------
-@@ -1227,7 +1231,7 @@
+@@ -1173,7 +1177,7 @@
  
      # The main Tix library
      #
@@ -65,7 +83,7 @@
      TIX_MAKE_LIB="\${SHLIB_LD} -o ${TIX_LIB_FILE} \${OBJS} ${SHLIB_LD_LIBS}"
  
      # The Tcl SAM library
-@@ -1245,7 +1249,7 @@
+@@ -1191,7 +1195,7 @@
      # The Tix SAM library
      #
      VERSION=${BIN_VERSION}
@@ -74,7 +92,7 @@
      TIX_MAKE_SAM="\${SHLIB_LD} -o ${TIX_SAM_FILE} \${TIX_SAM_OBJS} ${SHLIB_LD_LIBS}"
  
  else
-@@ -1707,15 +1711,15 @@
+@@ -1653,15 +1657,15 @@
  s%@SHLIB_VERSION@%$SHLIB_VERSION%g
  s%@DL_LIBS@%$DL_LIBS%g
  s%@LD_FLAGS@%$LD_FLAGS%g
@@ -94,7 +112,7 @@
  s%@TK_BIN_DIR@%$TK_BIN_DIR%g
  s%@TK_XINCLUDES@%$TK_XINCLUDES%g
  s%@TIX_LD_SEARCH_FLAGS@%$TIX_LD_SEARCH_FLAGS%g
-@@ -1738,8 +1742,8 @@
+@@ -1684,8 +1688,8 @@
  s%@TIX_SAM_FILE@%$TIX_SAM_FILE%g
  s%@TIX_MAKE_SAM@%$TIX_MAKE_SAM%g
  s%@TIX_DEFS@%$TIX_DEFS%g
