- Update to 0.1.1.13 - Correct way to use USE_RC_SUBR - Update MAINTAINER email
PR:		93314
Submitted by:	maintainer

diff --git a/security/tor-devel/pkg-install b/security/tor-devel/pkg-install
--- a/security/tor-devel/pkg-install
+++ b/security/tor-devel/pkg-install
@@ -1,35 +1,40 @@
-#!/bin/sh
+#! /bin/sh
+#
+# taken from devel/perforce
 
-if [ x"$2" = xPRE-INSTALL ]; then
-    USER="_tor"
-    UID="256"
-    GROUP="_tor"
-    GID="256"
+PATH=/bin:/usr/sbin
 
-   if /usr/sbin/pw groupshow "${GROUP}" 2>/dev/null; then
-       echo "You already have a group \"${GROUP}\", so I will use it."
-   else
-       if /usr/sbin/pw groupadd ${GROUP} -g ${GID}; then
-           echo "Added group \"${GROUP}\"."
-       else
-           echo "Adding group \"${GROUP}\" failed..."
-           echo "Please create it, and try again."
-           exit 1
-       fi
-   fi
+TOR_USER=${TOR_USER:-_tor}
+TOR_GROUP=${TOR_GROUP:-_tor}
 
-   if /usr/sbin/pw user show "${USER}" 2>/dev/null; then
-       echo "You already have a user \"${USER}\", so I will use it."
-   else
-       if /usr/sbin/pw useradd ${USER} -u ${UID} -g ${GROUP} -h - \
-           -d /var/db/tor \
-           -s /bin/sh \
-           -c "Tor anonymising router"; then
-           echo "Added user \"${USER}\"."
-       else
-           echo "Adding user \"${USER}\" failed..."
-           echo "Please create it, and try again."
-           exit 1
-       fi
-   fi
-fi
+case $2 in
+PRE-INSTALL)
+	USER=${TOR_USER}
+	GROUP=${TOR_GROUP}
+
+	if pw group show "${GROUP}" 2>/dev/null; then
+		echo "You already have a group \"${GROUP}\", so I will use it."
+	else
+		if pw groupadd ${GROUP} ; then
+			echo "Added group \"${GROUP}\"."
+		else
+			echo "Adding group \"${GROUP}\" failed..."
+			exit 1
+		fi
+	fi
+
+	if pw user show "${USER}" 2>/dev/null; then
+		echo "You already have a user \"${USER}\", so I will use it."
+	else
+		if pw useradd ${USER} -g ${GROUP} -h - \
+			-d /nonexistent -c "Tor Daemon" -s /bin/sh
+		then
+			echo "Added user \"${USER}\"."
+		else
+			echo "Adding user \"${USER}\" failed..."
+			exit 1
+		fi
+	fi
+
+	;;
+esac
