Upgrade to 3.23.51.

diff --git a/databases/mysql40-server/files/patch-configure b/databases/mysql40-server/files/patch-configure
--- a/databases/mysql40-server/files/patch-configure
+++ b/databases/mysql40-server/files/patch-configure
@@ -1,17 +1,17 @@
---- configure.orig	Wed May  9 22:34:50 2001
-+++ configure	Sat May 12 11:23:21 2001
-@@ -2994,7 +2994,7 @@
+--- configure.orig	Mon Jun  3 12:39:20 2002
++++ configure	Mon Jun 17 19:16:58 2002
+@@ -4188,7 +4188,7 @@
    ;;
  esac
  fi
--HOSTNAME="$ac_cv_path_HOSTNAME"
+-HOSTNAME=$ac_cv_path_HOSTNAME
 +HOSTNAME="$ac_cv_path_HOSTNAME -s"
+ 
  if test -n "$HOSTNAME"; then
-   echo "$ac_t""$HOSTNAME" 1>&6
- else
-@@ -3128,38 +3128,7 @@
- echo $ac_n "checking "how to check if pid exists"""... $ac_c" 1>&6
- echo "configure:3130: checking "how to check if pid exists"" >&5
+   echo "$as_me:4194: result: $HOSTNAME" >&5
+@@ -4366,40 +4366,7 @@
+ echo "$as_me:4366: checking \"how to check if pid exists\"" >&5
+ echo $ECHO_N "checking \"how to check if pid exists\"... $ECHO_C" >&6
  PS=$ac_cv_path_PS
 -# Linux style
 -if $PS p $$ 2> /dev/null | grep $0 > /dev/null
@@ -42,28 +42,38 @@
 -      FIND_PROC="$PS -e | grep mysqld | grep \" \$\$PID \" > /dev/null"
 -      ;;
 -    *)
--      { echo "configure: error: Could not find the right ps switches. Which OS is this ?. See the Installation chapter in the Reference Manual." 1>&2; exit 1; }
+-      { { echo "$as_me:4398: error: Could not find the right ps switches. Which OS is this ?. See the Installation chapter in the Reference Manual." >&5
+-echo "$as_me: error: Could not find the right ps switches. Which OS is this ?. See the Installation chapter in the Reference Manual." >&2;}
+-   { (exit 1); exit 1; }; }
 -  esac
 -fi
 +FIND_PROC="$PS -uaxww | grep mysqld | grep \" \$\$PID \" > /dev/null"
  
- echo "$ac_t"""$FIND_PROC"" 1>&6
- 
-@@ -5922,7 +5891,6 @@
- #define $ac_tr_lib 1
+ echo "$as_me:4404: result: \"$FIND_PROC\"" >&5
+ echo "${ECHO_T}\"$FIND_PROC\"" >&6
+@@ -7907,7 +7874,6 @@
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+-LIBS="-lc_r  $LIBS"
+ cat >conftest.$ac_ext <<_ACEOF
+ #line 7912 "configure"
+ #include "confdefs.h"
+@@ -7955,7 +7921,6 @@
+ #define HAVE_LIBC_R 1
  EOF
  
 -  LIBS="-lc_r $LIBS"
  
- else
-   echo "$ac_t""no" 1>&6
-@@ -6154,28 +6122,6 @@
  fi
  
+@@ -8312,29 +8277,6 @@
+ 
+ fi
  
 -# Build optimized or debug version ?
 -# First check for gcc and g++
--if test "$ac_cv_prog_gcc" = "yes"
+-if test "$ac_cv_c_compiler_gnu" = "yes"
 -then
 -  DEBUG_CFLAGS="-g"
 -  DEBUG_OPTIMIZE_CC="-O"
@@ -83,50 +93,54 @@
 -  DEBUG_OPTIMIZE_CXX=""
 -  OPTIMIZE_CXXFLAGS="-O"
 -fi
+-
  # Check whether --with-debug or --without-debug was given.
  if test "${with_debug+set}" = set; then
    withval="$with_debug"
-@@ -6856,10 +6802,6 @@
- ac_link='${CXX-g++} -o conftest${ac_exeext} $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
- cross_compiling=$ac_cv_prog_cxx_cross
+@@ -10066,10 +10008,6 @@
+ ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
  
--if test "$ac_cv_prog_gxx" = "yes"
+-if test "$ac_cv_cxx_compiler_gnu" = "yes"
 -then
 -  CXXFLAGS="$CXXFLAGS -Werror"
 -fi
  mysql_cv_btype_last_arg_accept=none
- cat > conftest.$ac_ext <<EOF
- #line 6866 "configure"
-@@ -9019,10 +8961,6 @@
- #do not treat warnings as errors if we are linking agaist other libc
- #this is to work around gcc not being permissive on non-system includes
- #with respect to ANSI C++
--if test "$ac_cv_prog_gxx" = "yes" -a "$with_other_libc" = "no" 
--then
--  CXXFLAGS="$CXXFLAGS -Werror"
--fi
- cat > conftest.$ac_ext <<EOF
- #line 9028 "configure"
- #include "confdefs.h"
-@@ -9087,10 +9025,6 @@
- ac_link='${CXX-g++} -o conftest${ac_exeext} $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
- cross_compiling=$ac_cv_prog_cxx_cross
+ cat >conftest.$ac_ext <<_ACEOF
+ #line 10075 "configure"
+@@ -12739,13 +12677,6 @@
+ ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
  
--if test "$ac_cv_prog_gxx" = "yes" -a "$with_other_libc" = "no"
+-# Do not treat warnings as errors if we are linking agaist other libc
+-# this is to work around gcc not being permissive on non-system includes
+-# with respect to ANSI C++
+-if test "$ac_cv_cxx_compiler_gnu" = "yes" -a "$with_other_libc" = "no"
 -then
 -  CXXFLAGS="$CXXFLAGS -Werror"
 -fi
- cat > conftest.$ac_ext <<EOF
- #line 9096 "configure"
+ cat >conftest.$ac_ext <<_ACEOF
+ #line 12750 "configure"
  #include "confdefs.h"
-@@ -9154,10 +9088,6 @@
- ac_link='${CXX-g++} -o conftest${ac_exeext} $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
- cross_compiling=$ac_cv_prog_cxx_cross
+@@ -12822,10 +12753,6 @@
+ ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
  
--if test "$ac_cv_prog_gxx" = "yes" -a "$with_other_libc" = "no"
+-if test "$ac_cv_cxx_compiler_gnu" = "yes" -a "$with_other_libc" = "no"
 -then
 -  CXXFLAGS="$CXXFLAGS -Werror"
 -fi
- cat > conftest.$ac_ext <<EOF
- #line 9163 "configure"
+ cat >conftest.$ac_ext <<_ACEOF
+ #line 12830 "configure"
+ #include "confdefs.h"
+@@ -12901,10 +12828,6 @@
+ ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+ 
+-if test "$ac_cv_cxx_compiler_gnu" = "yes" -a "$with_other_libc" = "no"
+-then
+-  CXXFLAGS="$CXXFLAGS -Werror"
+-fi
+ cat >conftest.$ac_ext <<_ACEOF
+ #line 12909 "configure"
  #include "confdefs.h"
