- Fix build with iconv
PR:		153670
Submitted by:	Gleb Sushko <neuroworker@gmail.com> (maintainer)

diff --git a/games/instead/files/patch-configure b/games/instead/files/patch-configure
--- a/games/instead/files/patch-configure
+++ b/games/instead/files/patch-configure
@@ -1,5 +1,5 @@
---- configure.sh	2010-10-12 19:06:42.000000000 +0800
-+++ configure.sh	2010-12-24 02:55:29.000000000 +0700
+--- configure.sh.orig	2010-10-12 19:06:42.000000000 +0800
++++ configure.sh	2011-01-04 12:04:35.000000000 +0700
 @@ -1,4 +1,4 @@
 -#!/bin/bash
 +#!/bin/sh
@@ -35,7 +35,40 @@
  fi
  
  
-@@ -140,20 +140,20 @@
+@@ -109,30 +109,8 @@
+ echo "ok"
+ rm -f /tmp/sdl-test.c /tmp/sdl-test
+ 
+-cat << EOF >/tmp/iconv-test.c
+-#include <iconv.h>
+-int main(int argc, char **argv)
+-{
+-	iconv_open("","");
+-}
+-EOF
+-echo $cc
+-echo -n "Checking iconv...("
+-echo -n "$cc /tmp/iconv-test.c -o iconv-test)..."
+-if ! $cc /tmp/iconv-test.c -o /tmp/iconv-test; then
+-	if ! $cc /tmp/iconv-test.c -liconv -o /tmp/iconv-test; then
+-		echo -n "failed. Build without iconv.".
+-	else
+-		CFLAGS="$CFLAGS -D_HAVE_ICONV"
+-		LDFLAGS="$LDFLAGS -liconv"
+-		echo "ok, with -liconv"
+-	fi
+-else
+-	CFLAGS="$CFLAGS -D_HAVE_ICONV"
+-	echo "ok"
+-fi
+-
+-rm -f /tmp/iconv-test.c /tmp/iconv-test
++#build with iconv
++CFLAGS="$CFLAGS -D_HAVE_ICONV"
+ 
+ if ! make clean >/dev/null 2>&1; then
+ 	echo " * Warning!!! Can not do make clean..."
+@@ -140,20 +118,20 @@
  echo -n "Generating config.make..."
  echo "# autamatically generated by configure.sh" >config.make
  
@@ -60,7 +93,7 @@
  	echo "SUBDIRS=src/zlib" >> config.make
  	echo "ZLIB_CFLAGS=-I../zlib" >> config.make
  	echo "ZLIB_LFLAGS=../zlib/libz.a" >> config.make
-@@ -169,26 +169,7 @@
+@@ -169,26 +147,7 @@
  echo "SDL_CFLAGS=\$(shell sdl-config --cflags)" >> config.make
  echo "SDL_LFLAGS=\$(shell sdl-config --libs) -lSDL_ttf -lSDL_mixer -lSDL_image" >> config.make
  echo "ok"
@@ -88,7 +121,7 @@
  	
  	rm -f Rules.make
  	ln -s Rules.make.system Rules.make
-@@ -204,16 +185,12 @@
+@@ -204,16 +163,12 @@
  	echo "ICONPATH=\$(DESTDIR)\$(PREFIX)/share/pixmaps" >> config.make
  	echo "DOCPATH=\$(DESTDIR)\$(PREFIX)/share/doc/instead" >> config.make
  	echo "LANGPATH=\$(DATAPATH)/languages" >> config.make
