Make this port build with an empty /usr/local.

diff --git a/net/tinyfugue/files/patch-ac b/net/tinyfugue/files/patch-ac
--- a/net/tinyfugue/files/patch-ac
+++ b/net/tinyfugue/files/patch-ac
@@ -1,6 +1,26 @@
---- unix/tfconfig.orig	Fri Apr  4 11:51:58 1997
-+++ unix/tfconfig	Mon Jun 16 18:00:45 1997
-@@ -211,17 +211,17 @@
+--- unix/tfconfig.orig	Sat Mar  6 16:43:28 1999
++++ unix/tfconfig	Sun Sep 19 19:03:12 1999
+@@ -168,19 +168,14 @@
+ # The cd;pwd is needed to normalize the directory name in case of links, etc.
+ 
+ DIR1=`echo $TF      | sed 's;/[^/]*$;;'`
+-DIR1=`cd $DIR1 && pwd`
+ DIR2=`echo $LIBDIR  | sed 's;/[^/]*$;;'`
+-DIR2=`cd $DIR2 && pwd`
+ DIR3=`echo $SYMLINK | sed 's;/[^/]*$;;'`
+-DIR3=`cd $DIR3 && pwd`
+ 
+ if [ -z "$DIR1" ] || [ -z "$DIR2" ] || [ -z "$DIR3" ]; then
+     echo "Error in directory."
+     exit 1;
+ fi
+ 
+-DIR1=`cd $DIR1 && pwd || { echo "Error in directory $DIR1."; false; }`
+-
+ BUILDTREE=`cd .. && pwd`
+ if echo "${DIR1}/" | egrep "^${BUILDTREE}/" >/dev/null 2>&1 ||
+    echo "${DIR2}/" | egrep "^${BUILDTREE}/" >/dev/null 2>&1 ||
+@@ -223,17 +218,17 @@
  echo
  
  echo 'To change these locations type "n" now and edit the unix/Config file.'
@@ -28,4 +48,4 @@
 +# done
  echo; echo
  
- echo "#define LIBDIR     \"${LIBDIR}\"" >&4
+ rm -f ../src/Makefile ${AOUT}
