Update to 0.4.

diff --git a/www/crawl/files/patch-configure b/www/crawl/files/patch-configure
--- a/www/crawl/files/patch-configure
+++ b/www/crawl/files/patch-configure
@@ -1,9 +1,11 @@
---- configure.in.orig	Wed Jun 20 14:41:44 2001
-+++ configure.in	Wed Jun 20 17:30:07 2001
-@@ -38,11 +38,11 @@
-      ;;
+$FreeBSD$
+
+--- configure.orig	Sun Dec 21 12:18:11 2003
++++ configure	Sun Dec 21 12:18:28 2003
+@@ -2545,11 +2545,11 @@
    *)
-      AC_MSG_RESULT($withval)
+      echo "$as_me:$LINENO: result: $withval" >&5
+ echo "${ECHO_T}$withval" >&6
 -     if test -f $withval/event.h -a -f $withval/libevent.a; then
 +     if test -f $withval/include/event.h -a -f $withval/lib/libevent.a; then
          owd=`pwd`
@@ -13,5 +15,5 @@
 +        EVENTINC="-I$withval/include"
 +        EVENTLIB="-L$withval/lib -levent"
       else
-         AC_ERROR(event.h or libevent.a not found in $withval)
-      fi
+         { { echo "$as_me:$LINENO: error: event.h or libevent.a not found in $withval" >&5
+ echo "$as_me: error: event.h or libevent.a not found in $withval" >&2;}
