- remove duplicate entry of mod_charset_lite [1] - add PCRE_FROM_PORTS to OPTIONS - use @dirrmtry for include/apache22 - workaround plist issues when upgrading, but it's not as safe as I   would expect, it requires more work.
Spotted by:     bland@ [1]

diff --git a/www/apache22/files/patch-Makefile.in b/www/apache22/files/patch-Makefile.in
--- a/www/apache22/files/patch-Makefile.in
+++ b/www/apache22/files/patch-Makefile.in
@@ -1,5 +1,5 @@
 --- Makefile.in.orig	Tue Apr 24 13:08:01 2007
-+++ Makefile.in	Sun Sep  9 11:57:06 2007
++++ Makefile.in	Wed Sep 19 21:28:08 2007
 @@ -31,9 +31,11 @@
  install-conf:
  	@echo Installing configuration files
@@ -31,7 +31,64 @@
  	    	fi; \
  	    	fi; \
  	    done ; \
-@@ -206,12 +208,14 @@
+@@ -117,48 +119,32 @@
+ 	doxygen $(top_srcdir)/docs/doxygen.conf
+ 
+ install-htdocs:
+-	-@if [ -d $(DESTDIR)$(htdocsdir) ]; then \
+-           echo "[PRESERVING EXISTING HTDOCS SUBDIR: $(DESTDIR)$(htdocsdir)]"; \
+-        else \
+-	    echo Installing HTML documents ; \
++	    @echo Installing HTML documents ; \
+ 	    $(MKINSTALLDIRS) $(DESTDIR)$(htdocsdir) ; \
+ 	    if test -d $(htdocs-srcdir) && test "x$(RSYNC)" != "x" && test -x $(RSYNC) ; then \
+ 		$(RSYNC) --exclude .svn -rlpt --numeric-ids $(htdocs-srcdir)/ $(DESTDIR)$(htdocsdir)/; \
+ 	    else \
+ 		test -d $(htdocs-srcdir) && (cd $(htdocs-srcdir) && cp -rp * $(DESTDIR)$(htdocsdir)) ; \
+ 		cd $(DESTDIR)$(htdocsdir) && find . -name ".svn" -type d -print | xargs rm -rf 2>/dev/null || true; \
+-	    fi; \
+-	fi
++	    fi;
+ 
+ install-error:
+-	-@if [ -d $(DESTDIR)$(errordir) ]; then \
+-           echo "[PRESERVING EXISTING ERROR SUBDIR: $(DESTDIR)$(errordir)]"; \
+-        else \
+-	    echo Installing error documents ; \
++	    @echo Installing error documents ; \
+ 	    $(MKINSTALLDIRS) $(DESTDIR)$(errordir) ; \
+ 	    cd $(top_srcdir)/docs/error && cp -rp * $(DESTDIR)$(errordir) ; \
+-	    test "x$(errordir)" != "x" && cd $(DESTDIR)$(errordir) && find . -name ".svn" -type d -print | xargs rm -rf 2>/dev/null || true; \
+-	fi
++	    test "x$(errordir)" != "x" && cd $(DESTDIR)$(errordir) && find . -name ".svn" -type d -print | xargs rm -rf 2>/dev/null || true; 
+ 
+ install-icons:
+-	-@if [ -d $(DESTDIR)$(iconsdir) ]; then \
+-           echo "[PRESERVING EXISTING ICONS SUBDIR: $(DESTDIR)$(iconsdir)]"; \
+-        else \
+-	    echo Installing icons ; \
++	    @echo Installing icons ; \
+ 	    $(MKINSTALLDIRS) $(DESTDIR)$(iconsdir) ; \
+ 	    cd $(top_srcdir)/docs/icons && cp -rp * $(DESTDIR)$(iconsdir) ; \
+-	    test "x$(iconsdir)" != "x" && cd $(DESTDIR)$(iconsdir) && find . -name ".svn" -type d -print | xargs rm -rf 2>/dev/null || true; \
+-	fi
++	    test "x$(iconsdir)" != "x" && cd $(DESTDIR)$(iconsdir) && find . -name ".svn" -type d -print | xargs rm -rf 2>/dev/null || true; 
+ 
+ install-cgi:
+-	-@if [ -d $(DESTDIR)$(cgidir) ];then \
+-	    echo "[PRESERVING EXISTING CGI SUBDIR: $(DESTDIR)$(cgidir)]"; \
+-	else \
+-	   echo Installing CGIs ; \
++	   @echo Installing CGIs ; \
+ 	   $(MKINSTALLDIRS) $(DESTDIR)$(cgidir) ; \
+ 	   cd $(top_srcdir)/docs/cgi-examples && cp -rp * $(DESTDIR)$(cgidir) ; \
+-	   test "x$(cgidir)" != "x" && cd $(DESTDIR)$(cgidir) && find . -name ".svn" -type d -print | xargs rm -rf 2>/dev/null || true; \
+-	fi
++	   test "x$(cgidir)" != "x" && cd $(DESTDIR)$(cgidir) && find . -name ".svn" -type d -print | xargs rm -rf 2>/dev/null || true;
+ 
+ install-other:
+ 	@test -d $(DESTDIR)$(logfiledir) || $(MKINSTALLDIRS) $(DESTDIR)$(logfiledir)
+@@ -206,12 +192,14 @@
  	@test -d $(DESTDIR)$(manualdir)   || $(MKINSTALLDIRS) $(DESTDIR)$(manualdir)
  	@cp -p $(top_srcdir)/docs/man/*.1 $(DESTDIR)$(mandir)/man1
  	@cp -p $(top_srcdir)/docs/man/*.8 $(DESTDIR)$(mandir)/man8
