Adjust mysql's homedirectory if already exists.

diff --git a/databases/mysql51-server/pkg-install b/databases/mysql51-server/pkg-install
--- a/databases/mysql51-server/pkg-install
+++ b/databases/mysql51-server/pkg-install
@@ -25,6 +25,13 @@ POST-INSTALL)
 
 	if pw user show "${USER}" 2>/dev/null; then
 		echo "You already have a user \"${USER}\", so I will use it."
+		if pw usermod ${USER} -d ${DB_DIR}
+		then
+			echo "Changed home directory of \"${USER}\" to \"${DB_DIR}\""
+		else
+			echo "Changing home directory of \"${USER}\" to \"${DB_DIR}\" failed..."
+			exit 1
+		fi
 	else
 		if pw useradd ${USER} -u ${UID} -g ${GROUP} -h - \
 			-d ${DB_DIR} -s /sbin/nologin -c "MySQL Daemon"
