Update to 2.2.5.5.

diff --git a/x11/gdm2/files/patch-configure b/x11/gdm2/files/patch-configure
--- a/x11/gdm2/files/patch-configure
+++ b/x11/gdm2/files/patch-configure
@@ -1,61 +1,58 @@
---- configure.orig	Thu Jan 10 10:45:20 2002
-+++ configure	Thu Jan 10 10:55:39 2002
-@@ -11066,6 +11066,58 @@
- 
+
+$FreeBSD$
+
+--- configure	2002/03/13 23:11:57	1.3
++++ configure	2002/03/13 23:16:32
+@@ -8575,6 +8575,52 @@
  fi
  
-+for ac_header in sys/types.h login_cap.h
+ 
++for ac_hdr in sys/types.h login_cap.h
 +do
-+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
-+echo "$as_me:11072: checking for $ac_header" >&5
-+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
-+if eval "test \"\${$as_ac_Header+set}\" = set"; then
-+	echo $ECHO_N "(cached) $ECHO_C" >&6
++ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
++echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
++echo "configure:8583: checking for $ac_hdr" >&5
++if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
++  echo $ac_n "(cached) $ac_c" 1>&6
 +else
-+	cat >conftest.$ac_ext <<_ACEOF
-+#line 11078 "configure"
++  cat > conftest.$ac_ext <<EOF
++#line 8588 "configure"
 +#include "confdefs.h"
-+#include <$ac_header>
-+_ACEOF
-+if { (eval echo "$as_me:11082: \"$ac_cpp conftest.$ac_ext\"") >&5
-+	(eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-+	ac_status=$?
-+	egrep -v '^ *\+' conftest.er1 >conftest.err
-+	rm -f conftest.er1
-+	cat conftest.err >&5
-+	echo "$as_me:11088: \$? = $ac_status" >&5
-+	(exit $ac_status); } >/dev/null; then
-+	if test -s conftest.err; then
-+		ac_cpp_err=$ac_c_preproc_warn_flag
-+	else
-+		ac_cpp_err=
-+	fi
-+else
-+	ac_cpp_err=yes
-+fi
-+if test -z "$ac_cpp_err"; then
-+	eval "$as_ac_Header=yes"
-+else
-+	echo "$as_me: failed program was:" >&5
-+	cat conftest.$ac_ext >&5
-+	eval "$as_ac_Header=no"
-+fi
-+rm -f conftest.err conftest.$ac_ext
-+fi
-+echo "$as_me:11107: result: `eval echo '${'$as_ac_Header'}'`" >&5
-+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
-+if test `eval echo '${'$as_ac_Header'}'` = yes; then
-+	 cat >>confdefs.h <<EOF
-+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
++#include <$ac_hdr>
 +EOF
-+
-+			LIBS="$LIBS -lutil"
-+		cat >>confdefs.h <<\EOF
++ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
++{ (eval echo configure:8593: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
++ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
++if test -z "$ac_err"; then
++  rm -rf conftest*
++  eval "ac_cv_header_$ac_safe=yes"
++else
++  echo "$ac_err" >&5
++  echo "configure: failed program was:" >&5
++  cat conftest.$ac_ext >&5
++  rm -rf conftest*
++  eval "ac_cv_header_$ac_safe=no"
++fi
++rm -f conftest*
++fi
++if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
++  echo "$ac_t""yes" 1>&6
++    ac_tr_hdr=HAVE_`echo $ac_hdr | sed 'y%abcdefghijklmnopqrstuvwxyz./-%ABCDEFGHIJKLMNOPQRSTUVWXYZ___%'`
++  cat >> confdefs.h <<EOF
++#define $ac_tr_hdr 1
++EOF
++ 
++		 LIBS="$LIBS -lutil"
++		 cat >> confdefs.h <<\EOF
 +#define HAVE_LOGINCAP 1
 +EOF
++
++else
++  echo "$ac_t""no" 1>&6
 +fi
 +done
 +
++
  if test x$enable_authentication_scheme = xpam -a x$have_pam = xno ; then
- 	{ { echo "$as_me:11070: error: PAM support requested but not available" >&5
- echo "$as_me: error: PAM support requested but not available" >&2;}
+ 	{ echo "configure: error: PAM support requested but not available" 1>&2; exit 1; }
+ fi
