Replace CONFLICTS=gcc-2.95.*, which actually is too late to prevent us running into build problems, by an earlier check (pre-extract).
Suggested by:	pav

diff --git a/lang/gcc43/Makefile b/lang/gcc43/Makefile
--- a/lang/gcc43/Makefile
+++ b/lang/gcc43/Makefile
@@ -28,9 +28,6 @@ LIB_DEPENDS=	gmp.7:${PORTSDIR}/math/libgmp4 \
 SUFFIX=		43
 LATEST_LINK?=	gcc${SUFFIX}${PKGNAMESUFFIX}
 NOT_FOR_ARCHS=	alpha ia64
-# Building libgcj with lang/gcc295 installed is causing a failure about
-# "hidden symbol `__eprintf'" in libgcc.a(_eprintf.o).
-CONFLICTS=	gcc-2.95.*
 USE_BISON=	build
 USE_BZIP2=	yes
 USE_GMAKE=	yes
@@ -146,6 +143,14 @@ pre-everything::
 	  exit 1; \
 	fi
 .endif
+
+pre-extract:
+	@# Building libgcj with lang/gcc295 installed is causing a failure
+	@# about "hidden symbol `__eprintf'" in libgcc.a(_eprintf.o).
+	@if type gcc295 >/dev/null ; then \
+	  echo "This port will not build in the presence of lang/gcc295."; \
+	  exit 1; \
+	fi
 
 post-patch:
 	@${REINPLACE_CMD} -e 's|\(const char version_string.*\)";|\1 [FreeBSD]";|' \
