Not deleting the PID file but emptying it. Reasoning behind this is that /var/run is not writable to 'www'. Also cleaned things up here and there.
Bumped PORTREVISION.

diff --git a/www/orion-devel/files/orionctl b/www/orion-devel/files/orionctl
--- a/www/orion-devel/files/orionctl
+++ b/www/orion-devel/files/orionctl
@@ -91,20 +91,27 @@ app() {
 
 start() {
 	# Make sure the application is not started previously
-	if [ -e %%PID_FILE%% ]; then
-		error "Found %%APP_TITLE%% PID file at %%PID_FILE%%. It is probably already running."
+	if [ -s %%PID_FILE%% ]; then
+		error "%%APP_TITLE%% is probably already running. The PID file at %%PID_FILE%% is not empty."
 		exit 1
 	fi
 
 	# Perform the checks that apply to stopping as well
 	checks
 
-	# Create the process ID file
-	rm -f %%PID_FILE%%
-	touch %%PID_FILE%%
-	chown %%USER_NAME%%:%%GROUP_NAME%% %%PID_FILE%%
+	# Fix the permissions for the PID file, just in case
+	chown %%USER%%:%%GROUP%% %%PID_FILE%%
 	chmod 600 %%PID_FILE%%
+
+	# Start the application
+	echo -n ">> Starting %%APP_TITLE%%..."
 	(cd ${APP_HOME} && ${JAVA_CMD} -jar ${JAR_FILE} & echo $! > %%PID_FILE%%) >> ${STDOUT_LOG} 2>> ${STDERR_LOG}
+	if [ $? -eq 0 ]; then
+		echo " [ DONE ]"
+	else
+		echo " [ FAILED ]"
+		exit 13
+	fi
 }
 
 
@@ -120,12 +127,25 @@ stop() {
 	checks
 
 	# Kill the running program
-	if [ ! -e %%PID_FILE%% ]; then
-		error "Unable to find %%APP_TITLE%% PID file at %%PID_FILE%%. It is probably not running."
+	if [ ! -s %%PID_FILE%% ]; then
+		error "%%APP_TITLE%% is probably not running. The PID file at %%PID_FILE%% is empty."
 		exit 16
 	fi
-	/bin/kill `cat %%PID_FILE%%`
-	rm -f %%PID_FILE%%
+	PID=`cat %%PID_FILE%%`
+	echo -n ">> Killing %%APP_TITLE%% process (${PID})..."
+	/bin/kill ${PID} > /dev/null 2> /dev/null
+	if [ $? -eq 0 ]; then
+		echo " [ DONE ]"
+	else
+		echo " [ FAILED ]"
+	fi
+	echo -n ">> Emptying PID file (%%PID_FILE%%)..."
+	> %%PID_FILE%% 2> /dev/null
+	if [ $? -eq 0 ]; then
+		echo " [ DONE ]"
+	else
+		echo " [ FAILED ]"
+	fi
 }
 
 
diff --git a/www/orion/pkg-deinstall b/www/orion/pkg-deinstall
--- a/www/orion/pkg-deinstall
+++ b/www/orion/pkg-deinstall
@@ -13,16 +13,27 @@
 
 # Make sure we're in the right stage of the process
 if [ "$2" = "DEINSTALL" ]; then
+
 	# Kill Orion if it is still running
 	PID_FILE=/var/run/orion.pid
-	if [ -e ${PID_FILE} ]; then
-		echo -n "Orion Server is still running."
-		/bin/kill `cat ${PID_FILE}`
-		rm -f ${PID_FILE}
-		echo " Stopped."
+	if [ -s ${PID_FILE} ]; then
+		PID=`cat ${PID_FILE}`
+		echo -n ">> Killing Orion Server process (${PID})..."
+		/bin/kill ${PID} > /dev/null 2> /dev/null
+		if [ $? -eq 0 ]; then
+			echo " [ DONE ]"
+		else
+			echo " [ FAILED ]"
+		fi
+		echo -n ">> Removing PID file (${PID_FILE})..."
+		rm ${PID_FILE} > /dev/null 2> /dev/null
+		if [ $? -eq 0 ]; then
+			echo " [ DONE ]"
+		else
+			echo " [ FAILED ]"
+		fi
 	fi
 fi
-
 
 if [ "$2" = "POST-DEINSTALL" ]; then
 	# If the user exists, then display a message
