- Update to 1.7
PR:		ports/61599
Submitted by:	No-Name <arundel@gmx.net> (maintainer)

diff --git a/emulators/vba/files/patch-ab b/emulators/vba/files/patch-ab
--- a/emulators/vba/files/patch-ab
+++ b/emulators/vba/files/patch-ab
@@ -1,64 +1,103 @@
-*** configure.orig	Sat Aug 23 16:20:50 2003
---- configure	Fri Sep  5 01:50:01 2003
+*** configure.orig	Sun Jan 11 22:22:03 2004
+--- configure	Sun Jan 11 22:24:51 2004
 ***************
-*** 2726,2784 ****
+*** 5424,5521 ****
   
   fi
   
-- echo $ac_n "checking for socklen_t""... $ac_c" 1>&6
-- echo "configure:2731: checking for socklen_t" >&5
-- cat > conftest.$ac_ext <<EOF
-- #line 2733 "configure"
-- #include "confdefs.h"
+- echo "$as_me:$LINENO: checking for socklen_t" >&5
+- echo $ECHO_N "checking for socklen_t... $ECHO_C" >&6
+- cat >conftest.$ac_ext <<_ACEOF
+- #line $LINENO "configure"
+- /* confdefs.h.  */
+- _ACEOF
+- cat confdefs.h >>conftest.$ac_ext
+- cat >>conftest.$ac_ext <<_ACEOF
+- /* end confdefs.h.  */
 - #include <sys/socket.h>
 - socklen_t x;
 - 
-- int main() {
+- int
+- main ()
+- {
 - 
-- ; return 0; }
-- EOF
-- if { (eval echo configure:2742: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
--   rm -rf conftest*
--   echo "$ac_t""yes" 1>&6
+-   ;
+-   return 0;
+- }
+- _ACEOF
+- rm -f conftest.$ac_objext
+- if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+-   (eval $ac_compile) 2>&5
+-   ac_status=$?
+-   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-   (exit $ac_status); } &&
+-          { ac_try='test -s conftest.$ac_objext'
+-   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+-   (eval $ac_try) 2>&5
+-   ac_status=$?
+-   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-   (exit $ac_status); }; }; then
+-   echo "$as_me:$LINENO: result: yes" >&5
+- echo "${ECHO_T}yes" >&6
 - else
--   echo "configure: failed program was:" >&5
--   cat conftest.$ac_ext >&5
--   rm -rf conftest*
--   
-- cat > conftest.$ac_ext <<EOF
-- #line 2751 "configure"
-- #include "confdefs.h"
+-   echo "$as_me: failed program was:" >&5
+- sed 's/^/| /' conftest.$ac_ext >&5
+- 
+- 
+- cat >conftest.$ac_ext <<_ACEOF
+- #line $LINENO "configure"
+- /* confdefs.h.  */
+- _ACEOF
+- cat confdefs.h >>conftest.$ac_ext
+- cat >>conftest.$ac_ext <<_ACEOF
+- /* end confdefs.h.  */
 - #include <sys/socket.h>
 - int accept (int, struct sockaddr *, size_t *);
 - 
-- int main() {
+- int
+- main ()
+- {
 - 
-- ; return 0; }
-- EOF
-- if { (eval echo configure:2760: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
--   rm -rf conftest*
--   
-- echo "$ac_t""size_t" 1>&6
-- cat >> confdefs.h <<\EOF
+-   ;
+-   return 0;
+- }
+- _ACEOF
+- rm -f conftest.$ac_objext
+- if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+-   (eval $ac_compile) 2>&5
+-   ac_status=$?
+-   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-   (exit $ac_status); } &&
+-          { ac_try='test -s conftest.$ac_objext'
+-   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+-   (eval $ac_try) 2>&5
+-   ac_status=$?
+-   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-   (exit $ac_status); }; }; then
+- 
+- echo "$as_me:$LINENO: result: size_t" >&5
+- echo "${ECHO_T}size_t" >&6
+- cat >>confdefs.h <<\_ACEOF
 - #define socklen_t size_t
-- EOF
+- _ACEOF
 - 
 - else
--   echo "configure: failed program was:" >&5
--   cat conftest.$ac_ext >&5
--   rm -rf conftest*
--   
-- echo "$ac_t""int" 1>&6
-- cat >> confdefs.h <<\EOF
+-   echo "$as_me: failed program was:" >&5
+- sed 's/^/| /' conftest.$ac_ext >&5
+- 
+- 
+- echo "$as_me:$LINENO: result: int" >&5
+- echo "${ECHO_T}int" >&6
+- cat >>confdefs.h <<\_ACEOF
 - #define socklen_t int
-- EOF
+- _ACEOF
 - 
 - fi
-- rm -f conftest*
+- rm -f conftest.$ac_objext conftest.$ac_ext
 - fi
-- rm -f conftest*
+- rm -f conftest.$ac_objext conftest.$ac_ext
 - 
-  echo $ac_n "checking whether byte ordering is bigendian""... $ac_c" 1>&6
-  echo "configure:2784: checking whether byte ordering is bigendian" >&5
-  if eval "test \"`echo '$''{'ac_cv_c_bigendian'+set}'`\" = set"; then
---- 2726,2731 ----
+  echo "$as_me:$LINENO: checking whether byte ordering is bigendian" >&5
+  echo $ECHO_N "checking whether byte ordering is bigendian... $ECHO_C" >&6
+  if test "${ac_cv_c_bigendian+set}" = set; then
+--- 5424,5429 ----
