- Update INN to 2.5.2 release - Handle deprecated perl declarations [1]
PR:		166031 [1]
Submitted by:	Joe Horn <joehorn AT gmail DOT com> [1]
Suggested by:	cy (via email, most part of update)

diff --git a/news/inn/files/patch-configure b/news/inn/files/patch-configure
--- a/news/inn/files/patch-configure
+++ b/news/inn/files/patch-configure
@@ -1,42 +1,23 @@
---- configure.orig	2008-06-30 04:56:57.000000000 +1100
-+++ configure	2008-08-18 12:35:35.000000000 +1100
-@@ -7535,36 +7535,9 @@
- 	    done
-         done
+--- configure.orig	2010-03-25 06:10:36.000000000 +1000
++++ configure	2012-06-27 21:44:02.000000000 +1100
+@@ -15762,7 +15762,7 @@
+ echo $ECHO_N "checking for Berkeley DB location... $ECHO_C" >&6; }
+     if test x"$DB_DIR" = xyes ; then
+         for dir in $prefix /usr/local /usr ; do
+-            if test -f "$dir/include/db.h" ; then
++            if test -f "$dir/include/${DB_VER}/db.h" ; then
+                 DB_DIR=$dir
+                 break
+             fi
+@@ -15773,9 +15773,9 @@
+ echo "$as_me: error: cannot find Berkeley DB" >&2;}
+    { (exit 1); exit 1; }; }
+     else
+-        DB_CPPFLAGS="-I$DB_DIR/include"
++        DB_CPPFLAGS="-I$DB_DIR/include/${DB_VER}"
+         DB_LDFLAGS="-L$DB_DIR/lib"
+-        DB_LIBS="-ldb"
++        DB_LIBS="-l${DB_LIB}"
+         { echo "$as_me:$LINENO: result: $DB_DIR" >&5
+ echo "${ECHO_T}$DB_DIR" >&6; }
      fi
--    if test x"$BERKELEY_DB_DIR" = xyes ; then
--        for v in db46 db45 db44 db43 db42 db41 db4 db3 db2 ; do
--            if test -d "/usr/local/include/$v" ; then
--                BERKELEY_DB_LDFLAGS="-L/usr/local/lib"
--                BERKELEY_DB_CFLAGS="-I/usr/local/include/$v"
--                BERKELEY_DB_LIB="-l$v"
--                echo "$ac_t""FreeBSD locations" 1>&6
--                break
--            fi
--        done
--        if test x"$BERKELEY_DB_LIB" = x ; then
--            for v in db44 db43 db42 db41 db4 db3 db2 ; do
--                if test -d "/usr/include/$v" ; then
--                    BERKELEY_DB_CFLAGS="-I/usr/include/$v"
--                    BERKELEY_DB_LIB="-l$v"
--                    echo "$ac_t""Linux locations" 1>&6
--                    break
--                fi
--            done
--            if test x"$BERKELEY_DB_LIB" = x ; then        
--                BERKELEY_DB_LIB=-ldb
--                echo "$ac_t""trying -ldb" 1>&6
--            fi
--        fi
--    else
--        BERKELEY_DB_LDFLAGS="-L$BERKELEY_DB_DIR/lib"
--        BERKELEY_DB_CFLAGS="-I$BERKELEY_DB_DIR/include"
--        BERKELEY_DB_LIB="-ldb"
--        echo "$ac_t""$BERKELEY_DB_DIR" 1>&6
--    fi
-+         BERKELEY_DB_LDFLAGS="-L$BERKELEY_DB_DIR/lib"
-+         BERKELEY_DB_CFLAGS="-I$BERKELEY_DB_DIR/include/${DB_VER}"
-+         BERKELEY_DB_LIB="-l${DB_LIB}"
-     cat >> confdefs.h <<\EOF
- #define USE_BERKELEY_DB 1
- EOF
