- Update to 0.27 - Add staging support - Convert optional dependencies to new format - Add a few clang patches but switch to USE_GCC=any because there's quite some work left (contributors?)

diff --git a/audio/mythplugin-mythmusic/files/patch-configure b/audio/mythplugin-mythmusic/files/patch-configure
--- a/audio/mythplugin-mythmusic/files/patch-configure
+++ b/audio/mythplugin-mythmusic/files/patch-configure
@@ -1,5 +1,5 @@
---- configure.orig	2012-04-10 07:29:22.000000000 +0200
-+++ configure	2012-04-13 22:04:24.501203271 +0200
+--- configure.orig	2013-09-18 20:06:08.000000000 +0000
++++ configure	2013-10-16 15:21:39.000000000 +0000
 @@ -227,6 +227,10 @@
      append ECXXFLAGS "$@"
  }
@@ -11,18 +11,18 @@
  check_cxx(){
      log check_cxx "$@"
      cat > $TMPCXX
-@@ -555,6 +559,10 @@
- CXXPPFLAGS=${CXXPPFLAGS#CXXPPFLAGS=}
- OPENGLV=$(cat mythconfig.mak | grep -e "^CONFIG_OPENGL_VIDEO=yes")
+@@ -561,6 +565,10 @@
+ EXTRALIBS=$(cat mythconfig.mak | grep -e "^EXTRALIBS=")
+ EXTRALIBS=${EXTRALIBS#EXTRALIBS=}
  
 +add_cppflags "-I${prefix}/include"
 +add_cxxflags "-I${prefix}/include"
 +add_ldflags "-L${prefix}/lib"
 +
- if ! is_qmake4 $qmake; then
-     is_qmake4 qmake-qt4 && qmake=qmake-qt4 || die "qmake for Qt4.6 or newer not found.\nPlease specify the correct qmake with --qmake="
- fi
-@@ -646,6 +654,7 @@
+ if ! is_qmake5 $qmake ; then
+   if ! is_qmake4 $qmake; then
+       is_qmake4 qmake-qt4 && qmake=qmake-qt4 || die "qmake for Qt4.8 or newer not found.\nPlease specify the correct qmake with --qmake="
+@@ -653,6 +661,7 @@
          echo "MythMusic requires FLAC."
      fi
  
