- Update to 0.24.8 - Cleanup Makefile to use modern constructs (COPYTREE_SHARE, PORTDOCS, etc) - Fix typos in pkg-message - Cleanup properly in pkg-deinstall
PR:		ports/129185 (based upon)
Submitted by:	l.messner@physik.tu-berlin.de
Approved by:	maintainer timeout (3+ months)

diff --git a/sysutils/puppet/files/pkg-install.in b/sysutils/puppet/files/pkg-install.in
--- a/sysutils/puppet/files/pkg-install.in
+++ b/sysutils/puppet/files/pkg-install.in
@@ -8,6 +8,7 @@ UID=814
 GID=$UID
 
 RUNDIR=%%PUPPET_RUNDIR%%
+WORKDIR=%%PUPPET_WORKDIR%%
 
 PW="pw"
 CHOWN="chown"
@@ -36,7 +37,18 @@ if [ "$2" = "PRE-INSTALL" ]; then
 	fi
 
 elif [ "$2" = "POST-INSTALL" ]; then
-	${INSTALL_DIR} ${RUNDIR}
+	if [ -d ${RUNDIR} ]; then
+		echo "=> ${RUNDIR} already exists."
+	else
+		echo -n "=> Creating RUNDIR ${RUNDIR}... "
+		${INSTALL_DIR} ${RUNDIR} || echo "failed"
+	fi
+	if [ -d ${WORKDIR} ]; then
+		echo "=> ${WORKDIR} already exists."
+	else
+		echo -n "=> Creating WORKDIR ${WORKDIR}... "
+		${INSTALL_DIR} ${WORKDIR} || echo "failed"
+	fi
 fi
 
 exit 0
