Cleanup etc. submitted by port maintainer.  Create account automatically if it doesn't exist, and chown everything to the right UID after unpacking.
Submitted by:	maintainer

diff --git a/japanese/Wnn6/pkg-install b/japanese/Wnn6/pkg-install
--- a/japanese/Wnn6/pkg-install
+++ b/japanese/Wnn6/pkg-install
@@ -1,19 +1,184 @@
 #!/bin/sh
-if [ "$2" != "POST-INSTALL" ]; then exit 0; fi
+# an installation script for Wnn6
 
-mkdir -p /usr/local/bin
-mkdir -p /usr/local/lib
-cd /usr/local/bin; rm -f Wnn6; ln -s ${PKG_PREFIX}/OMRONWnn6/Wnn6fbsd Wnn6
-cd /usr/local/lib; rm -f wnn6; ln -s ${PKG_PREFIX}/OMRONWnn6/wnn6fbsd wnn6
-cd ${PKG_PREFIX}/OMRONWnn6/wnn6fbsd/ja_JP; rm -f dic; ln -s ../../wnn6dic dic
-chown -R 127.bin ${PKG_PREFIX}/OMRONWnn6
+check_pw()
+{
+    if which -s pw; then
+	:
+    else
+	cat <<EOF
 
-echo "######################################################################"
-echo "Execute ${PKG_PREFIX}/OMRONWnn6/setup.sh  for startup configuration."
-if [ X${PKG_PREFIX} != X"/usr/local" ]; then
-    echo
-    echo "Warning!!"
-    echo "We made symbolic links from \"/usr/local/bin/Wnn6\" to \"${PKG_PREFIX}/OMRONWnn6/Wnn6fbsd\""
-    echo "and from \"/usr/local/lib/wnn6\" to \"${PKG_PREFIX}/OMRONWnn6/wnn6fbsd\""
-fi
-echo "######################################################################"
+This system looks like a pre-2.2 version of FreeBSD.  We see that it
+is missing the "pw" utility.  We need this utility.  Please get and
+install it, and try again.  You can get the source from:
+
+  ftp://ftp.freebsd.org/pub/FreeBSD/FreeBSD-current/src/usr.sbin/pw.tar.gz
+
+EOF
+	exit 1
+    fi
+}
+
+ask() {
+    local question default answer
+
+    question=$1
+    default=$2
+    if [ -z "${PACKAGE_BUILDING}" ]; then
+	read -p "${question} (y/n) [${default}]? " answer
+    fi
+    if [ x${answer} = x ]; then
+	answer=${default}
+    fi
+    echo ${answer}
+}
+
+yesno() {
+    local dflt question answer
+
+    question=$1
+    dflt=$2
+    while :; do
+	answer=$(ask "${question}" "${dflt}")
+	case "${answer}" in
+	[Yy]*)		return 0;;
+	[Nn]*)		return 1;;
+	esac
+	echo "Please answer yes or no."
+    done
+}
+
+case $2 in
+PRE-INSTALL)
+
+    ## Hack /etc/services ##
+    FILE="/etc/services"
+    # check
+    OK=no
+    HAS_WNN6=no
+    COUNT=1
+    for i in `grep wnn6 $FILE `; do
+	if [ $COUNT = 1 ] && [ X"$i" = X"wnn6" ]; then
+	    HAS_WNN6=yes
+	elif [ $COUNT = 2 ] && [ $HAS_WNN6 = yes ] && \
+		[ X"$i" = X"22273/tcp" ]; then
+	    OK=yes
+	    break
+	fi
+	COUNT=`expr ${COUNT} + 1`
+    done
+    # add an entry for wnn6 to /etc/services
+    if [ $OK = no ]; then
+	echo "This system has no entry for Wnn6 in ${FILE}"
+	if yesno "Would you like to add it automatically?" y; then
+	    mv ${FILE} ${FILE}.bak
+	    (grep -v wnn6 ${FILE}.bak ; \
+		echo "wnn6		22273/tcp	# Wnn6") >> ${FILE}
+	    rm ${FILE}.bak
+	else
+	    echo "Please add 'wnn6 22273/tcp' into ${FILE}, and try again."
+	    exit 1
+	fi
+    fi
+
+    ## Hack /etc/master.passwd ##
+    # check
+    id_69=`id -u 69 2> /dev/null`
+    id_wnn=`id -u wnn 2> /dev/null`
+    if [ X"$id_wnn" = X69 ];then
+	exit 0
+    elif [ X"$id_69" != X ]; then
+cat <<EOF
+
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+This system already has an account whose name is not 'wnn' and ID
+number is 69.
+
+   '`id 69`'
+
+For Wnn6 in this port or package, ID number of 'wnn' has to be 69.
+Please try again after you delete the account.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+EOF
+	exit 1
+    elif [ X"$id_wnn" != X ]; then
+	cat <<EOF
+
+This system has an 'wnn' account whose ID number is $id_wnn.  It seems
+that Wnn4.2 has been already installed.  For Wnn6 in this ports or
+package, ID number of 'wnn' has to be 69.  So we do the following two
+things:
+
+1) You should delete the account.
+
+2) It seems that all of files or directories for Wnn4.2 are in
+    ${PKG_PREFIX}/lib/wnn and ${PKG_PREFIX}/bin.  You should change these ID
+    number from '$id_wnn' to '69'.
+
+    Notice: After doing 1) and 2), we will create a new 'wnn' account
+	    whose ID number is '69'.
+
+EOF
+	if yesno "Would you like to do the above things automatically" y; then
+	    # We need a command 'pw(8)'
+	    check_pw
+	    pw userdel wnn
+	    if [ $? != 0 ]; then
+		echo ""
+		echo "Cannot delete it. Please do it, and try again."
+		exit 1
+	    fi
+	    find ${PKG_PREFIX}/lib/wnn ${PKG_PREFIX}/bin \
+		-user $id_wnn -exec chown 69 {} \;
+	else
+	    echo "Please do those, and try again."
+	    exit 1
+	fi
+    fi
+
+    # add an account 'wnn' to this system
+    echo ""
+    echo "You need an account 'wnn' whose ID number is 69"
+    if yesno "Would you like to create it automatically?" y; then
+	# We need a command 'pw(8)'
+	check_pw
+	pw useradd wnn -u 69 -g 7 -h - -d /nonexistent \
+		-s /nonexistent -c Wnn6 || exit
+    else
+	echo "Please create it, and try again."
+	exit 1
+    fi
+    ;;
+
+POST-INSTALL)
+
+    mkdir -p /usr/local/bin
+    mkdir -p /usr/local/lib
+    cd /usr/local/bin; rm -f Wnn6; ln -s ${PKG_PREFIX}/OMRONWnn6/Wnn6fbsd Wnn6
+    cd /usr/local/lib; rm -f wnn6; ln -s ${PKG_PREFIX}/OMRONWnn6/wnn6fbsd wnn6
+    if [ X${PKG_PREFIX} != X"/usr/local" ]; then
+	echo
+	echo "Warning!!"
+	echo "We made symbolic links from \"/usr/local/bin/Wnn6\" to \"${PKG_PREFIX}/OMRONWnn6/Wnn6fbsd\""
+	echo "and from \"/usr/local/lib/wnn6\" to \"${PKG_PREFIX}/OMRONWnn6/wnn6fbsd\""
+    fi
+    cd ${PKG_PREFIX}/OMRONWnn6/wnn6fbsd/ja_JP; rm -f dic; ln -s ../../wnn6dic dic
+    chown -R wnn ${PKG_PREFIX}/OMRONWnn6
+
+    ## create a startup script ##
+    wnnserver=/usr/local/bin/Wnn6/jserver
+    wnnname=Wnn6
+    startup_script=${PKG_PREFIX}/etc/rc.d/${wnnname}.sh
+    if [ ! -f ${startup_script} ]; then
+      echo "Installing ${startup_script} startup file."
+      echo '#!/bin/sh' > ${startup_script};
+      echo "wnn=${wnnserver}" >> ${startup_script};
+      echo 'if [ -f $wnn ]; then' >> ${startup_script};
+      echo "    echo -n ' ${wnnname}'" >> ${startup_script};
+      echo '    $wnn' >> ${startup_script};
+      echo "fi" >> ${startup_script};
+      chmod 755 ${startup_script}
+      chown bin.bin ${startup_script}
+    fi
+    ;;
+esac
