Add the compression enhancement from junkbuster-zlib (I see zero reason to have to have a seperate port rather than enhance this one).
This patched version of Junkbuster now has the ability to automatically
compress text/html and text/plain documents to save downstream modem/network
bandwidth.  It also allows one to specify appearance of blocked GIFs.

diff --git a/www/junkbuster/files/junkbuster.sh.in b/www/junkbuster/files/junkbuster.sh.in
--- a/www/junkbuster/files/junkbuster.sh.in
+++ b/www/junkbuster/files/junkbuster.sh.in
@@ -1,11 +1,21 @@
 #!/bin/sh
+# $CVSHeader$
 
 case $1 in
 start)
-	test -d JDIR -a -x PREFIX/sbin/junkbuster -a -f JDIR/configfile || exit 1
-	cd JDIR
-	su -m nobody -c "PREFIX/sbin/junkbuster configfile &"
-	echo -n " junkbuster"
+	if [ -d %%JDIR%% \
+	     -a -x %%PREFIX%%/sbin/junkbuster \
+	     -a -f %%JDIR%%/configfile ]; then
+		: seems OK
+	else
+		echo >&2 "$0: missing files!"
+		exit 1
+	fi
+	cd %%JDIR%%
+	su -m nobody -c "%%PREFIX%%/sbin/junkbuster configfile &" \
+	    >/dev/null \
+	&& echo -n " junkbuster" \
+	|| echo " junkbuster FAILED TO START"
 	;;
 stop)
 	killall junkbuster && echo -n " junkbuster"
