*/*: Change dependency from japanese/anthy to japanese/anthy-unicode
It should have been done at the removal of japanese/anthy.

Reported by:	thierry

diff --git a/chinese/gcin/files/patch-configure b/chinese/gcin/files/patch-configure
--- a/chinese/gcin/files/patch-configure
+++ b/chinese/gcin/files/patch-configure
@@ -15,6 +15,15 @@
      exit
  fi
  
+@@ -172,7 +172,7 @@ echo -n ".... Testing anthy    :  "
+ fi
+ 
+ echo -n ".... Testing anthy    :  "
+-USE_ANTHY=`pkg-config --libs anthy`
++USE_ANTHY=`pkg-config --libs anthy-unicode`
+ if [ $? != 0 ]; then
+   USE_ANTHY=N
+   echo "Not found. It's ok if you don't want anthy support."
 @@ -232,7 +232,7 @@ QT4_IM='N'
  
  
