Support builds using zfs and tmpfs backing store
zfs:

* Enabled by use_zfs=1 in portbuild.conf

* Populate build chroots by cloning a zfs snapshot instead of maintaining
  many duplicate copies.  In principle this is very efficient since
  everything is copy-on-write and zfs snapshot creation is almost
  instantaneous.  There might be additional overheads from building on zfs
  though.  Currently the snapshot base is hard-wired to y/${branch}@base
  but should be parametrized.  This also must be populated beforehand, e.g.
  during machine startup

* Clean build chroots by just destroying the snapshot.

tmpfs:

* Enabled by use_tmpfs=1 and tmpfs_size in portbuild.conf

* The previous md strategy of mounting in used/, populating and then
  remounting (to avoid possible races from multiple builds claiming the
  same chroot) doesn't work here because tmpfs instances are destroyed at
  umount.  I am not entirely sure the simpler approach is free from races.

diff --git a/Tools/portbuild/scripts/claim-chroot b/Tools/portbuild/scripts/claim-chroot
--- a/Tools/portbuild/scripts/claim-chroot
+++ b/Tools/portbuild/scripts/claim-chroot
@@ -27,7 +27,11 @@ buildenv ${pb} ${arch} ${branch}
 
 pkgname=$(basename $1 ${PKGSUFFIX})
 
-chrootdir=${buildroot}/${branch}/chroot
+if [ "${use_zfs}" = 1 ]; then
+  chrootdir=${buildroot}/${branch}
+else
+  chrootdir=${buildroot}/${branch}/chroot
+fi
 
 # Perform initial sanity check
 
@@ -73,7 +77,11 @@ done
 chrootnum=$$
 # If we didn't find a pre-existing directory, create and claim a new one.
 while [ ${found} != 1 ]; do
-  if [ "${use_md_swap}" = "1" ]; then
+  if [ "${use_zfs}" = "1" ]; then
+    chroot=${chrootdir}/${chrootnum}
+    zfs clone y/${branch}@base $(echo ${chrootdir} | sed -e 's,/,,')/${chrootnum}
+    mkdir ${chroot}/used
+  elif [ "${use_md_swap}" = "1" ]; then
     unit=$(mdconfig -a -t swap -s ${md_size})
     newfs /dev/${unit} > /dev/null
     chrootnum=$(echo ${unit} | sed 's,md,,')
@@ -85,14 +93,21 @@ while [ ${found} != 1 ]; do
     touch ${chroot}/used/used/${pkgname}
     umount ${chroot}/used
     mount -o async /dev/${unit} ${chroot}/
+    touch ${chroot}/.notready
   else
     chrootnum=$(($chrootnum+1))
     chroot=${chrootdir}/${chrootnum}
-    mkdir -p ${chroot} 2>/dev/null || continue
+    mkdir -p ${chrootdir} 2> /dev/null || continue
+    mkdir ${chroot} 2>/dev/null || continue
     mkdir ${chroot}/used 2>/dev/null || continue
+    touch ${chroot}/.notready
+  fi
+  if [ "${use_tmpfs}" = "1" ]; then
+    mount -t tmpfs -o "size=${tmpfs_size}" foo ${chroot}
+    mkdir ${chroot}/used 2>/dev/null || echo "ERROR: mkdir race"
+    touch ${chroot}/.notready
   fi
   touch ${chroot}/used/${pkgname}
-  touch ${chroot}/.notready
   found=1
 done
 
