Go back to force unmounting because not doing so was too unreliable.

diff --git a/Tools/portbuild/scripts/clean-chroot b/Tools/portbuild/scripts/clean-chroot
--- a/Tools/portbuild/scripts/clean-chroot
+++ b/Tools/portbuild/scripts/clean-chroot
@@ -24,11 +24,11 @@ cleanup_mount() {
   if [ -d ${chroot}${mount} ]; then
     mdir=$(fstat -f ${chroot}${mount} | head -2 | tail -1 | awk '{print $5}')
     if [ "${mdir}" = "MOUNT" ]; then
-      umount ${chroot}${mount} || echo "Cleanup of ${chroot}${mount} failed!"
+      umount -f ${chroot}${mount} || echo "Cleanup of ${chroot}${mount} failed!"
     fi
     if [ "${mdir}" = "${chroot}${mount}" ]; then
       kill_procs ${chroot} ${mount}
-      umount ${chroot}${mount} || echo "Cleanup of ${chroot}${mount} failed!" 
+      umount -f ${chroot}${mount} || echo "Cleanup of ${chroot}${mount} failed!" 
     fi
   fi
 }
