Support builds using zfs and tmpfs backing store
zfs:

* Enabled by use_zfs=1 in portbuild.conf

* Populate build chroots by cloning a zfs snapshot instead of maintaining
  many duplicate copies.  In principle this is very efficient since
  everything is copy-on-write and zfs snapshot creation is almost
  instantaneous.  There might be additional overheads from building on zfs
  though.  Currently the snapshot base is hard-wired to y/${branch}@base
  but should be parametrized.  This also must be populated beforehand, e.g.
  during machine startup

* Clean build chroots by just destroying the snapshot.

tmpfs:

* Enabled by use_tmpfs=1 and tmpfs_size in portbuild.conf

* The previous md strategy of mounting in used/, populating and then
  remounting (to avoid possible races from multiple builds claiming the
  same chroot) doesn't work here because tmpfs instances are destroyed at
  umount.  I am not entirely sure the simpler approach is free from races.

diff --git a/Tools/portbuild/scripts/clean-chroot b/Tools/portbuild/scripts/clean-chroot
--- a/Tools/portbuild/scripts/clean-chroot
+++ b/Tools/portbuild/scripts/clean-chroot
@@ -73,10 +73,24 @@ done
 
 #kill_procs ${chroot}
 
-if [ "${use_md_swap}" = "1" -a \( "${md_persistent}" != "1" -a "${clean}" -gt "0" \) -o "${clean}" = "2" ]; then
+if [ "${use_zfs}" = "1" ]; then
+  cleanup_mount ${chroot} ""
+  zfs destroy $(echo ${chroot} | sed -e 's,/,,' )
+elif [ "${use_tmpfs}" = "1" -a "${clean}" = "2" ]; then
+  cleanup_mount ${chroot} ""
+  if ! rm -rf ${chroot} >/dev/null 2>&1; then
+    chflags -R noschg ${chroot} >/dev/null 2>&1
+    rm -rf ${chroot} >/dev/null 2>&1
+  fi
+  # XXX possible race from cleanup and claim by next build?
+elif [ "${use_md_swap}" = "1" -a \( "${md_persistent}" != "1" -a "${clean}" -gt "0" \) -o "${clean}" = "2" ]; then
+  cleanup_mount ${chroot} /used
   cleanup_mount ${chroot} ""
   mdconfig -d -u $(basename ${chroot})
-  rm -rf ${chroot}
+  if ! rm -rf ${chroot} >/dev/null 2>&1; then
+    chflags -R noschg ${chroot} >/dev/null 2>&1
+    rm -rf ${chroot} >/dev/null 2>&1
+  fi
 else
   if [ "${clean}" = 1 ]; then
     rm -rf ${chroot}/tmp/*
