Generalize the packge building scripts to be able to be run on more than one 'head' node, rather than just pointyhat itself.
Constants are factored out into installation-specific files known as
portbuild/conf/server.conf and portbuild/conf/client.conf.  There is
only one server.conf file.  Individual <arch> directories may have
their own client.conf files, or may symlink to ../conf/client.conf.

Add the copying over of client.conf to the clients, and take care
to force the file copy regardless of whether it is a symlink.

Feature safe:	yes

diff --git a/Tools/portbuild/scripts/dosetupnode b/Tools/portbuild/scripts/dosetupnode
--- a/Tools/portbuild/scripts/dosetupnode
+++ b/Tools/portbuild/scripts/dosetupnode
@@ -1,5 +1,8 @@
 #!/bin/sh
-#
+# $FreeBSD$
+
+# server-side script to set up an individual client
+
 # XXX Use a worker pool that only runs N setups at once to avoid
 # raping the server.  Hard to do in shell?
 
@@ -19,6 +22,7 @@ buildid=$3
 nodelist=$4
 shift 4
 
+. ${pb}/conf/server.conf
 if [ -f ${pb}/${arch}/portbuild.conf ]; then
     . ${pb}/${arch}/portbuild.conf
 else
@@ -66,6 +70,11 @@ setup() {
 	rsync ${rsync_gzip} -e "${ssh_cmd}" -r -l -p --delete ${pb}/scripts \
 	    ${client_user}@${node}:${pb}/
 	checkerror $? || (echo "Copying scripts to ${node} failed"; return 1)
+
+	# client.conf can be a symlink; copy the actual file
+	rsync ${rsync_gzip} -e "${ssh_cmd}" -r -L -p --delete ${pb}/${arch}/client.conf \
+	    ${client_user}@${node}:${pb}/${arch}
+	checkerror $? || (echo "copying client.conf to ${node} failed"; return 1)
 
 	rsync ${rsync_gzip} -e "${ssh_cmd}" -r -l -p --delete ${pb}/${arch}/portbuild* \
 	    ${client_user}@${node}:${pb}/${arch}
