Generalize the packge building scripts to be able to be run on more than one 'head' node, rather than just pointyhat itself.
Constants are factored out into installation-specific files known as
portbuild/conf/server.conf and portbuild/conf/client.conf.  There is
only one server.conf file.  Individual <arch> directories may have
their own client.conf files, or may symlink to ../conf/client.conf.

Gracefully handle the case of INDEX failing to build.  This helps the
calling script to exit instead of spewing errors.

Feature safe:	yes

diff --git a/Tools/portbuild/scripts/makeindex b/Tools/portbuild/scripts/makeindex
--- a/Tools/portbuild/scripts/makeindex
+++ b/Tools/portbuild/scripts/makeindex
@@ -28,6 +28,7 @@ shift 3
 
 builddir=${pb}/${arch}/${branch}/builds/${buildid}
 
+. ${pb}/conf/server.conf
 . ${pb}/${arch}/portbuild.conf
 . ${pb}/scripts/buildenv
 
@@ -41,6 +42,10 @@ export LOCALBASE=/nonexistentlocal
 
 cd ${PORTSDIR}
 make index
+if [ ! -e ${INDEXFILE} ]; then
+  echo "makeindex: failed to make ${INDEXFILE}"
+  exit 1
+fi
 
 # remove extra spaces in dependency list -- this causes problems
 # Also transform the dummy paths to their canonical locations
