Update to 1.4rc3.
Change the configuration process, so that extraneous files are not
downloaded.

diff --git a/www/linux-mozilla-devel/scripts/configure b/www/linux-mozilla-devel/scripts/configure
--- a/www/linux-mozilla-devel/scripts/configure
+++ b/www/linux-mozilla-devel/scripts/configure
@@ -42,3 +42,7 @@ echo "$choice" \
 	| sed -e "s/$/.xpi/g" \
 	| perl -pi -e "s/ /\n/g" \
 	> ${WRKSRC}/components.conf
+
+echo "* Your choices are saved.  You must run the \"make\" command again to"
+echo "* complete the build.  Ignore the \"Error code 1\" below."
+exit 1
