graphics/rawtherapee: update to 5.8, and more
* Update rawtherapee to 5.8.
- New Capture Sharpening tool (on the "Raw" tab)
- CR3 support for decoding (not metadata yet)
- Improvements of various camera models.
- http://rawtherapee.com/downloads/5.8/

* Add two post-release patches cherry-picked from Git
- The Canon sRAW/mRAW black level computation fix, 4221fdf3
- The fix to install 32/64/SVG icons, 37bfa83 (291abfd)

* Switch MASTER_SITES to https://rawtherapee.com (from http://)

* Add local MASTER_SITES and mirror 5.8 source.

* Add a TCMALLOC option for i386/amd64, and by default enable it.
  This requires google-perftools, which isn't available on all other
  platforms, but if your platform does provide it let me know,
  so I can whitelist it.

* Restrict 11.x to amd64, it is known to malfunction for instance
  on 11.3 i386 with TIFF export.

* Limit LIB_DEPENDS+=devel/openmp to 11.2 and 12.0 and early 13-CURRENT.
  11.3, 12.1 have OpenMP in base. Note that 12.0 will be EOL soon.

* Under WITH_DEBUG=yes, use -O1 and RelWithDebInfo. -O0 is just
  no fun to run, way too slow.

* Improve the post-install self-tests
- Make them work even if no older rawtherapee is installed, by setting
  up an RT_SETTINGS folder. This still causes complaints by the test
  suite, but it works nonetheless.
- More thorough error detection (tracks exit codes)
- Run TIFF export, too (rawtherapee-cli -tz)

* NOTES:
- Getting this port to work reliably across versions and architectures
  has taken several days and many compiles to get right.
  - liblensfun 0.3.95 needed fixing against memory corruption when
    loading the database (committed as r525547/lensfun 0.3.95_1)
- Attempting base clang on 12.1/11.3 builds has failed again, so
  we'll continue with GCC for now. This rules out MIPS.
- You really really really only want to run RawTherapee on a system
  with 64-bit address space and sufficient RAM. On 32-bit, it will
  run out of memory all too easily.
- You also really only want to run RawTherapee on a platform that
  supports OpenMP and with multi-core processors with sufficient
  horsepower.
- On the single attempt to get ARM64 working, the self-tests fail.
  Run at your own risk on Tier 2/3/4 architectures.
- Known good FreeBSD versions and architectures
  - 11.3: amd64
  - 12.0: amd64, i386 (12.0 EOL soon)
  - 12.1: amd64, i386

diff --git a/graphics/rawtherapee/Makefile b/graphics/rawtherapee/Makefile
--- a/graphics/rawtherapee/Makefile
+++ b/graphics/rawtherapee/Makefile
@@ -2,10 +2,10 @@
 # $FreeBSD$
 
 PORTNAME=	rawtherapee
-PORTVERSION=	5.7
-PORTREVISION=	2
+PORTVERSION=	5.8
 CATEGORIES=	graphics
-MASTER_SITES=	http://rawtherapee.com/shared/source/
+MASTER_SITES=	https://rawtherapee.com/shared/source/ \
+		LOCAL/mandree/
 
 MAINTAINER=	mandree@FreeBSD.org
 COMMENT=	Powerful RAW image processing application
@@ -32,12 +32,13 @@ USES=		cmake desktop-file-utils compiler:gcc-c++11-lib gnome \
 
 DOS2UNIX_REGEX=	.*\.(cc|h)
 USE_GNOME=	gtkmm30 librsvg2
+INSTALLS_ICONS=	yes
 
 # Binutils required for LTO (base ar/nm/ld/ranlib don't work)
 USE_BINUTILS=	yes
 
 # As of 2019-09-29, this port is known to be miscompiled by clang90
-# (SIGSEGV or SIBGUS).
+# (SIGSEGV or SIBGUS) and 12.1's base clang.
 #
 # FreeBSD 11.2/12.0's base clang 6.0.1 emits worse code with
 # considerably higher processing times, and on i386 additional calls to
@@ -47,10 +48,9 @@ USE_GCC=	9+
 _LTO_FLAGS=	-flto=${MAKE_JOBS_NUMBER}
 # gcc needs -flto=${MAKE_JOBS_NUMBER} for parallel link (fixed in GCC 10?)
 #     and does not understand -flto=thin
-#   
+#
 # llvm/clang needs -flto=thin and will automatically parallelize the link
 #
-# XXX re _AR/_RANLIB: might be worth checking if plain binutils is good
 _AR=		${CC:S/gcc/gcc-ar/}
 _RANLIB=	${CC:S/gcc/gcc-ranlib/}
 CFLAGS+=	-I${LOCALBASE}/include -fPIC ${_LTO_FLAGS} ${_OPT_FLAGS}
@@ -70,8 +70,6 @@ CMAKE_ARGS+=	-DDOCDIR="${DOCSDIR}" \
 # linker flags are passed. Else -lomp is not found with clang.
 # See: https://cmake.org/cmake/help/v3.4/policy/CMP0056.html
 
-INSTALLS_ICONS=	yes
-
 .if defined(PACKAGE_BUILDING) && empty(CFLAGS:M-march*) && (${ARCH} == i386 || ${ARCH} == amd64 || ${ARCH} == aarch64)
 # this gets translated to -mtune=generic, see ${WRKSRC}/ProcessorTargets.cmake
 # and as of GCC 8.3, it appears that among FreeBSD's supported architectures,
@@ -84,20 +82,35 @@ CMAKE_ARGS+=	-DCMAKE_C_COMPILER_LAUNCHER=${CCACHE_BIN} \
 		-DCMAKE_CXX_COMPILER_LAUNCHER=${CCACHE_BIN}
 .endif
 
-RTDIR=		${PREFIX}/libdata/${PORTNAME}
-
 OPTIONS_DEFINE=		DOCS NATIVE
-OPTIONS_DEFINE_i386=	DOCS NATIVE OPENMP
-OPTIONS_DEFINE_amd64=	DOCS NATIVE OPENMP
-OPTIONS_DEFAULT=	OPENMP
+OPTIONS_DEFINE_i386=	OPENMP TCMALLOC
+OPTIONS_DEFINE_amd64=	OPENMP TCMALLOC
+OPTIONS_DEFAULT=	OPENMP TCMALLOC
 OPENMP_DESC=		Enable OpenMP parallel processing (i386/amd64 only)
 NATIVE_DESC=		Use -march=native (avoid for generic packages!)
+TCMALLOC_DESC=		Use Google's tcmalloc instead of system allocator
 
 OPENMP_CMAKE_BOOL=	OPTION_OMP
+
+TCMALLOC_CMAKE_BOOL=	ENABLE_TCMALLOC
+TCMALLOC_LIB_DEPENDS=	libtcmalloc.so:devel/google-perftools
 
 .include <bsd.port.options.mk>
 
 # -------------------------------------------------------------------
+
+.if (${OPSYS} == FreeBSD) && (${OSVERSION} <  1200000)
+# can't save 16-bit TIFF on FreeBSD 11.3 i386:
+# "TIFFWriteDirectoryTagIfdIfd8Array: Attempt to write value
+# larger than 0xFFFFFFFF in Classic TIFF file"
+#
+# And no, the maintainer is not going to spend any time on it
+# unless there is a tested proven well-integrated patch offered.
+#
+# Tier-2 only supported on the latest stable FreeBSD release.
+ONLY_FOR_ARCHS=	amd64
+ONLY_FOR_ARCHS_REASON= i386 malfunctions on 11.x - upgrade to 12.x
+.endif
 
 .if (${OPSYS} == FreeBSD) && (${OSVERSION} >= 1300000)
 # don't waste everybody's time with Tier-2 and moving targets.
@@ -112,16 +125,21 @@ CMAKE_ARGS+=	-DPROC_TARGET_NUMBER="2"
 .endif
 
 .if !empty(PORT_OPTIONS:MOPENMP) && !empty(OPTIONS_DEFINE:MOPENMP)
+. if ${OSVERSION} < 1102507 || (${OSVERSION} >= 1200000 && ${OSVERSION} < 1200506) || (${OSVERSION} >= 1300000 && ${OSVERSION} < 1300050)
 LIB_DEPENDS+=	libomp.so:devel/openmp
+. endif
 OPENMP_FLAGS=	-lm -lomp
 LDFLAGS+=	${OPENMP_FLAGS}
 .endif
 
 .if defined(WITH_DEBUG)
 STRIP=
+CMAKE_BUILD_TYPE=	RelWithDebInfo
+_OPT_FLAGS=	-O1
+.else
+_OPT_FLAGS=	-O3 -funroll-loops
 .endif
 
-_OPT_FLAGS=	-O3 -funroll-loops
 # GCC >= 5.4 includes -fexpensive-optimizations in -O2 already
 .if (${ARCH} == i386) || (${ARCH} == amd64)
 # and SSE2 has been around since the years 2000...2003 latest
@@ -143,20 +161,39 @@ post-patch:
 
 TESTIMAGES=	${FILESDIR}/../testimages
 
-# paranoia: run rawtherapee --help to be sure it finds all its
+# paranoia: run rawtherapee to be sure it finds all its
 # shared libraries (this hinges on proper RPATH setting and propagation)
+#
+# _check_version strips stuffixes from distnames etc. that do not appear
+# in the program's version numbering
+_check_version=	${PKGVERSION:C/.g0//}
+_env=		LANG= LC_ALL=C LANGUAGE= DISPLAY= HOME="$$TMP" RT_SETTINGS=${WRKDIR}/rt-config RT_CACHE="$$TMP/rtcache"
 post-install:
 	@${ECHO_MSG} "===> Running smoke tests"
+	@${RM} -f ${WRKDIR}/selftest.exitcodes ${WRKDIR}/selftest.expect 
+	@${RM} -rf ${WRKDIR}/rt-config
+	${MKDIR} ${WRKDIR}/rt-config ${WRKDIR}/rt-config/dcpprofiles ${WRKDIR}/rt-config/profiles
+	${CP} ${WRKSRC}/rtengine/camconst.json ${WRKDIR}/rt-config
+	${CP} ${WRKSRC}/rtdata/options/options.lin ${WRKDIR}/rt-config/options
+	(cd ${WRKSRC}/rtdata/ && ${COPYTREE_SHARE} "profiles dcpprofiles" ${WRKDIR}/rt-config )
 	@(set -x ; TMP=$$(${MKTEMP} -d -t ${PORTNAME}) && trap "rc=$$? ; ${RM} -rf \"$$TMP\" ; exit \$$rc" 0 && \
-	${SETENV} LANG= LC_ALL=C LANGUAGE= DISPLAY= HOME="$$TMP" ${STAGEDIR}${PREFIX}/bin/rawtherapee --help 2>&1 \
-	    | ${EGREP} -q "RawTherapee, version ${PKGVERSION:C/_.*//:C/,.*//}|cannot open display:" && \
-	${SETENV} LANG= LC_ALL=C LANGUAGE= DISPLAY= HOME="$$TMP" ${STAGEDIR}${PREFIX}/bin/rawtherapee-cli --version 2>&1 \
-	    | ${EGREP} -q "RawTherapee, version ${PKGVERSION:C/_.*//:C/,.*//}" && \
-	if test -n "$(TESTIMAGES)" ; then \
-	  time ${SETENV} LANG= LC_ALL=C LANGUAGE= DISPLAY= HOME="$$TMP" ${STAGEDIR}${PREFIX}/bin/rawtherapee-cli \
-		-o "$$TMP" -q -f -c $(TESTIMAGES) && \
-	  time ${SETENV} LANG= LC_ALL=C LANGUAGE= DISPLAY= HOME="$$TMP" ${STAGEDIR}${PREFIX}/bin/rawtherapee-cli \
-		-o "$$TMP" -q -s -Y -c $(TESTIMAGES) ; \
-	fi )
+		( ${SETENV} ${_env} ${STAGEDIR}${PREFIX}/bin/rawtherapee -v 2>&1 ; \
+		    echo $$? >&3 ) 3>&3 | ${EGREP} -q "RawTherapee, version ${_check_version:C/_.*//:C/,.*//}|cannot open display:" && \
+		( ${SETENV} ${_env} ${STAGEDIR}${PREFIX}/bin/rawtherapee-cli 2>&1 ; \
+		    echo $$? >&3 ) 3>&3 | ${EGREP} -q "RawTherapee, version ${_check_version:C/_.*//:C/,.*//}" && \
+		expect='0\n0\n' && \
+		onefile=$$(ls "${TESTIMAGES}"/* | head -1) && \
+		if test -d "${TESTIMAGES}" && test -n "$$onefile" -a -r "$$onefile" ; then \
+		  expect='0\n0\n0\n0\n0\n' && \
+		  /usr/bin/time ${SETENV} ${_env} ${STAGEDIR}${PREFIX}/bin/rawtherapee-cli \
+			-o "$$TMP" -q -f -c ${TESTIMAGES} ; echo $$? >&3 ; \
+		  /usr/bin/time ${SETENV} ${_env} ${STAGEDIR}${PREFIX}/bin/rawtherapee-cli \
+			-o "$$TMP" -q -s -Y -c ${TESTIMAGES} ; echo $$? >&3 ; \
+		  /usr/bin/time ${SETENV} ${_env} ${STAGEDIR}${PREFIX}/bin/rawtherapee-cli \
+			-o "$$TMP" -q -s -Y -tz -c ${TESTIMAGES} ; echo $$? >&3 ; \
+		fi ; \
+		ls -Rlbai "${TESTIMAGES}" "$${TMP}"; \
+	${PRINTF} "%s" "$$expect" >&4 ) 3>${WRKDIR}/selftest.exitcodes 4>${WRKDIR}/selftest.expect ; \
+	${PRINTF} "$$(cat ${WRKDIR}/selftest.expect)" | cmp - ${WRKDIR}/selftest.exitcodes || { ${ECHO_CMD} '===> !!! SELF-TEST FAILED !!! <===' ; exit 1 ; }
 
 .include <bsd.port.post.mk>
