Update port to version 0.86, add better handling of BATCH in "make install" and pkg_add, don't let setup.sh start the service. The setup script is now automatically called when not installing in batch mode.
Also, "borrow" better pkg-plist implementation from the vim5 port: it
allows to have @execs at the end of pkg-plist (thanks to O'Brien :-))

diff --git a/sysutils/webmin/Makefile b/sysutils/webmin/Makefile
--- a/sysutils/webmin/Makefile
+++ b/sysutils/webmin/Makefile
@@ -6,8 +6,7 @@
 #
 
 PORTNAME=	webmin
-PORTVERSION=	0.85
-PORTREVISION=	8
+PORTVERSION=	0.86
 CATEGORIES=	sysutils
 MASTER_SITES=	http://webadmin.sourceforge.net/webmin/updates/ \
 		http://webadmin.sourceforge.net/webmin/download/
@@ -22,12 +21,7 @@ NO_BUILD=	yes
 USE_PERL5=	yes
 SCRIPTS_ENV+=	WRKDIR="${WRKDIR}"
 
-WEBMIN_MODULES=	postgresql-0.85-1.wbm.gz squid-0.85-1.wbm.gz \
-		useradmin-0.85-1.wbm.gz net-0.85-1.wbm.gz \
-		apache-0.85-2.wbm.gz quota-0.85-1.wbm.gz \
-		bind8-0.85-1.wbm.gz mysql-0.85-1.wbm.gz \
-		shell-0.85-1.wbm.gz man-0.85-1.wbm.gz
-WEBMIN_SERVER=	miniserv.pl
+WEBMIN_MODULES=
 
 post-extract:
 	@if [ "${WEBMIN_MODULES}" != "" ]; then \
@@ -36,7 +30,6 @@ post-extract:
 			${TAR} xfz ${DISTDIR}/$${webmin_module} -C ${WRKSRC}; \
 		done; \
 	fi
-	@${CP} ${DISTDIR}/${WEBMIN_SERVER} ${WRKSRC}
 	@find ${WRKSRC} -name "*.bak" | xargs ${RM}
 
 post-patch:
@@ -79,15 +72,33 @@ do-install:
 	@${CP} -r ${WRKSRC}/* ${PREFIX}/lib/webmin
 	@cd ${PREFIX}/lib/webmin && find . -name "*.orig" -print \
 		| xargs ${RM}
+# we may have 2 levels of empty directories which cause the plist generation
+# system to fail
+	@cd ${PREFIX}/lib/webmin && find . -type d -empty -print \
+		| xargs ${RMDIR}
+	@cd ${PREFIX}/lib/webmin && find . -type d -empty -print \
+		| xargs ${RMDIR}
 	@${CP} ${WRKDIR}/webmin.sh ${PREFIX}/etc/rc.d/webmin.sh
 	@${CHMOD} 554 ${PREFIX}/etc/rc.d/webmin.sh
 
 post-install:
-	@${CP} ${PLIST} ${TMPPLIST}
-	@find ${PREFIX}/lib/webmin -type f | ${SED} -e "s@${PREFIX}/@@" | sort >> ${TMPPLIST}
-	@find ${PREFIX}/lib/webmin -type l | ${SED} -e "s@${PREFIX}/@@" | sort >> ${TMPPLIST}
-	@find ${PREFIX}/lib/webmin -type d | ${SED} -e "s@${PREFIX}/@@" | ${PERL} -e 'print (join ("\n", reverse map ("\@dirrm " . substr ($$_, 0, -1), <STDIN>)) . "\n");' >> ${TMPPLIST}
-	@if [ -d ${PREFIX}/etc/webmin ]; then echo | ${PREFIX}/lib/webmin/setup.sh ; fi
+	@cd ${PREFIX} ; find lib/webmin -type f -o -type l | sort \
+		> ${WRKDIR}/PLIST.lib-webmin
+	@cd ${PREFIX} ; find lib/webmin -type d | sort -r \
+	    	| ${SED} -e 's/^/@dirrm /g' \
+		>> ${WRKDIR}/PLIST.lib-webmin
+
+	@${ECHO} "r ${TMPPLIST}"		> ${WRKDIR}/ex.script
+	@${ECHO} "/Insert PLIST.lib-webmin"	>> ${WRKDIR}/ex.script
+	@${ECHO} "d"				>> ${WRKDIR}/ex.script
+	@${ECHO} "r ${WRKDIR}/PLIST.lib-webmin"	>> ${WRKDIR}/ex.script
+	@${ECHO} "x!"				>> ${WRKDIR}/ex.script
+	@${CP} -p ${TMPPLIST} ${TMPPLIST}.pre-lib-webmin
+	@cd ${WRKDIR} ; ex < ex.script
+# upgrade configuration if etc/webmin exists
+	@[ ! -d ${PREFIX}/etc/webmin ] || echo | nostart=Y ${PREFIX}/lib/webmin/setup.sh
+# run interactive setup if not in BATCH mode and no configuration exists
+	@[ -n "$BATCH" ] || ([ -d ${PREFIX}/etc/webmin ] || nostart=Y ${PREFIX}/lib/webmin/setup.sh)
 	@${CAT} ${PKGMESSAGE}
 
 .include <bsd.port.mk>
