- Update to 0.8.5 - Split Makefile into Makefile.inc to make it a little easier to maintain - Turn on or off knobs by default per configure script  o GNOMEVFS on by default  o AVAHI on by default  o FLAC off by default  o X264 on by default  o DAAP on by default  o LIVEMEDIA off by default  o SAMBA on by default  o SDL on by default  o SPEEX on by default

diff --git a/multimedia/vlc/files/patch-configure b/multimedia/vlc/files/patch-configure
--- a/multimedia/vlc/files/patch-configure
+++ b/multimedia/vlc/files/patch-configure
@@ -1,34 +1,45 @@
---- configure.orig	Sun Nov 27 13:45:02 2005
-+++ configure	Sun Nov 27 13:46:20 2005
-@@ -41006,12 +41006,12 @@
-         pkg_cv_BONJOUR_CFLAGS="$BONJOUR_CFLAGS"
+--- configure.orig	Sun Jan  1 18:01:13 2006
++++ configure	Mon Jan  2 14:38:53 2006
+@@ -21195,11 +21195,7 @@
+   done
+ 
      else
-         if test -n "$PKG_CONFIG" && \
--    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"avahi-client >= 0.3\"") >&5
--  ($PKG_CONFIG --exists --print-errors "avahi-client >= 0.3") 2>&5
-+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"avahi-client >= 0.3\"" avahi-client < 0.6) >&5
-+  ($PKG_CONFIG --exists --print-errors "avahi-client >= 0.3 avahi-client < 0.6") 2>&5
-   ac_status=$?
-   echo "$as_me:$LINENO: \$? = $ac_status" >&5
-   (exit $ac_status); }; then
--  pkg_cv_BONJOUR_CFLAGS=`$PKG_CONFIG --cflags "avahi-client >= 0.3" 2>/dev/null`
-+  pkg_cv_BONJOUR_CFLAGS=`$PKG_CONFIG --cflags "avahi-client >= 0.3 avahi-client < 0.6" 2>/dev/null`
- else
-   pkg_failed=yes
+-            echo "$as_me:$LINENO: result: no" >&5
+-echo "${ECHO_T}no" >&6
+-      { { echo "$as_me:$LINENO: error: cannot find ${with_dv_raw1394}/include/libraw1394/raw1394.h" >&5
+-echo "$as_me: error: cannot find ${with_dv_raw1394}/include/libraw1394/raw1394.h" >&2;}
+-   { (exit 1); exit 1; }; }
++	echo "not found"
+     fi
+   else
+ 
+@@ -21361,8 +21357,7 @@
+         if test -n "${enable_dv}"
+         then
+           { { echo "$as_me:$LINENO: error: cannot find libraw1394 headers" >&5
+-echo "$as_me: error: cannot find libraw1394 headers" >&2;}
+-   { (exit 1); exit 1; }; }
++echo "$as_me: error: cannot find libraw1394 headers" >&2;} ;}
+         fi
+ 
  fi
-@@ -41024,12 +41024,12 @@
-         pkg_cv_BONJOUR_LIBS="$BONJOUR_LIBS"
-     else
-         if test -n "$PKG_CONFIG" && \
--    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"avahi-client >= 0.3\"") >&5
--  ($PKG_CONFIG --exists --print-errors "avahi-client >= 0.3") 2>&5
-+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"avahi-client >= 0.3 avahi-client < 0.6\"") >&5
-+  ($PKG_CONFIG --exists --print-errors "avahi-client >= 0.3 avahi-client < 0.6") 2>&5
-   ac_status=$?
-   echo "$as_me:$LINENO: \$? = $ac_status" >&5
-   (exit $ac_status); }; then
--  pkg_cv_BONJOUR_LIBS=`$PKG_CONFIG --libs "avahi-client >= 0.3" 2>/dev/null`
-+  pkg_cv_BONJOUR_LIBS=`$PKG_CONFIG --libs "avahi-client >= 0.3 avahi-client < 0.6" 2>/dev/null`
- else
-   pkg_failed=yes
+@@ -21381,8 +21376,7 @@
+             echo "$as_me:$LINENO: result: no" >&5
+ echo "${ECHO_T}no" >&6
+       { { echo "$as_me:$LINENO: error: cannot cd to ${real_dv_raw1394_tree}" >&5
+-echo "$as_me: error: cannot cd to ${real_dv_raw1394_tree}" >&2;}
+-   { (exit 1); exit 1; }; }
++echo "$as_me: error: cannot cd to ${real_dv_raw1394_tree}" >&2;} ;}
+     fi
+     if test -f "${real_dv_raw1394_tree}/src/.libs/libraw1394.a"
+     then
+@@ -21610,8 +21604,7 @@
+         if test -n "${enable_dv}"
+         then
+           { { echo "$as_me:$LINENO: error: cannot find libavc1394 headers" >&5
+-echo "$as_me: error: cannot find libavc1394 headers" >&2;}
+-   { (exit 1); exit 1; }; }
++echo "$as_me: error: cannot find libavc1394 headers" >&2;} ; }
+         fi
+ 
  fi
