Update to 0.8.6b (merged from multimedia/vlc-devel, note this requires ffmpeg-devel now!)

diff --git a/multimedia/vlc/files/patch-configure b/multimedia/vlc/files/patch-configure
--- a/multimedia/vlc/files/patch-configure
+++ b/multimedia/vlc/files/patch-configure
@@ -1,19 +1,16 @@
---- configure.orig	Sun Jan  1 18:01:13 2006
-+++ configure	Mon Jan  2 14:38:53 2006
-@@ -21195,11 +21195,7 @@
-   done
- 
-     else
--            echo "$as_me:$LINENO: result: no" >&5
--echo "${ECHO_T}no" >&6
--      { { echo "$as_me:$LINENO: error: cannot find ${with_dv_raw1394}/include/libraw1394/raw1394.h" >&5
--echo "$as_me: error: cannot find ${with_dv_raw1394}/include/libraw1394/raw1394.h" >&2;}
+--- configure.orig	Fri Dec  8 20:33:49 2006
++++ configure	Sun Dec 10 09:40:46 2006
+@@ -2412,8 +2412,7 @@
+ done
+ if test -z "$ac_aux_dir"; then
+   { { echo "$as_me:$LINENO: error: cannot find install-sh or install.sh in autotools \"$srcdir\"/autotools" >&5
+-echo "$as_me: error: cannot find install-sh or install.sh in autotools \"$srcdir\"/autotools" >&2;}
 -   { (exit 1); exit 1; }; }
-+	echo "not found"
-     fi
-   else
++echo "$as_me: error: cannot find install-sh or install.sh in autotools \"$srcdir\"/autotools" >&2;} }
+ fi
  
-@@ -21361,8 +21357,7 @@
+ # These three variables are undocumented and unsupported,
+@@ -37873,8 +37872,7 @@
          if test -n "${enable_dv}"
          then
            { { echo "$as_me:$LINENO: error: cannot find libraw1394 headers" >&5
@@ -23,9 +20,9 @@
          fi
  
  fi
-@@ -21381,8 +21376,7 @@
-             echo "$as_me:$LINENO: result: no" >&5
- echo "${ECHO_T}no" >&6
+@@ -37893,8 +37891,7 @@
+             { echo "$as_me:$LINENO: result: no" >&5
+ echo "${ECHO_T}no" >&6; }
        { { echo "$as_me:$LINENO: error: cannot cd to ${real_dv_raw1394_tree}" >&5
 -echo "$as_me: error: cannot cd to ${real_dv_raw1394_tree}" >&2;}
 -   { (exit 1); exit 1; }; }
@@ -33,7 +30,7 @@
      fi
      if test -f "${real_dv_raw1394_tree}/src/.libs/libraw1394.a"
      then
-@@ -21610,8 +21604,7 @@
+@@ -38113,8 +38110,7 @@
          if test -n "${enable_dv}"
          then
            { { echo "$as_me:$LINENO: error: cannot find libavc1394 headers" >&5
