- Fix IPv6 support is not built - Bump portrevision
PR:		ports/130213
Submitted by:	Wes Morgan <morganw@chemikals.org>

diff --git a/irc/bitchx/files/patch-configure b/irc/bitchx/files/patch-configure
--- a/irc/bitchx/files/patch-configure
+++ b/irc/bitchx/files/patch-configure
@@ -1,27 +1,53 @@
---- configure.in.orig   Sun Mar 24 10:30:49 2002
-+++ configure.in        Tue May 28 10:06:37 2002
-@@ -685,48 +685,16 @@
 
- AC_MSG_CHECKING(whether to enable IPv6 support)
- AC_ARG_ENABLE(ipv6,
--[  --enable-ipv6           Enable IPv6 support (Linux only)],
-+[  --enable-ipv6           Enable ipv6 support],
- [ case "$enableval" in
+--- configure~	2009-01-05 18:02:04.883269233 -0600
++++ configure	2009-01-05 18:02:04.886269145 -0600
+@@ -11830,100 +11830,27 @@
+ echo $ECHO_N "checking whether to enable IPv6 support... $ECHO_C" >&6
+ # Check whether --enable-ipv6 or --disable-ipv6 was given.
+ if test "${enable_ipv6+set}" = set; then
+-  enableval="$enable_ipv6"
+-   case "$enableval" in
++  enableval=$enable_ipv6;  case "$enableval" in
      yes)
 -      case "$(uname -s)" in
 -        Linux)
 -          if test -d "/usr/inet6/include"; then
 -            CFLAGS="$CFLAGS -I/usr/inet6/include"
 -            LIBS="-L/usr/inet6/lib -linet6 $LIBS"
--            AC_MSG_RESULT(yes (libinet6))
--            AC_DEFINE(IPV6, 1, Define this if you want IPV6 support.)
+-            echo "$as_me:$LINENO: result: yes (libinet6)" >&5
+-echo "${ECHO_T}yes (libinet6)" >&6
++       { $as_echo "$as_me:$LINENO: result: yes (notchecked)" >&5
++$as_echo "yes (notchecked)" >&6; }
+ 
+ cat >>confdefs.h <<\_ACEOF
+ #define IPV6 1
+ _ACEOF
+ 
 -          else
 -            if test -d "/usr/local/v6/lib"; then
 -              LIBS="-L/usr/local/v6/lib -linet6 $LIBS"
--              AC_MSG_RESULT(yes (freebsd+kame))
--              AC_DEFINE(IPV6, 1, Define this if you want IPV6 support.)
+-              echo "$as_me:$LINENO: result: yes (freebsd+kame)" >&5
+-echo "${ECHO_T}yes (freebsd+kame)" >&6
+-
+-cat >>confdefs.h <<\_ACEOF
+-#define IPV6 1
+-_ACEOF
+-
 -            else
--              AC_TRY_RUN([
+-              if test "$cross_compiling" = yes; then
+-  { echo "$as_me:$LINENO: WARNING: cross-compiling: assuming no ipv6" >&5
+-echo "$as_me: WARNING: cross-compiling: assuming no ipv6" >&2;}
++       ;;
++    *)
++       { $as_echo "$as_me:$LINENO: result: no" >&5
++$as_echo "no" >&6; }
++       ;;
++    esac
+ else
+-  cat >conftest.$ac_ext <<_ACEOF
+-#line $LINENO "configure"
+-#include "confdefs.h"
+-
 -              int main()
 -              {
 -                 #if !defined(__GLIBC__) || (__GLIBC__ < 2)
@@ -32,27 +58,60 @@
 -                   exit(0);
 -                 else
 -                   exit(1);
--              }],[ AC_MSG_RESULT(yes (glibc2))
--                   AC_DEFINE(IPV6, 1, Define this if you want IPV6 support.)
--                 ], [AC_MSG_RESULT(no)], [AC_MSG_WARN(cross-compiling: assuming no ipv6)])
+-              }
+-_ACEOF
+-rm -f conftest$ac_exeext
+-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+-  (eval $ac_link) 2>&5
+-  ac_status=$?
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+-  (eval $ac_try) 2>&5
+-  ac_status=$?
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); }; }; then
+-   echo "$as_me:$LINENO: result: yes (glibc2)" >&5
+-echo "${ECHO_T}yes (glibc2)" >&6
++  { $as_echo "$as_me:$LINENO: result: no" >&5
++$as_echo "no" >&6; }
+ 
+-cat >>confdefs.h <<\_ACEOF
+-#define IPV6 1
+-_ACEOF
+-
+-
+-else
+-  echo "$as_me: program exited with status $ac_status" >&5
+-echo "$as_me: failed program was:" >&5
+-cat conftest.$ac_ext >&5
+-( exit $ac_status )
+-echo "$as_me:$LINENO: result: no" >&5
+-echo "${ECHO_T}no" >&6
+-fi
+-rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+ fi
 -            fi
 -          fi
 -          ;;
 -        *)
--          AC_MSG_RESULT(no (ipv6 support can currently be enabled on Linux only))
+-          echo "$as_me:$LINENO: result: no (ipv6 support can currently be enabled on Linux only)" >&5
+-echo "${ECHO_T}no (ipv6 support can currently be enabled on Linux only)" >&6
 -          ;;
 -      esac
 -      ;;
 -    no)
--      AC_MSG_RESULT(no)
+-      echo "$as_me:$LINENO: result: no" >&5
+-echo "${ECHO_T}no" >&6
 -      ;;
--  esac ],
-+       AC_MSG_RESULT(yes (notchecked))
-+       AC_DEFINE(IPV6, 1, Define this if you want IPV6 support.)
-+       ;;
-+    *)
-+       AC_MSG_RESULT(no)
-+       ;;
-+    esac],
- AC_MSG_RESULT(no)
- )
+-  esac
+-else
+-  echo "$as_me:$LINENO: result: no" >&5
+-echo "${ECHO_T}no" >&6
+ 
+-fi;
+ 
+ echo "$as_me:$LINENO: checking whether to enable SOCKS support" >&5
+ echo $ECHO_N "checking whether to enable SOCKS support... $ECHO_C" >&6
+
+
