Update to 2.0.2.  This is release comes after a big rewrite to remove deprectaed code, and fix I18N support.

diff --git a/mail/balsa2/files/patch-configure b/mail/balsa2/files/patch-configure
--- a/mail/balsa2/files/patch-configure
+++ b/mail/balsa2/files/patch-configure
@@ -1,13 +1,13 @@
---- configure.orig	Mon Jun 10 04:35:15 2002
-+++ configure	Tue Sep 10 14:01:26 2002
-@@ -7644,13 +7644,13 @@
+--- configure.orig	Sun Sep 15 14:42:04 2002
++++ configure	Mon Sep 16 02:28:13 2002
+@@ -8477,13 +8477,13 @@
  
- subdirs="$subdirs libmutt"
  
--echo "$as_me:7647: checking for new_pspell_manager in -lpspell" >&5
+ 
+-echo "$as_me:$LINENO: checking for new_pspell_manager in -lpspell" >&5
 -echo $ECHO_N "checking for new_pspell_manager in -lpspell... $ECHO_C" >&6
 -if test "${ac_cv_lib_pspell_new_pspell_manager+set}" = set; then
-+echo "$as_me:7647: checking for new_aspell_speller in -lpspell" >&5
++echo "$as_me:$LINENO: checking for new_aspell_speller in -lpspell" >&5
 +echo $ECHO_N "checking for new_aspell_speller in -lpspell... $ECHO_C" >&6
 +if test "${ac_cv_lib_pspell_new_aspell_speller+set}" = set; then
    echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -16,14 +16,18 @@
 -LIBS="-lpspell -lstdc++ -lpspell-modules $LIBS"
 +LIBS="-lpspell -lstdc++ $LIBS"
  cat >conftest.$ac_ext <<_ACEOF
- #line 7655 "configure"
+ #line $LINENO "configure"
  #include "confdefs.h"
-@@ -7661,11 +7661,11 @@
+@@ -8494,7 +8494,7 @@
  #endif
  /* We use char because int might match the return type of a gcc2
     builtin and then its argument prototype would still apply.  */
 -char new_pspell_manager ();
 +char new_aspell_speller ();
+ #ifdef F77_DUMMY_MAIN
+ #  ifdef __cplusplus
+      extern "C"
+@@ -8504,7 +8504,7 @@
  int
  main ()
  {
@@ -32,9 +36,9 @@
    ;
    return 0;
  }
-@@ -7682,18 +7682,18 @@
+@@ -8521,18 +8521,18 @@
    ac_status=$?
-   echo "$as_me:7683: \$? = $ac_status" >&5
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); }; }; then
 -  ac_cv_lib_pspell_new_pspell_manager=yes
 +  ac_cv_lib_pspell_new_aspell_speller=yes
@@ -47,66 +51,30 @@
  rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
  LIBS=$ac_check_lib_save_LIBS
  fi
--echo "$as_me:7694: result: $ac_cv_lib_pspell_new_pspell_manager" >&5
+-echo "$as_me:$LINENO: result: $ac_cv_lib_pspell_new_pspell_manager" >&5
 -echo "${ECHO_T}$ac_cv_lib_pspell_new_pspell_manager" >&6
 -if test $ac_cv_lib_pspell_new_pspell_manager = yes; then
-+echo "$as_me:7694: result: $ac_cv_lib_pspell_new_aspell_speller" >&5
++echo "$as_me:$LINENO: result: $ac_cv_lib_pspell_new_aspell_speller" >&5
 +echo "${ECHO_T}$ac_cv_lib_pspell_new_aspell_speller" >&6
 +if test $ac_cv_lib_pspell_new_aspell_speller = yes; then
-   cat >>confdefs.h <<EOF
+   cat >>confdefs.h <<_ACEOF
  #define HAVE_LIBPSPELL 1
- EOF
-@@ -9345,7 +9345,7 @@
-   echo "$as_me: failed program was:" >&5
- cat conftest.$ac_ext >&5
- CATOBJEXT=.mo
--	         DATADIRNAME=lib
-+	         DATADIRNAME=share
- fi
- rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
- 	      INSTOBJEXT=.mo
-@@ -9643,7 +9643,7 @@
+ _ACEOF
+@@ -12348,7 +12348,7 @@
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
    ac_check_lib_save_LIBS=$LIBS
 -LIBS="-lldap -llber -lresolv $LIBS"
 +LIBS="-lldap -llber $LIBS"
  cat >conftest.$ac_ext <<_ACEOF
- #line 9648 "configure"
+ #line $LINENO "configure"
  #include "confdefs.h"
-@@ -9690,7 +9690,7 @@
-   cat >>confdefs.h <<\EOF
+@@ -12403,7 +12403,7 @@
  #define ENABLE_LDAP 1
- EOF
-- LIBS="-lldap -llber -lresolv $LIBS"
-+ LIBS="-lldap -llber $LIBS"
+ _ACEOF
+ 
+-              LIBS="-lldap -llber -lresolv $LIBS"
++              LIBS="-lldap -llber $LIBS"
  else
-   { { echo "$as_me:9695: error: *** You enabled LDAP but ldap library is not found." >&5
+   { { echo "$as_me:$LINENO: error: *** You enabled LDAP but ldap library is not found." >&5
  echo "$as_me: error: *** You enabled LDAP but ldap library is not found." >&2;}
-@@ -9726,7 +9726,7 @@
-   echo $ECHO_N "(cached) $ECHO_C" >&6
- else
-   ac_check_lib_save_LIBS=$LIBS
--LIBS="-lesmtp -lpthread $LIBS"
-+LIBS="-lesmtp "-pthread" $LIBS"
- cat >conftest.$ac_ext <<_ACEOF
- #line 9731 "configure"
- #include "confdefs.h"
-@@ -9770,7 +9770,7 @@
- echo "$as_me:9770: result: $ac_cv_lib_esmtp_smtp_start_session" >&5
- echo "${ECHO_T}$ac_cv_lib_esmtp_smtp_start_session" >&6
- if test $ac_cv_lib_esmtp_smtp_start_session = yes; then
--  LIBS="$LIBS -lesmtp -lpthread"
-+  LIBS="$LIBS -lesmtp "-pthread""
- else
-   { { echo "$as_me:9775: error: *** You enabled ESMTP but esmtp library is not found." >&5
- echo "$as_me: error: *** You enabled ESMTP but esmtp library is not found." >&2;}
-@@ -11508,7 +11508,7 @@
-       { echo "$as_me:11508: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
- echo "$as_me: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&6;}
-       # The eval makes quoting arguments work.
--      eval $ac_sub_configure $ac_sub_configure_args \
-+      eval $ac_sub_configure \
-            --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir ||
-         { { echo "$as_me:11513: error: $ac_sub_configure failed for $ac_subdir" >&5
- echo "$as_me: error: $ac_sub_configure failed for $ac_subdir" >&2;}
