Update to version 1.3
PR:		ports/67801
Submitted by:	maintainer

diff --git a/games/gl-117/files/patch-configure b/games/gl-117/files/patch-configure
--- a/games/gl-117/files/patch-configure
+++ b/games/gl-117/files/patch-configure
@@ -1,6 +1,6 @@
---- configure.orig	Fri Aug 22 08:07:20 2003
-+++ configure	Sun Aug 24 12:25:25 2003
-@@ -5602,7 +5602,7 @@
+--- configure.orig	Sat Jun 12 01:44:13 2004
++++ configure	Mon Jun 14 11:14:35 2004
+@@ -6154,7 +6154,7 @@
   path=""
   for tmp in /usr/local /usr/X11R6 /usr $with_sdl_dir
   do
@@ -9,18 +9,18 @@
     path=$tmp
    fi
   done
-@@ -5612,8 +5612,8 @@
+@@ -6164,8 +6164,8 @@
   else
    echo "$as_me:$LINENO: result: $path" >&5
  echo "${ECHO_T}$path" >&6
 -  CPPFLAGS="$CPPFLAGS -I$path/include"
 -  CXXFLAGS="$CXXFLAGS -I$path/include"
-+  CPPFLAGS="$CPPFLAGS -I$path/include/SDL11"
-+  CXXFLAGS="$CXXFLAGS -I$path/include/SDL11"
++  CPPFLAGS="$CPPFLAGS -I$path/include -I$path/include/SDL11"
++  CXXFLAGS="$CXXFLAGS -I$path/include -I$path/include/SDL11"
    LIBS="$LIBS -L$path/lib"
   fi
  
-@@ -6280,8 +6280,8 @@
+@@ -6871,8 +6871,8 @@
  
  
  if test "${ac_cv_header_SDL_SDL_h+set}" = set; then
@@ -31,7 +31,7 @@
  if test "${ac_cv_header_SDL_SDL_h+set}" = set; then
    echo $ECHO_N "(cached) $ECHO_C" >&6
  fi
-@@ -6289,8 +6289,8 @@
+@@ -6880,8 +6880,8 @@
  echo "${ECHO_T}$ac_cv_header_SDL_SDL_h" >&6
  else
    # Is the header compilable?
@@ -40,18 +40,18 @@
 +echo "$as_me:$LINENO: checking SDL11/SDL.h usability" >&5
 +echo $ECHO_N "checking SDL11/SDL.h usability... $ECHO_C" >&6
  cat >conftest.$ac_ext <<_ACEOF
- #line $LINENO "configure"
  /* confdefs.h.  */
-@@ -6299,7 +6299,7 @@
+ _ACEOF
+@@ -6889,7 +6889,7 @@
  cat >>conftest.$ac_ext <<_ACEOF
  /* end confdefs.h.  */
  $ac_includes_default
 -#include <SDL/SDL.h>
-+#include <SDL11/SDL.h>
++#include <SDL.h>
  _ACEOF
  rm -f conftest.$ac_objext
  if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-@@ -6325,8 +6325,8 @@
+@@ -6925,15 +6925,15 @@
  echo "${ECHO_T}$ac_header_compiler" >&6
  
  # Is the header present?
@@ -60,9 +60,8 @@
 +echo "$as_me:$LINENO: checking SDL11/SDL.h presence" >&5
 +echo $ECHO_N "checking SDL11/SDL.h presence... $ECHO_C" >&6
  cat >conftest.$ac_ext <<_ACEOF
- #line $LINENO "configure"
  /* confdefs.h.  */
-@@ -6334,7 +6334,7 @@
+ _ACEOF
  cat confdefs.h >>conftest.$ac_ext
  cat >>conftest.$ac_ext <<_ACEOF
  /* end confdefs.h.  */
@@ -71,41 +70,49 @@
  _ACEOF
  if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
    (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-@@ -6367,10 +6367,10 @@
+@@ -6967,25 +6967,25 @@
  # So?  What about this header?
- case $ac_header_compiler:$ac_header_preproc in
-   yes:no )
+ case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+   yes:no: )
 -    { echo "$as_me:$LINENO: WARNING: SDL/SDL.h: accepted by the compiler, rejected by the preprocessor!" >&5
 -echo "$as_me: WARNING: SDL/SDL.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
--    { echo "$as_me:$LINENO: WARNING: SDL/SDL.h: proceeding with the preprocessor's result" >&5
--echo "$as_me: WARNING: SDL/SDL.h: proceeding with the preprocessor's result" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: SDL/SDL.h: proceeding with the compiler's result" >&5
+-echo "$as_me: WARNING: SDL/SDL.h: proceeding with the compiler's result" >&2;}
 +    { echo "$as_me:$LINENO: WARNING: SDL11/SDL.h: accepted by the compiler, rejected by the preprocessor!" >&5
 +echo "$as_me: WARNING: SDL11/SDL.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-+    { echo "$as_me:$LINENO: WARNING: SDL11/SDL.h: proceeding with the preprocessor's result" >&5
-+echo "$as_me: WARNING: SDL11/SDL.h: proceeding with the preprocessor's result" >&2;}
-     (
-       cat <<\_ASBOX
- ## ------------------------------------ ##
-@@ -6381,12 +6381,12 @@
-       sed "s/^/$as_me: WARNING:     /" >&2
++    { echo "$as_me:$LINENO: WARNING: SDL11/SDL.h: proceeding with the compiler's result" >&5
++echo "$as_me: WARNING: SDL11/SDL.h: proceeding with the compiler's result" >&2;}
+     ac_header_preproc=yes
      ;;
-   no:yes )
+   no:yes:* )
 -    { echo "$as_me:$LINENO: WARNING: SDL/SDL.h: present but cannot be compiled" >&5
 -echo "$as_me: WARNING: SDL/SDL.h: present but cannot be compiled" >&2;}
--    { echo "$as_me:$LINENO: WARNING: SDL/SDL.h: check for missing prerequisite headers?" >&5
--echo "$as_me: WARNING: SDL/SDL.h: check for missing prerequisite headers?" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: SDL/SDL.h:     check for missing prerequisite headers?" >&5
+-echo "$as_me: WARNING: SDL/SDL.h:     check for missing prerequisite headers?" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: SDL/SDL.h: see the Autoconf documentation" >&5
+-echo "$as_me: WARNING: SDL/SDL.h: see the Autoconf documentation" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: SDL/SDL.h:     section \"Present But Cannot Be Compiled\"" >&5
+-echo "$as_me: WARNING: SDL/SDL.h:     section \"Present But Cannot Be Compiled\"" >&2;}
 -    { echo "$as_me:$LINENO: WARNING: SDL/SDL.h: proceeding with the preprocessor's result" >&5
 -echo "$as_me: WARNING: SDL/SDL.h: proceeding with the preprocessor's result" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: SDL/SDL.h: in the future, the compiler will take precedence" >&5
+-echo "$as_me: WARNING: SDL/SDL.h: in the future, the compiler will take precedence" >&2;}
 +    { echo "$as_me:$LINENO: WARNING: SDL11/SDL.h: present but cannot be compiled" >&5
 +echo "$as_me: WARNING: SDL11/SDL.h: present but cannot be compiled" >&2;}
-+    { echo "$as_me:$LINENO: WARNING: SDL11/SDL.h: check for missing prerequisite headers?" >&5
-+echo "$as_me: WARNING: SDL11/SDL.h: check for missing prerequisite headers?" >&2;}
++    { echo "$as_me:$LINENO: WARNING: SDL11/SDL.h:     check for missing prerequisite headers?" >&5
++echo "$as_me: WARNING: SDL11/SDL.h:     check for missing prerequisite headers?" >&2;}
++    { echo "$as_me:$LINENO: WARNING: SDL11/SDL.h: see the Autoconf documentation" >&5
++echo "$as_me: WARNING: SDL11/SDL.h: see the Autoconf documentation" >&2;}
++    { echo "$as_me:$LINENO: WARNING: SDL11/SDL.h:     section \"Present But Cannot Be Compiled\"" >&5
++echo "$as_me: WARNING: SDL11/SDL.h:     section \"Present But Cannot Be Compiled\"" >&2;}
 +    { echo "$as_me:$LINENO: WARNING: SDL11/SDL.h: proceeding with the preprocessor's result" >&5
 +echo "$as_me: WARNING: SDL11/SDL.h: proceeding with the preprocessor's result" >&2;}
++    { echo "$as_me:$LINENO: WARNING: SDL11/SDL.h: in the future, the compiler will take precedence" >&5
++echo "$as_me: WARNING: SDL11/SDL.h: in the future, the compiler will take precedence" >&2;}
      (
        cat <<\_ASBOX
- ## ------------------------------------ ##
-@@ -6397,8 +6397,8 @@
+ ## ------------------------------------------ ##
+@@ -6996,8 +6996,8 @@
        sed "s/^/$as_me: WARNING:     /" >&2
      ;;
  esac
@@ -116,7 +123,7 @@
  if test "${ac_cv_header_SDL_SDL_h+set}" = set; then
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
-@@ -6420,8 +6420,8 @@
+@@ -7019,8 +7019,8 @@
  
  
  if test "${ac_cv_header_SDL_SDL_mixer_h+set}" = set; then
@@ -127,7 +134,7 @@
  if test "${ac_cv_header_SDL_SDL_mixer_h+set}" = set; then
    echo $ECHO_N "(cached) $ECHO_C" >&6
  fi
-@@ -6429,8 +6429,8 @@
+@@ -7028,8 +7028,8 @@
  echo "${ECHO_T}$ac_cv_header_SDL_SDL_mixer_h" >&6
  else
    # Is the header compilable?
@@ -136,9 +143,9 @@
 +echo "$as_me:$LINENO: checking SDL11/SDL_mixer.h usability" >&5
 +echo $ECHO_N "checking SDL11/SDL_mixer.h usability... $ECHO_C" >&6
  cat >conftest.$ac_ext <<_ACEOF
- #line $LINENO "configure"
  /* confdefs.h.  */
-@@ -6439,7 +6439,7 @@
+ _ACEOF
+@@ -7037,7 +7037,7 @@
  cat >>conftest.$ac_ext <<_ACEOF
  /* end confdefs.h.  */
  $ac_includes_default
@@ -147,7 +154,7 @@
  _ACEOF
  rm -f conftest.$ac_objext
  if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-@@ -6465,8 +6465,8 @@
+@@ -7073,15 +7073,15 @@
  echo "${ECHO_T}$ac_header_compiler" >&6
  
  # Is the header present?
@@ -156,9 +163,8 @@
 +echo "$as_me:$LINENO: checking SDL11/SDL_mixer.h presence" >&5
 +echo $ECHO_N "checking SDL11/SDL_mixer.h presence... $ECHO_C" >&6
  cat >conftest.$ac_ext <<_ACEOF
- #line $LINENO "configure"
  /* confdefs.h.  */
-@@ -6474,7 +6474,7 @@
+ _ACEOF
  cat confdefs.h >>conftest.$ac_ext
  cat >>conftest.$ac_ext <<_ACEOF
  /* end confdefs.h.  */
@@ -167,41 +173,49 @@
  _ACEOF
  if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
    (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-@@ -6507,10 +6507,10 @@
+@@ -7115,25 +7115,25 @@
  # So?  What about this header?
- case $ac_header_compiler:$ac_header_preproc in
-   yes:no )
+ case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+   yes:no: )
 -    { echo "$as_me:$LINENO: WARNING: SDL/SDL_mixer.h: accepted by the compiler, rejected by the preprocessor!" >&5
 -echo "$as_me: WARNING: SDL/SDL_mixer.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
--    { echo "$as_me:$LINENO: WARNING: SDL/SDL_mixer.h: proceeding with the preprocessor's result" >&5
--echo "$as_me: WARNING: SDL/SDL_mixer.h: proceeding with the preprocessor's result" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: SDL/SDL_mixer.h: proceeding with the compiler's result" >&5
+-echo "$as_me: WARNING: SDL/SDL_mixer.h: proceeding with the compiler's result" >&2;}
 +    { echo "$as_me:$LINENO: WARNING: SDL11/SDL_mixer.h: accepted by the compiler, rejected by the preprocessor!" >&5
 +echo "$as_me: WARNING: SDL11/SDL_mixer.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-+    { echo "$as_me:$LINENO: WARNING: SDL11/SDL_mixer.h: proceeding with the preprocessor's result" >&5
-+echo "$as_me: WARNING: SDL11/SDL_mixer.h: proceeding with the preprocessor's result" >&2;}
-     (
-       cat <<\_ASBOX
- ## ------------------------------------ ##
-@@ -6521,12 +6521,12 @@
-       sed "s/^/$as_me: WARNING:     /" >&2
++    { echo "$as_me:$LINENO: WARNING: SDL11/SDL_mixer.h: proceeding with the compiler's result" >&5
++echo "$as_me: WARNING: SDL11/SDL_mixer.h: proceeding with the compiler's result" >&2;}
+     ac_header_preproc=yes
      ;;
-   no:yes )
+   no:yes:* )
 -    { echo "$as_me:$LINENO: WARNING: SDL/SDL_mixer.h: present but cannot be compiled" >&5
 -echo "$as_me: WARNING: SDL/SDL_mixer.h: present but cannot be compiled" >&2;}
--    { echo "$as_me:$LINENO: WARNING: SDL/SDL_mixer.h: check for missing prerequisite headers?" >&5
--echo "$as_me: WARNING: SDL/SDL_mixer.h: check for missing prerequisite headers?" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: SDL/SDL_mixer.h:     check for missing prerequisite headers?" >&5
+-echo "$as_me: WARNING: SDL/SDL_mixer.h:     check for missing prerequisite headers?" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: SDL/SDL_mixer.h: see the Autoconf documentation" >&5
+-echo "$as_me: WARNING: SDL/SDL_mixer.h: see the Autoconf documentation" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: SDL/SDL_mixer.h:     section \"Present But Cannot Be Compiled\"" >&5
+-echo "$as_me: WARNING: SDL/SDL_mixer.h:     section \"Present But Cannot Be Compiled\"" >&2;}
 -    { echo "$as_me:$LINENO: WARNING: SDL/SDL_mixer.h: proceeding with the preprocessor's result" >&5
 -echo "$as_me: WARNING: SDL/SDL_mixer.h: proceeding with the preprocessor's result" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: SDL/SDL_mixer.h: in the future, the compiler will take precedence" >&5
+-echo "$as_me: WARNING: SDL/SDL_mixer.h: in the future, the compiler will take precedence" >&2;}
 +    { echo "$as_me:$LINENO: WARNING: SDL11/SDL_mixer.h: present but cannot be compiled" >&5
 +echo "$as_me: WARNING: SDL11/SDL_mixer.h: present but cannot be compiled" >&2;}
-+    { echo "$as_me:$LINENO: WARNING: SDL11/SDL_mixer.h: check for missing prerequisite headers?" >&5
-+echo "$as_me: WARNING: SDL11/SDL_mixer.h: check for missing prerequisite headers?" >&2;}
++    { echo "$as_me:$LINENO: WARNING: SDL11/SDL_mixer.h:     check for missing prerequisite headers?" >&5
++echo "$as_me: WARNING: SDL11/SDL_mixer.h:     check for missing prerequisite headers?" >&2;}
++    { echo "$as_me:$LINENO: WARNING: SDL11/SDL_mixer.h: see the Autoconf documentation" >&5
++echo "$as_me: WARNING: SDL11/SDL_mixer.h: see the Autoconf documentation" >&2;}
++    { echo "$as_me:$LINENO: WARNING: SDL11/SDL_mixer.h:     section \"Present But Cannot Be Compiled\"" >&5
++echo "$as_me: WARNING: SDL11/SDL_mixer.h:     section \"Present But Cannot Be Compiled\"" >&2;}
 +    { echo "$as_me:$LINENO: WARNING: SDL11/SDL_mixer.h: proceeding with the preprocessor's result" >&5
 +echo "$as_me: WARNING: SDL11/SDL_mixer.h: proceeding with the preprocessor's result" >&2;}
++    { echo "$as_me:$LINENO: WARNING: SDL11/SDL_mixer.h: in the future, the compiler will take precedence" >&5
++echo "$as_me: WARNING: SDL11/SDL_mixer.h: in the future, the compiler will take precedence" >&2;}
      (
        cat <<\_ASBOX
- ## ------------------------------------ ##
-@@ -6537,8 +6537,8 @@
+ ## ------------------------------------------ ##
+@@ -7144,8 +7144,8 @@
        sed "s/^/$as_me: WARNING:     /" >&2
      ;;
  esac
@@ -212,7 +226,7 @@
  if test "${ac_cv_header_SDL_SDL_mixer_h+set}" = set; then
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
-@@ -6743,13 +6743,13 @@
+@@ -7380,13 +7380,13 @@
  echo "$as_me: WARNING: GLUT not found - please install GLUT or MesaGLUT" >&2;}
  fi
  
@@ -225,11 +239,11 @@
  else
    ac_check_lib_save_LIBS=$LIBS
 -LIBS="-lSDL -lpthread $LIBS"
-+LIBS="-lSDL-1.1 -pthread $LIBS"
++LIBS="-lSDL-1.1 -lpthread $LIBS"
  cat >conftest.$ac_ext <<_ACEOF
- #line $LINENO "configure"
  /* confdefs.h.  */
-@@ -6798,7 +6798,7 @@
+ _ACEOF
+@@ -7445,7 +7445,7 @@
  echo "$as_me:$LINENO: result: $ac_cv_lib_SDL_SDL_Init" >&5
  echo "${ECHO_T}$ac_cv_lib_SDL_SDL_Init" >&6
  if test $ac_cv_lib_SDL_SDL_Init = yes; then
@@ -238,3 +252,12 @@
  else
    { echo "$as_me:$LINENO: WARNING: SDL not found - please install SDL" >&5
  echo "$as_me: WARNING: SDL not found - please install SDL" >&2;}
+@@ -7524,7 +7524,7 @@
+ 
+ 
+ CFLAGS="$CFLAGS"
+-CPPFLAGS="-DDATADIR='\"$datadir\"' -Wall -pedantic"
++CPPFLAGS="-DDATADIR='\"$datadir\"' -Wall"
+ CXXFLAGS="$CXXFLAGS"
+ 
+                     ac_config_files="$ac_config_files Makefile src/Makefile"
