Remove the old brute-force script that generates thousands of XLFD. Many of them are unnecessary, and most of the task are handled by ttfm now.
It's also aware of chinese/{CJK, ghostscript6}.  It supports XFree86
3.x or 4.x by default.  Users only need to define GS6=yes or CJK=yes
when installing, then it'll do most of the work.  CJK and ghostscript6
ports should specify their respective variables via DEPENDS_ARGS.

chinese/{moettf,moefonts-cid,wangttf} will have similar changes.

diff --git a/chinese/arphicttf/pkg-install b/chinese/arphicttf/pkg-install
--- a/chinese/arphicttf/pkg-install
+++ b/chinese/arphicttf/pkg-install
@@ -1,113 +1,55 @@
 #!/bin/sh
-FONTDIR=${PKG_PREFIX}/lib/X11/fonts/TrueType
+
 if [ "$2" = "PRE-INSTALL" ]; then
-  echo "Please add ${FONTDIR} to your /etc/XF86Config file"
   exit 0
 fi
-cd ${FONTDIR}
 
-echo "Updating fonts.dir & fonts.alias. This may take a while..."
-# Update fonts.dir
-touch fonts.dir
-sed -e '/ -ar-/d' -e '/ -arphic-/d' fonts.dir > fonts.dir.tmp
-# Add 16 new fonts
-numfonts=$(echo $(cat fonts.dir.tmp |wc -l) - 1 + 16 |bc)
-if [ ${numfonts} -le 16 ]; then # fonts.dir.tmp is empty
-  echo 16 > fonts.dir
-else
-  echo ${numfonts} > fonts.dir
-  sed -e 1d fonts.dir.tmp >> fonts.dir
+PKGNAME=$1
+PREFIX=${PKG_PREFIX}
+TTFM=${PREFIX}/bin/ttfm.sh
+
+FONTDIR=${PREFIX}/share/fonts/TrueType
+FONTS="bkai00mp.ttf bsmi00lp.ttf gbsn00lp.ttf gkai00mp.ttf"
+DEFAULTMING="bsmi00lp.ttf gbsn00lp.ttf"
+DEFAULTKAI="bkai00mp.ttf gkai00mp.ttf"
+
+[ "X$XTT" = "X" ] && XTT=YES
+
+if [ ! -x $TTFM ]; then
+    echo "$TTFM not found!"
+    exit 1
 fi
-rm -f fonts.dir.tmp
 
-# The TTF filenames are so diverse that we can only iterate one
-# by one, instead of a generic for loop.
+rm -f $FONTDIR/$PKGNAME
 
-# bkai00mp.ttf (Big5)
-echo bkai00mp.ttf -ar-kai-medium-r-normal--0-0-0-0-c-0-big5-0 >> fonts.dir
-echo ab=y:bkai00mp.ttf -ar-kai-bold-r-normal--0-0-0-0-c-0-big5-0 >> fonts.dir
-echo ai=0.3:bkai00mp.ttf -ar-kai-medium-i-normal--0-0-0-0-c-0-big5-0 >> fonts.dir
-echo ab=y:ai=0.3:bkai00mp.ttf -ar-kai-bold-i-normal--0-0-0-0-c-0-big5-0 >> fonts.dir
+if [ "$CJK" = "YES" -o "$CJK" = "yes" ]; then
+    # There's no CJK module now.
+fi
 
-# bsmi00lp.ttf (Big5)
-echo bsmi00lp.ttf -ar-ming-medium-r-normal--0-0-0-0-c-0-big5-0 >> fonts.dir
-echo ab=y:bsmi00lp.ttf -ar-ming-bold-r-normal--0-0-0-0-c-0-big5-0 >> fonts.dir
-echo ai=0.3:bsmi00lp.ttf -ar-ming-medium-i-normal--0-0-0-0-c-0-big5-0 >> fonts.dir
-echo ab=y:ai=0.3:bsmi00lp.ttf -ar-ming-bold-i-normal--0-0-0-0-c-0-big5-0 >> fonts.dir
+if [ "$GS6" = "YES" -o "$GS6" = "yes" ]; then
+    for f in $FONTS; do
+        $TTFM --add ghostscript6 $FONTDIR/$f
+    done
+    for f in $DEFAULTMING; do
+        $TTFM --setdefault ghostscript6 $FONTDIR/$f
+    done
+    for f in $DEFAULTKAI; do
+        $TTFM --setdefault_kai ghostscript6 $FONTDIR/$f
+    done
+    echo "ghostscript6" >> $FONTDIR/$PKGNAME
+fi
 
-# gbsn00lp.ttf (GB)
-echo gbsn00lp.ttf -ar-sung-medium-r-normal--0-0-0-0-c-0-gb2312.1980-0 >> fonts.dir
-echo ab=y:gbsn00lp.ttf -ar-sung-bold-r-normal--0-0-0-0-c-0-gb2312.1980-0 >> fonts.dir
-echo ai=0.3:gbsn00lp.ttf -ar-sung-medium-i-normal--0-0-0-0-c-0-gb2312.1980-0 >> fonts.dir
-echo ab=y:ai=0.3:gbsn00lp.ttf -ar-sung-bold-i-normal--0-0-0-0-c-0-gb2312.1980-0 >> fonts.dir
+if [ "$XTT" = "YES" -o "$XTT" = "yes" ]; then
+    for f in $FONTS; do
+        $TTFM --add xttfm $FONTDIR/$f
+    done
+    for f in $DEFAULTMING; do
+        $TTFM --setdefault xttfm $FONTDIR/$f
+    done
+    for f in $DEFAULTKAI; do
+        $TTFM --setdefault_kai xttfm $FONTDIR/$f
+    done
+    echo "xttfm" >> $FONTDIR/$PKGNAME
+fi
 
-# gkai00mp.ttf (GB)
-echo gkai00mp.ttf -ar-kai-medium-r-normal--0-0-0-0-c-0-gb2312.1980-0 >> fonts.dir
-echo ab=y:gkai00mp.ttf -ar-kai-bold-r-normal--0-0-0-0-c-0-gb2312.1980-0 >> fonts.dir
-echo ai=0.3:gkai00mp.ttf -ar-kai-medium-i-normal--0-0-0-0-c-0-gb2312.1980-0 >> fonts.dir
-echo ab=y:ai=0.3:gkai00mp.ttf -ar-kai-bold-i-normal--0-0-0-0-c-0-gb2312.1980-0 >> fonts.dir
-
-
-# Update fonts.alias, font size ranges from 8 to 128.
-# Medium/Bold & Roman/Italic variations are also added.
-touch fonts.alias
-sed -e '/^-ar-/d' -e '/^-arphic-/d' fonts.alias > fonts.alias.tmp
-mv -f fonts.alias.tmp fonts.alias
-
-# Iterate four fonts, same as in fonts.dir.
-
-# bkai00mp.ttf (Big5)
-SIZE=8
-for WEIGHT in medium bold
-do
-  (for SLANT in r i
-   do
-     (while [ ${SIZE} -le 128 ]
-      do
-        echo -arphic-kai-${WEIGHT}-${SLANT}-normal--${SIZE}-`expr ${SIZE} \* 10`-0-0-c-`expr ${SIZE} \* 10`-big5-0 -ar-kai-${WEIGHT}-${SLANT}-normal--${SIZE}-`expr ${SIZE} \* 10`-0-0-c-`expr ${SIZE} \* 10`-big5-0 >> fonts.alias;
-        SIZE=`expr ${SIZE} + 1`;
-      done)   # SIZE
-   done)   # SLANT
-done   # WEIGHT
-
-# bsmi00lp.ttf (Big5)
-SIZE=8
-for WEIGHT in medium bold
-do
-  (for SLANT in r i
-   do
-     (while [ ${SIZE} -le 128 ]
-      do
-        echo -arphic-ming-${WEIGHT}-${SLANT}-normal--${SIZE}-`expr ${SIZE} \* 10`-0-0-c-`expr ${SIZE} \* 10`-big5-0 -ar-ming-${WEIGHT}-${SLANT}-normal--${SIZE}-`expr ${SIZE} \* 10`-0-0-c-`expr ${SIZE} \* 10`-big5-0 >> fonts.alias;
-      SIZE=`expr ${SIZE} + 1`;
-      done)   # SIZE
-   done)   # SLANT
-done   # WEIGHT
-
-# gbsn00lp.ttf (GB)
-SIZE=8
-for WEIGHT in medium bold
-do
-  (for SLANT in r i
-   do
-     (while [ ${SIZE} -le 128 ]
-      do
-        echo -arphic-sung-${WEIGHT}-${SLANT}-normal--${SIZE}-`expr ${SIZE} \* 10`-0-0-c-`expr ${SIZE} \* 10`-gb2312.1980-0 -ar-sung-${WEIGHT}-${SLANT}-normal--${SIZE}-`expr ${SIZE} \* 10`-0-0-c-`expr ${SIZE} \* 10`-gb2312.1980-0 >> fonts.alias;
-        SIZE=`expr ${SIZE} + 1`;
-      done)   # SIZE
-   done)   # SLANT
-done   # WEIGHT
-
-# gkai00mp.ttf (GB)
-SIZE=8
-for WEIGHT in medium bold
-do
-  (for SLANT in r i
-   do
-     (while [ ${SIZE} -le 128 ]
-      do
-        echo -arphic-kai-${WEIGHT}-${SLANT}-normal--${SIZE}-`expr ${SIZE} \* 10`-0-0-c-`expr ${SIZE} \* 10`-gb2312.1980-0 -ar-kai-${WEIGHT}-${SLANT}-normal--${SIZE}-`expr ${SIZE} \* 10`-0-0-c-`expr ${SIZE} \* 10`-gb2312.1980-0 >> fonts.alias;
-        SIZE=`expr ${SIZE} + 1`;
-      done)   # SIZE
-   done)   # SLANT
-done   # WEIGHT
+exit 0
